### ISSUE TITLE
Doesn't recognize templates specified using require()

### ISSUE THREAD

**Issue by jkachurek** [angular/vscode-ng-language-service#100]
I am getting the error that "Component [name]Component must have a template or templateUrl" on all of my components.  I am guessing this is because rather than using templateUrls or inline templates, I am using webpack and `require()` to import the templates.  It would be great if the extension could resolve routes/modules that use `require()`.

**Comment by jamesdking** [comment]
+1

**Comment by mrahhal** [comment]
Facing this as well.

**Comment by mrahhal** [comment]
So I've been investigating a bit. It seems that this can't be fixed from this package as this uses the [angular language-service package](https://github.com/angular/angular/tree/master/packages/language-service) to obtain the template references.

In particular, [this line](https://github.com/angular/angular/blob/5af143e8e43cb1c0d0560c558271f9d3b7201da9/packages/language-service/src/typescript_host.ts#L278) is interesting. Seems like the service only has knowledge of "templateUrl". If this is to be fixed, the language-service package is where this should happen. Not sure if this is feasible though.

**Comment by mrahhal** [comment]
Opened an issue in the angular repo, linked above.

**Comment by chuckjaz** [comment]
Closed in angular as well.

**Comment by DerZyklop** [comment]
Related Angular issue: https://github.com/angular/angular/issues/23553
