### ISSUE TITLE
The TypeScript extension crashed

### ISSUE THREAD

**Issue by mlicciardi** [angular/vscode-ng-language-service#1005]
Issue Type: <b>Bug</b>
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

Occours every time I open vscode 

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

Extension version: 0.1100.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 5|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|. --crash-reporter-id dd26c912-d23c-4620-94ad-d182ba329fba|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ayazhafiz** [comment]
Hi, is this the TypeScript language service crashing or the angular one? Can you please include the logs for the angular language service (see how at https://github.com/angular/vscode-ng-language-service/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
