### ISSUE TITLE
Throws a false error with local variable

### ISSUE THREAD

**Issue by vladrmnv** [angular/vscode-ng-language-service#103]
![screen shot 2017-06-02 at 11 42 05 pm](https://cloud.githubusercontent.com/assets/13325924/26750318/445b4e62-47ed-11e7-9149-f32fb8d23e13.png)

Does not detect that `rla2` is a local variable of `routerLinkActive` services for some reason, but everything works. Is this a glitch?

**Comment by kyliau** [comment]
Closing this, since issue is more than two years old. If problem persists, please open a new issue with relevant screenshots, code example, and complete log information. Thanks!
