### ISSUE TITLE
Failed to resolve ngcc

### ISSUE THREAD

**Issue by arobinson** [angular/vscode-ng-language-service#1032]
**Describe the bug**

I created a brand new Angular 11 application and the only change I made was to set "enableIvy" to true in the tsconfig. I then set the option to enable Ivy in the workspace for the Angular Language Service. The log then shows this:

```
[Info  - 5:44:38 PM] Angular language server process ID: 94830
[Info  - 5:44:38 PM] Using typescript/lib/tsserverlibrary v4.0.5 from /Users/andrew/.vscode/extensions/angular.ng-template-0.1100.2/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 5:44:38 PM] Using @angular/language-service/bundles/ivy v11.0.3 from /Users/andrew/.vscode/extensions/angular.ng-template-0.1100.2/server/node_modules/@angular/language-service/bundles/ivy.js
[Info  - 5:44:38 PM] Log file: /Users/andrew/Library/Application Support/Code/logs/20201216T174434/exthost1/Angular.ng-template/nglangsvc.log
[Error - 5:44:42 PM] Failed to find project for /Users/andrew/development/work/Angular/test-ts-config/src/app/app.component.html
[Error - 5:44:42 PM] Failed to run ngcc for /Users/andrew/development/work/Angular/test-ts-config/tsconfig.json:
Failed to resolve ngcc from /Users/andrew/development/work/Angular/test-ts-config
Language service will remain disabled.
```

Running ls shows that it is there as the service seems to be looking:
```
$ ll node_modules/@angular/compiler-cli/ngcc/main-ngcc.js
-rwxr-xr-x  1 andrew  staff   4.8K Oct 26  1985 node_modules/@angular/compiler-cli/ngcc/main-ngcc.js 
```

**To Reproduce**

1. Have angular CLI installed globally
2. Create a new project using ng new: `ng new testapp`
3. Install Angular Language Service
4. Enable `angular.experimental-ivy` in vs code
5. Set `"enableIvy": true` in the `angularCompilerOptions` portion of the tsconfig.json
6. Error above results

**Expected behavior**

Extension should work with a new Angular 11 application

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
See above

2. Log file (Path is printed to the console output at startup)
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/5706305/nglangsvc.log)

**Screenshots**

**Additional context**

**Comment by kyliau** [comment]
This has been fixed in https://github.com/angular/vscode-ng-language-service/pull/1016, and released in https://github.com/angular/vscode-ng-language-service/releases/tag/v0.1101.0-next.1
