### ISSUE TITLE
LSParseConfigHost potentially mishandling extended config

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#1035]
Same problem here with "angular.experimental-ivy:true". Also tried latest manual install (0.1101.0-next.1)

An issue appears to be the concatenation of paths in the vscode extension when locating the `tsconfig.json` file:

```
[Info  - 11:28:47 AM] Angular language server process ID: 33010
[Info  - 11:28:47 AM] Using typescript/lib/tsserverlibrary v4.0.5 from /Users/lincoln/projects/maritlabs/topdecked-unified/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 11:28:47 AM] Using @angular/language-service/bundles/ivy v11.1.0-next.3 from /Users/lincoln/.vscode/extensions/angular.ng-template-0.1101.0-next.1/node_modules/@angular/language-service/bundles/ivy.js
[Info  - 11:28:47 AM] Log file: /Users/lincoln/Library/Application Support/Code/logs/20201217T103253/exthost1/Angular.ng-template/nglangsvc.log
[Error - 11:28:53 AM] Cannot read file '/Users/lincoln/projects/maritlabs/topdecked-unified/Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.base.json'.
[Info  - 11:28:54 AM] Enabling Ivy language service for /Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.json.
```

Note this line:

```
Cannot read file '/Users/lincoln/projects/maritlabs/topdecked-unified/Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.base.json'.
```

This should clearly be `/Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.base.json`. Not sure why this is happening. I don't think I have any special configuration for file paths.

Happy to provide the nglangsvc.log file (directly to devs) as well but cannot post online for security reasons.

_Originally posted by @lincolnthree in https://github.com/angular/vscode-ng-language-service/issues/1002#issuecomment-747552907_

**Comment by kyliau** [comment]
Might need caused by https://github.com/angular/angular/pull/39619, will investigate shortly.

**Comment by kyliau** [comment]
@lincolnthree could you please show me the `extends` field in your `tsconfig.json`?

**Comment by lincolnthree** [comment]
@kyliau 
```
  "extends": "./tsconfig.base.json",
```

**Comment by lincolnthree** [comment]
Confirmed this is now working with the default angular generated tsconfig.app/base/.ts structure.
