### ISSUE TITLE
Prevents other extensions from running

### ISSUE THREAD

**Issue by diminutivesloop** [angular/vscode-ng-language-service#104]
Whenever I have this extension enabled I will regularly experience extended periods after launching the application where none of the commands for my other extensions can be run. The application itself is still responsive but any keyboard shortcut or command palette option that is associated with an extension simply fails to run. Additionally whenever I mouse over a symbol in the editor, a tooltip appears with the text "Loading...". If I wait long enough the issue sometimes resolves itself, but so far this only appears to happen for Angular projects.

**Comment by biltongza** [comment]
I'm having the same issue here. I can immediately get all other extensions to respond or start working by killing the code.exe process that hosts the extension.

**Comment by biltongza** [comment]
I've found that if I exclude node_modules from vscode, things start working again, so I think the issue could be related to the extension scanning that directory and blocking things until it finishes.

**Comment by diminutivesloop** [comment]
@biltongza Excluding node_modules seems to have done the trick. Thanks for the tip.

**Comment by ianchi** [comment]
I have the same problem, when enabling this extension a `code` process eats the processor and goes up in memory usage  until it hits about 1.5GB and crashes. 
Excluding `node_modules` is a work arround, but is there a way to exclude it from this extension, but not from the file explorer? There should be a specific option for this. (like there is a separate exclude setting for search).

I'm using v0.1.4 and VSCode Linux 1.14 (and also happened in 1.13).

**Comment by kyliau** [comment]
Closing this, since issue is more than two years old and has since been fixed.
