### ISSUE TITLE
"Go to definition" sometimes does not work for variables and template references 

### ISSUE THREAD

**Issue by lincolnthree** [angular/vscode-ng-language-service#1054]
**Describe the bug**

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

**To Reproduce**

```
  "angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "skipTemplateCodegen": false,
    "strictInjectionParameters": true,
    "strictMetadataEmit": false
  }
```

1. Create a dynamic `<ng-template #name>` within a .html template.
2. Reference using `<ng-container *ngTemplateOutlet="name"></ng-container>`
3. Hover mouse or attempt to ctrl-click through the `name` reference.
4. Template name link is properly identified as a `TemplateRef`, but cannot be followed.

**Expected behavior**

The template name ref should hot-link/follow to the `<ng-template>` definition within the .html template.

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
2. Log file (Path is printed to the console output at startup)
```
[Info  - 10:35:16 AM] Angular language server process ID: 51676
[Info  - 10:35:16 AM] Using typescript/lib/tsserverlibrary v4.0.5 from /Users/lincoln/projects/maritlabs/topdecked-unified/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 10:35:16 AM] Using @angular/language-service/bundles/ivy v11.1.0-next.4 from /Users/lincoln/.vscode/extensions/angular.ng-template-0.1101.0-next.2/node_modules/@angular/language-service/bundles/ivy.js
[Info  - 10:35:16 AM] Log file: /Users/lincoln/Library/Application Support/Code/logs/20201219T115842/exthost5/Angular.ng-template/nglangsvc.log
[Info  - 10:35:16 AM] Disabling language service for /Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
[33mWarning:[0m Entry point '@rx-angular/template' contains deep imports into '/Users/lincoln/projects/maritlabs/topdecked-unified/node_modules/rxjs/internal/types'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[Info  - 10:35:24 AM] Enabling Ivy language service for /Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.app.json.
[Info  - 10:35:45 AM] Disabling language service for /Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.worker.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
[33mWarning:[0m Entry point '@rx-angular/template' contains deep imports into '/Users/lincoln/projects/maritlabs/topdecked-unified/node_modules/rxjs/internal/types'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
[Info  - 10:35:46 AM] Enabling Ivy language service for /Users/lincoln/projects/maritlabs/topdecked-unified/tsconfig.spec.json.

```

(language server log can be provided privately upon request)

**Screenshots**

![Screen Shot 2021-01-08 at 10 53 18 AM](https://user-images.githubusercontent.com/362329/104035113-bef04780-519f-11eb-90fe-a4644be0be90.png)

**Additional context**

Good news is the IVY language service is now working on our project! Keep up the great work :)

**Comment by atscott** [comment]
@lincolnthree - thanks for the report. I think this is an issue that I had discovered the other day that has to do with the way we handle changes to the templates in our incremental build/compile. The issue is that the definition _is_ found, but we have incorrectly stored the template file name as simply `'override.html'`, which then can't be resolved to a location. If you restart the Angular language server (cmd+shift+p, then "Angular: Restart Angular Language server"), this "go to definition" action should work. 

// cc @alxhub @zarend

**Comment by lincolnthree** [comment]
Interesting. I just double checked this. It seems to be working from what I can tell - though I can't verify that a restart of the LS is what got it to do so. I'll keep an eye on this and see if/when it stops working again. Since I haven't really changed anything except do a full build of the app since filing the issue.
