### ISSUE TITLE
Language Service can't recognize module imports!

### ISSUE THREAD

**Issue by tx8821** [angular/vscode-ng-language-service#107]
VS Code, Angular CLI generated project with several modules.

There are these errors all over the place:

> 'my-input' is not a known element:
> 1. If 'my-input' is an Angular component, then verify that it is part of this module.
> 2. If 'my-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 

// 'my-input' here is the name of the example component not being recognized.

Basically components and directives from the imported modules are not recognized. This bug is similar and might be related to #79 but I think there's more to it than not seeing re-exported stuff.

The Service is effectively useless because of this bug. Majority of the needed components and directives are re-exported from a SharedModule, which I use in all my other modules. None of them are recognized so the Language Service is just unusable.

But there's more to it... I noticed that if I directly import the module that is elsewhere re-exported, in isn't recognized even then. Seems very strange[?]

Anyway.... my solution has 6 modules (App/Shared/Core/Widgets/Admin/Sales), organized according to the best practices available in the NgModule docs itself. It works perfectly with `ng build` and `ng serve`, but Language Service reports gazillion of errors.

Unfortunately I can't provide the source code (its a commercial app) but I can provide access to my machine via TeamViewer or similar remote-access tool, any time of day you wish, and you could investigate the issue at hand. Please let me know if I can help. Right now Language Service is practically unusable for anything but simple hello-world projects I guess, so I'm surprised it is one of the most well-rated extensions of VS Code.

**Comment by tx8821** [comment]
Apparently this fixes the problem: https://github.com/angular/vscode-ng-language-service/issues/108

**Comment by chuckjaz** [comment]
Fixed in 0.1.4
