### ISSUE TITLE
Ivy LS: CRLF line endings breaks sourcemap positions - LS features get provided as if CRLF is 1 character when it is 2

### ISSUE THREAD

**Issue by andrius-pra** [angular/vscode-ng-language-service#1082]
**Describe the bug**

Angular language service does not return completions in interpolations when using CRLF line endings.

**To Reproduce**

1. Generate new angular app: ng new ivy-app
2. Enable the Ivy language service.
3. Change app.component.html content :
```
<div></div>
{{}}
```
4. change file line endings from LF to CRLF
5. move cursor to empty interpolation and ask ide for completions (ctrl+space)

Actual behavior

Completion list is empty. 

**Expected behavior**

Completion list does not depends on template line endings.

**Screenshots**

![CRLF](https://user-images.githubusercontent.com/17968027/105757736-070cb980-5f57-11eb-845e-7f7f07810c14.gif)

**Comment by kyliau** [comment]
Sounds like a repeat of this bug: https://github.com/angular/angular/pull/33241

**Comment by atscott** [comment]
Fixed by https://github.com/angular/angular/pull/40597
