### ISSUE TITLE
auto-apply optional chaining on nullable symbol

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#1094]
In TypeScript, TSLS automatically inserts the optional chaining operator (`?.`) when property access (`.`) is done on a nullable symbol.
Implement a similar feature in Angular language service.
This will help avoid bugs, promote better code pattern (otherwise users might resort to non-null assertion operator `!`), and improve user experience.

**Comment by atscott** [comment]
Fixed by #1469
