### ISSUE TITLE
Autocomplete string literal union types in templates

### ISSUE THREAD

**Issue by atscott** [angular/vscode-ng-language-service#1096]
The native TS language service has the ability to provide autocompletions for string literal union types. For example, `let pet: 'cat'|'dog' = '|'"` will provide `'cat'` and `'dog'` as autocomplete results ([playground example](https://www.typescriptlang.org/play?#code/FAGwpgLgBADpBcUDkBjAhhJAfJATA9gOZJQC8ySQA)). 

This feature request is for Angular to do the same in templates. The Angular Language Service does not provide these completions when the type of an input, method argument, etc. in a template is a string literal union.

**Comment by zarend** [comment]
This feature was implemented in https://github.com/angular/angular/pull/41456
