### ISSUE TITLE
Span for pipe is not computed correctly

### ISSUE THREAD

**Issue by frederikschubert** [angular/vscode-ng-language-service#11]
The span of a pipe is not computed correctly. In case of an error the whole node in which the pipe is located, is highlighted.

<img width="656" alt="bildschirmfoto 2016-12-08 um 22 38 03" src="https://cloud.githubusercontent.com/assets/4137975/21028805/0fad15e6-bd97-11e6-8ed3-0916cc6c346d.png">

**Comment by chuckjaz** [comment]
Thanks for the report!!

I added a corresponding bug in (https://github.com/angular/angular/issues/13326).

I will close this bug when the fix for this issue in `@angular/language-service` is committed to master.

**Comment by chuckjaz** [comment]
Closed in 0.0.11

**Comment by frederikschubert** [comment]
Glad to hear! Thanks for your good work! :)
