### ISSUE TITLE
Ivy LS makes some features in TS context unusably slow

### ISSUE THREAD

**Issue by objt-mni** [angular/vscode-ng-language-service#1104]
Some features, like autocomplete and 'Navigate to element' become unusably slow when the experimental Ivy language service is enabled.

Demo:

![recording](https://user-images.githubusercontent.com/72925943/107511673-153d1580-6ba6-11eb-87cd-65e2d1a75a62.gif)

Note: this performance regression can only be observed when the experimental Ivy language service is enabled

Angular Language Service version: 11.1.3

**Comment by CaselIT** [comment]
I have the same issue, setting `"angular.experimental-ivy": false` in the configuration fixes the issue even without reloading vscode so I would think that the slowdown is due to the ivy being enabled.

**Comment by atscott** [comment]
Copied from #1127:

**Describe the bug**

In my project, IntelliSense is significantly slower when Ivy is enabled.

**To Reproduce**

I can go to any TS-file, start typing something, and wait for the suggestion box to pop up. Without Ivy enabled this happens almost instantaneously, after an initial loading time the first time you do it. With Ivy enabled it takes almost 10 seconds, every time.

**Expected behavior**

Ivy shouldn't be that much slower at providing suggestions compared to the old engine.

**Logs**

***Without Ivy***
[Info  - 11:49:53 AM] Angular language server process ID: 4632
[Info  - 11:49:53 AM] Using typescript/lib/tsserverlibrary v4.1.5 from f:\git\ProntoWeb\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 11:49:53 AM] Using @angular/language-service v11.2.0 from c:\Users\magnus.bakken\.vscode\extensions\angular.ng-template-11.2.1\node_modules\@angular\language-service\bundles\language-service.js
[Info  - 11:49:53 AM] Log file: c:\Users\magnus.bakken\AppData\Roaming\Code\logs\20210218T114948\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 11:50:08 AM] Enabling VE language service for f:/git/ProntoWeb/tsconfig.json.
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/6002224/nglangsvc.log)

***With Ivy***
[Info  - 11:51:36 AM] Angular language server process ID: 17672
[Info  - 11:51:36 AM] Using typescript/lib/tsserverlibrary v4.1.5 from f:\git\ProntoWeb\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 11:51:36 AM] Using @angular/language-service/bundles/ivy v11.2.0 from c:\Users\magnus.bakken\.vscode\extensions\angular.ng-template-11.2.1\node_modules\@angular\language-service\bundles\ivy.js
[Info  - 11:51:36 AM] Log file: c:\Users\magnus.bakken\AppData\Roaming\Code\logs\20210218T115129\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 11:51:49 AM] Enabling Ivy language service for f:/git/ProntoWeb/tsconfig.json.
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/6002240/nglangsvc.log)

**Screenshots**

***Without Ivy***
![tab-completion-no-ivy](https://user-images.githubusercontent.com/284189/108346617-ddeeea00-71df-11eb-9d03-3c6c7d5af9c9.gif)

***With Ivy***
![tab-completion-ivy](https://user-images.githubusercontent.com/284189/108346628-e0e9da80-71df-11eb-908c-caf43cafeab6.gif)

**Comment by reed-lawrence** [comment]
I can also confirm that the intellisense issues as documented above are present in HTML templates. Imported Angular components are not suggesed by intellisense. Linting, and symbol navigation still work as expected. 

Angular CLI: 11.2.1
Angular Language Services: 11.2.2
VS Code: 1.53.2

**Comment by kyliau** [comment]
I updated the title of the issue to emphasize that this bug affects autocompletion in **TypeScript** context.
Both TS extension and Angular extension register themselves as provider for autocompletion, but Angular is holding vscode back from returning TS results immediately in a context where Angular does not provide additional results.

**Comment by atscott** [comment]
FYI - we plan to do a release today that will include a fix for this.

**Comment by AlissonRS** [comment]
Thanks @atscott . I posted an [answer in SO](https://stackoverflow.com/a/66327083/2263507) suggesting to temporarily disable this option, but once this release comes up I'll update my answer suggesting people to just update the extension.

**Comment by atscott** [comment]
Hi @AlissonRS, this fix was included in the [11.2.3 release](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.2.3) yesterday. Sorry for not providing an update here. Please let us know if you're still experiencing issues.

**Comment by AlissonRS** [comment]
Thanks @atscott , that was fast. I re-enabled Ivy and will do some tests, if everything goes well I'll update [the answer in SO](https://stackoverflow.com/a/66327083/2263507). The original question is unrelated, but some people with this issue ended up there (including me).

**Comment by atscott** [comment]
@AlissonRS - Thanks. We've also identified room for improvement in the ngcc performance (which is more directly related to that SO question): https://github.com/angular/angular/issues/40969. That will likely land either this week or next.

**Comment by AlissonRS** [comment]
@atscott just came back to say everything looks ok since v11.2.3, I didn't face any performance issues so far. I updated my answer in SO as well. Thank you very much,

**Comment by CaselIT** [comment]
I'm still facing some slowdown.
It's definitely better than before, but it's still a quite noticeable ~ 1-2s

**Comment by chavesdaniel** [comment]
Hi !
I'm still facing some slowdown... but it is not always, it seems to be intermittent :(
I'm using the version 11.2.3

**Comment by kyliau** [comment]
@CaselIT @chavesdaniel Could you please open a new issue and let us know when did the slowness occur?
- Were you typing in TS source code, or Angular template?
- If Angular template, was it an inline template or external file?
- Were you expecting Angular results, or TypeScript results?
- How big is your project?
- Please consider uploading the logs to help us understand your setup.

**Comment by chavesdaniel** [comment]
@kyliau I've just disabled the plugin option "Angular: Experimental-Ivy" and it seems to be resolved (Ctrl + click on angular html components).
I've tested some autocomplete (Ctrl + spacebar at ts files) and seems fast too.
Where can I check the logs to see if the problems is definitively resolved ?
Thanks for your fast reply

**Comment by kyliau** [comment]
@chavesdaniel Yeah, `experimental-ivy` is the new thing we are rolling out, and in a couple months we'll switch over. It'll help us tremendously if you could give us some insight into what went poorly when you were using `experimental-ivy`. To get the logs, open the command palette (Cmd + Shift + P on Mac, Ctrl + Shift + P on Windows I believe), and search for "Open Angular Server log". Once you get the logs, please open a new issue to help us triage better. Thank you :) 

<img width="1792" alt="Screen Shot 2021-03-01 at 9 16 58 PM" src="https://user-images.githubusercontent.com/2941178/109601400-a4698900-7ad3-11eb-9f80-0c71f903fd9b.png">

**Comment by chavesdaniel** [comment]
@kyliau I set the "angular.enable-experimental-ivy-prompt" to true, than I went to one of my component template file (.html), then tried to Ctrl+click on a custom componente inside it:

See if this piece of log helps you:

Info 62   [2:39:53.668] -----------------------------------------------
Info 63   [2:39:54.511] Before ensureProjectForOpenFiles:
Info 64   [2:39:54.511] After ensureProjectForOpenFiles:
Err 65    [2:39:54.732] No config file for c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/src/app/modules/payments-and-transactions/transmit-files/transmit-files/send-files/file-transmission/file-transmission.component.html
Err 66    [2:39:54.734] No config file for c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/src/app/modules/payments-and-transactions/transmit-files/transmit-files/send-files/step-choose-account/step-choose-account.component.html
Err 67    [2:39:54.734] No config file for c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/src/app/modules/payments-and-transactions/transmit-files/transmit-files/transmit-files.component.html
Info 68   [2:39:56.206] DirectoryWatcher:: Triggered with c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular/node_modules 1 undefined Project:  WatchType: node_modules for closed script infos in them
Info 69   [2:39:56.206] Elapsed:: 0.15729999542236328ms DirectoryWatcher:: Triggered with c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular/node_modules 1 undefined Project:  WatchType: node_modules for closed script infos in them
Info 70   [2:39:56.206] DirectoryWatcher:: Triggered with c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules 1 undefined Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json WatchType: Failed Lookup Locations
Info 71   [2:39:56.207] Elapsed:: 0.03710097074508667ms DirectoryWatcher:: Triggered with c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules 1 undefined Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json WatchType: Failed Lookup Locations
Info 72   [2:39:56.207] DirectoryWatcher:: Triggered with c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 73   [2:39:56.207] Elapsed:: 0.02459895610809326ms DirectoryWatcher:: Triggered with c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/node_modules 1 undefined Project: /dev/null/inferredProject1* WatchType: Failed Lookup Locations
Info 74   [2:39:56.207] DirectoryWatcher:: Triggered with c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular 1 undefined Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json WatchType: Wild card directory
Info 75   [2:39:56.207] Elapsed:: 0.1119999885559082ms DirectoryWatcher:: Triggered with c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__ :: WatchInfo: c:/users/danielch/desenvolvimento/abcbrasil.ib.corporate.angular 1 undefined Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json WatchType: Wild card directory
**_>>>>> maybe here ?_**   **<<<<<<<<<<<<<<<<<<<<<<**
Info 76   [2:39:56.234] Enabling Ivy language service for c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json.
Info 77   [2:39:58.489] Starting updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json
Info 78   [2:40:8.911] Finishing updateGraphWorker: Project: **c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json Version: 3 structureChanged: true Elapsed: 10421.50870102644ms**
======================================
Info 79   [2:40:8.911] Project 'c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json' (Configured)
Info 80   [2:40:8.911] 	Files (1520)

Info 81   [2:40:8.911] -----------------------------------------------
Info 82   [2:40:28.394] Before ensureProjectForOpenFiles:
Info 83   [2:40:28.395] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
Info 84   [2:40:28.405] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 4 structureChanged: true **Elapsed: 9.198698997497559ms**
Info 85   [2:40:28.405] Project '/dev/null/inferredProject1*' (Inferred)
Info 86   [2:40:28.405] 	Files (0)

Info 87   [2:40:28.405] -----------------------------------------------
Info 88   [2:40:28.405] After ensureProjectForOpenFiles:
Info 89   [2:40:28.467] Starting updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json
Info 90   [2:40:28.810] Finishing updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json Version: 4 structureChanged: true Elapsed: **342.9574000239372ms**
Info 91   [2:40:28.810] Project 'c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json' (Configured)
Info 92   [2:40:28.810] 	Files (1521)

Info 93   [2:40:28.810] -----------------------------------------------
Info 94   [2:40:28.899] Starting updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json
Info 95   [2:40:29.147] Finishing updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json Version: 5 structureChanged: true Elapsed: **247.15900099277496ms**
Info 96   [2:40:29.147] Project 'c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json' (Configured)
Info 97   [2:40:29.147] 	Files (1522)

Info 98   [2:40:29.147] -----------------------------------------------
Info 99   [2:40:29.174] Starting updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json
Info 100  [2:40:29.397] Finishing updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json Version: 6 structureChanged: true Elapsed: **223.10109901428223ms**
Info 101  [2:40:29.397] Project 'c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json' (Configured)
Info 102  [2:40:29.397] 	Files (1523)

Info 103  [2:40:29.398] -----------------------------------------------
Info 104  [2:40:29.427] Starting updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json
Info 105  [2:40:29.633] Finishing updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json Version: 7 structureChanged: true Elapsed: **205.04999899864197ms**
Info 106  [2:40:29.633] Project 'c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json' (Configured)
Info 107  [2:40:29.633] 	Files (1524)

Info 108  [2:40:29.633] -----------------------------------------------
Info 109  [2:40:29.797] Search path: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/src/app/modules/payments-and-transactions/transmit-files/transmit-files/select-files
Info 110  [2:40:29.802] For info: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/src/app/modules/payments-and-transactions/transmit-files/transmit-files/select-files/select-files.component.ts :: Config file name: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json
Info 111  [2:40:29.802] `remove Project::
Info 112  [2:40:29.802] Project '/dev/null/inferredProject1*' (Inferred)
Info 113  [2:40:29.802] 	Files (0)

Info 114  [2:40:29.803] -----------------------------------------------
Info 115  [2:40:30.119] Starting updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json
Info 116  [2:40:30.819] Finishing updateGraphWorker: Project: c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json Version: 8 structureChanged: true Elapsed: **700.4605010151863ms**
Info 117  [2:40:30.820] Project 'c:/Users/danielch/Desenvolvimento/ABCBrasil.IB.Corporate.Angular/tsconfig.json' (Configured)
Info 118  [2:40:30.820] 	Files (1525)

Info 119  [2:40:30.820] -----------------------------------------------

**Comment by CaselIT** [comment]
> 
> 
> @CaselIT @chavesdaniel Could you please open a new issue and let us know when did the slowness occur?
> 
>     * Were you typing in TS source code, or Angular template?
> 
>     * If Angular template, was it an inline template or external file?
> 
>     * Were you expecting Angular results, or TypeScript results?
> 
>     * How big is your project?
> 
>     * Please consider uploading the logs to help us understand your setup.

Sorry forgot yo mention. This was in a typescript file (with no components or service, but it does not seem to matter), so I was expecting typescript result. I tried an a simple variable `const foo: string[] = []` so nothing complex regarding types.

Regarding how bit is the project, not sure how to quantify. I count ~140 `@Component` and ~70 `@Injectable`.

I'll try to find some time to investigate this a bit more and provide logs / reproduction in a new issue. Thanks for the reply in the meantime

**Comment by chavesdaniel** [comment]
> > @CaselIT @chavesdaniel Could you please open a new issue and let us know when did the slowness occur?
> > ```
> > * Were you typing in TS source code, or Angular template?
> > 
> > * If Angular template, was it an inline template or external file?
> > 
> > * Were you expecting Angular results, or TypeScript results?
> > 
> > * How big is your project?
> > 
> > * Please consider uploading the logs to help us understand your setup.
> > ```
> 
> Sorry forgot to mention. This was in a typescript file (with no components or service, but it does not seem to matter), so I was expecting typescript result. I tried an a simple variable `const foo: string[] = []` so nothing complex regarding types.
> 
> Regarding how bit is the project, not sure how to quantify. I count ~140 `@Component` and ~70 `@Injectable`.
> 
> I'll try to find some time to investigate this a bit more and provide logs / reproduction in a new issue. Thanks for the reply in the meantime

Did it, #1168
