### ISSUE TITLE
Template variables (let-) in <ng-template> are not inferred

### ISSUE THREAD

**Issue by snebjorn** [angular/vscode-ng-language-service#1136]
**Describe the bug**

The types from `TemplateRef<C>` are not inferred in `<ng-template>`.

_Experimental-ivy is enabled_

**To Reproduce**
Given
```ts
@Component({ selector: 'app-test', template: '' })
export class TestComponent {
  @Input() ref?: TemplateRef<{ $implicit: string; foo: boolean; bar: number }>;
}
```
Then `implicit`, `foo` and `bar` are all any
```html
<app-test [ref]="tmpl"></app-test>

<ng-template #tmpl let-implicit let-foo="foo" let-bar="bar">
  {{ implicit }}
  {{ foo }}
  {{ bar }}
</ng-template>
```

**Expected behavior**

As `TemplateRef<{ $implicit: string; foo: boolean; bar: number }>;` have the types defined I was expecting

```html
<ng-template #tmpl let-implicit let-foo="foo" let-bar="bar">
  {{ implicit }} to be a string
  {{ foo }}  to be a boolean
  {{ bar }} to be a number
</ng-template>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1266245/108578918-d2f1a200-7324-11eb-9085-fb616ae52ce9.png)

**Additional context**

> Angular Language Service Version: 11.2.2
> 
> VSCode:
> Version: 1.53.2 (user setup)
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19041

Related to https://github.com/angular/angular/issues/28731

**Comment by Airblader** [comment]
I don't think the template's context type should be inferred from it being passed to some other place. This makes the type definition very "non-local", and its semantically incorrect. Rather, the template should somehow define the type that it needs and then you get an error when you pass it to `app-test` because the type does not match the type of the input. See the related issue.

**Comment by Airblader** [comment]
This problem can be nicely translated into a language such as TypeScript. Inferring the type like this is basically saying that

```
function fn(x) {
}

fn(42);
```

should infer the function argument `x` to be `number`. This is problematic for many reasons. For example, should it be `number` or `42`? What if there's another `fn('test')`, should it now be inferred to be `number | string` resp. `42 | 'test'`? Basically the way the function is called _anywhere else_ changes how its signature is inferred, which basically means that you need to scan for any place that uses this function and combine all of these call sites.

Needless to say, TypeScript's type inference doesn't work that way.

---

With templates, all of this is essentially the same. Angular would have to analyze _usages_ of the template to infer the type _of_ the template('s context). Which also means that if you change what you pass, it suddenly breaks in a very different part of the application (and is, computationally, very costly). For example, what if that component itself has a generic type argument?

```
// Have fun finding all usages of MyComponent, never mind that this breaks locality and is in general impossible (lazy modules etc.)
export class MyComponent<T> {
  @Input() tpl: TemplateRef<T>;
}
```

**Comment by snebjorn** [comment]
> I don't think the template's context type should be inferred from it being passed to some other place. This makes the type definition very "non-local", and its semantically incorrect. Rather, the template should somehow define the type that it needs and then you get an error when you pass it to `app-test` because the type does not match the type of the input. See the related issue.

That would make sense.
Essentially what I'm after is type safety in `<ng-template>`.

Also if we started defining the context type on `<ng-template>` via something like `[ngTemplateContextType]` then we could probably also get rid of the rather confusing `let-` syntax.

**Comment by Airblader** [comment]
> we could probably also get rid of the rather confusing let- syntax

You still need a way to actually define the template-local variables, and keep in mind thst structural directives require this to desugar, plus of course compatibility; I don't think that'd go anywhere, or would even have to.

All we need is be able to type template contexts, and for Angular to type-check this where reasonably possible.

But this really isn't a language service issue. The core framework simply doesn't allow typing the context at the moment.

**Comment by atscott** [comment]
@Airblader is correct, this isn't an issue with the language service but a limitation in the compiler. As noted, this is related to https://github.com/angular/angular/issues/28731
