### ISSUE TITLE
HTML tag can't be renamed.

### ISSUE THREAD

**Issue by erqk** [angular/vscode-ng-language-service#1139]
**Describe the bug**
Cannot simply rename tag in HTML when F2 button is pressed.

**To Reproduce**

1. Open any HTML docs
2. select any tag
3. Press F2 or Rename Symbol on right click menu
4. Error message get.

**Expected behavior**

Should be able to rename the tag when F2 button is pressed.

**Screenshots**

![image](https://user-images.githubusercontent.com/64851043/108687883-3866ae00-7532-11eb-99f5-71f45637b323.png)

**Comment by atscott** [comment]
Closing, as this doesn't appear to be an issue anymore when using the latest version and having Ivy enabled.
