### ISSUE TITLE
Extension prevents TS from reporting errors when an AngularJS project is open

### ISSUE THREAD

**Issue by mrahhal** [angular/vscode-ng-language-service#114]
I have a legacy AngularJS application that I develop with TS + vscode, and I have this extension installed. TypeScript won't report errors at all as long as this extension is active.

Took me a while to rule this extension out, but this is definitely the cause. For now, I've disabled it in my AngularJS workspace.

**Comment by tstackhouse** [comment]
I've noticed that sometimes my machine would start spinning and intellisense for my TypeScript code would break as well.  I'm in the midst of preparing an AngularJS project to migrate to Angular and having the TypeScript errors is kind of important.  I has been working around it with a restart (including having to use Task Manager to kill VSCode after exiting) when it happened, which would clear it up for a while, but it would always hang again.  I'll try this and see if it helps.

**Comment by kyliau** [comment]
In the new extension, there's a mechanism to detect non-Angular projects and disable the language service completely. Please open a new issue if this problem persists.
