### ISSUE TITLE
No more completion for components / HTML tags in Ivy mode

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/vscode-ng-language-service#1140]
**Describe the bug**

When enabling the Ivy language service, there is no more components / HTML tags completion/suggestions at all.

**To Reproduce**

1. `npm i @angular/cli -g`
2. `ng new demo --inline-template` (and say "Yes" to strict mode)
3. `cd demo`
4. `code .`
5. Enable extension's Ivy mode when proposed
5. Try writing any HTML tag in `AppComponent` template: no autocomplete at all
6. `ng g component demo`
7. Try writing `<app-de` in `AppComponent` template: no autocomplete at all (but if I manually write the full tag, the language service is OK with it)

Note: there is the same issue with external templates (in this case you have HTML tags autocomplete because it's a HTML file, but you have no more components tags autocomplete).

**Expected behavior**

Components / HTML tags should be suggested.

**Logs**

```
[Info  - 4:44:27 PM] Angular language server process ID: 6223
[Info  - 4:44:27 PM] Using typescript/lib/tsserverlibrary v4.1.5 from /Users/xxx/.vscode/extensions/angular.ng-template-11.2.2/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 4:44:27 PM] Using @angular/language-service/bundles/ivy v11.2.1 from /Users/xxx/.vscode/extensions/angular.ng-template-11.2.2/node_modules/@angular/language-service/bundles/ivy.js
[Info  - 4:44:27 PM] Log file: /Users/xxx/Library/Application Support/Code/logs/20210222T163701/exthost1/Angular.ng-template/nglangsvc.log
[Info  - 4:44:30 PM] Enabling Ivy language service for /Users/xxx/xxx/xxx/lsivyissue/tsconfig.json.
```

The log file is empty.

**Additional context**

VS Code version: 1.53.2
Extension and Angular project version: 11.2.2
OS: macOS 11.2.1 (Intel)
No other extension.

**Comment by reed-lawrence** [comment]
+ 1. 

I have the same issue. As a quick fix, disabling the experimental Ivy features in VS Code settings, the completion returns to expected behavior.

**Comment by CthulhuOfStars** [comment]
Same behavior + always crash

Thanks

**Comment by jpike88** [comment]
Same problem, enabling the ivy engine makes it no longer recognise component tags, something is broken

**Comment by tnastula** [comment]
Same problem. @reed-lawrence suggested good temporary solution.
