### ISSUE TITLE
When Ivy is enabled, TypeScript code is super slow

### ISSUE THREAD

**Issue by hinok** [angular/vscode-ng-language-service#1176]
**Describe the bug**

TypeScript autocompletion and navigation is super slow to a point where normal work is not anymore possible.
`Loading...` tooltips and broken autocompletion complicates working with TypeScript so much that at some point day-to-day work is exhausting.

**To Reproduce**

1. Have a "big angular" project...
2. Create a very simple file that exports one thing and import "2 or 3 things" like in videos below
3. Try to use `cmd|ctrl` + `click` or use autocompletion / IntelliSense

**Expected behavior**

Navigation after `cmd|ctrl` + `click` should be "quick".
IntelliSense should be "quick".
There should NOT be any `Loading...` tooltip that lasts forever.

**Logs**

> Log file gives us deep insight into the behavior and performance of the extension, so we strongly
> recommend you upload it.
> 
> Go to the command palette (Cmd+Shift+P on Mac, Ctrl+Shift+P on Windows), search `Open Angular Server log`
> 

I cannot provide logs because they reveal project structure, files names and I cannot take the risk of exposing such informations, sorry 😓

**Videos**

When `ivy` **disabled**

https://user-images.githubusercontent.com/1313605/110027837-c745a880-7d32-11eb-838a-a4ab9947eca4.mp4

When `ivy` **enabled**

https://user-images.githubusercontent.com/1313605/110027910-e0e6f000-7d32-11eb-8038-6f80a9771f50.mp4

**Additional context**

- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `11.2.5`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.54.0`

**Related issues**

- https://github.com/angular/vscode-ng-language-service/issues/1104
- https://github.com/angular/vscode-ng-language-service/issues/1168

**Comment by atscott** [comment]
Re-opening since the commit which fixed this was reverted. We should be able to get this back in to a release this week.
