### ISSUE TITLE
Unresponsive: Performance Issue

### ISSUE THREAD

**Issue by bhaireshm** [angular/vscode-ng-language-service#1265]
- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `11.2.9`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 12220,
		"activateCallTime": 32,
		"activateResolvedTime": 989,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Angular.ng-template",
				"_lower": "angular.ng-template"
			},
			"activationEvent": "onLanguage:typescript"
		}
	},
	"runtimeErrors": []
}
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
