### ISSUE TITLE
ctrl + click on template variable not working.

### ISSUE THREAD

**Issue by sanket-bhalerao** [angular/vscode-ng-language-service#1280]
Issue Type: <b>Bug</b>

ctrl + click on template variable not working.

create angular project
use a ts variable in template, try to ctrl + click on the variable, nothing happens.

Extension version: 11.2.10
VS Code version: Code - Insiders 1.56.0-insider (48387dfc3d691558404cff1ea2582e3862a40080, 2021-04-13T05:15:20.350Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.81GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfilebutton:30280634
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2ct:30286873

```

</details>

**Comment by atscott** [comment]
Hi @sanket-bhalerao  - I wasn't able to reproduce this issue. Please ensure that your [Angular compiler options](https://angular.io/guide/angular-compiler-options) are appropriately configured. Ideally, set `"strictTemplates": true` in the `tsconfig` and enable the experimental Ivy version in the settings.
