### ISSUE TITLE
angular language service doesn't run correctly

### ISSUE THREAD

**Issue by shadoowz97** [angular/vscode-ng-language-service#1290]
one week ago,my angular language service doesn't run correctly.
all third-part directive will show an error like pic below

<img width="451" alt="screenshoot" src="https://user-images.githubusercontent.com/33770265/115108634-23435400-9fa4-11eb-9114-efebccafab81.png">
I'm pretty sure I've added all the dependencies to myproject ,<b>because the whole project works correctly</b> the log shows that 

> Disabling language service for /myproject/e2e/tsconfig.json because it is not an Angular project ('@angular/core' could not be found).

what's wrong with my vscode?

**Comment by atscott** [comment]
@shadoowz97 - Could you please provide some more information? There's not enough here for us to determine what's going on in your project. Are you able to provide an example github repository that we can use to reproduce this issue?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
