### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pedrammsafari** [angular/vscode-ng-language-service#1292]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `11.2.11`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Pedram\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kfeinUI** [comment]
It's been a problem for me. Hammers my system to the point that it got the company IT's attention. A possible fix just made it in a few days ago, so hoping the next release fixes it.

https://github.com/angular/vscode-ng-language-service/pull/1288

**Comment by kyliau** [comment]
This has been fixed in https://github.com/angular/vscode-ng-language-service/releases/tag/v11.2.12
