### ISSUE TITLE
Automatically disable extension for non-Angular projects

### ISSUE THREAD

**Issue by marshall007** [angular/vscode-ng-language-service#130]
Related to #62, it would be nice if we could come up with a heuristic for determining whether or not a given Typescript project is using Angular and only enable the extension in that case. I would think detecting any references to `@angular/*` in the project's `package.json` would be good enough.

It's possible to disable the extension manually for a given workspace, but this is not ideal when the majority of Typescript projects you work on are not Angular related.

**Comment by marshall007** [comment]
To be clear, I'm not saying the extension needs to be properly "disabled" in the same way a user would manually disable it (I don't even think you can programmatically disable extensions in the API). Rather, I'm just saying we should avoid starting the language client and server if possible.

**Comment by kyliau** [comment]
This has been implemented.
https://github.com/angular/vscode-ng-language-service/blob/d4a89884ca7ff586090121556383fa2bd8ba7f6d/server/src/session.ts#L419-L433
