### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AlejandroQR23** [angular/vscode-ng-language-service#1305]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `11.2.12`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\alqr2\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and follow the instructions in the issue template. Attaching the cpu profile would also be helpful. Thanks!
