### ISSUE TITLE
[Feat] Setting to control the Output window verbosity

### ISSUE THREAD

**Issue by mtycholaz** [angular/vscode-ng-language-service#131]
Would be great to have a setting to control the Output window verbosity. Seems very chatty right now, and drowns out other logs. Potentially could be an enum flag with the following possible values (INFO, WARN, ERROR, TRACE)

`"angularLanguageService.outputVerbosity": "WARN|ERROR"` //reports on only warnings and errors

**Comment by snewell92** [comment]
Slightly related to #187 - the same PR in that issue, #195 could be easily modified to take in an option instead of passing in `Never` all the time.

**Comment by chuckjaz** [comment]
Fixed with #195.
