### ISSUE TITLE
VS Code extension getting config errors for VS Code resources

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/vscode-ng-language-service#1315]
# 🐞 bug report

### Is this a regression?

I don't know

### Description

The extension is scanning VS Code resources every 20 seconds and getting errors because it can't find a config file for them.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Open a new Angular Project (I just downloaded a fresh one from stackblitz).
2. `npm install`
3. Open the output in VS Code and set it to `Angular Language Service`
4. Navigate to any Angular related file, change something and safe
5. Wait a few seconds

### **Logs**

```
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2018.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2017.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2016.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2017.object.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2016.array.include.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.reflect.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.proxy.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.promise.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.iterable.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.generator.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.core.d.ts
[Error - 17:25:31] Script info not found for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2018.regexp.d.ts
[Error - 17:25:31] Script info not found for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2018.promise.d.ts
[Error - 17:25:31] Script info not found for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2018.intl.d.ts
[Error - 17:25:31] Script info not found for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts
[Error - 17:25:31] Script info not found for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2018.asyncgenerator.d.ts
[Error - 17:25:31] Script info not found for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2017.intl.d.ts
[Error - 17:25:31] No config file for <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2017.string.d.ts
```

<pre><code>
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2016.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2017.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2018.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.core.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.generator.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.iterable.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
FileName: <My User Dir>/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.es2015.promise.d.ts ProjectRootPath: undefined
    Projects: /dev/null/inferredProject1*
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>11.2.10
</code></pre>

Extension Version:
<pre><code>11.2.12
</code></pre>

VSCode Version:
<pre><code>1.55.2
</code></pre>

Operating System:
<pre><code>Windows 10
</code></pre>

**Comment by jeweljacob387** [comment]
Same issue here. It was working fine until Angular 12, but with forced `angular.view-engine: true` .
But from Angular 13 Legacy View Engine is incompatible. 
![image](https://user-images.githubusercontent.com/22506100/150297580-da6eba47-566f-4585-8fb6-bf1ee3ad71ce.png)


Please find below he Project details:
```
Angular CLI: 13.1.3
Node: 14.18.1
Package Manager: npm 6.14.15
OS: win32 x64
```
Angular Language service extension : `v13.1.1`

Logs:
```
[Info  - 1:08:41 pm] Angular language server process ID: 5208
[Info  - 1:08:41 pm] Using typescript/lib/tsserverlibrary v4.5.4 from d:\Portals\**\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 1:08:41 pm] Using @angular/language-service v13.1.2 from c:\Users\jewel.jacob\.vscode\extensions\angular.ng-template-13.1.1\node_modules\@angular\language-service\index.js
[Info  - 1:08:41 pm] Log file: c:\Users\jewel.jacob\AppData\Roaming\Code\logs\20220120T095213\exthost6\Angular.ng-template\nglangsvc.log
[Error - 1:09:06 pm] No config file for d:/Portals/**/ITAdminPortal/src/app/profiles/components/candidate-detail/verify-popup-candidate/verify-popup-candidate.component.html
[Error - 1:09:06 pm] No config file for d:/Portals/**/ITAdminPortal/src/app/profiles/components/candidate-detail/verify-popup-candidate/verify-popup-candidate.component.html
[Error - 1:09:06 pm] No config file for d:/Portals/**/ITAdminPortal/src/app/profiles/components/candidate-detail/verify-popup-candidate/verify-popup-candidate.component.html
[Error - 1:09:06 pm] No config file for d:/Portals/**/ITAdminPortal/src/app/profiles/components/candidate-detail/verify-popup-candidate/verify-popup-candidate.component.html
[Info  - 1:09:13 pm] Enabling Ivy language service for d:/Portals/**/ITAdminPortal/tsconfig.json.
```
