### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by ghost** [angular/vscode-ng-language-service#132]
The plugin works for a while, then completions stops working for no good reason. Sometimes a restart of VSCode helps. No errors in the console.

macOS, latest June update of VSCode. Latest plugin version.

**Comment by cgatian** [comment]
Also seeing this issue.  I have code that's in a folder sibling to app (src/@myStuff) and it seems to crash and is unable to provide intellisense

**Comment by cgatian** [comment]
Looks like my issue is related to #99

**Comment by Davilink** [comment]
It's will be cool, if we can have a « Restart Angular Language service » or something like that. The OmniSharp Extensions have that mechanism. I prefer to restart the extension than restarting vscode.

**Comment by dylanvdmerwe** [comment]
As a note this is still consistently happening. Working in ng 6 or 7 projects for an extended period of time guarantees that this plugin will stop working for whatever reason and then VS Code needs to be restarted. I wish I could help pinpoint why it stops, but I have no idea. Version 0.1.10

**Comment by ayazhafiz** [comment]
Restarting language service available since e0f21ec4727175dc5b8cb9baa560c5f4ba55f948. Please open a new issue if you are experiencing this.
