### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SAElizondoR** [angular/vscode-ng-language-service#1320]
- Issue Type: `Performance`
- Extension 
Name: `ng-template`
- Extension Version: `11.2.13`
- OS Version: `Linux x64 5.4.0-72-generic`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/Angular.ng-template-unresponsive.cpuprofile.txt`
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/6416517/Angular.ng-template-unresponsive.cpuprofile.txt)
Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
@SAElizondoR Can you provide some additional information about your project and the high CPU load? Is it an ongoing issue? We would expect high CPU load while compiling the application. Since your profile is only appears to be 5 seconds, I'm not sure this is out of the ordinary.

**Comment by SAElizondoR** [comment]
The project was stuck, but I already found out that the problem was my on machine, not in VSC. Thanks for the reply.
