### ISSUE TITLE
Rename Symbols in Templates.

### ISSUE THREAD

**Issue by simonnagl** [angular/vscode-ng-language-service#133]
When I rename a symbol with VS-Code [F2] in a Component it would be nice if it gets renamed in the referenced template too.

**Comment by kukjevov** [comment]
I think it is duplicate of https://github.com/angular/vscode-ng-language-service/issues/29

**Comment by simonnagl** [comment]
@kukjevov Yes, I think so.

I added my wording to the open task so others searching like me will not open another duplicate.
