### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by alexjesjimalex** [angular/vscode-ng-language-service#1338]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `11.2.14`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.56.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MZT-SI~1\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
