### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kamvir** [angular/vscode-ng-language-service#1355]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `11.2.14`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Viraj-Pc\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
Hi @kamvir - Can you provide more details?

- Do you have a project we can use to reproduce the issue?
- Is the issue persistent? We expect high CPU load when the Angular is compiling your project but this should go away when finished.
- Can you attach the cpu profile? You've only provided the path on your system.
- Can you provide the Angular Server logs (run the Open Angular server log command)

Thanks.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
