### ISSUE TITLE
Parse Error - Erratic behavior

### ISSUE THREAD

**Issue by mahidaturgana** [angular/vscode-ng-language-service#137]
Occasionally the Angular Language Service parsing errors get out of whack and complain about errors that do not actually exist (red underline). Upon hovering over the supposed error, the details provided are very odd and erroneous (See screenshot).

I have been unable to pinpoint a reliable method for reproduction.

The only resolution is to restart VSCode.

VSCode Details:
Version 1.14.2
Shell 1.6.6
Renderer: 56.0.2924.87
Node 7.4.0

Angular Language Service: 0.1.4

Machine has Node 8.1.0 installed.

![image](https://user-images.githubusercontent.com/771594/28930591-0efc776a-7839-11e7-8a35-2b285de2787d.png)

**Comment by ayazhafiz** [comment]
This is probably a combination of the parse errors known with the Angular compiler (https://github.com/angular/angular/issues/31898). We should see this resolved when the language service is rewritten to use the new Ivy compiler. Please file a new issue if you are experiencing this.
