### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by enrique-esteban** [angular/vscode-ng-language-service#1381]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `12.0.2`
- OS Version: `Linux x64 5.4.0-73-generic`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by enrique-esteban** [comment]
"Do you have a project we can use to reproduce the issue?", no sorry, its private, but I fixed it when I activated strict mode ("strictTemplates": true) in project.

**Comment by atscott** [comment]
@enrique-esteban Thanks for the info. I'm going to close this as likely not an issue. strictTemplates doesn't affect CPU load in any way so this was likely just a result of high CPU during initial compilation.
