### ISSUE TITLE
Upgrade to TS 4.3

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#1386]
Features of interest:
- Go-to-Definition on Non-JavaScript File Paths [link](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#go-to-def-non-js)
- updated API for `getCompletionEntryDetails` (see PR #1384)
- Lazier Calculations in --incremental and --watch Compilations [link](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#lazier-incremental)
   - should not affect our codebase but good to make sure

**Comment by atscott** [comment]
Not updating to 4.3 is causing an issue with `@Input` and `override` - see #1424
