### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by inventd** [angular/vscode-ng-language-service#1389]
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/6569645/Angular.ng-template-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `12.0.3`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Diego\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
Can you provide more details?

- Do you have a project we can use to reproduce the issue?
- Is the issue persistent? We expect high CPU load when the Angular is compiling your project but this should go away when finished. I see that the cpu profile you've attached is just 5 seconds during/after activation. This is when we would expect CPU load to be high.
- Can you provide the Angular Server logs (run the Open Angular server log command)

Thanks.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
