### ISSUE TITLE
Custom pipes have incorrect type

### ISSUE THREAD

**Issue by atscott** [angular/vscode-ng-language-service#1404]
We are also experiencing issues like this with custom pipes. This pipe was working just fine previously, but now everything that gets returned is typed as "null". I tried playing with the method signatures (which are the same as the `async` pipe), but it is not working:

The expected type:

![image](https://user-images.githubusercontent.com/362329/120813726-2aa2ca80-c51c-11eb-9a18-9496c0b09c78.png)

The actual type result:

![image](https://user-images.githubusercontent.com/362329/120813168-a6504780-c51b-11eb-8dae-d4085aae7b9f.png)

```

  transform<U>(
    potentialObservable: null,
    config?: string | Observable<string>,
    renderCallback?: NextObserver<U>
  ): null;
  transform<U>(
    potentialObservable: undefined,
    config?: string | Observable<string>,
    renderCallback?: NextObserver<U>
  ): undefined;
  transform<U>(
    potentialObservable: ObservableInput<U>,
    config?: string | Observable<string>,
    renderCallback?: NextObserver<U>
  ): U;
  transform<U>(
    potentialObservable: ObservableInput<U> | null | undefined,
    config: string | Observable<string> | undefined,
    renderCallback?: NextObserver<U>
  ): U | null | undefined {
    //    ... do the work
    return this.renderedValue as U;
  }
```

This pipe is imported via a shared module:

```
const declarations = [
  // ...
  PushPipe
  // ...
];

@NgModule({
  declarations: [...declarations],
  imports: [
    CommonModule
  ],
  providers: [],
  exports: [...declarations]
})
export class TdCommonAngularModule {
  static forRoot(): ModuleWithProviders<TdCommonAngularModule> {
    return {
      ngModule: TdCommonAngularModule,
      providers: [ ]
    };
  }
}
```

Also just to clarify, this is a regression when we updated to the latest Angular & VSCode Language Plugin a few days ago.

_Originally posted by @lincolnthree in https://github.com/angular/vscode-ng-language-service/issues/1388#issuecomment-854748546_

**Comment by lincolnthree** [comment]
@atscott Thanks for splitting this out. I probably should have done so but thought it might be related :)

**Comment by lincolnthree** [comment]
@atscott `strictTemplates` is already enabled. This is the only pipe that stopped working. (It's also the only one with an overloaded method type-signature, though.)

```
  "angularCompilerOptions": {
    "enableIvy": true,
    "skipTemplateCodegen": false,
    "strictInjectionParameters": true,
    "strictMetadataEmit": false,
    "strictTemplates": true
  }
```

**Comment by atscott** [comment]
@lincolnthree could you provide some more information?  I couldn't reproduce this myself so I'll need something more to work with.

* A more complete example (stackblitz would be great).
* The version of the extension when this was working and the version that it stopped working with

**Comment by lincolnthree** [comment]
@atscott I'll do my best. Thanks. I don't remember which version it stopped with :( It's been a few weeks. Maybe 2 weeks.

**Comment by lincolnthree** [comment]
@atscott So, this appears to be an issue with my vscode workspace. I don't know why, but when I open my project in a brand new (unsaved) workspace, the type completion/intellisense functions normally for this pipe, yet it does not when I load my year-old workspace.

These are the only custom settings in the workspace that I know of:

```
    "settings": {
      "java.configuration.updateBuildConfiguration": "disabled",
      "typescript.tsdk": "topdecked-unified/node_modules/typescript/lib",
    }

```

**Comment by atscott** [comment]
@lincolnthree Is it possible that your workspace settings overwrite the language service to use legacy View Engine? I'm not sure if there's anything actionable here at the moment since we don't have any reproduction and it seems to be working on a clean workspace.

**Comment by lincolnthree** [comment]
@atscott I don't believe so, verified view-engine is off in the settings, but I'm still trying to dig in and see what's actually different. I'm at a bit of a loss. 

user:
![image](https://user-images.githubusercontent.com/362329/122108041-c6201f00-cde9-11eb-82a5-69663deef3d1.png)

workspace:
![image](https://user-images.githubusercontent.com/362329/122108129-d637fe80-cde9-11eb-98d2-915699686df7.png)

**Comment by atscott** [comment]
Closing since we don't have a way to reproduce this issue. If you find a way to reproduce it, please file a new issue and we can go from there. Thanks!
