### ISSUE TITLE
Intellisense don't work as expected

### ISSUE THREAD

**Issue by pavangayakwad** [angular/vscode-ng-language-service#1415]
The left side is the VS code shows "the issue" and the right side: 'what is expected'.

![vscode-vs-webstorm-angular](https://user-images.githubusercontent.com/1834890/122214965-56cd2c80-cec8-11eb-8917-6ffb62c9a9ac.gif)

**Comment by atscott** [comment]
Closing, as this is unrelated to the Angular Language service extension. We don't provide any features for style files.

**Comment by pavangayakwad** [comment]
Let me show you another instance then. Is this not related as well?

![vscode-vs-webstorm-angular](https://user-images.githubusercontent.com/1834890/124104141-9a569780-da7f-11eb-9fff-aea34562db08.gif)

**Comment by atscott** [comment]
@pavangayakwad yes, this will be fixed by https://github.com/angular/angular/pull/42640. (issue reported in #1420)
