### ISSUE TITLE
Component Directive can't show IntelliSense properly when using any Structural Directives with it

### ISSUE THREAD

**Issue by doggy8088** [angular/vscode-ng-language-service#1420]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: `Not sure specific version`

### Description

See **Reproduction**.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. Clone sample project

    ```sh
    git clone https://github.com/coolrare/dct-110012.git
    cd dct-110012
    npm install
    code .
    ```

2. Open `src\app\app.component.html` file, check the Line 12.

    ```html
    <app-article *ngFor="let item of (data$ | async); let i=index" [item]="item" [i]="i" (delete)="removeArticle($event)">
    </app-article>
    ```

    The VSCode with Angular Language Service do know the `item` property.

    ![image](https://user-images.githubusercontent.com/88981/122676821-3e377c00-d212-11eb-95f5-c6d4d07e9987.png)

3. Remove the `[item]="item"` property binding and re-type `[item` again. There is NO intellsense for the property.

    ![image](https://user-images.githubusercontent.com/88981/122676860-6921d000-d212-11eb-87d4-876be0e2ecd1.png)

4. If I wrap the `<app-article>` directive with a `<ng-container>` directive and move `*ngFor` into it. Then problem solved.

    ```html
    <ng-container *ngFor="let item of (data$ | async); let i=index">
      <app-article [item]="i" [i]="i" (delete)="removeArticle($event)"></app-article>
    </ng-container>
    ```

    ![image](https://user-images.githubusercontent.com/88981/122676962-d03f8480-d212-11eb-8fe8-ed6ee0972aec.png)

**Expected behavior**

I expected to have IntelliSense for property binding or event binding even the `*ngFor` is used in a Component Directive.

## 🌍  Your Environment
**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.5
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

Extension Version:
<pre><code>
v12.0.5
</code></pre>

VSCode Version:
<pre><code>
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
</code></pre>

Operating System:
<pre><code>
Windows 10 Version 10.0.19042.1052
</code></pre>

**Anything else relevant?**

N/A

**Comment by atscott** [comment]
@doggy8088 This fix was included in the `12.1.2` release last week.

**Comment by pavangayakwad** [comment]
The intellisense just don't work and it is not fixed. Similar reports raised #1415, #1420, #42640 were closed and restricting users to comment further.

![image](https://user-images.githubusercontent.com/1834890/128204389-544f8488-037b-4758-9efc-d4b037003999.png)

**Comment by atscott** [comment]
@pavangayakwad Do you have strictTemplates turned in for your project?

**Comment by pavangayakwad** [comment]
yes it is!
![image](https://user-images.githubusercontent.com/1834890/128362624-d556c79e-f7d1-42f3-8058-f0a9709c814a.png)

**Comment by pavangayakwad** [comment]
Interestingly, Just after posting my above comment, noticed in my vscode extension section asking me to reload for plugin update (to v12.2.0) and after the IDE reload, it is working. I will continue to use it and revert if the issue persist.

**Comment by pavangayakwad** [comment]
Happening again! Am I missing something? please suggest.
![image](https://user-images.githubusercontent.com/1834890/128520691-0cf702f0-a5b7-4bd6-8410-90ddc1ad7a49.png)

**Comment by pavangayakwad** [comment]
..and for normal angular components now. When I close and start vscode things just work fine, however, in between during the work, it suddenly refuse to resolve components. It is inconsistent but happening often.

![image](https://user-images.githubusercontent.com/1834890/128529425-ef23592d-fe07-40a1-aaca-2d0b4be56a2c.png)
