### ISSUE TITLE
Refactor Rename class opens files, doesn't save, with no save all

### ISSUE THREAD

**Issue by pauldaustin** [angular/vscode-ng-language-service#1429]
This could be in TypeScript, Angular or core code

1. Rename a class that is used in multiple other files
2. Save the class
3. Many of the other files are loaded into the editor but not saved. (why does it load the files into the editor, it should just be done in the background, it's an extra step to make sure they are all saved and then close them)
4. The Open editors shows unsaved files
5. Save All option in the File menu isn't shown.

This doesn't happen all the time, but at least 50%

**Comment by atscott** [comment]
Closing as this issue is with vscode.

Note that because of https://github.com/microsoft/vscode/issues/115354, we don't even participate in renames inside TypeScript files unless you are renaming inside a string literal (to enable renames for inline templates and pipe names).
