### ISSUE TITLE
Сhoosing tsconfig.json

### ISSUE THREAD

**Issue by Deeathwiing** [angular/vscode-ng-language-service#1433]
# 🚀 feature request

### Description
Hi, thank you for your ext )
Can u make the next feature: choosing tsconfig.json.
I have tsconfig.app.json and your ext don't work with it ((

P.S. I cant rename tsconfig.app.json (((

**Comment by atscott** [comment]
@Deeathwiing - Can you please provide a project that reproduces the problem and a description of what exactly is not working? Solution style tsconfigs _do_ generally work correctly with the extension so it could be an issue with your project setup. Does your main `tsconfig` reference the `tsconfig.app.json` file? 
```
 "references": [
    {
      "path": "./tsconfig.app.json"
    },
  ],
```

**Comment by Deeathwiing** [comment]
Sry, but it is commercial project, I cant provide a project (
tsconfig.app.json reference to tsconfig.json

**Comment by Deeathwiing** [comment]
![image](https://user-images.githubusercontent.com/47850355/125356463-e6061c80-e36e-11eb-9bd2-b24f5b11d0ba.png)

**Comment by atscott** [comment]
@Deeathwiing That looks like your `tsconfig.app.json` extending the base `tsconfig`. Is there any `tsconfig` that lists your `tsconfig.app.json` as a references via 
```
 "references": [
    {
      "path": "some/path/to/your/tsconfig.app.json"
    },
  ],
```

**Comment by Deeathwiing** [comment]
![image](https://user-images.githubusercontent.com/47850355/125357236-084c6a00-e370-11eb-9e5d-252b8e08b13a.png)
Its in tsconfig.json

**Comment by Deeathwiing** [comment]
Yep, our tsconfig.app.json extending the base tsconfig.json

**Comment by Deeathwiing** [comment]
And error in tsconfig: 
`Path to referenced tsconfig or to folder containing tsconfig.

Referenced project 'c:/work/******/******/src/projects/cms/tsconfig.app.json' must have setting "composite": true.ts`

**Comment by Deeathwiing** [comment]
But in tsconfig.app.json:
![image](https://user-images.githubusercontent.com/47850355/125357712-a5a79e00-e370-11eb-9d1b-adcfa52ef88c.png)

**Comment by Deeathwiing** [comment]
I was solved this problem,but in html I am getting error: Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.ngtsc(2584)

**Comment by Deeathwiing** [comment]
oh,lol )
I was restart vs code and it was work )
Thank you so much )))
Best regards )
