### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AbdulRafaySalsoftNew** [angular/vscode-ng-language-service#1446]
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/6806940/Angular.ng-template-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `12.1.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.58.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\2975~1.SAL\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
Can you provide some additional information about your project and the high CPU load? Is it an ongoing issue? We would expect high CPU load while compiling the application. Since your profile is only appears to be 5 seconds during the initial compilation, I'm not sure this is out of the ordinary.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
