### ISSUE TITLE
The server should check if the client has support for InsertReplaceEdits

### ISSUE THREAD

**Issue by predragnikolic** [angular/vscode-ng-language-service#1451]
Hello :wave: 

I am one of the maintainers of the [LSP-angular](https://packagecontrol.io/packages/LSP-angular) plugin for Sublime Text, and I noticed one issue when I tried to update the language server to a newer version (https://github.com/sublimelsp/LSP-angular/pull/43) :)

# 🐞 bug report

### Is this a regression?

This is sort of a regression, because previously the angular language server returned a `textEdit: TextEdit` in the completion item:

```
{'label': 'title', 'textEdit': {'range': {'start': {'line': 345, 'character': 13}, 'end': {'line': 345, 'character': 15}}, 'newText': 'title'}, 'detail': 'property', 'data': {'position': {'line': 345, 'character': 15}, 'kind': 'ngCompletionOriginData', 'filePath': '/home/predragnikolic/Documents/sandbox/ang-app/src/app/app.component.html'}, 'kind': 10, 'sortText': 'title'}
```
but now it returns a `textEdit: InsertReplaceEdit`:
```
{'label': 'title', 'data': {'filePath': '/home/predragnikolic/Documents/sandbox/ang-app/src/app/app.component.html', 'kind': 'ngCompletionOriginData', 'position': {'character': 15, 'line': 345}}, 'detail': 'property', 'kind': 10, 'sortText': '1', 'textEdit': {'replace': {'end': {'character': 15, 'line': 345}, 'start': {'character': 13, 'line': 345}}, 'newText': 'title', 'insert': {'end': {'character': 15, 'line': 345}, 'start': {'character': 13, 'line': 345}}}}
```

### Description

Currently the language server doesn't check if the client support the `textDocument.completion.completionItem.insertReplaceSupport`, and now it always returns a `textEdit: InsertReplaceEdit`. 

This breaks clients that currently do not implement `insertReplaceSupport`.

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [X] Angular Language Service server

**Expected behavior**

The server should check if the clinet has `insertReplaceSupport`, and if it does return `textEdit: InsertReplaceEdit` in the completion item. 

If the client do not support  `insertReplaceSupport`, do a graceful fallback and return `textEdit: TextEdit` in the completion item.

Extension Version:
<pre><code>
Angular Language Service'. Example: v12.1.1
</code></pre>

**Anything else relevant?**

To quote the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/):

> Most editors support two different operations when accepting a completion
item. One is to insert a completion text and the other is to replace an
existing text with a completion text. Since this can usually not be
predetermined by a server it can report both ranges. **Clients need to
signal support for InsertReplaceEdits via the
textDocument.completion.completionItem.insertReplaceSupport client
capability property.**

**Comment by atscott** [comment]
@predragnikolic thanks for the report. Would you be able to send a PR to fix this?

**Comment by atscott** [comment]
The fix is merged and will be included in next week's release

**Comment by predragnikolic** [comment]
Andrew that was quick!
Thank you very much :)
