### ISSUE TITLE
How do I navigate to the component that implements a tag?

### ISSUE THREAD

**Issue by 18549** [angular/vscode-ng-language-service#1456]
In a template file if I hover over the tag of an application defined component e.g. `app-my-component` then a helpful popup appears which contains the name of the component that implements that tag e.g. `(component) SomeModule.MyComponent`

However I cannot for the life of me work out how to use the popup to navigate to the component. I assume there must be a way to do it otherwise what's the point of displaying the popup in the first place.

**Comment by atscott** [comment]
This popup is just a tooltip. You can navigate to the component by right clicking and choosing "go to definition"
