### ISSUE TITLE
Angular Languaje Service not working at all in somesituations

### ISSUE THREAD

**Issue by Osolemio44** [angular/vscode-ng-language-service#1476]
# 🐞 bug report

### Description
When you turn ON the Settings sync, the plugin Angular Language Service stop working. Auto-complete, intellisence, etc doesnt work anymore. As soon as i deactivate "Settings sync"everything works fine again.

It has also happened to me with a project that I downloaded from an Angular course that I am following. I open the project, it doesn't give any error, but the Angular Language Service plugin just doesn't work. It is as if it is not installed since nothing works. And in this case, I don't have Settings sync enabled.

Version: 1.58.2 (system setup)
Commit: c3f1263
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

## Bug Type
What does this bug affect

- [ X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Go to index.ts in the project atached and try to create a string variable. You will that intelisense, autocomplete, etc is not working. Even the formater is not detected by vscode.

### **Screenshots**

![image](https://user-images.githubusercontent.com/55595063/128312170-8c3286e8-6e67-4cfe-95e3-bc265f70b0ba.png)

## 🌍  Your Environment
Angular CLI: 12.1.4
Node: 14.15.4
Package Manager: npm 6.14.10
OS: win32 x64

Angular: undefined

...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.4 (cli-only)
@angular-devkit/core         12.1.4 (cli-only)
@angular-devkit/schematics   12.1.4 (cli-only)
@schematics/angular          12.1.4 (cli-only)
typescript                   3.9.10
webpack                      4.46.0

</code></pre>

Extension Version: v12.2.0

VSCODE Version: 1.58.2 (system setup)
Commit: c3f1263
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

[curso-angular-intro-typescript-ecmascript-1.0.1.zip](https://github.com/angular/vscode-ng-language-service/files/6936946/curso-angular-intro-typescript-ecmascript-1.0.1.zip)

### Temporal solution

Sometimes when you restart VSCode it fixes the problem until it reoccurs at another time.

**Comment by atscott** [comment]
Closing. This issue would be unrelated to the Angular Language Service. We don't provide any information in TypeScript files outside of very specific things like `templateUrl` and `styleUrls`. The autocomplete there is covered by the built-in TS language service so there's something else going on with your environment.
