### ISSUE TITLE
Native events not listed in completions for output bindings in templates: `<div (|)`

### ISSUE THREAD

**Issue by ww2406** [angular/vscode-ng-language-service#1479]
DOM events [ (click), (keydown), (focus), etc. ] are not included in the autocomplete list for elements in Angular templates.

All of the other pertinent details are identical as #1388.

11.2.14

![Code_W9FxVnqUP3](https://user-images.githubusercontent.com/57472892/128781035-db8a6fbf-9378-4b95-83b4-b9852b5461e2.png)

vs

12.x (12.2.0 shown, but exists in all 12.x versions as I originally reported in #1388)

![Code_3CPzZ5E9T3](https://user-images.githubusercontent.com/57472892/128781164-cf271cc8-090c-47e9-a98f-607e1896b99f.png)

**Comment by atscott** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

![image](https://user-images.githubusercontent.com/479713/128779953-f0f39801-7e8d-4bfd-b32d-509198659c9e.png)


If the problem still exists in your application please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.

**Comment by ww2406** [comment]
@atscott I think you actually reproduced it exactly--none of the DOM events [ (click), (keydown), (focus), etc. ] are listed. However, you're right that custom event properties on components work, hadn't tried that yet.

All of the other pertinent details are identical as #1388.

11.2.14

![Code_W9FxVnqUP3](https://user-images.githubusercontent.com/57472892/128781035-db8a6fbf-9378-4b95-83b4-b9852b5461e2.png)

vs

12.x (12.2.0 shown, but exists in all 12.x versions as I originally reported in #1388)

![Code_3CPzZ5E9T3](https://user-images.githubusercontent.com/57472892/128781164-cf271cc8-090c-47e9-a98f-607e1896b99f.png)

**Comment by atscott** [comment]
Oh, you're talking about _native_ events. I understand now. Reopening (and rewording)

**Comment by ww2406** [comment]
Yes sir! My apologies for not being clearer to start...fwiw it made sense to me at the time :D Let me know if there's anything else you need from me.

**Comment by Text-only** [comment]
![Screenshot_20210827-021210_CryptoTab Browser Lite.png](https://user-images.githubusercontent.com/70195553/131759922-54fc6d38-944a-47d4-adc8-ee74306f0814.png)
