### ISSUE TITLE
Language service fails to start with error "Language service does not have a program"

### ISSUE THREAD

**Issue by rekna1** [angular/vscode-ng-language-service#1487]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: version 11?

### Description

 I do not have code completion anymore in HTML
I can see in the output an exception :  UnhandledPromiseRejectionWarning: Error: Language service does not have a program!

These are my compiler options
<pre><code>
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "strictTemplates": true
  }
</code>
</pre>

## Bug Type
What does this bug affect

- [x ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

**Expected behavior**

### **Logs**

<pre><code>
[Info  - 07:33:06] Angular language server process ID: 24832
[Info  - 07:33:06] Using typescript/lib/tsserverlibrary v4.3.4 from c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 07:33:06] Using @angular/language-service v12.2.0 from c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\node_modules\@angular\language-service\index.js
[Info  - 07:33:06] Logging is turned off. To enable, run command 'Open Angular server log'.
[Info  - 07:33:25] Enabling Ivy language service for c:/projects/xxx/tsconfig.json.
[Info  - 08:27:49] Enabling Ivy language service for c:/projects/xxx/tsconfig.json.
(node:24832) UnhandledPromiseRejectionWarning: Error: Language service does not have a program!
    at Object.getProgram (c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\node_modules\@angular\language-service\bundles\ivy.js:44765:27)
    at CompilerFactory.getOrCreate (c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\node_modules\@angular\language-service\bundles\ivy.js:41818:50)
    at LanguageService.withCompilerAndPerfTracing (c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\node_modules\@angular\language-service\bundles\ivy.js:44680:51)
    at LanguageService.getSemanticDiagnostics (c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\node_modules\@angular\language-service\bundles\ivy.js:44420:25)
    at Object.getSemanticDiagnostics (c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\node_modules\@angular\language-service\bundles\ivy.js:44864:38)
    at Session.sendPendingDiagnostics (c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\server\index.js:3642:54)
    at Timeout._onTimeout (c:\Users\xxx\.vscode\extensions\angular.ng-template-12.2.0\server\index.js:3628:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
</code></pre>

### **Screenshots**

![Example Screenshot](./output.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 11.2.1
Node: 12.19.0
OS: win32 x64

Angular: 11.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.1
@angular-devkit/build-angular   0.1102.1
@angular-devkit/core            11.2.1
@angular-devkit/schematics      11.2.1
@angular/cdk                    11.1.0
@schematics/angular             11.2.1
@schematics/update              0.1102.1
rxjs                            6.6.3
typescript                      4.1.3

</code></pre>

Extension Version:
<pre><code>
v12.2.0

</code></pre>

VSCode Version:
<pre><code>
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19042

</code></pre>

Operating System:
<pre><code>
 Windows 10 Version 20H2 OS Build 19042.1165 

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
@rekna1 That's a pretty odd error to get. Are you able to provide a minimal project to reproduce this issue with? I don't seen anything out of the ordinary about the project information you provided.

**Comment by rekna1** [comment]
@atscott Today I checked again, and the error is gone from the log but it's not working like I would expect.

e.g. I have in a template
`*ngFor="let tokenitem of vm.tokenList" `

- When I hover over tokenitem it displays tooltip **(variable) tokenitem: ITokenData**
- When I hover over vm **(variable) vm: ivm**
- When I hover over tokenList no tooltip displays
- When do goto definition on any of them it does take me to definition in ts (so it seems to know what it is)

Same view :
`(click)="removeTokenSubj.next(tokenitem)`

- hover over removeTokenSubj, no tooltip
- goto definition on removeTokenSubj, works
- hover over tokenItem, displays tooltip

Code completion sees none of the public members on my components in html templates.

Will try to create minimal reproduction if possible. It will not be easy as it is a rather large project with some dependencies.

**Comment by mvnrhd** [comment]
@atscott I had the same error and solved it. after running ng version I realized I was running an unsupported node version (16, while 14 is supported). with node 14 it seems to work fine. maybe this solves it for you too😊

**Comment by atscott** [comment]
Closing as this appears to be a workspace configuration/node incompatibility issue.
