### ISSUE TITLE
Completion of method should add parenthesis

### ISSUE THREAD

**Issue by fknop** [angular/vscode-ng-language-service#15]
When using completion of the `(click)` event for example to complete a method. No parenthesis are added by default to the method.

For example:

![image](https://cloud.githubusercontent.com/assets/6775689/21072612/f222f558-bec8-11e6-977a-66f1b1787693.png)
![image](https://cloud.githubusercontent.com/assets/6775689/21072618/05a70768-bec9-11e6-89ec-c5cbb03b6aad.png)

After pressing `TAB`:

![image](https://cloud.githubusercontent.com/assets/6775689/21072621/15cb3236-bec9-11e6-8604-200fa8417b03.png)

It would be nice if we could have parenthesis added by default and the cursor inside of these parenthesis like:

![image](https://cloud.githubusercontent.com/assets/6775689/21072625/33d20174-bec9-11e6-8a8c-995df68a5ab5.png)

**Comment by angelozerr** [comment]
IMHO I think this issue should be fixed by the @angular/language-service by returning a CompletionEntry#replacementSpan https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L1514

By doing that any editor (like Eclipse in my case) could benefit with this fix.

**Comment by chuckjaz** [comment]
@angelozerr I agree `Completion` should be augmented but `TextSpan` is not sufficient as I need to mark where the cursor should be which is what VS Code uses its snippet language for.

For now, you can simulate this behavior by looking or a `'method'` in the `kind` field of the completion. It is then safe to add the something like `({{}})` to the end of the completion (or whatever string acts like a snippet for the host).
