### ISSUE TITLE
[feature] Don't warn about abstract components not in module

### ISSUE THREAD

**Issue by RandomShaper** [angular/vscode-ng-language-service#150]
If a `Component` class is declared abstract you should not get this warning for it:

> Component '???' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration

What do you think?

**Comment by DuncanFaulkner** [comment]
Any news on this issue, not really usable as every file ends up as having an error, just uninstalled 0.900.0 as it was throwing up too many of these warnings.

**Comment by ayazhafiz** [comment]
Should we only exclude NgModule errors for abstract components? Should we exclude other errors, like missing `template`/`templateUrl` properties? What do you think @kyliau @andrius-pra?

**Comment by andrius-pra** [comment]
Is there any reason you will need to use `@Component` decorator on abstract class? I think that all components should be declared in the NgModules. The language service [should allow directives with no selector that are not in NgModules](https://github.com/angular/angular/blob/master/packages/compiler-cli/test/ngc_spec.ts#L2290-L2310) and it should not produce any error.

**Comment by ayazhafiz** [comment]
Yes, `@Component` on an abstract class is not necessary. But I think we should still allow this to be used without generating diagnostics that don't apply to an abstract class, like including them in NgModule.

**Comment by kyliau** [comment]
This is fixed in https://github.com/angular/angular/pull/34115
