### ISSUE TITLE
Automatic NgModule Imports

### ISSUE THREAD

**Issue by wSedlacek** [angular/vscode-ng-language-service#1501]
**Is your feature request related to a problem? Please describe.**

No

# 🚀 feature request

### Description
One of the killer features of Webstorm when working with angular is the ability to automatically import NgModules from templates as an auto completion for components, directives and pipes.

It would be fantastic if such a feature could be brought into vsc

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

### Describe the solution you'd like

This is probably a tricky problem to solve as it relies on knowing all the possible NgModules (something that even TypeScript struggles with for things like submodules imports of @angular/material) and then adding the import via a code completion to a file that is potentially not open.

The closest thing I can think of that currently exist in vsc is renaming files automatically updating their imports which I believe the TypeScript language service manages. 

### Anything else relevant?

 
WebStorm added this feature in 2019 but I don't think their work on it is open source, at least I couldn't find it easily.

**Comment by dylhunn** [comment]
Just for the record -- I'm working on this, building on top of the work as per [this PR](https://github.com/angular/angular/pull/46764) for #1610.

**Comment by eneajaho** [comment]
@dylhunn This is great news 🥳. Will it also import the module in @Component imports array?

**Comment by laggage** [comment]
Expecting this feature~

**Comment by atscott** [comment]
@dylhunn As far as I can tell, this is working with components that are declared in NgModules and standalone components so I think we can close this as completed. Is that correct?

**Comment by dylhunn** [comment]
@dylhunn Yes, closing this!

**Comment by A77AY** [comment]
@dylhunn What about the same problem with external libraries?
(In VS Code, there are still no code actions available for Material package modules)

**Comment by dylhunn** [comment]
I'm intending to enable this for external libraries in a future release. I was worried about performance issues, and so I put it on the back burner for a while. (Although the primary motivation is standalone, there's no reason we can't also do it for NgModules)

**Comment by laggage** [comment]
> I was worried about performance issues, and so I put it on the back burner for a while

May be we can have an option to opt-in
