### ISSUE TITLE
Please stop showing the console

### ISSUE THREAD

**Issue by wbhob** [angular/vscode-ng-language-service#151]
I have a 13 inch machine. The extension always crashes, and takes up my entire display about how the Angular Language Service crashed. It's a real pain, because this happens all the time, even outside Angular projects.

Please have an option that will prevent the terminal from opening, and just have a warning saying it crashed.

**Comment by chuckjaz** [comment]
Closed in 0.1.6

The exceptions are now logged as normal logging instead of escaping to VS Code

**Comment by wbhob** [comment]
Wow, that was lightning fast! Thank you!

**Comment by wbhob** [comment]
@chuckjaz I'm still getting this issue with v0.1.6, practically as I type, because it recognizes errors if I stop for even a moment.

**Comment by luchsamapparat** [comment]
Same here

**Comment by cvharris** [comment]
this is still a problem for me as well. Should we reopen this issue or create a new one?
