### ISSUE TITLE
[Angular] Identifier 'required' is not defined. '__type' does not contain such a member

### ISSUE THREAD

**Issue by Kurtz1993** [angular/vscode-ng-language-service#152]
property errors of AbstractControlDirective

I have the following code:

```html
<div>
    <label for="fullname">Passenger name:</label>
    <input
      type="text"
      name="fullname"
      required
      #fullname="ngModel"
      [ngModel]="detail?.fullname">

      <div class="error" *ngIf="fullname.errors?.required && fullname.dirty">
        Passenger name is required.
      </div>
  </div>
```

By using a property inside the `errors` property of the ngModel reference it shows me that error.
This shouldn't be an error since it's valid syntax for template-driven forms.

**Comment by Kurtz1993** [comment]
Closing because duplicate of #149

**Comment by Ajinath07** [comment]
I have tried with above approach but it failed miserably.

Please look at this code - 
<div *ngIf="username.errors.required">This field is required</div>
              <div *ngIf="username.errors.minlength">Minimum length should be {{username.errors.minlength.requiredLength}}</div>

Throwing error by TS compiler - 
[Angular] Identifier 'required' is not defined. '__type' does not contain such a member

**Comment by Mallesh25nayak** [comment]
i tried same thing bu tnot getting out put

**Comment by Danielapariona** [comment]
Example
try to add "?" after "price".
<div *ngIf="price?.errors.required">Price is required.</div>

**Comment by Mallesh25nayak** [comment]
<div *ngIf="firstName.errors.required">First Name is required.
          <div *ngIf="firstName.errors.minlength">First Name should be minimum 3 character.</div>
          <div *ngIf="firstName.errors.pattern">First Name doesn't Match pattern.</div>
         </div>
      i tried this

**Comment by Mallesh25nayak** [comment]
` <div *ngIf="firstName.errors.required">First Name is required.
          <div *ngIf="firstName.errors.minlength">First Name should be minimum 3 character.</div>
          <div *ngIf="firstName.errors.pattern">First Name doesn't Match pattern.</div>
         </div>
      i tried this `

**Comment by danbete** [comment]
this will solve the issue:
just add casting to bool using !! :
      <div class="error" *ngIf="!!fullname.errors?.required && !!fullname.dirty">
        Passenger name is required.
      </div>

**Comment by heenamanglani** [comment]
> Example
> try to add "?" after "price".
> "<div *ngIf="price?.errors.required">Price is required."

I solved this issue adding ? before parameter and not after errors? But can you please elaborate it and try to explain how this issue is solved just by moving the question mark?

**Comment by suprcodr** [comment]
> this will solve the issue:
> just add casting to bool using !! :
> <div class="error" *ngIf="!!fullname.errors?.required && !!fullname.dirty">
> Passenger name is required.

This solved my issue! thanks!

**Comment by EeeEui** [comment]
> Example
> try to add "?" after "price".
> "<div *ngIf="price?.errors.required">Price is required."

It worked for me. Could you please tell me why should add "?"

**Comment by MianMahroz** [comment]
this also solve my issue just add ?

**Comment by FeehGb** [comment]
try price['errors']['required']

**Comment by danbete** [comment]
@EeeEui the ? Operator is for safe navigation , it will take a variable even if it's might be invalid (and deal with the exception internally - invalid = for in this case).

**Comment by binDongKim** [comment]
`?` didn't work for me. `!!` only worked in my case.

**Comment by codermahadi** [comment]
#? didn't work f. **!!** only worked in angular 7+.
```
<div class="alert alert-danger" *ngIf="username.touched && username.invalid" class="alert alert-danger">
            <div *ngIf="!!username.errors.required">Username is required</div>
            <div *ngIf="!!username.errors.minlength">Username Should be minimum {{ !!username.errors.minlength.requiredLength }} Charecters.</div>
          </div>
```

**Comment by mhSangar** [comment]
It now seems like a problem with VSCode, because the error is still highlighted in my editor, but Angular does not detect it as so. What I did to resolve this for VSCode is check the error on the TypeScript side, with a function.

> HTML

![html](https://user-images.githubusercontent.com/14298877/59511001-6f5b7400-8eb5-11e9-8244-a89dfa705e0f.PNG)

> TypeScript

![ts](https://user-images.githubusercontent.com/14298877/59511006-72566480-8eb5-11e9-9920-02214f4432f1.PNG)

**Comment by sathishiva** [comment]
This worked for me and it looks cleaner.
<div class="error" *ngIf="fullname.hasError('required') && fullname.dirty">

**Comment by dhair-seva** [comment]
I had the same error. Doing `*ngIf="formGroup?.get('fullName').hasError('required')"` worked for me

**Comment by smallprogram** [comment]
> It now seems like a problem with VSCode, because the error is still highlighted in my editor, but Angular does not detect it as so. What I did to resolve this for VSCode is check the error on the TypeScript side, with a function.
> 
> > HTML
> 
> ![html](https://user-images.githubusercontent.com/14298877/59511001-6f5b7400-8eb5-11e9-8244-a89dfa705e0f.PNG)
> 
> > TypeScript
> 
> ![ts](https://user-images.githubusercontent.com/14298877/59511006-72566480-8eb5-11e9-9920-02214f4432f1.PNG)

Big Brother, this is too much trouble for you.

**Comment by prodplus** [comment]
Do *ngIf="yourForm.get('yourfield').hasError('required')"
