### ISSUE TITLE
Autocomplete: Sort component properties by relevance

### ISSUE THREAD

**Issue by FredricW** [angular/vscode-ng-language-service#1537]
**Is your feature request related to a problem? Please describe.**

When using our own components in the templates, it is almost always more relevant or absolutely necessary to use the **custom properties that is defined on it**, rather than generic html props or even the props added by angular. As of now, suggestions for properties seems to be sorted alphabetically and there is no difference between generic and custom ones. That leaves us scrolling through a hundred props, trying to identify which ones are the ones defined in the component.
More often than not it is just faster to break the flow, open the component and the check the definitions directly, which omit the need for autocomplete in these scenarios all together. 

# 🚀 feature request

### Description
Ability to sort custom component properties before generic html/angular properties and mark them as custom (with its own icon).

### Feature Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [x] Angular Language Service server

### Describe the solution you'd like

Have all custom properties first, listed alphabetically with their own icon (that indicates they are custom properties). Then show all the generic properties after.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Looking up the components manually.

### Anything else relevant?

 
Example:
Here I have a component that takes two inputs:
![image](https://user-images.githubusercontent.com/42540861/138236233-05c7bccb-226f-4368-bcd9-69efdc4ac229.png)

Triggering autocomplete looks like this:
![image](https://user-images.githubusercontent.com/42540861/138236413-35a8f8b4-0012-450c-b374-065c62f2511c.png)

Even when starting to write and scrolling all the way down, there is nothing that separates them from other angular defined properties:
![image](https://user-images.githubusercontent.com/42540861/138236730-a1284ac2-679f-4017-ad5f-e2a5bd9186d6.png)

**Comment by Harpush** [comment]
Pretty annoying... I would expect them to be first

**Comment by atscott** [comment]
Fixed in the latest release (published today)
