### ISSUE TITLE
It shows errors with Angular 13

### ISSUE THREAD

**Issue by kyroluskamal** [angular/vscode-ng-language-service#1555]
I updated my angular application to Angular 13. VS code shows errors that router-outlet, any directives of @angular/common and any angular material tags are unknown. 

First, I guessed that it is the npm cache error. I deleted npm cache. I even installed node.js version 16. But, all the errors is removed when I disabled angular language service.

But, When angular language service was enabled and VS code shows the errors, the application run successfully without any errors. 

With visual studio 2019, no errors are shown but it doesn't work with angular 13.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by thaoula** [comment]
Hi @atscott,

What information do you require to re-open this issue? 

We are experiencing the same issue on a large Angular application that was recently updated.

We get these kinds of errors -

`Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".`

![image](https://user-images.githubusercontent.com/349133/141253066-f7428e35-b5d9-4890-a232-a221381db1d6.png)

The common module is definitely imported and the app compiles and runs fine.

Regards,
Tarek

**Comment by atscott** [comment]
Hi @thaoula - the issue template outlines the appropriate information to provide as a starting point for investigations.

**Comment by kyroluskamal** [comment]
It is solved when deactivating the legacy engine, but, it did not work properly as well. The errors are gone, but, I can't see any suggestions for component properties in the HTML template
