### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sporkupine** [angular/vscode-ng-language-service#1557]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `13.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.62.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Owner\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-loa
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/7490993/Angular.ng-template-unresponsive.cpuprofile.txt)
d

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
