### ISSUE TITLE
Duplicated MSMarket Place 

### ISSUE THREAD

**Issue by feitzi** [angular/vscode-ng-language-service#157]
There are two entries on the Microsoft Marketplace:

-[Version 1.4](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template)
-[Version 1.6](https://marketplace.visualstudio.com/items?itemName=Angular.ng-language-service)

![30-08-2017 08-35-06](https://user-images.githubusercontent.com/2361489/29858556-3a6b7420-8d5e-11e7-97d9-158b334160fd.png)

I think this is confusing. Why not use one release on MarketPlace?

**Comment by chuckjaz** [comment]
That certainly was not my intent. I will figure out how I got in this state and resolve it.
