### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lxman** [angular/vscode-ng-language-service#1573]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `13.0.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\jorda\AppData\Local\Temp\Angular.ng-template-unresponsive.cpuprofile.txt`

File is not present

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.

**Comment by lxman** [comment]
I'm sorry about the delay. I honestly don't remember what I was doing at the time. VSCode just prompted me to report it, so I did. There was a file in the %appdata% folder that it asked for, but when I went to look for it, it wasn't there. Otherwise I would have included it.

If this is not enough information to process, feel free to close.

**Comment by atscott** [comment]
@lxman Yea, we see these reports often and I was looking at them more closely in the beginning (ex: #1320). Every time the profile was attached, it always showed high CPU during compilation and there were not any confirmed reports of it being a persistent problem. We do expect this to be the case - compiling an Angular application _is_ very CPU intensive.
