### ISSUE TITLE
Inputs with `$` suffix prevent elements from being recognized

### ISSUE THREAD

**Issue by bstrandjev** [angular/vscode-ng-language-service#1574]
# 🐞 bug report

### Is this a regression?

Yes and no. This still works for Angular < 12. Also it seems to be similar to issue: https://github.com/angular/vscode-ng-language-service/issues/1109
However, i never got a setup that worked for Angular 13.

### Description

 A clear and concise description of the problem...

I am using recent Visual Studio code and it works ok with Angular 12, however, for Angular 13 projects all my custom components that are under `*ngIf` DOM element can not be navigated to. I can not navigate to them to using CTRL + mouse click. Also right click and Go to definition tells me "No definition found".

I have read this [issue thread ](https://github.com/angular/vscode-ng-language-service/issues/1109) and I tried setting `"angular.experimental-ivy": false` in my Visual Studio code, but to no avail.

I am using Visual Studio Code on Ubuntu with the following versions:

```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-90-generic snap
```
The Angular I tried using is 13.0.1.

## Bug Type
What does this bug affect

- [x ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Load whatever Angular 13 project in Visual Studio Code
2. Open any HTML file with `*ngIf` protected DOM element
3. Try navigating (e.g. with CTRL + mouse click) to any element listed under it: either custom component or template varible
4. Nothing will happen. 
5. Right click -> `Go to definition` triggers "No definition found for"

**Expected behavior**

The navigation should work as for older angular versions

## 🌍  Your Environment
**Angular Version:**
<pre><code>
13.0.1.
</code></pre>

VSCode Version:
<pre><code>
1.62.3
</code></pre>

Operating System:
<pre><code>
Linux x64 5.4.0-90-generic snap
</code></pre>

Extension options:
<pre><code>
"angular.experimental-ivy": false
</code></pre>

**Comment by atscott** [comment]
@bstrandjev - what are your `angularCompilerOptions` in the `tsconfig`? In version 12, the default became the ivy version of the language service. With this, the compiler options that you've configured for compiling your application are the exact ones used in the language service. This means that the information you see will match what the compiler understands during the application build. If you do not have `strictTemplates: true`, this will often mean you will see things like this, specifically with structural directives.

**Comment by bstrandjev** [comment]
Hi @atscott thanks for the quick reaction and for the additional hint. I did not have `"strictTemplates": true` in my tsconfig.json. Now I added it, but it made no difference. Either way, without claiming to fully understand your explanation, I think this reasoning would not justify why I have no problem in projects configured with Angular 12, but Angular 13 is problematic.

**Comment by atscott** [comment]
@bstrandjev Could you also check if you have the "Legacy View Engine" option enabled in the extension options? If so, try disabling that.

**Comment by bstrandjev** [comment]
@atscott it has been disabled all along

**Comment by atscott** [comment]
@bstrandjev Are you able to provide a minimal reproduction of the problem with a github repo? If not, there's not much more that can be done here for investigation.

**Comment by bstrandjev** [comment]
@atscott I should be able to (obviously setup and tested on my environment). However, this will be in few hours. Thanks for being available 24 / 7

**Comment by bstrandjev** [comment]
@atscott I have created an example repo here: https://github.com/qualifast/VSCodeNavigationBug

Actually, as I was setting up the example it turned out another situation was the trigger of the problem, not as per my initial analysis:

Navigation to components with `Observable` inputs is broken, it seems. This is not affected by `*ngIf` check presence. However, I remain convinced this is also connected with Angular version, because I have other projects setup to use Angular 12 and they do not exhibit the problem.

**Comment by ilya-marinov-axon** [comment]
@bstrandjev @atscott 
I have the same problem, after updating Angular version to 13 on work project, VSCode starts highlight angular syntax in templates with messages like: `"Can't bind to 'ngSwitch'..."`, `"router-outlet is not a known element"` and etc... At the same time everything compiles well.

I've created new test project with Angular 13 version and had same issue there. My suggestion that this is something wrong with extension.

**Comment by atscott** [comment]
@ilya-marinov-axon Do you have the legacy view engine option enabled in the extension options? 
![image](https://user-images.githubusercontent.com/479713/143051912-e3c2eba6-599f-4203-b14d-a898a4bc171e.png)
View Engine support was was dropped in v13

@bstrandjev I do not see any issues with the project you've provided (unless I enabled the "View-engine" option which will not work with v13 projects). The only other time I saw issues was when I did not have the dependencies installed in `node_modules`. After installing the dependencies (`yarn/npm install`), you have to run the `Restart Angular language server` command.

**Comment by bstrandjev** [comment]
@atscott can you navigate to `exp-example` using ctrl + mouse click in `app.component.html` in my code?
How does one "run the Restart Angular language server command." in VS Code?

**Comment by atscott** [comment]
> @atscott can you navigate to `exp-example` using ctrl + mouse click in `app.component.html` in my code? 

Yes, I can.

> How does one "run the Restart Angular language server command." in VS Code?

It's in the command palette 
![image](https://user-images.githubusercontent.com/479713/143054224-5ae14589-b880-4649-93a8-517ba0ce3986.png)

**Comment by atscott** [comment]
@bstrandjev Can you also attach the server logs? These steps are outlined in the template for submitting a new issue:

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>
 If the issue is accompanied by log file output, please share it below.

Set the Angular Log level to verbose by opening settings (File/Preferences/Settings on Windows, Code/Preferences/Settings on Mac), go to Extensions/Angular Language Service, set `angular.log` to `verbose`.

To open the log file, go to the command palette (Cmd+Shift+P on Mac, Ctrl+Shift+P on Windows), search `Open Angular Server log`.

Alternatively, if the log file is long, it can be uploaded instead of pasting below.

**Comment by bstrandjev** [comment]
Sorry, I missed this part in the bug template, agreed. 
I am not sure how I can trigger specific logs, so I just enabled in verbose and directly attaching the log.

[angular.log](https://github.com/angular/vscode-ng-language-service/files/7589246/angular.log)

I also confirm that restarting the server did not fix my issue.

**Comment by atscott** [comment]
@bstrandjev I don't see anything irregular in the logs either. Your example project works on both my Mac and Linux machines. Unfortunately I'm at a loss for where to go from here since I cannot reproduce this issue.

**Comment by bstrandjev** [comment]
@atscott thanks for all the effort! I had a friend setup the project and he experienced no problems like you. Then I realized there are local changes in the example repository that I had not committed (I am very sorry about that). I did a push now and both me and him experience the abovementioned problem. Apparently the problem appears when we suffix the observables with a `$` a practice we usually follow with my colleagues.

**Comment by ilya-marinov-axon** [comment]
> @ilya-marinov-axon Do you have the legacy view engine option enabled in the extension options? ![image](https://user-images.githubusercontent.com/479713/143051912-e3c2eba6-599f-4203-b14d-a898a4bc171e.png) View Engine support was was dropped in v13

@atscott  Yep, it was enabled. It works correctly now, thanks a lot! 🙏🏻

**Comment by bstrandjev** [comment]
@atscott after being able to pinpoint the cause of the problem (`$` in the `@Input` of a component) I checked different versions of Angular. Angular 10 and 12 also exhibit this problem. With these experiments the bug description needs to be changed significantly. What is the correct behavior from my side: should I alter the bug description?

**Comment by atscott** [comment]
@ilya-marinov-axon Great. I've created #1575 to make this incompatibility show up as a notification.

@bstrandjev Ah, very interesting. I see the issue now as well. I'll find some time to investigate further. No need to update the title for now. I'll do that when I have more information about what the root cause is.

**Comment by atscott** [comment]
@bstrandjev Ah, found the issue. I should have a fix out shortly. I'll be on holiday for the beginning of December so I'll see if someone else on the team can do a release for the language service next week.
