### ISSUE TITLE
Version of Angular Language Service used?

### ISSUE THREAD

**Issue by jtsom** [angular/vscode-ng-language-service#158]
What determines the version of the Angular Language Service that is used? I have this extension installed on a couple systems (one each of Windows 10, Mac, and Ubuntu). All are running the latest VS Code Insiders, and 0.1.6 of the extension.

On the Linux and Mac, on startup, or project load, in the Output window it is displaying:
```
Angular Language Service: 4.3.6
TypeScript: 2.4.2
```

But on the Windows machine, it shows:
```
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
```

The project on Windows has, in the project.json:
`"@angular/language-service": "4.3.1",`

and on the other two it's:
`"@angular/language-service": "^4.3.6",`

On the commit that fixed the issues with v0.1.4, it mentions updating to use the 5.0.0-beta.5 version, so I'm not sure what's going on?

**Comment by chuckjaz** [comment]
If you have a version of the language service installed locally in your project it will use that version instead of the built in version.

**Comment by jtsom** [comment]
I'll have to check but I'm sure the windows project has the language service locally installed, as I mentioned 4.6.1

**Comment by jtsom** [comment]
Odd. I pulled the same project down onto the Mac, npm installed, and that version is showing 
`Angular Language Service: 4.1.6`

Removing node_modules and re-installing on windows still shows 5.0.0-beta.5

**Comment by Meligy** [comment]
+1 here on Windows 8.1. It doesn't seem to detect the local version, even thought VSCode is opened to the folder that contains `package.json` and `node_modules`, and running `npm ls @angular/language-service` in the folder shows v4.3.6.

**Comment by jtsom** [comment]
Any traction on this issue??? I've got a project that has @angular/language-service: 5.1.0, but in the output window it is showing 5.0.0-beta.5.  I NEED the newer version (along with the newer Typescript) in order fix problems with intellisense (Seeing multiple, incorrect entries in the dropdown). HOW can I get this extension to use the newer version?

**Comment by jdeanwaite** [comment]
For me, adding `"@angular/language-service": "~5.1.0"`, installing, and restarting VSC fixed the problem. Running macOS.

**Comment by kyliau** [comment]
Closing this, since original issue is more than 2 years old. The extension now prints version number of @angular/language-service to the console.
