### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by malvarez30** [angular/vscode-ng-language-service#1582]
- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `13.0.0`
- OS Version: `Windows_NT ia32 10.0.19043`
- VS Code version: `1.62.3`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11236,
		"activateCallTime": 354,
		"activateResolvedTime": 15,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Angular.ng-template",
				"_lower": "angular.ng-template"
			},
			"activationEvent": "onLanguage:html"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please open a new issue and follow the instructions in the issue template.
