### ISSUE TITLE
error in Html file

### ISSUE THREAD

**Issue by aliChavoshi** [angular/vscode-ng-language-service#1584]
hi ,
It shows me an error in HTML when I install this program, but when I disable it, this problem solved
![image](https://user-images.githubusercontent.com/59391372/145701724-640f64b1-9ded-4702-a98d-578a914477d4.png)

**Comment by guisperandio** [comment]
Same problem here. Are you using NX?

**Comment by guisperandio** [comment]
@aliChavoshi I was having the same problem, then I unchecked the Use legacy view engine language service on the angular language service extension and it is all working normally again

![image](https://user-images.githubusercontent.com/29610284/145986411-36d2954e-de14-45ea-a693-dbe6a680ab32.png)


Can you check if you have it marked?

**Comment by aliChavoshi** [comment]
oh, so thanks, :) 
thanks, brother 👍
