### ISSUE TITLE
Navigating to definition of library code compiled with declarationMap still goes to `.d.ts` file rather than original source

### ISSUE THREAD

**Issue by kryshac** [angular/vscode-ng-language-service#1588]
# 🐞 bug report

### Is this a regression?

in version 12-13 I tested and it doesn't work

### Description

I have a monorepo with a project and libraries.
Go to definition not working correctly from template

## Reproduction

`ng new test --create-application false`
`cd test`
`ng g app demo`
`ng g lib tst`

build in development mode to have declarationMap
`ng build tst --configuration=development `

**Expected behavior**
go to definition works correctly from ts:

`projects/demo/src/app/app.module.ts`
execute goToDefinition on `TstModule`
result: `projects/tst/src/lib/tst.module.ts`

but in html is not working properly:
`projects/demo/src/app/app.component.html`
execute goToDefinition on `<lib-tst></lib-tst>`
result: `dist/tst/lib/tst.component.d.ts` 
but we expect it to be: `projects/tst/src/lib/tst.component.ts`

### **Screenshots**
![image](https://user-images.githubusercontent.com/19764133/149040589-298d3d04-5a79-4aa9-9379-37327f45938a.png)
![image](https://user-images.githubusercontent.com/19764133/149040653-e5e06be5-6c57-4202-803e-b36481f33d6d.png)

*Error*

![image](https://user-images.githubusercontent.com/19764133/149040763-6262d61a-230a-4505-b443-e06a862d3c43.png)
![image](https://user-images.githubusercontent.com/19764133/149040801-10a730fd-73ea-444c-bf07-5baecd472eb0.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.4
Node: 14.18.1
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
ng-packagr                      13.1.2
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

Extension Version:
<pre><code>
v13.1.0
</code></pre>

VSCode Version:
<pre><code>
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:58:13.605Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.19-2-MANJARO
</code></pre>

Extension options:
<pre><code>
  "angular.trace.server": "verbose",
  "angular.log": "verbose",
</code></pre>

**Comment by atscott** [comment]
Can you please provide a minimal reproduction?

**Comment by kryshac** [comment]
@atscott I created a repository: [`git@github.com:kryshac/vscode-ng-language-service-bug.git`](https://github.com/kryshac/vscode-ng-language-service-bug)

**Comment by atscott** [comment]
@kryshac Thanks for that. Interestingly the "find references" doesn't work with the mapping from the TS code either even though the "go to definition" does. 
I'm not really familiar with what's going on here though. Given that you can simply do another "go to definition" once you get to the `.d.ts` file to get to the original source, I don't think this is very high priority to investigate.

**Comment by atscott** [comment]
I investigated this some more and don't believe this is going to be feasible to fix. The generated type check block for the template is 
```
import * as i0 from '../../../../../../../../Users/atscott/Downloads/vscode-ng-language-service-bug-master/projects/demo/src/app/app.component';
import * as i1 from 'tst';



/*tcb1*/
function _tcb1(ctx: i0.AppComponent) { if (true) {
    ctx. /*D:ignore*/ /*T:COMPCOMP*/;
    var _t1 = document.createElement("lib-tst") /*51,60*/;
    var _t2: i1.TstComponent /*T:DIR*/ /*51,60*/ = null!;
    var _t3 = document.createElement("app-root") /*72,82*/;
    var _t4: i0.AppComponent /*T:DIR*/ /*72,82*/ = null!;
} }

export const IS_A_MODULE = true;
```

When we attempt to go to definition of `lib-tst`, we find the `_t2: i1.TstComponent /*T:DIR*/ /*51,60*/ = null!;` node that represents the element declaration in the template. From there, we use the `typeChecker` to get information about the node: https://github.com/angular/angular/blob/290df4f806472cb3c3fe1d7cbd132990bf3b15ab/packages/compiler-cli/src/ngtsc/typecheck/src/template_symbol_builder.ts#L561-L565
```
      tsSymbol = this.getTypeChecker().getSymbolAtLocation(node);
...
    const type = this.getTypeChecker().getTypeAtLocation(node);
```

The type checker returns a symbol which references the `.d.ts` file rather than the original source. Even stepping through the debugger more to the location where we have the typescript language service, attempting to use that to `getDefinitionAtPosition` at the `i1.TstComponent` position still gives the result as the `.d.ts` file. It could have something to do with the `program` used by the compiler itself and it not knowing about or how to use the source map, but I really don't know. There's vanishingly little documentation on these APIs so I don't think I'll be able to make any more progress on this investigation.

**Comment by ivanwonder** [comment]
The method that vscode built-in extension jump into original source is implemented outside the Project Service. vscode-ng-language-service should handle it the same way.

https://github.com/microsoft/TypeScript/blob/818962087cadaae70a44303678ef166c61ca0bb1/src/server/session.ts#L1253

This [`project.getSourceMapper().tryGetSourcePosition(location);`](https://github.com/microsoft/TypeScript/blob/818962087cadaae70a44303678ef166c61ca0bb1/src/server/session.ts#L587) is used to map DTS to original source, but it's [internal](https://github.com/microsoft/TypeScript/blob/818962087cadaae70a44303678ef166c61ca0bb1/src/server/project.ts#L629), it will take a risk to use it.
