### ISSUE TITLE
```json  { 	"messages": [], 	"activationTimes": { 		"codeLoadingTime": 15630, 		"activateCallTime": 2209, 		"activateResolvedTime": 20, 		"activationReason": { 			"startup": false, 			"extensionId": { 				"value": "Angular.ng-template", 				"_lower": "angular.ng-template" 			}, 			"activationEvent": "onLanguage:html" 		} 	}, 	"runtimeErrors": [], 	"runningLocation": 1 } ```Extension issue

### ISSUE THREAD

**Issue by gpr1nce** [angular/vscode-ng-language-service#1595]
- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `13.1.0`
- OS Version: `Linux x64 5.11.0-43-generic`
- VS Code version: `1.63.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. 

If the problem still exists in your application, please open a new issue and follow the instructions in the issue template.
