### ISSUE TITLE
Progress notifications lack `kind` field

### ISSUE THREAD

**Issue by j-hui** [angular/vscode-ng-language-service#1607]
# 🐞 bug report

### Is this a regression?

Not to my knowledge.

### Description

I'm the author of a [Neovim plugin](https://github.com/j-hui/fidget.nvim) that reports the ongoing progress of LSP servers via the [`$/progress` endpoint](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workDoneProgressEnd).

When using my plugin with this language server, [some users noticed](https://github.com/j-hui/fidget.nvim/pull/26#issue-1118502502) that angularls was not sending any `end` notifications. This does not appear to be compliant with the LSP spec.

I took a peek at the source code and found progress being [sent directly via the `sendProgress` method](https://github.com/angular/vscode-ng-language-service/blob/9a5ecd92cf617259e474fc23461cb586cc6ead76/server/src/session.ts#L1197) without any `kind` field. This seems to differ from the library-provided [`done` helper](https://github.com/microsoft/vscode-languageserver-node/blob/main/server/src/common/progress.ts#L72) helper, which takes cares of specifying the `end` kind.

## Bug Type

- [ ] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

I'm not able to reproduce this behavior myself since I don't really know my way around web projects, but if there is a small demo project you could point me to, I could probably easily reproduce it just by opening that.

**Expected behavior**

When progress is complete, the server sends an `end` notification.

### **Logs**

<pre><code>
n/a
</code></pre>

### **Screenshots**

See https://github.com/j-hui/fidget.nvim/pull/26

## 🌍  Your Environment

```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/10k3bc68v0602pvaz6m5k420q13x83g6-neovim-unwrapped-0.6.1/share/nvim
"

Run :checkhealth for more info
```

**Comment by atscott** [comment]
@j-hui Thanks for the thorough explanation. If you wanted to try reproducing, the test project used here is in `integration/project`. All you would need to do is install the `node_modules` with `yarn`.

Would you like to send a PR to fix this? Seems like you've already done all the hard work in determining what the correct fix is and all that's needed.

**Comment by j-hui** [comment]
Sorry, but I'm unable to build/run this project, because I don't really know how to use yarn. I was able to run `yarn compile` successfully, though it complains about "vscode" being an an invalid engine. I was also able to get `scripts/build.sh` to work using Node v 14.15.0. However, `yarn test` complains about `ngcc` missing, and I was unable to find any language server executable to run.

I'm still willing to make the PR if I can figure out how I can build and test my changes. Are there any complete build instructions that I can follow? And what are the dependencies required to build and run the language server?

Using `fnm`, I'm running v14.15.0 of `node`.

**Comment by ivanwonder** [comment]
> However, `yarn test` complains about `ngcc` missing, and I was unable to find any language server executable to run.

You do not need to run it, because this is used to test the NGCC command. If you want, run `scripts/test.sh`.

If you want to test LS, I recommend you to use VS Code to run and debug. This is the [debug config](https://github.com/angular/vscode-ng-language-service/blob/58c903d2cc8e9c30c26bf204698491a81fe07aa0/.vscode/launch.json#L87) and adds a test case [here](https://github.com/angular/vscode-ng-language-service/blob/58c903d2cc8e9c30c26bf204698491a81fe07aa0/integration/lsp/ivy_spec.ts#L651).

**Comment by atscott** [comment]
Circling back on this: [Generic progress reporting](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#progress) does not seem to require that all forms of progress reporting conform to the [work done progress[(https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workDoneProgress) specification. Specifically, it states

> This mechanism can be used to report any kind of progress including work done progress (usually used to report progress in the user interface using a progress bar) and partial result progress to support streaming of results.

The [WorkDoneProgressBeing](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workDoneProgressBegin) interface doesn't support the generic data that is required to associate specific `ngcc` progress by their `tsconfig` files. Correct me if I'm wrong, but my understanding of this now is that this issue can be closed.

**Comment by j-hui** [comment]
@atscott thanks for circling back. I didn't realize that the WorkDoneProgressBegin interface is not required by the Progress handler. So this should not be considered a bug. 

However, not conforming to that interface makes it difficult for plugins like mine to know what fields are present to provide the user feedback. I haven't had time to set up VScode lately, but ultimately want to handle these progress notifications in the same way. I still have to see what that behavior is, but in the meantime feel free to close this for now.

**Comment by ivanwonder** [comment]
We can refactor the progress report to use the built-in `WorkDoneProgressReport`

> The [WorkDoneProgressBeing](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workDoneProgressBegin) interface doesn't support the generic data that is required to associate specific ngcc progress by their tsconfig files.

The `tsconfig` is not needed to report the NGCC progress. The built-in report is distinguished by the token that is generated [when we create the `WorkDoneProgressReport`](https://github.com/microsoft/vscode-languageserver-node/blob/d58c00bbf8837b9fd0144924db5e7b1c543d839e/server/src/common/progress.ts#L177).

But there is a delay to show in the vscode status bar between the `ProjectLoadingFinishEvent` and the start of the NGCC event when I test it in the vscode.

You @atscott @j-hui  can take a look at this [PR](https://github.com/angular/vscode-ng-language-service/pull/1614).

**Comment by atscott** [comment]
@ivanwonder Awesome, thanks for the additional research there. I'll review your PR soon and maybe we can get this in for the release this week.
