### ISSUE TITLE
Property rename not working in Angular components

### ISSUE THREAD

**Issue by moniuch** [angular/vscode-ng-language-service#1609]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

Could be considered a bug, could be considered a feature.

In angular cli app:

**Component in separate files (html + ts)**

Rename a component property doesn't update template when initiated from ts.
It works when initiated from template though.

```ts
// mycomp.component.ts
@Component({
  selector: 'my-comp',
  templateUrl: './mycomp.component.html'.
})
export class MyComponent {
  foo: any;
} 
```

```html
<!-- mycomp.component.html -->
<div>{{ foo }}</div>
```

- `foo` **won't** get renamed in html when rename (highlight + F2) initiated from ts.
- `foo` **will** get renamed in ts when rename initiated from html.

**Single file component (ts)**

```ts
@Component({
  selector: 'my-comp',
  template: `<div>{{ foo }}</div>`
})
class MyComp {
  foo: any;
}
```

- Rename won't get initiated from within html template (This element cannot be renamed)
- `foo` **will not** get renamed in html when rename initiated from within class.

## 🌍  Your Environment
**Angular Version:**
<pre><code>

13.1
</code></pre>

Extension Version:
<pre><code>

13.2.2
</code></pre>

VSCode Version:
<pre><code>

VSCode: 1.64.0
</code></pre>

Operating System:
<pre><code>

macOS 12.2 (Monterey)
</code></pre>

Extension options:
<pre><code>

(none)
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
This is working as expected at the moment and due to https://github.com/microsoft/vscode/issues/115354.  We currently only support renaming from templates and string literals in typescript files. The v14 release will enable renaming from typescript files by disabling the built in TS rename provider.
