### ISSUE TITLE
Create missing component members from within template

### ISSUE THREAD

**Issue by moniuch** [angular/vscode-ng-language-service#1610]
**Is your feature request related to a problem? Please describe.**

# 🚀 feature request

### Description
 A clear and concise description of the problem or missing capability...

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Please provide creating a missing component member (property or method) from within template, as a QuickFix.

When you first develop a chunk of html and refer to methods/properties that don't exist yet, it would be a great helper and time-saver to:

- be able to create them automatically in .ts as QuickFix, without having to copy/paste the name of the member
- have the newly created members infer the types as much as possible
- have it as a bulk operation (ie. if 3 members missing, create them all in one go)
- have the QuickFix menu item available regardless of the caret position:
    - **Create missing method 'foo()'** - when cursor over the squiggled `foo`
    - **Create missing member(s)** - available anywhere if members missing

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by ivanwonder** [comment]
https://github.com/ivanwonder/angular/commit/6bb8770e6c590997930a51bf85b80408bd78832c

I made a prototype for this recently. Waiting for the official implementation😀

**Comment by ivanwonder** [comment]
If OK, I think I can finish my code this week and open a PR.

**Comment by ivanwonder** [comment]
@dylhunn The [PR](https://github.com/angular/angular/pull/46764) is alreay.

You can try it in vscode with this [PR](https://github.com/angular/vscode-ng-language-service/pull/1723).

**Comment by atscott** [comment]
Re-opening since this still needs to be supported on the extension side: https://github.com/angular/vscode-ng-language-service/pull/1723

**Comment by atscott** [comment]
fixed by #1723
