### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MykhailoIskiv** [angular/vscode-ng-language-service#1615]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `13.2.5`
- OS Version: `Darwin x64 21.3.0`
- VS Code version: `1.65.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/bs/td4lwg4j03x4l5xw1bxk1s_w0000gn/T/Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/8251448/Angular.ng-template-unresponsive.cpuprofile.txt)
github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please open a new issue and follow the instructions in the issue template.
