### ISSUE TITLE
Errors in html template when JS/TS file is replaced externally

### ISSUE THREAD

**Issue by daniol** [angular/vscode-ng-language-service#1624]
# 🐞 bug report

### Description

Every time a .ts or .js file is replaced externally, html templates are swamped with errors (see screenshot).

## Bug Type

What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. Open an Angular 13 Project
2. Start development server (`ng serve`)
3. Replace a file externally, with a copy that just adds a line of code (emulates an external code generation tool)
4. "ngtsc" non-sense errors are displayed

Errors remain until Angular Language Server is restarted

**Expected behavior**

No errors should be displayed. It should not be necessary to restart the language server.

### **Logs**

<pre><code>
Info 772  [8:32:8.69] A plugin threw an exception in getExternalFiles: Error: Debug Failure. False expression: getScriptInfo
Verbose Debug Information: scriptInfo for a file 'c:/XXX/src/generated/common_pb.d.ts' Path: 'c:/XXX/src/generated/common_pb.d.ts' / 'c:/XXX/src/generated/common_pb.d.ts' is missing.
Info 773  [8:32:8.90] Error: Debug Failure. False expression: getScriptInfo
Verbose Debug Information: scriptInfo for a file 'c:/XXX/src/generated/common_pb.d.ts' Path: 'c:/XXX/src/generated/common_pb.d.ts' / 'c:/XXX/src/generated/common_pb.d.ts' is missing.
    at c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164982:30
    at Object.map (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:652:29)
    at ConfiguredProject.Project.getScriptInfos (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164980:27)
    at Object.getExternalFiles (c:\Users\XXX\.vscode\extensions\angular.ng-template-14.0.0-next.0\node_modules\@angular\language-service\bundles\language-service.js:45477:42)
    at Object.getExternalFiles (c:\Users\XXX\.vscode\extensions\angular.ng-template-14.0.0-next.0\node_modules\@angular\language-service\index.js:27:149)
    at c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164876:46
    at Object.flatMap (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:716:25)
    at ConfiguredProject.Project.getExternalFiles (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164872:35)
    at ProjectService.reloadFileNamesOfConfiguredProject (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:168109:86)
    at ConfiguredProject.updateGraph (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:166141:54)
</code></pre>

### **Screenshots**

![errors](https://user-images.githubusercontent.com/196808/161693956-49575c1b-1f0f-43d8-b500-9cb6e7662418.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      13.2.4
@angular/cli                    13.2.4
@schematics/angular             13.2.4
ng-packagr                      13.2.1
rxjs                            7.5.4
typescript                      4.5.5
</code></pre>

Extension Version:
<pre><code>
v14.0.0-next.0
</code></pre>

VSCode Version:
<pre><code>
1.63.2 (user setup)
</code></pre>

Operating System:
<pre><code>
Windows_NT x64 10.0.19042
</code></pre>

Extension options:
<pre><code>
"angular.disableNgcc": true
</code></pre>

**Comment by daniol** [comment]
@atscott I created this separated issue from #1616 as suggested 🙂

**Comment by atscott** [comment]
@daniol Thanks for that - it gets impossible to track several different root causes with a similar ending error in one issue. Are you able to reproduce this bug in a fresh Angular app? I wasn't able to reproduce the error so I'm wondering if it is something more specific to your project.

**Comment by daniol** [comment]
I finally solved the issue, it was caused by some _weirdness_.
Updating this plug-in and deleting every **node_modules** Folder solved the issue.
The TS language service is now working very stable.

**Comment by atscott** [comment]
@daniol Thanks for the update and sorry you were experiencing issues. These kinds of things are the most frustrating to experience and so difficult for us to investigate.
