### ISSUE TITLE
Go to definition in angular 13

### ISSUE THREAD

**Issue by theOofDoctor** [angular/vscode-ng-language-service#1633]
# 🐞 bug report
### Description
Ctrl + Click and Go to definition no longer work for angular components in Angular 13 project

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Open an Angular 13 project in vscode
2. Open a template file that has a component in it
3. Hold ctrl and hover over the component

**Expected behavior**

Component name should be underlined and I should be taken to the component file when it is clicked.

### **Screenshots**

https://user-images.githubusercontent.com/58712803/165388730-0fa3fb6b-2194-4c6a-a1f5-e9f7f1125e15.mp4

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 13.3.2
Node: 16.14.2
Package Manager: npm 8.6.0
OS: win32 x64

Angular: 13.3.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@angular/cdk                    12.2.13
@angular/material               12.2.13
@schematics/angular             13.3.2
rxjs                            6.6.6
typescript                      4.6.3
</code></pre>

Extension Version:
<pre><code>v13.3.1</code></pre>

VSCode Version:
<pre><code>Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22593
</code></pre>

Operating System:
<pre><code>Windows 11, version 22H2 Insider Preview 10.0.22598.200 (ni_release)
</code></pre>

Extension options:
<pre><code>"angular.enable-strict-mode-prompt": false,
</code></pre>

**Comment by atscott** [comment]
Do you have an example project? There's not enough information here to determine what's happening for you. To be clear, go to definition _does_ work in Angular v13 so it must be something specific to your project/setup.

**Comment by atscott** [comment]
I notice that you've set the strict mode prompt to `false` in the extension options. What does the `angularCompilerOptions` look like in your `tsconfig.json`?

**Comment by theOofDoctor** [comment]
@atscott Was hoping that it wasn't a me issue lol. It has worked great for the past year or so, just noticed that since we updated to angular 13 it hasn't worked.

Here's my `tsconfig.json`

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "module": "es2020",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "target": "es2018",
    "skipLibCheck": true,
    "typeRoots": [
      "node_modules/@types",
      "src/typings.d.ts"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
To be honest, I have no idea when strict mode prompt was set to false, I don't remember ever manually setting it to that.

**Comment by atscott** [comment]
@theOofDoctor Can you try adding
```
"angularCompilerOptions": {
    "strictTemplates": true,
  }
```

I don't know what version you're updating _from_ but older versions of the language service had its own template parsing.  This meant that the diagnostics would not always match the compiler output when you tried to build. Now it uses the same compiler as when building your project. This does have the side effect of not having type information if you've configured your project to build without strict types.

**Comment by theOofDoctor** [comment]
@atscott That worked! Thanks so much.
