### ISSUE TITLE
Template intellisense breaks when attribute quotes are auto-added

### ISSUE THREAD

**Issue by sammce** [angular/vscode-ng-language-service#1636]
# 🐞 bug report

### Description
When I select one of the suggestions offered by the extension for any attribute in a template (such as `id`) by pressing `Enter`, the suggestions inside the double quotes do not work. I have included a screen recording of this happening in a barebones angular project created with `ng new`.

VSCode also has an HTML specific setting (`html.autoCreateQuotes`) which automatically inserts double quotes when you type `=` after the attribute. The suggestions also do not work when these quotes are inserted. This can be seen in the clip when I add the `[id]` binding for the second time, where I press `=` manually instead of pressing `Enter`.

If I move my cursor out of the quotes, and back in, the suggestions return and work as expected, as shown in the screen recording.

https://user-images.githubusercontent.com/78268167/165985021-3b8dba21-0a37-41e7-a60c-c3c1302c9982.mov

If I disable `html.autoCreateQuotes` and add the quotes manually, the error is not present. Only when the quotes are auto-added by either accepting the extension suggestion or by the aforementioned setting does the problem occur.

The clip below is a recording of the suggestions working when `html.autoCreateQuotes` is set to `false` in `settings.json`.

https://user-images.githubusercontent.com/78268167/165987008-9148615c-5f6a-4e80-86ce-a3dbb3d714e4.mov

## Bug Type

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

Steps to reproduce the behaviour:
1. Use `Tab` or `Enter` to select one of the auto-suggested attribute bindings.
1. The component suggestions aren't shown.

**Expected behaviour**

The suggestions should show up when the quotes are being auto-added by either the extension of VSCode itself.

## 🌍  Your Environment
**Angular Version:**
```
Angular CLI: 13.3.4
Node: 16.14.2
Package Manager: pnpm 6.32.6
OS: darwin arm64

Angular: 13.3.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.4 (cli-only)
@angular-devkit/build-angular   13.3.4
@angular-devkit/core            13.3.4 (cli-only)
@angular-devkit/schematics      13.3.4 (cli-only)
@angular/cli                    13.3.4
@schematics/angular             13.3.4 (cli-only)
rxjs                            7.5.5
typescript                      4.6.4
```

Extension Version:
```
Angular Language Service: v13.3.1
```

VSCode Version:
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:47:29.396Z (2 wks ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.1.0
```

Operating System:
```
macOS Monterey 12.0.1
```

Extension options:
I haven't altered any extension settings.

**Anything else relevant?**
I was also able to reproduce the bug on my Linux machine.

**Angular Version:**
```
Angular CLI: 13.3.4
Node: 16.13.1
Package Manager: pnpm 6.32.3
OS: linux x64

Angular: 13.3.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.4 (cli-only)
@angular-devkit/build-angular   13.3.4
@angular-devkit/core            13.3.4 (cli-only)
@angular-devkit/schematics      13.3.4 (cli-only)
@angular/cli                    13.3.4
@schematics/angular             13.3.4 (cli-only)
rxjs                            7.5.5
typescript                      4.6.4
```

Extension Version:
```
Angular Language Service: v13.3.1
```

VSCode Version:
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.16.19-76051619-generic
```

Operating System:
```
Pop!_OS 21.10 x86_64
Kernel: 5.16.19-76051619-generic
```

Extension options:
```
I haven't altered any extension settings.
```

**Comment by atscott** [comment]
This is appears to be a VSCode issue. After a snippet is inserted, autocompletion is not requested automatically by typing characters. You have to trigger it with the ctrl+[space].
