### ISSUE TITLE
Angular Language Service breaks Typescript intellisense

### ISSUE THREAD

**Issue by distante** [angular/vscode-ng-language-service#164]
I was instructed to post in the Angular but I suppose here is a better place for this. I will just copy what I have posted there.

## Current behavior
When the Angular Language Service Extension is enabled `*.ts` files intellisense does not work.

## Expected behavior
Intellisense should still work when the extension is enabled.

## Minimal reproduction of the problem with instructions
1. create a new ionic project with `ionic start` and select "conference" (since it is a complete project).
2. Install Angular Language Service.
3. Test intellisense on ts files

Repo: https://github.com/distante/Angular-Language-Service-Breaks-Intellisense

## Environment
<pre><code>Extension Version: 0.1.7</pre></code>

## For Tooling issues: 
<pre><code>- Node version: v6.11.2 
- Platform:  Mac, Windows</pre></code>
## Others:
 <pre><code>OS: Windows 10 creators update / MacOS Sierra
VS Code version: tested on 1.14.2 and 1.15.1 (32bits and 64bits)
</pre></code>
## Extensions:
 <pre><code>Angular.ng-template
bobjoy.vscode-browser-plus
christian-kohler.path-intellisen
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
helixquar.asciidecorator
jakethashi.vscode-angular2-emmet
johnpapa.Angular2
michelemelluso.code-beautifier
mrmlnc.vscode-apache
rbbit.typescript-hero
Shan.code-settings-sync
vsmobile.cordova-tools
wayou.vscode-todo-highlight
Zignd.html-css-class-completion

</code></pre>

**Comment by kyliau** [comment]
Closing this, since this issue is more than two years old. Please open a new one if problem persists.
