### ISSUE TITLE
Using template with require causes error to be reported.

### ISSUE THREAD

**Issue by bhagatparwinder** [angular/vscode-ng-language-service#165]
In a component where we use require to load in the template angular language service reports this error:
[Angular] Component TestComponent must have a template or templateUrl.

@component({
selector: "test-component",
template: require("./test-component.html")
})

![Screenshot](https://user-images.githubusercontent.com/6809087/30167346-b98e55ee-93ab-11e7-9ffd-36cb7ef9d4ed.png)

Updated issue: https://github.com/angular/vscode-ng-language-service/issues/70

**Comment by andycwk** [comment]
Yeh... I see the same issue, and for a project that uses `require(...)` heavily for templating it would be nice to see this tool following `require(...)` in addition to inline & url template styles!

**Comment by mrjamesriley** [comment]
Am still having this issue myself, with VS Code `1.17.2` (which is using Typescript `2.5.3`).

**Comment by chuckjaz** [comment]
The language service does not support `require` as it is only supported during JIT.
