### ISSUE TITLE
Support Angular v14 RC

### ISSUE THREAD

**Issue by keatkeat87** [angular/vscode-ng-language-service#1657]
# 🚀 feature request

### Description
Angular v14 RC is out, Language Service is very important extension in Angular eco, hope can have a early try. 
I try create a angular app with version 14 RC, and get a error in language service.

![image](https://user-images.githubusercontent.com/8691013/168062976-1dc7e0f2-7b6d-46d3-9848-6bd2a2c06a6f.png)
this is the output log

![image](https://user-images.githubusercontent.com/8691013/168063010-9c762be1-4b65-4a58-ac68-e8a0b011b5c6.png)
I also try manually install Language Service v14.0.0-next.0, but the error is same.

![image](https://user-images.githubusercontent.com/8691013/168065912-2e8c26b9-2328-40b5-a294-2d9daac3ef18.png)

[git repository](https://github.com/keatkeat87/angular-14-rc-language-service-issue.git)

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### ng version
Angular CLI: 14.0.0-rc.0
Node: 16.15.0
Package Manager: yarn 1.22.15 
OS: win32 x64

Angular: 14.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0-rc.0
@angular-devkit/build-angular   14.0.0-rc.0
@angular-devkit/core            14.0.0-rc.0
@angular-devkit/schematics      14.0.0-rc.0
@schematics/angular             14.0.0-rc.0
rxjs                            7.5.5
typescript                      4.6.4

**Comment by atscott** [comment]
The fix for this was included in the 13.3.4 release
