### ISSUE TITLE
angular.json support or custom path parameter to tsconfig.json

### ISSUE THREAD

**Issue by Viapatis** [angular/vscode-ng-language-service#1667]
# 🚀 feature request

### Description
My project has angular.json with given path for tsconfig
```
{
...
  "projects": {
    ...
    "frontend": {
      ...
      "architect": {
        ...
        "build": {
          ...
            "tsConfig": "src/tsconfig.app.json",
        }
      }
    }
  },
}
```
since the extension requires `sctrictTamplate:true` for full-fledged work, which is already enabled in src/tsconfig.app.json , I would not want to write it in tsconfig.json , it bothers me there

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
add angular.json support

### Describe alternatives you've considered
add path parameter to tsconfig in extension settings

**Comment by atscott** [comment]
> I would not want to write it in tsconfig.json , it bothers me there

What exactly do you mean by this? Do you mean you just don't like seeing it in the `tsconfig.json`? Or that by doing so, you get compilation errors that you cannot resolve? In the v14 release, there is an option to enable strict templates for the extension and ignoring what you have set in the `tsconfig.json`. Would that work for you?
