### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Vijay69** [angular/vscode-ng-language-service#1699]
- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `14.0.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
