### ISSUE TITLE
undefined is unrecognized primitive?

### ISSUE THREAD

**Issue by fxck** [angular/vscode-ng-language-service#17]
why?

**Comment by chuckjaz** [comment]
Can I get an example of what you mean?

**Comment by fxck** [comment]
It's an error throw when you try to compare value to undefined in template.

*ngIf="foo === undefined"

**Comment by chuckjaz** [comment]
Tracking in https://github.com/angular/angular/issues/13412

**Comment by chuckjaz** [comment]
Closed in 0.0.11
