### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vishalrindhe** [angular/vscode-ng-language-service#1709]
- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `14.0.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8168,
		"activateCallTime": 40,
		"activateResolvedTime": 4,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Angular.ng-template",
				"_lower": "angular.ng-template"
			},
			"activationEvent": "onLanguage:html"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please open a new issue and follow the instructions in the issue template.
