### ISSUE TITLE
Plugin does not work / Troubleshooting section available?

### ISSUE THREAD

**Issue by apazureck** [angular/vscode-ng-language-service#171]
Hi,

Your plug-in does not work for me.

I installed the extension, added a userlist.component.ts and a userlist.component.html, which is set as template in my component class.  I do not get any intellisense in my html template. How can I fix this? Do you have any log level settings? How can I even find out what's wrong. I only get for example getHoverAt: 6ms, getDefinitionAt: 0ms output entries.

userList.component.html:
```html
<table>
    <thead>
        <th>ID</th>
        <th>Vorname</th>
        <th>Nachname</th>
        <th>email</th>
        <th>Kontostand</th>
    </thead>
    <tbody>
        <tr *ngFor="let user of users">
            <td>{{user.id}}</td>
            <td>{{user.firstName}}</td>
            <td>{{user.secondName}}</td>
            <td>{{user.email}}</td>
            <td>{{user.balance | currency:'EUR':true}}</td>
        </tr>
    </tbody>
</table>
```

The userlist.component.ts
```typescript
import {Component} from "@angular/core";
import { ICustomer } from "./ICustomer";

@Component({
    selector: "bs-user-admin",
    templateUrl: "app/user/userList.component.html"
})
export class UserAdminstrationComponent {
    users: ICustomer[] = [
        { firstName: "Hans", secondName: "Wurst", id: 1, balance: 0, email: "hans@wurst.de", passwordHash: "asdfefaw" },
        { firstName: "Sepp", secondName: "Meier", id: 1, balance: 0, email: "sepp@meier.de", passwordHash: "aasgserd" }
    ]
}
```

Thanks

**Comment by joeeames** [comment]
same

**Comment by Maximaximum** [comment]
I had a similar issue: nothing worked at all, I got only the general intellisense hints, just as if the extension was not installed.
However, when I removed the extension and re-installed it again, it started to work. I wonder, though, how much time will it last until it goes down again.

**Comment by apazureck** [comment]
@Maximaximum Thank you for that hint, I'll try it next time I work with angular. Otherwise I will fork it and see what happens.

**Comment by Darkein** [comment]
Same problem here :(

**Comment by apazureck** [comment]
@Darkein: Have you tried the solution by @Maximaximum?

**Comment by Darkein** [comment]
i tried many times yesteday but nothing worked (reinstall the extension, reload window, restart vscode)
Nevertheless it seems to work today. Maybe restart the computer corrected the problem ?

**Comment by chuckjaz** [comment]
The location of your template is not resolved by the language service.

The language service uses the AOT compiler to resolve `.html` references and they need to be expressed as relative to the current component. For example, `"./userList.component.html"`.

**Comment by Maximaximum** [comment]
After I had reinstalled the extension, it seemed to work for a few hours, but eventually it falls down again and again. It seem like when I do nothing, it works ok :) but when I start to actively write the code, it dies

**Comment by kyliau** [comment]
The language service now has a debug mode which will print external templates discovered in the program to the logs if you set the environment variable `NG_DEBUG`.
