### ISSUE TITLE
Binding syntax outside of an attribute still highlighted as a binding rather than plain text

### ISSUE THREAD

**Issue by Cdrew92** [angular/vscode-ng-language-service#1725]
# 🐞 bug report

### Is this a regression?

N/A

### Description

 A clear and concise description of the problem...

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

## Bug Type
What does this bug affect

-  [x] Angular Language Service VSCode extension

- [ ] Angular Language Service server

## Reproduction

1. in a component.html file add the following:
```
    <app-image-img>
        [filesArray]="event.Event_Files" //this line of text is blue!
    </app-image-img>
```

**Expected behavior**

- Because the ```filesArray``` property is defined outside the closing arrow of the opening ```<app-image-img>``` element, I would expect the text to turn white as it does when a property without an array is added outside the opening arrow:

```
    <app-image-img>
        [filesArray]="event.Event_Files" //this line of  text is blue, indicating no error!
        files="test" //this line of text is white, denoting an error!
    </app-image-img>
```

### **Logs**

N/A - No errors in Angular Server Log or Browser Console

### **Screenshots**

Incorrectly added property tag outside of closing arrow: (unexpected behavior, text is blue.)
![image](https://user-images.githubusercontent.com/39171327/179254371-7cda3e60-df5a-4620-9752-8ba4dd9a00a8.png)

Shows white text when non-bracketed property is added: (expected behavior, showing white text)
![image](https://user-images.githubusercontent.com/39171327/179254707-52aedae4-bcbb-4ba9-8288-d3e03cf76bf4.png)

Correct implementation of property binding: (working properly)
![image](https://user-images.githubusercontent.com/39171327/179254840-4250f2f2-41ec-4a15-bf04-aed03e7f354b.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 13.3.7
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64
</code></pre>

Extension Version:
<pre><code>
Angular Language Service v14.01
</code></pre>

VSCode Version:
<pre><code>
Version: 16.9.0 (user setup)
</code></pre>

Operating System:
<pre><code>
Edition	Windows 10 Pro
Version	21H2
Installed on	‎5/‎28/‎2021
OS build	19044.1766
Experience	Windows Feature Experience Pack 120.2212.4180.0
</code></pre>

Extension options:
<pre><code>
{
    "angular.log": "verbose"
}
</code></pre>

**Anything else relevant?**
N/A

**Comment by atscott** [comment]
This is not a syntax error. Syntactically, this is just a text literal. 

The blue and white highlighting is the syntax highlighting, which is regex-based. White is a text literal and blue is an attribute. 

There won't ever be an error for this, but we could investigate how feasible it is to ensure the syntax highlighting gets fixed here.

**Comment by Cdrew92** [comment]
Thanks, Andrew!

**Comment by atscott** [comment]
Closing in favor of https://github.com/angular/angular/issues/49842

**Comment by a-stewart** [comment]
I've just come across the same issue. The challenge is that the language is injected into `L:text.html -comment` which means it applies the logic at the root element.

There are a few patterns which are inserted:

```
    {
      "include": "#interpolation"
    },
    {
      "include": "#propertyBinding"
    },
    {
      "include": "#eventBinding"
    },
    {
      "include": "#twoWayBinding"
    },
    {
      "include": "#templateBinding"
    }
```

If we remove `#propertyBinding` and `#eventBinding`, the default html language extension seems to be fine highlighting the contents anyway.

![image](https://github.com/angular/vscode-ng-language-service/assets/150152/d8109dd9-952d-4360-adab-1a9040f1c839)

![image](https://github.com/angular/vscode-ng-language-service/assets/150152/7e27d1fb-b54d-4114-88fd-aa5ace757fa8)

![image](https://github.com/angular/vscode-ng-language-service/assets/150152/1b5a05d5-ce15-4a38-ac6d-33c2a26a490d)

What do you reckon to removing the bindings and letting the default html extension handle these?


An alternative option could be to have a second injected grammar which injects into something like `L:text.html meta.tag -comment`. This would allow for defining certain grammars which are only matched in tags, such as these bindings, whilst also allowing for things like interpolation to be defined on `source.html`.

**Comment by atscott** [comment]
Hi @a-stewart, that seems reasonable. Would you like to send a PR out for this?
