### ISSUE TITLE
Intellisense not working inside the HTML files

### ISSUE THREAD

**Issue by jesorian** [angular/vscode-ng-language-service#1736]
The Intellisense  is not working inside the html files. I am using angular 13 LTS with the latest vscode and angular language service.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please open a new issue and follow the instructions in the issue template.
