### ISSUE TITLE
Extension breaks after updating to latest Angular v14.2.0 & Typescript 4.8.2

### ISSUE THREAD

**Issue by TomTomB** [angular/vscode-ng-language-service#1746]
# 🐞 bug report

### Description

I've just updated angular & typescript to latest verions. 
After updating typescript to 4.8.2 the extension is completly broken. 

My project compiles fine, but I am now getting errors like the following all over my code

```
'ChangeDetectionStrategy' is defined but never used.eslint[@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars)

Class is using Angular features but is not decorated. Please add an explicit Angular decorator.(-992007)
```

for the following component:

```
import { ChangeDetectionStrategy, Component, ViewEncapsulation } from '@angular/core';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  selector: 'app-comp',
  templateUrl: './comp.component.html',
})
export class SomeComponent {}
```

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>
[Trace - 00:07:00] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "(omitted)",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 16,
                    "character": 13
                },
                "end": {
                    "line": 16,
                    "character": 31
                }
            },
            "message": "Class is using Angular features but is not decorated. Please add an explicit Angular decorator.",
            "severity": 1,
            "code": -992007
        }
    ]
}
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
   Node : 16.16.0
   OS   : linux x64
   yarn : 3.2.1
   
  @angular : 14.2.0
   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : 14.5.4
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.8.2
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 14.3.0
         @ngrx/entity: 14.3.0
         @ngrx/router-store: 14.3.0
         @ngrx/store: 14.3.0
         @tomtomb/ngrx-toolkit: 3.4.1
         apollo-angular: 3.0.1
         @ngrx/schematics: 14.3.0
         @ngrx/store-devtools: 14.3.0
         @storybook/angular: 6.5.10
</code></pre>

Extension Version:
<pre><code>
v14.1.0
</code></pre>
VSCode Version:
<pre><code>
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.25188
</code></pre>

Operating System:
<pre><code>
Windows 11 Pro Insider Preview 22H2 (25188.1000 rs_prerelease)
</code></pre>

**Comment by ivanwonder** [comment]
I think we should wait for the maintainer to release the new version to be compatible with Angular v14.2.0.

@dylhunn

**Comment by laggage** [comment]
Got the same problem, have to go back to typescript@4.7 as a temp workaround. Any plan for typescript4.8 support?

**Comment by NoumanMukhtar** [comment]
Any update about a new supported release😕?

**Comment by zuohuadong** [comment]
see : 
https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#decorators-are-placed-on-modifiers-on-typescripts-syntax-trees

**Comment by dylhunn** [comment]
[VSCode Extension 14.2.0](https://marketplace.visualstudio.com/) has now been published, and this should be fixed.

**Comment by dylhunn** [comment]
@TomTomB Let me know if you still experience issues.
