### ISSUE TITLE
Yarn PnP - "No config file" error on a project using Yarn PnP mode

### ISSUE THREAD

**Issue by ld210** [angular/vscode-ng-language-service#1748]
# 🐞 bug report

### Description
We recently choose Yarn against NPM, and manage to have a working Plug&Play repo, no node_modules anymore. Everything is working as expected except for the language service. It doesn't work anymore, with a "No config file..." error.
In the logs, i can see that the extension uses its own tsserver instead of the workspace's one.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

I have set up a repro with PnP here : https://github.com/ld210/yarnpnp-storybook-angular-repro
It was for a Storybook related issue, but it applies for this one as well.
For a working example, simply generate a new app with `ng new`

**Expected behavior**
Angular Language Service extension for VSCode should be working in a project that uses Yarn PnP

### **Logs**

<pre><code>
[Trace - 11:54:42 AM] Sending request 'initialize - (0)'.
[Trace - 11:54:43 AM] Received notification 'window/logMessage'.
[Info  - 11:54:43 AM] Angular language server process ID: 21212
[Trace - 11:54:43 AM] Received notification 'window/logMessage'.
[Info  - 11:54:43 AM] Using typescript/lib/tsserverlibrary v4.7.4 from /Users/.../.vscode/extensions/angular.ng-template-14.1.0/node_modules/typescript/lib/tsserverlibrary.js
[Trace - 11:54:43 AM] Received notification 'window/logMessage'.
[Info  - 11:54:43 AM] Using @angular/language-service v14.1.0 from /Users/.../.vscode/extensions/angular.ng-template-14.1.0/node_modules/@angular/language-service/index.js
[Trace - 11:54:43 AM] Received notification 'window/logMessage'.
[Info  - 11:54:43 AM] Logging is turned off. To enable, run command 'Open Angular server log'.
[Trace - 11:54:43 AM] Received response 'initialize - (0)' in 238ms.
[Trace - 11:54:43 AM] Sending notification 'initialized'.
[Trace - 11:54:43 AM] Sending notification 'textDocument/didOpen'.
[Trace - 11:54:43 AM] Sending notification 'textDocument/didOpen'.
[Trace - 11:54:43 AM] Sending notification 'textDocument/didOpen'.
[Trace - 11:54:43 AM] Received notification 'angular/projectLoadingStart'.
[Trace - 11:54:44 AM] Received notification 'angular/projectLoadingFinish'.
[Trace - 11:54:49 AM] Sending request 'textDocument/codeLens - (1)'.
[Trace - 11:54:49 AM] Received notification 'window/logMessage'.
[Error - 11:54:49 AM] No config file for /Users/.../Documents/Git/front-angular/src/app/dashboard/statistics/tiles/traffic-tile/traffic-tile.component.html
[Trace - 11:54:49 AM] Received response 'textDocument/codeLens - (1)' in 2ms.
[Trace - 11:54:49 AM] Sending request 'textDocument/codeLens - (2)'.
[Trace - 11:54:49 AM] Received notification 'window/logMessage'.
[Error - 11:54:49 AM] No config file for /Users/.../Documents/Git/front-angular/src/app/dashboard/statistics/tiles/traffic-tile/traffic-tile.component.html
[Trace - 11:54:49 AM] Received response 'textDocument/codeLens - (2)' in 1ms.
[Trace - 11:55:27 AM] Sending request 'textDocument/codeLens - (3)'.
[Trace - 11:55:27 AM] Received response 'textDocument/codeLens - (3)' in 1ms.
[Trace - 11:55:27 AM] Sending request 'textDocument/codeLens - (4)'.
[Trace - 11:55:27 AM] Received response 'textDocument/codeLens - (4)' in 1ms.

</code></pre>

And here is the output on a working environment : 

<pre><code>
[Info  - 2:18:04 PM] Using typescript/lib/tsserverlibrary v4.7.4 from /Users/.../Documents/Git/test-app/node_modules/typescript/lib/tsserverlibrary.js
[Trace - 2:18:04 PM] Received notification 'window/logMessage'.
[Info  - 2:18:04 PM] Using @angular/language-service v14.1.0 from /Users/.../.vscode/extensions/angular.ng-template-14.1.0/node_modules/@angular/language-service/index.js
...
No config file for /Users/.../Documents/Git/test-app/src/app/app.component.html
[Trace - 2:18:06 PM] Received response 'textDocument/codeLens - (2)' in 200ms.
[Trace - 2:18:06 PM] Received notification '$/progress'.
[Trace - 2:18:06 PM] Received notification 'window/logMessage'.
[Info  - 2:18:06 PM] Enabling Ivy language service for /Users/.../Documents/Git/test-app/tsconfig.json.
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 14.2.1
Node: 16.17.0
Package Manager: yarn 3.2.3 
OS: darwin arm64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1 (cli-only)
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1 (cli-only)
@angular-devkit/schematics      14.2.1 (cli-only)
@angular/cli                    14.2.1
@schematics/angular             14.2.1 (cli-only)
rxjs                            7.5.6
typescript                      4.7.4
</code></pre>

Extension Version:
<pre><code>
v14.1.0
</code></pre>

VSCode Version:
<pre><code>
v1.70.2

</code></pre>

Operating System:
<pre><code>
MacOS Monterey 12.5.1

</code></pre>

**Anything else relevant?**
Here is the content of vscode settings.json
<pre><code>
{
  "search.exclude": {
    "**/.yarn": true,
    "**/.pnp.*": true
  },
  "eslint.nodePath": ".yarn/sdks",
  "typescript.tsdk": ".yarn/sdks/typescript/lib",
  "typescript.enablePromptUseWorkspaceTsdk": true
}
</code></pre>

And here the typescript version used in the sdk :

<pre><code>
{
  "name": "typescript",
  "version": "4.7.4-sdk",
  "main": "./lib/typescript.js",
  "type": "commonjs"
}
</code></pre>

**Comment by ld210** [comment]
Ok, after digging a little bit, there's variations between the Typescript SDK installed by Yarn and used in the workspace, and a typical Typescript installation.
In the SDK, there's no `lib.*.d.ts` files. But looking at the `resolveTsServerFromTsdk` function, the path to the package.json is resolved relatives to the `tsserverlibrary.js` file, like this : `path.resolve(tsserverlib, '../../package.json')`, but in the Yarn sdk context, it should be `path.resolve(tsserverlib, '../package.json')` so the resolveTsServerFromTsdk returns `undefined` instead of the `NodeModule` object.

**Comment by ld210** [comment]
After some digging, i found 2 issues.
The first one is in the function `resolveWithMinVersion` from `server/src/version_provider.ts`. More specifically, it is the `resolve` function from `common/resolver.ts` that fails to return a `NodeModule` object.
After fixing it, then it's ngcc that failed (because of the absence of node_modules folder, i guess). When checking the "disabled automatic ngcc" option, the language service works fine.

**Comment by ld210** [comment]
I made a dirty patch. I could make a PR, but i don't know how you guys would want to handle this. Here is what i did : 
```typescript
import * as path from 'path';

export function resolve(packageName: string, location: string, rootPackage?: string): NodeModule|
    undefined {
  const isYarnModule = location.startsWith('.yarn/sdks');
  location = isYarnModule ? '.yarn/sdks' : location;
  rootPackage = rootPackage || packageName;
  try {
    const packageJsonPath = isYarnModule ? path.resolve(`${location}/${rootPackage}/package.json`) : require.resolve(`${rootPackage}/package.json`, {
      paths: [location],
    });
    // Do not use require() to read JSON files since it's a potential security
    // vulnerability.
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    const resolvedPath = isYarnModule ? path.resolve(`${location}/${packageName}`) : require.resolve(packageName, {
      paths: [location],
    });
    return {
      name: packageName,
      resolvedPath,
      version: new Version(packageJson.version),
    };
  } catch {
  }
}
```

**Comment by ld210** [comment]
I'm still facing the same issue with v14.2.0

**Comment by atscott** [comment]
> I made a dirty patch. I could make a PR, but i don't know how you guys would want to handle this.

I was on leave for the last month but I'm back now. Could you open a PR for this?

**Comment by ld210** [comment]
@atscott I'll be happy to. I will open a PR as soon as i can.
