### ISSUE TITLE
Extension issue```json  { 	"messages": [], 	"activationTimes": { 		"codeLoadingTime": 15863, 		"activateCallTime": 14, 		"activateResolvedTime": 440, 		"activationReason": { 			"startup": false, 			"extensionId": { 				"value": "Angular.ng-template", 				"_lower": "angular.ng-template" 			}, 			"activationEvent": "onLanguage:typescript" 		} 	}, 	"runtimeErrors": [], 	"runningLocation": { 		"affinity": 0, 		"kind": 1 	} } ```

### ISSUE THREAD

**Issue by satyam1509** [angular/vscode-ng-language-service#1752]
- Issue Type: `Bug`
- Extension Name: `ng-template`
- Extension Version: `14.2.0`
- OS Version: `Linux x64 5.15.0-46-generic`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
