### ISSUE TITLE
Disabling language service for [...] because it is not an Angular project

### ISSUE THREAD

**Issue by JoshuaWalsh** [angular/vscode-ng-language-service#1755]
# 🐞 bug report

### Is this a regression?

I don't think so. I see the same behaviour in v0.1001.1, v11.1.0, and v11.2.14.

### Description

Intellisense isn't working inside Angular template files. When I check the Angular Language Server output, it says:

<pre><code>
[Info  - 1:55:55 pm] Disabling language service for c:/git/wrongopinions/client/tsconfig.json because it is not an Angular project ('@angular/core' could not be found).
</code></pre>

My project is an Angular app created using `ng new`. @angular/core is present in package.json, and installed within the node_modules directory.

I have no idea why the language server isn't considering it an Angular project.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

I can reproduce this bug by opening any Angular template file in any Angular project.

**Expected behavior**

Intellisense should work within Angular template files.

### **Logs**

https://pastebin.com/0Vxb2wP4

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 14.2.2
Node: 16.17.0
Package Manager: npm 8.15.0 
OS: win32 x64

Angular: 14.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.2
@angular-devkit/build-angular   14.2.2
@angular-devkit/core            14.2.2
@angular-devkit/schematics      14.2.2
@angular/cli                    14.2.2
@schematics/angular             14.2.2
rxjs                            7.5.6
typescript                      4.7.4
</code></pre>

Extension Version:
<pre><code>
v0.1001.1
v11.1.0
v11.2.14

</code></pre>

VSCode Version:
<pre><code>
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19044
</code></pre>

Operating System:
<pre><code>
Microsoft Windows 10 Pro 10.0.19044 Build 19044
</code></pre>

Extension options:
<pre><code>
{
    "angular.log": "verbose"
}
</code></pre>

(I have tried with "Experimental-ivy" both enabled and disabled, and I see the same behaviour.)

**Anything else relevant?**
Usually I open my `C:/git/wrongopinions` monorepo directly. I also tried adding `C:/git/wrongopinions/client` to a workspace, and opening `C:/git/wrongopinions/client` directly, but I see the same results.

I tried opening an older project of mine which I know used to work, but it no longer does. I can't think of anything that's changed since I last opened that project, other than upgrading NodeJS.

**Comment by atscott** [comment]
It looks like you're using version 11 of the extension. This certainly won't work for newer versions of Angular projects. Closing as unsupported.
