### ISSUE TITLE
Do we have a stable release that supports standalone components yet?

### ISSUE THREAD

**Issue by Memeplexx** [angular/vscode-ng-language-service#1759]
I cannot get the language service to work inside templates of standalone components.

I have found [this](https://github.com/angular/vscode-ng-language-service/issues/1662) but no stable version has been published yet.

PS. Thanks for this amazing extension :)

**Comment by Memeplexx** [comment]
Perhaps I'm doing something wrong then.
Are more recent versions available for vscode?
<img width="507" alt="image" src="https://user-images.githubusercontent.com/17923511/191320752-8e9b5a6d-60f8-483b-88b2-3fbbe8ca55af.png">

**Comment by atscott** [comment]
Your VSCode version is likely quite old. When we release the extension, we often bump the minimum required version of VSCode as well.
