### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by awoyemipatrick** [angular/vscode-ng-language-service#1769]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `14.2.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

(https://github.com/angular/vscode-ng-language-service/files/9681240/Angular.ng-template-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by atscott** [comment]
The extension requires running an Angular compilation of your project which we do expect to cause high CPU load. Based on the provided cpuprofile, this is what's happening. Closing as working as expected.
