### ISSUE TITLE
components suggestions are breaking emmet

### ISSUE THREAD

**Issue by fxck** [angular/vscode-ng-language-service#177]
![image](https://user-images.githubusercontent.com/1303561/31275268-e279c504-aa96-11e7-8c71-53ca1ae74876.png)

after you press enter here, "nothing" happens, it just enters the string, unlike when you typer say `div`

![image](https://user-images.githubusercontent.com/1303561/31275289-f791b550-aa96-11e7-90b9-fb12e3f068c7.png)

which inserts `<div></div>` with caret inside

cc @chuckjaz

**Comment by kyliau** [comment]
This issue is more than two years old, and it is no longer relevant in the v9 extension. 
In an external template, emmet autocompletion works correctly.
If problem persists, please open a new issue.

**Comment by olaszakos** [comment]
Come one now you just closed the other issue #232 because this one was open and now you close it. It's clearly broken.
