### ISSUE TITLE
No type hint on hover using *ngFor

### ISSUE THREAD

**Issue by TomaszCz** [angular/vscode-ng-language-service#1771]
I am not sure if this is VsCode bug or this extension itself. Please help me understand.

# 🐞 bug report

### Is this a regression?

Not sure

### Description

I dont see types in html when using *ngFor or *ngIf or async pipe

![image](https://user-images.githubusercontent.com/20865719/194004095-8c6fb79e-7bda-4178-97ed-44f08cc1e361.png)
![image](https://user-images.githubusercontent.com/20865719/194004754-5455def6-678e-4169-94c2-55029d85e720.png)

## Bug Type

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## 🌍  Your Environment
**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 14.2.1
Node: 16.17.1
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@angular/flex-layout            14.0.0-beta.40
@schematics/angular             14.2.1
ng-packagr                      14.2.0
rxjs                            6.6.7
webpack                         4.46.0
</code></pre>

Extension Version:
<pre><code>

v14.2.0
</code></pre>

VSCode Version:
<pre><code>

Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z (2 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

[OK] [Copy]
</code></pre>

Extension options:
![image](https://user-images.githubusercontent.com/20865719/194005446-e7b4681d-cd0d-42b4-9392-92582f48722a.png)

**Comment by atscott** [comment]
@TomaszCz can you provide an example project?

**Comment by TomaszCz** [comment]
ok, with those settings, all works 
```
"angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
```
  
  I had
  ```
"angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "strictInputAccessModifiers": true,
    "strictAttributeTypes": true,
    "strictSafeNavigationTypes": true,
    "strictDomLocalRefTypes": true,
    "strictDomEventTypes": false, // maybe some day
    "strictContextGenerics": true,
    "strictLiteralTypes": true,
    "strictNullInputTypes": true,
    "strictOutputEventTypes": true,
    "strictInputTypes": false, // maybe some day
    "strictTemplates": true
  }
```
  and then it doesnt.
Closing this one, sorry for confusion!

**Comment by atscott** [comment]
@TomaszCz Ah, yea that'll do it. It might help to start with `strictTemplates: false` in your project and _enable_ things one by one rather than `strictTemplates: true` and disabling things you're not ready for. This way, when you check the "force strict templates" box in the extension options, you'll get the entire strict templates checking from the language service since you haven't overridden any specific option to be `false`. The logic for this is here: https://github.com/angular/angular/blob/0d65e1de2c8ea76a5e48df227638cdeabac82c42/packages/compiler-cli/src/ngtsc/core/src/compiler.ts#L727-L827
