### ISSUE TITLE
property x of y is info on hover is duplicated multiple times after updating to 1.17.0 vsc

### ISSUE THREAD

**Issue by fxck** [angular/vscode-ng-language-service#178]
![image](https://user-images.githubusercontent.com/1303561/31275774-bc484caa-aa98-11e7-94a8-447b56a00266.png)

**Comment by chuckjaz** [comment]
Can you create a repository that demonstrates this issue and supply a link to it?

**Comment by kyliau** [comment]
I believe this has been fixed and is no longer an issue. Please reopen otherwise, thank you!
