### ISSUE TITLE
Initializing Angular language features pending

### ISSUE THREAD

**Issue by pilz97** [angular/vscode-ng-language-service#1782]
# 🐞 bug report

I have a big angular project, where I use the angular language service.
It worked fine for months but now, the "initializing Angular lanugage features"-Step never finishes.
I already searched through the issue board but couldn't find a solution.

I am using v14.2.0 with angular/cli: 14.2.3

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### **Logs**
<pre><code>

Info 0    [8:4:34.521] Format host information updated
Info 1    [8:4:34.523] reload projects.
Info 2    [8:4:34.523] Before ensureProjectForOpenFiles:
Info 3    [8:4:34.523] Open files: 
Info 3    [8:4:34.523] After ensureProjectForOpenFiles:
Info 4    [8:4:34.523] Open files: 
Info 4    [8:4:34.523] Host file extension mappings updated
Info 5    [8:4:34.523] Host watch options changed to {"watchFile":4,"watchDirectory":0,"fallbackPolling":2}, it will be take effect for next watches.
Info 6    [8:4:34.525] Angular language server process ID: 37456
Info 7    [8:4:34.525] Using typescript/lib/tsserverlibrary v4.8.4 from c:\angular-app\node_modules\typescript\lib\tsserverlibrary.js
Info 8    [8:4:34.526] Using @angular/language-service v14.2.0 from c:\Users\user\.vscode\extensions\angular.ng-template-14.2.0\node_modules\@angular\language-service\index.js
Info 9    [8:4:34.526] Log file: c:\Users\user\AppData\Roaming\Code\logs\20221021T080428\exthost1\Angular.ng-template\nglangsvc.log
Info 10   [8:4:34.538] Search path: c:/angular-app/projects/clinet/src/app/clientModule/components/notification-widget
Info 11   [8:4:34.540] For info: c:/angular-app/projects/clinet/src/app/clientModule/components/notification-widget/notification-widget.component.ts :: Config file name: c:/angular-app/tsconfig.json
Info 12   [8:4:34.541] Creating configuration project c:/angular-app/tsconfig.json
Info 13   [8:4:34.544] FileWatcher:: Added:: WatchInfo: c:/angular-app/tsconfig.json 2000 {"watchFile":4,"watchDirectory":0,"fallbackPolling":2} Project: c:/angular-app/tsconfig.json WatchType: Config file
Info 14   [8:4:34.546] Loading new project: Creating possible configured project for c:/angular-app/projects/client/src/app/clientModule/components/notification-widget/notification-widget.component.ts to open

</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 14.2.3
Node: 16.13.2
Package Manager: npm 8.4.0
OS: win32 x64

Angular: 14.2.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.3
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.3
@angular-devkit/schematics      14.2.3
@angular/cdk                    14.2.2
@angular/flex-layout            14.0.0-beta.40
@angular/language-service       14.2.7
@angular/material               14.2.2
@schematics/angular             14.2.3
ng-packagr                      14.2.1
rxjs                            6.6.7
typescript                      4.8.4
webpack                         4.44.2
</code></pre>

Extension Version:
<pre><code>
14.2.0

</code></pre>

VSCode Version:
<pre><code>
1.72.2
</code></pre>

Operating System:
<pre><code>
Windows 11 Version 21H2 (Build 22000.1098)

</code></pre>

**Comment by pilz97** [comment]
@atscott thx for your answer the issue occurs in older versions also.

It worked fine for months but suddenly the problem poped up and i am not able to fix it yet.

Our workspace also contains a big react application is it possible that, this causes the issue? Is there any option to exclude specific folders?

**Comment by atscott** [comment]
There isn’t a way to ignore folders but there are a lot of short-circuit checks that skip any work if the project making a language service request doesn’t have Angular installed. 

Are you able to go backwards in your project history to find the point at which things stopped working?

**Comment by pilz97** [comment]
@atscott I made a new checkout from my repository and removed the react application now everything seems to work again.

Thx for your efforts.
