### ISSUE TITLE
"IntelliSense for CSS class names" extention breaks "Angular Language Service"

### ISSUE THREAD

**Issue by mikaeljensen** [angular/vscode-ng-language-service#180]
With both "IntelliSense for CSS class names" and "Angular Language Service" enabled, following happened. 

Starting VS Code with Angular Language Service enabled in a pretty basic test project spawns a VSC process that continues to increase memory consumption at 10-13% CPU load (i7-6800K) ultimately resulting in ALS repoting "JavaScript heap out of memory". 

Closing VS Code does not kill the process, but leaves it running at CPU load and memory fluctuating around 2-3 GB. 

Disabling Angular Language Service makes everything else work.
Disabling IntelliSense for CSS class names makes everything else work.

When adding IntelliSense for CSS class names, the output for ALS shows 
`Search path: c:/1work/Programming/angular2/routing-start/node_modules/clone`

Full log with IntelliSense for CSS class names (autocomplete/intellisense never works for anything)
```
Search path: c:/1work/Programming/angular2/routing-start/src/app/servers
Config file name: c:/1work/Programming/angular2/routing-start/src/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
getTemplateRefrences: 818ms
Add recursive watcher for: c:/1work/Programming/angular2/routing-start/src
Opened configuration file c:/1work/Programming/angular2/routing-start/src/tsconfig.json
getTemplateRefrences: 0ms
Search path: c:/1work/Programming/angular2/routing-start/node_modules/clone
Config file name: c:/1work/Programming/angular2/routing-start/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
getTemplateRefrences: 632ms
Add recursive watcher for: c:/1work/Programming/angular2/routing-start
Opened configuration file c:/1work/Programming/angular2/routing-start/tsconfig.json
getTemplateRefrences: 0ms
getTemplateRefrences: 0ms
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
getTemplateRefrences: 105ms
Search path: c:/1work/Programming/angular2/routing-start/src/app
Config file name: c:/1work/Programming/angular2/routing-start/src/tsconfig.json
getTemplateRefrences: 0ms
getTemplateRefrences: 0ms
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

Full log without IntelliSense for CSS class names (autocomplete/intellisense works at startup)
```
Search path: c:/1work/Programming/angular2/routing-start/src/app/servers
Config file name: c:/1work/Programming/angular2/routing-start/src/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
getTemplateRefrences: 711ms
Add recursive watcher for: c:/1work/Programming/angular2/routing-start/src
Opened configuration file c:/1work/Programming/angular2/routing-start/src/tsconfig.json
getTemplateRefrences: 0ms
getDiagnostics: 43ms
```

Note that, there is an similar issue with same extension breaking the Polymer/vscode-plugin, so the "fault" is probably theirs.

**Comment by kyliau** [comment]
We have completely rewrote the extension, and it has fixed many fundamental issues like this.
The new extension is now live. Please download it from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
I'd like to close this issue for now. Please open a new issue for any lingering bugs, thank you!
