### ISSUE TITLE
The Angular Language Service server crash on start

### ISSUE THREAD

**Issue by tkobiela** [angular/vscode-ng-language-service#1821]
# 🐞 bug report

### Is this a regression?
 Yes, the previous version in which this bug was not present was 14.

### Description
After updating to version 15 extension is constantly crashing.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

Open VSC and wait for extension initialization. 

**Expected behavior**

VSC extension should start.

### **Logs**

<pre><code>
Error: Cannot find module 'c:\Users\Kobi\.vscode\extensions\angular.ng-template-15.0.1\v12_language_service\node_modules\@angular\language-server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 15:58:17] Connection to server got closed. Server will not be restarted.

</code></pre>

### **Screenshots**

![image](https://user-images.githubusercontent.com/119336429/204311359-3b5d98f0-239c-4301-b6b3-3069e7b840a2.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 12.0.3
Node: 16.15.0
Package Manager: yarn 2.4.3
OS: win32 x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.11
@angular-devkit/build-angular      12.2.0
@angular-devkit/core               8.3.23
@angular-devkit/schematics         14.2.5
@angular/cdk                       12.2.11
@angular/flex-layout               12.0.0-beta.35
@angular/localize                  12.2.11
@angular/material                  11.2.13
@angular/material-moment-adapter   11.2.13
@schematics/angular                12.0.3
ng-packagr                         12.2.0
rxjs                               6.6.7
typescript                         4.2.4
webpack                            5.59.1
</code></pre>

Extension Version:
<pre><code>

v15.0.1
</code></pre>

VSCode Version:
<pre><code>

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
</code></pre>

Operating System:
<pre><code>

Windows 10 Pro  Version 22H2 Build 19045.2311
</code></pre>

Extension options:
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Fixed by https://github.com/angular/vscode-ng-language-service/pull/1826. This should go out in the release today.
