### ISSUE TITLE
Performance weak. I see the »Getting code actions from …« message almost always

### ISSUE THREAD

**Issue by DerZyklop** [angular/vscode-ng-language-service#1828]
Type: <b>Bug</b>

It happens almost always when I enable »Angular Language Service«. Rarely, when I disable the extension. 

If I can help with any more information (e.g. if it happens after certain config changes), please feel free to give me any hints on what to do. 

Tested it on M1 MacBook, Intel MacBook as well as a Win machine.

M1 Mac specs:

Extension version: 15.0.1
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|45, 31, 24|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|. --crash-reporter-id a5c7819b-1ec1-4c37-a353-9dec052ab101|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by atscott** [comment]
In lieu of an actual reproduction can we get more information about your project and what you're doing when this happens? How large is your project? There are at least a couple sections in the issue template that are relevant but not included in your report:
```
Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error ocured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>
<!-- If the issue is accompanied by log file output, please share it below.

Set the Angular Log level to verbose by opening settings (File/Preferences/Settings on Windows, Code/Preferences/Settings on Mac), go to Extensions/Angular Language Service, set `angular.log` to `verbose`.

To open the log file, go to the command palette (Cmd+Shift+P on Mac, Ctrl+Shift+P on Windows), search `Open Angular Server log`.

Alternatively, if the log file is long, it can be uploaded instead of pasting below. -->
<!-- ✍️-->

</code></pre>

### **Screenshots**

If applicable, add screenshots to help explain your problem.

![Example Screenshot](./output.png)
```

**Comment by atscott** [comment]
@dylhunn I would imagine this is due to the code fixes for standalone imports.

**Comment by ivanwonder** [comment]
https://github.com/microsoft/vscode/issues/102956#issuecomment-671212551

```
"editor.codeActionsOnSave": {
    "source.fixAll": true
  }
```

Can deleting this config resolve your problem? @DerZyklop

**Comment by dylhunn** [comment]
I'm unsure why this would be a performance issue as it stands -- my new quick fix code should never execute except when a particular error schema exists for an invalid element selector. Perhaps it's sometime to do with "quick fix all"  I will play with it with a large project though, and see if I can reproduce.

**Comment by ivanwonder** [comment]
> [microsoft/vscode#102956 (comment)](https://github.com/microsoft/vscode/issues/102956#issuecomment-671212551)
> 
> ```
> "editor.codeActionsOnSave": {
>     "source.fixAll": true
>   }
> ```
> 
> Can deleting this config resolve your problem? @DerZyklop


I think the problem is when the user saves the file, the vs code will send [`source.fixAll`](https://github.com/microsoft/vscode-languageserver-node/blob/edfd57c55b46725fb809d39cdbf1fb0b4a71c3fe/types/src/main.ts#L3039_L3047) action or other action configured by the user to the language service, and Angular LS treats it as a quick fix, try to fix all errors in the whole file, it's expensive.

So we should filter the code action except for the [`quickfix`](https://github.com/microsoft/vscode-languageserver-node/blob/edfd57c55b46725fb809d39cdbf1fb0b4a71c3fe/types/src/main.ts#L2978_L2981). I will open a PR for this.

**Comment by DerZyklop** [comment]
I confirm, we have fix on save enabled. The Error message mentions 'Angular Language Service', 'ESLint' and 'Intellicode API Usage Examples'. 

@ivanwonder we don't have 
```json
"editor.codeActionsOnSave": {
    "source.fixAll": true
 }
 ```
but we have
```json
…
"editor.codeActionsOnSave": {
	"source.fixAll.eslint": true,
	"source.fixAll.stylelint": true,
	"source.addMissingImports": true
},
```

If I set it to 
```json
…
"editor.codeActionsOnSave": {
	"source.fixAll.eslint": false,
	"source.fixAll.stylelint": false,
	"source.addMissingImports": false
},
```

it expectedly becomes very fast when saving files, and there will be no such message. 

@atscott thanks for the hint. I will provide that log file later.

**Comment by DerZyklop** [comment]
@atscott the requested log for one of these cases 
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/10186559/nglangsvc.log)

**Comment by DerZyklop** [comment]
@atscott Answer to your question _How large is your project?_: 

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                    1001          15885          26320          88464
HTML                           316           2102            653          30438
XML                              2              0              0          25921
SCSS                           191           2621            777          11815
CSS                              7           1801             31           7214
JavaScript                      19            452            526           3605
JSON                            41             84              0           3576
Markdown                         3            139              0            496
Cucumber                         4             14             31             74
Bourne Shell                     2              1              3             11
-------------------------------------------------------------------------------
SUM:                          1586          23099          28341         171614
-------------------------------------------------------------------------------
```

**Comment by jpduckwo** [comment]
I'm waiting for the next release and hoping this fixes my issues too. The plugin grinds to a halt as we type changes into inline templates in single component files and then blocks saving the file for a long time.

We have `"source.fixAll.eslint": true,` on save actions also. Our project has 1200 ts files

@atscott is there a way I can test this already?

**Comment by DerZyklop** [comment]
Some info in addition to @jpduckwo’s comment: 
We don’t have any inline templates or standalone components.

**Comment by jpduckwo** [comment]
15.0.3 seems to fix it for me, thanks!
