### ISSUE TITLE
Navigate to definition does not work for method invokes

### ISSUE THREAD

**Issue by attmik** [angular/vscode-ng-language-service#1831]
# 🐞 bug report

### Is this a regression?

 No, the problem seems to be around for a while

### Description

 The navigate-to-definition or ctrl+click feature from html templates to component code does not work for explicitly invoked functions even on clean projects created with ng new: 

Works here: <code>(click)="myClickHandler"</code>
Does not work here: <code>(click)="myClickHandler()"</code>

It seems to be good for any nested levels of properties but as soon as the ()-s are appearing at the end of the expression it cannot find the definition.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. add a click handler to any html element in a template
2. try to navigate to definition of the handler function
4. See error, cannot find the methoid

**Expected behavior**

The UI should navigate to the method the same way as it does for properties

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 14.1.3
Node: 14.17.5
Package Manager: npm 6.14.14 
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.1.3
@angular/cli                    14.1.3
@schematics/angular             14.1.3
rxjs                            7.5.7
typescript                      4.7.4
</code></pre>

Extension Version:
<pre><code>

Angular Language Service: v15.0.2
</code></pre>

VSCode Version:
<pre><code>

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
</code></pre>

Operating System:
<pre><code>

Windows 11 Pro Version 22H2 OS Build 22621.819
</code></pre>

Extension options:
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
I'm sorry but we can't reproduce the problem you are reporting. We require that reported issues have a minimal reproduction that showcases the problem.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.
