### ISSUE TITLE
[Schematics Workspace] Make use of "factory" property in "collection.json" to provide intelligent features

### ISSUE THREAD

**Issue by stagefright5** [angular/vscode-ng-language-service#1843]
**Is your feature request related to a problem? Please describe.**
no

# 🚀 feature request

### Description

- Ability to `Go To Definition` by clicking on the `"factory"` property value in `collection.js` the angular schema workspace.
- This will open the implementation for the factory function that the value points to.
- It could even show a red squiggly line if it has the path that does not exist (for ex., value has spelling mistake or the factory function name changed)
- Ability to "Rename" the factory function name

![ng-schema-collection json](https://user-images.githubusercontent.com/15051871/209658548-05aec84d-356a-45bd-aa65-35e3df355322.png)

### Feature Type
I actually don't know. But, I think it might be related to `Angular Language Service server`
- [] Angular Language Service VSCode extension
- [ x ] Angular Language Service server

**Comment by atscott** [comment]
Hi, thanks for the feature request. This would certainly be helpful. That said, schematics files are outside the scope of the language service so we won't be implementing this here.
