### ISSUE TITLE
ngFor directive loses typings for the `$implicit` variables

### ISSUE THREAD

**Issue by rgolea** [angular/vscode-ng-language-service#1847]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 14.2.0

### Description

 A clear and concise description of the problem...

`ngFor` variables are of type `unknown`

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Create a component and set some types
2. Use *ngFor and see the variable type

**Expected behavior**

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>
Object is of type 'unknown'.ngtsc(2571)
file-upload.component.ts(9, 12): Error occurs in the template of component FileUploadComponent.
</code></pre>

### **Screenshots**

<img width="894" alt="Screenshot 2023-01-09 at 17 51 40" src="https://user-images.githubusercontent.com/8843202/211362879-e1e23b37-99c1-42ee-b84b-839e57baa729.png">

## 🌍  Your Environment
**Angular Version😘*
<pre><code>
15.0.0
</code></pre>

Extension Version:
<pre><code>
v.15.0.0 - v.15.0.4
</code></pre>

VSCode Version:
<pre><code>
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No
</code></pre>

Operating System:
<pre><code>
MacOS Ventura 13.1 (22C65)

</code></pre>

Extension options:
<pre><code>
none
</code></pre>

**Anything else relevant?**

**Comment by rgolea** [comment]
Yes, I am.

**Comment by atscott** [comment]
@rgolea Can you provide a project that can be used to reproduce this problem? As I mentioned previously, I was not able to when following the 2 steps to reproduce outlined in the report.

**Comment by rgolea** [comment]
@atscott I will get right to it.

**Comment by rgolea** [comment]
@atscott you can see the repo here: https://github.com/rgolea/ng-for-issues-vscode-extension/blob/main/src/app/ng-for-implicit-lost/ng-for-implicit-lost.component.ts. I hope it's enough.

**Comment by rgolea** [comment]
A restart of the laptop seemed to fix everything. #1848 was fixed as well. Thank you @atscott for taking the time!
