### ISSUE TITLE
Can't import `ngFor` in a standalone component

### ISSUE THREAD

**Issue by rgolea** [angular/vscode-ng-language-service#1848]
# 🐞 bug report

### Is this a regression?

No, this is related to the new standalone component feature.

### Description

 A clear and concise description of the problem...

Extension doesn't seem to find `ngFor` in a standalone component 
## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Create a standalone component
2. Import `ngFor` or `CommonModule` in it's declaration
3. Hover on top of the `*ngFor` directive usage

**Expected behavior**

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>
The `*ngFor` directive was used in the template, but neither the `NgFor` directive nor the `CommonModule` was imported. Please make sure that either the `NgFor` directive or the `CommonModule` is included in the `@Component.imports` array of this component.ngtsc(-998103)
file-upload.component.ts(9, 1): Error occurs in the template of component FileUploadComponent.
</code></pre>

### **Screenshots**

<img width="1017" alt="Screenshot 2023-01-09 at 17 25 04" src="https://user-images.githubusercontent.com/8843202/211365826-c9952dbd-56b7-4501-af53-71e28a8ae2a1.png">

## 🌍  Your Environment
**Angular Version😘*
<pre><code>
15.0.0
</code></pre>

Extension Version:
<pre><code>
v.15.0.0 - v.15.0.4
</code></pre>

VSCode Version:
<pre><code>
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:26:09.430Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No
</code></pre>

Operating System:
<pre><code>
MacOS Ventura 13.1 (22C65)

</code></pre>

Extension options:
<pre><code>
none
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.

Following the given steps, everything was working as expected. If the issue is really as simple to reproduce as described, please provide a project with a minimal reproduction.

**Comment by rgolea** [comment]
@atscott what do you mean? I think it's pretty clear, isn't it?
I'm importing `ngFor` in my standalone component and the extension says I haven't. Furthermore, Angular compiles it but the extension doesn't detect it. You can see the screenshot.

**Comment by rgolea** [comment]
@atscott I've set up a repo here: https://github.com/rgolea/ng-for-issues-vscode-extension/blob/main/src/app/ng-for-standalone.component.ts

Would you please take a look? Thank you in advance!

**Comment by atscott** [comment]
I'm seeing the correct behavior in that project
![image](https://user-images.githubusercontent.com/479713/211383604-b6cb9293-6d5b-4f61-b691-93ff28f9ad60.png)
![image](https://user-images.githubusercontent.com/479713/211383642-dfb63895-d45f-4955-a57e-ea48979d95c2.png)

Can you double check that this project does reproduce the issue?

What do you see in the output for the language service?
![image](https://user-images.githubusercontent.com/479713/211383952-cf637e5d-99ae-4a96-b81b-e128018f5482.png)

Have you defined a specific tsdk version that overrides the one for the project? 
![image](https://user-images.githubusercontent.com/479713/211384126-b5a475a8-583f-45a3-b00e-80b1deea5a3b.png)

**Comment by rgolea** [comment]
@atscott I don't know what's happening but I can't for the life of me reproduce it again. I just ran out of battery on my laptop and rebooted it. Now everything seems to work fine on both issues without even touching it. No changes to user or workspace settings. I will close them now.

Thank you so much for your pacience with me and I hope I didn't bother you too much.

**Comment by atscott** [comment]
@rgolea No worries. Appreciate the quick responses and reproductions as well.
