### ISSUE TITLE
Problems List Does Not Clear On File Close

### ISSUE THREAD

**Issue by timdang** [angular/vscode-ng-language-service#185]
I don't know if this is how it's meant to work or not, but reported errors in template (HTML) files don't clear from VS Code's Problems list when the file is closed. I need to reload VS Code's window for the errors to be removed from Problems.

Let me know if there's any additional information I can provide to help. Thanks.

**Comment by snewell92** [comment]
Could be related to #187 ?

@timdang Are the errors you're talking about  on the `OUTPUT` tab of the integrated terminal dock?
![image](https://user-images.githubusercontent.com/25957964/33034386-43cea878-cded-11e7-8352-40c1c83a0bee.png)

**Comment by timdang** [comment]
@snewell92 Unfortunately not.

I hope you can see from this attached screenshot, I've no longer have the file named "real-estate-owned.template.html" open, but the errors for this file still appear in the problems list.

<img width="942" alt="screen shot 2017-11-20 at 12 03 05 pm" src="https://user-images.githubusercontent.com/7561014/33044242-06fc70dc-cdfd-11e7-9ac0-78ec11995aa3.png">

**Comment by snewell92** [comment]
Oh, yeah - this is expected behavior (I think).

From my perspective, the problems tab is meant to be open to show you the entire project's compilation errors so you can, step wise, go through the entire project and fix all compilation errors.

**Comment by timdang** [comment]
@snewell92 I would assume the behavior should be similar to TSLint. Those errors go away (from the Problems tab) when you close the offending file.

**Comment by snewell92** [comment]
Interesting discussion on that [here](https://github.com/Microsoft/vscode/issues/22289) and [here](https://github.com/tomv564/LSP/issues/233#issuecomment-357790195), but it seems you are correct.

**Comment by bartdonninger** [comment]
I also encounter this problem when I delete a file. The problems just stay listed while the file got deleted from the system.

![image](https://user-images.githubusercontent.com/22449250/56802206-bf0bb080-681f-11e9-8707-214c488d29c6.png)

**Comment by kyliau** [comment]
We have completely rewrote the extension, and it has fixed many fundamental problems like this.
Please download it from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
I'd like to close this issue for now. Please open a new issue for any lingering bugs, thank you!
