### ISSUE TITLE
ngtsc linter does not lint

### ISSUE THREAD

**Issue by sne-jzabinski** [angular/vscode-ng-language-service#1858]
Although I have the extension and it is enabled with default settings, it doesn't seem to lint class variables. I do get other functions like Intellisense, and it lints class functions fine, so I know that it is running/configured. A tiny test project lints class variables successfully, so I suspect that there is some setup specific to my broken project, but I don't know what it might be. In other words, the global extension lints successfully, but one specific project does not lint class variables only. The error in question:

"Property [some property] does not exist on type [some component]. Did you mean [a guess]?ngtsc(2551)"

It seems like there is some configuration setting that I am missing, but I don't see anything that controls that.

How do I troubleshoot why the extension is not working?

**Comment by atscott** [comment]
Do you have a minimal reproduction of the issue? You can get this by removing pieces of your project while the error still exists. At the moment, there's not enough information to determine what the issue is.

**Comment by sne-jzabinski** [comment]
I discovered that this issue was only occurring in components where variables were used in code being sent to undefined attributes. In such cases, `ngtsc` linting doesn't seem to alert the user that it does not recognize the attribute, and any code sent to the attribute is not linted.

This might be a limitation of the linter, but I would like to address it as a potential bug.

Example pending: will link to the bug report

**Comment by sne-jzabinski** [comment]
https://github.com/angular/vscode-ng-language-service/issues/1859
