### ISSUE TITLE
Autocomplete does not offer getBoundingClientRect() for ElementRef<any>.nativeElement

### ISSUE THREAD

**Issue by Omcsesz** [angular/vscode-ng-language-service#1860]
# 🐞 bug report

### Is this a regression?

No.

### Description

 When I start to type getBoundingClientRect() for a nativeElement variable, it is not offered in the AutoComplete suggestions.

## Bug Type
What does this bug affect

- [X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Create a new Angular project
2. Create a variable with a @ViewChild() decorator that accesses an element on the HTML page 
3. Start typing the variable's name in a function inside the .ts file, and type the first few letters of getBoundingClientRect() (see attachment)
4. The function is not in the autocomplete list

**Expected behavior**

When I start to type getBoundingClientRect() for a nativeElement variable, it should be offered in the AutoComplete suggestions.

### **Screenshots**

[getBoundingClientRectNotOffered](https://user-images.githubusercontent.com/1839739/218104567-b0c541a7-edcb-47b9-867a-c40b6d0fb668.gif)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 15.0.2
Node: 18.12.1
Package Manager: npm 9.3.0
OS: win32 x64

Angular: 15.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1500.2
@angular-devkit/build-angular      15.0.2
@angular-devkit/core               15.0.2
@angular-devkit/schematics         15.0.2
@angular/cdk                       14.2.7
@angular/material                  14.2.7
@angular/material-moment-adapter   14.2.7
@schematics/angular                15.0.2
rxjs                               6.6.7
typescript                         4.8.4

</code></pre>

Extension Version:
<pre><code>
v15.1.0
</code></pre>

VSCode Version:
<pre><code>
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
</code></pre>

Operating System:
<pre><code>
Windows_NT x64 10.0.19045
</code></pre>

**Comment by atscott** [comment]
Closing as working as expected. Your `ElementRef` generic is type `any` so there will be no good autocompletion there. You can update your type to be `ElementRef<HTMLElement>` to get better completions.

Side note: The autocomplete here is actually provided by the TypeScript language service, not the Angular language service.
