### ISSUE TITLE
Autocompletion did not work when the cursor was placed before the constructor()

### ISSUE THREAD

**Issue by WayneCYChang** [angular/vscode-ng-language-service#1866]
# 🐞 bug report

### Is this a regression?

 No.

### Description

Autocompletion did not work when the cursor was placed before the constructor()

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Go to 'the line before constructor(private service: Service)'
2. Type 'a = this.service.'
3. Autocompletion list doesn't show the method of service.

**Expected behavior**

Show method of service.

### **Logs**

No Log.

<pre><code>

</code></pre>

### **Screenshots**

![image](https://user-images.githubusercontent.com/46915773/220814253-009ae692-924c-4584-bfa5-176b081d80ce.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 14.2.10
Node: 14.20.1
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.7.4
</code></pre>

Extension Version:
<pre><code>

Angular Language Service  v15.2.0

</code></pre>

VSCode Version:
<pre><code>

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
</code></pre>

Operating System:
<pre><code>

Windows 11 21H2
</code></pre>

Extension options:
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Hi, this is the TypeScript language service. We don’t provide completions outside of templates in our extension.
