### ISSUE TITLE
This extension is not reliability.

### ISSUE THREAD

**Issue by infacto** [angular/vscode-ng-language-service#1870]
Based on my years of experience, I have to say that this extension is one of the most unreliable extensions. No offense. This issue is to improve it.

Do you know how to go to the component definition from an HTML file? No, not by CTRL + Shift, F12 or menu. I need to copy the tag name and search plain text over the project (CTRL + Shift + F). Because this feature works only max 1% of time. Even if the extention resolves that component on mouse hover (`(component) MyModule.MyComponent`). There is no link to jump to the definition file `my.component.ts`. But sometimes it works. In that case, I'll put a cross on the calendar to celebrate.

Another issue is that the extension is going to be confused when I delete a file. The error remains in the problems panel and I have to restart VS Code to fix that. Just one of the appearing pseudo errors.

On Angular Language Service Output console I see errors like: `No config file for blahblah.html`. Not for the file that doesn't work as described above. When I restart VS Code the "goto definion" (CTRL + Hover/Click) works. Even the console shows "No config file for this.html". I see no reason, why or when this works or not. It's like the uncertainty principle and hard to debug or check the log. But tell me, what would you do here?

And all these problems have been around for many years. I can't remember when this extension worked well. I tested it on many different projects and environments. I doubt a problem from my side. I wonder if this works on your side. Sometimes I think about if I could work better with Angular without this extention.  Anyway... Again: No offense. I'm just a bit disappointed and annoyed. And for all I wish that this extension works properly as expected. Ok, maybe this huge issue will not fix all the problems. But see this as feedback. I just had to vent my frustration. Do with this whatever you want. If you want to be inspired by a well-working extension, you can look at e.g. Flutter / Dart.

Versions doesn't matter. Because this is since many years with different setups / projects / environments. 
But here are my my current versions:

VS Code: 1.76.0
Angular Language Service: 15.2.0
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045

Since my project is currently on Angular 14, I also tested previous versions (v14) of this extention.

**Comment by atscott** [comment]
This space is not appropriate for complaints of this nature with no reproductions. Deleted files is an open issue already. Other complaints about unreliability have not been reproducible. Closing.
