### ISSUE TITLE
Always sending `LocationLink` and not respecting `textDocument.definition.linkSupport`

### ISSUE THREAD

**Issue by andlrc** [angular/vscode-ng-language-service#1874]
# 🐞 bug report

### Description

The LSP specification states that the client can request for additional meta data by specifying `textDocument.definition.linkSupport`, which I interpret as the client not supporting additional meta data if the property is not set.

This flag isn't respected by Angular Language Service as a `LocationLink` will always be send as a reply for `textDocument/definition` (go to definition), even to client which only supports `Location`

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#location  
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#locationLink

## Bug Type
The message `textDocument/definition` (go to definition) is not working on clients not supporting `LocationLink`.

- [x] Angular Language Service server

## Reproduction

Install a client which doesn't support `LocationLink`, and send the `textDocument/definition` message.

**Expected behavior**

Respect the specification.

Extension Version: 15.2.0

**Comment by atscott** [comment]
Thanks for the report. I think you're right.

We don't aim too hard at making the published `@angular/language-server` package compatible with anything but VSCode. We would accept PRs for this though.

**Comment by andlrc** [comment]
Thanks for your reply.

> We don't aim too hard at making the published @angular/language-server package compatible with anything but VSCode.

That's also what I assumed.

> We would accept PRs for this though.

That's good to know. I'll see if I can find a bit of time to take a proper look one of the next days.

**Comment by andlrc** [comment]
OK so it wasn't to hard getting a prototype of the code written.

But I'm about to give up on getting it build and tested.

Can you point to towards any document that can help guide me setting up my machine to run tests and build the source?

FWIW this is the git diff:

 ```diff
 diff --git a/integration/lsp/test_utils.ts b/integration/lsp/test_utils.ts
index 0d6a28bef..c1c3a876d 100644
--- a/integration/lsp/test_utils.ts
+++ b/integration/lsp/test_utils.ts
@@ -73,6 +73,7 @@ export function initializeServer(client: MessageConnection): Promise<lsp.Initial
           }
         },
         moniker: {},
+        declaration: {linkSupport: true}
       }
     },
     /**
diff --git a/server/src/session.ts b/server/src/session.ts
index ddd51a963..c48bda3aa 100644
--- a/server/src/session.ts
+++ b/server/src/session.ts
@@ -856,7 +856,8 @@ export class Session {
     return htmlLS.getFoldingRanges(virtualHtmlDoc);
   }
 
-  private onDefinition(params: lsp.TextDocumentPositionParams): lsp.LocationLink[]|null {
+  private onDefinition(params: lsp.TextDocumentPositionParams):
+      lsp.Location[]|lsp.LocationLink[]|null {
     const lsInfo = this.getLSAndScriptInfo(params.textDocument);
     if (lsInfo === null) {
       return null;
@@ -867,11 +868,20 @@ export class Session {
     if (!definition || !definition.definitions) {
       return null;
     }
+
+    const clientSupportsLocationLinks =
+        this.clientCapabilities.textDocument?.definition?.linkSupport ?? false;
+
+    if (!clientSupportsLocationLinks) {
+      return this.tsDefinitionsToLspLocation(definition.definitions);
+    }
+
     const originSelectionRange = tsTextSpanToLspRange(scriptInfo, definition.textSpan);
     return this.tsDefinitionsToLspLocationLinks(definition.definitions, originSelectionRange);
   }
 
-  private onTypeDefinition(params: lsp.TextDocumentPositionParams): lsp.LocationLink[]|null {
+  private onTypeDefinition(params: lsp.TextDocumentPositionParams):
+      lsp.Location[]|lsp.LocationLink[]|null {
     const lsInfo = this.getLSAndScriptInfo(params.textDocument);
     if (lsInfo === null) {
       return null;
@@ -882,6 +892,14 @@ export class Session {
     if (!definitions) {
       return null;
     }
+
+    const clientSupportsLocationLinks =
+        this.clientCapabilities.textDocument?.definition?.linkSupport ?? false;
+
+    if (!clientSupportsLocationLinks) {
+      return this.tsDefinitionsToLspLocation(definitions);
+    }
+
     return this.tsDefinitionsToLspLocationLinks(definitions);
   }
 
@@ -965,6 +983,40 @@ export class Session {
     });
   }
 
+  private tsDefinitionsToLspLocation(definitions: readonly ts.DefinitionInfo[]): lsp.Location[] {
+    const results: lsp.Location[] = [];
+    for (const d of definitions) {
+      const scriptInfo = this.projectService.getScriptInfo(d.fileName);
+
+      // Some definitions, like definitions of CSS files, may not be recorded files with a
+      // `scriptInfo` but are still valid definitions because they are files that exist. In this
+      // case, check to make sure that the text span of the definition is zero so that the file
+      // doesn't have to be read; if the span is non-zero, we can't do anything with this
+      // definition.
+      if (!scriptInfo && d.textSpan.length > 0) {
+        continue;
+      }
+
+      let mappedInfo = d;
+      let range = EMPTY_RANGE;
+      if (scriptInfo) {
+        const project = this.getDefaultProjectForScriptInfo(scriptInfo);
+        mappedInfo = project ? getMappedDefinitionInfo(d, project) : mappedInfo;
+        // After the DTS file maps to original source file, the `scriptInfo` should be updated.
+        const originalScriptInfo =
+            this.projectService.getScriptInfo(mappedInfo.fileName) ?? scriptInfo;
+        range = tsTextSpanToLspRange(originalScriptInfo, mappedInfo.textSpan);
+      }
+
+      const uri = filePathToUri(mappedInfo.fileName);
+      results.push({
+        uri,
+        range,
+      });
+    }
+    return results;
+  }
+
   private tsDefinitionsToLspLocationLinks(
       definitions: readonly ts.DefinitionInfo[],
       originSelectionRange?: lsp.Range): lsp.LocationLink[] {

 ```

**Comment by atscott** [comment]
I think the developer guide is relatively up to date: https://github.com/angular/vscode-ng-language-service/blob/main/DEVELOPER.md

The project was recently migrated to be built with bazel, which complicates things a bit. You should be able to run things with the scripts:

* Test with `./scripts/test.sh`
* Build with `./scripts/build.sh package.json`

Running the extension locally should work with the `launch.json` configuration in the project.

**Comment by atscott** [comment]
@andlrc Sorry, I don't really know. That error is outside the codebase of this project. Do you want to just create a PR with your changes and let CI run the tests?

**Comment by andlrc** [comment]
Will do.
