### ISSUE TITLE
Language service crashes if there is an error during Typecheck block generation

### ISSUE THREAD

**Issue by atscott** [angular/vscode-ng-language-service#1881]
Discovered from https://github.com/angular/vscode-ng-language-service/issues/1840#issuecomment-1475586505

Steps to reproduce:

1. In the integration test project, update the [library component](https://github.com/angular/vscode-ng-language-service/blob/main/integration/project/libs/post/src/lib/post.component.ts) to use a non-exported host directive:

```
@Directive({standalone: true})
export class HostBindDirective {
}

@Component({
  selector: 'lib-post',
  template: '{{random}}',
  hostDirectives: [HostBindDirective],
})
export class PostComponent {
  random = Math.random();
}
```
(Note: also need to update the `index.ts` to export just `PostComponent` and `PostModule` rather than everything from the file.
2. build the integration project (`yarn --cwd integration/project build`)
3. Open `foo.component.html` - the language service will crash because the template type check block cannot import the non-exported `HostBindDirective`

**Comment by MTstomachTM** [comment]
Hi @atscott,

I'm sorry for commenting on closed issue. But after I update my Angular Language Service to 15.2.1, Angular to 15.2.8, and the component library, [Clarity Design](https://github.com/vmware-clarity/ng-clarity), to the latest version that had exported previously unexported directive, the issue persist.

I set `angular.trace.server: "verbose"`, and the last trace before the language service crash is
```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<FatalDiagnosticError>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
[Error - 4:11:36 PM] Connection to server got closed. Server will not be restarted.
```

Is there anything I can provide to help trace the cause?
