### ISSUE TITLE
String interpolation shows error in routerLink on angular v16.0.0

### ISSUE THREAD

**Issue by Omar-Ibrahim-0I** [angular/vscode-ng-language-service#1885]
The Compilation is successful and the routers are working perfectly. However, the extension shows an error msg.

> Can't bind to 'routerLink' since it isn't a known property of 'a'.ngtsc(-998002)
> product-list.component.ts(6, 41): Error occurs in the template of component ProductListComponent.

Here is the code which causes the error.
`
        <h3>
            <a
                [title]="product.name + ' details'"
                routerLink="products/{{ product.id }}"
            >
                {{ product.name }}
            </a>
        </h3>
`

Attached picture shows the error
![image](https://user-images.githubusercontent.com/101005261/229348343-486778cd-6aab-4936-b275-f788d27ec39a.png)

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
