### ISSUE TITLE
Angular ngcc

### ISSUE THREAD

**Issue by CutieDaisy** [angular/vscode-ng-language-service#1886]
Type: <b>Bug</b>

After updating my Insider version today, when I open an angular project, the Angular service keeps running ngcc and never gets completed.
Notification shows : 'Angular: Running ngcc for .../tsconfig.json'

Extension version: 15.2.0
VS Code version: Code - Insiders 1.78.0-insider (3e0b354932b8ddeb099c68ed3b7dfac25350dde2, 2023-04-06T05:20:25.265Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (13.49GB free)|
|Process Argv|--crash-reporter-id d16ecdc0-debd-4f00-a1d3-6cea2aa836de|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
vscrpc:30624061
pythonsymbol12:30651887
showlangstatbar:30659908
pythonb192cf:30661257
functionswalk:30687959
pythonms35:30671666
f08j5886:30680471
24365598:30687740
pythonclientmv:30700173

```

</details>

**Comment by atscott** [comment]
We haven't made any changes to this recently. I've opened an issue on the VSCode repository: https://github.com/microsoft/vscode/issues/179637. 

You can also disable `ngcc` in the extension options
![image](https://user-images.githubusercontent.com/479713/231013215-513d75e0-e00f-4c03-a1ce-1c9bfff844da.png)

**Comment by atscott** [comment]
https://github.com/microsoft/vscode/issues/179637 was fixed upstream so the next release hopefully contains the fix.
