### ISSUE TITLE
Since Angular v16 the vscode ext doesn't work anymore

### ISSUE THREAD

**Issue by elementalPRESS** [angular/vscode-ng-language-service#1894]
Well, it's easy to describe: since Angular 16 is up and running vscode shows always errors on [ngClass], [(ngModel)], [ngSwitch] etc. Vscode means, e.g.:

      Can't bind to 'ngSwitch' since it isn't a known property of 'span'.ngtsc(-998002)

The code runs and shows only the error in the editor. In Angular v15 there were no problems and issues.

Currently used ext version is v15.2.0. I see on the marketplace that there is a v16 but it's not offered in vscode v1.73.1.

Does anybody has an idea how to fix?

**Comment by elementalPRESS** [comment]
> I fixed that problem, just updating vscode that last stable version -> 1.78.2 from [here](https://code.visualstudio.com/) Then i could update Angular Language Service from extensions. Or just could download the vsix from [here](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) and installing manually that new 16.0.0 version

well, I need to run vscode 1.73 :-( here v16 is not installed

**Comment by atscott** [comment]
Using Angular v16 requires the v16 version of the extension. Closing as expected.
