### ISSUE TITLE
Structural errors introduced do no show up until a later modification

### ISSUE THREAD

**Issue by chuckjaz** [angular/vscode-ng-language-service#19]
1. Create a component:
```ts
@Component({
  moduleId: module.id,
  selector: 'my-dashboard',
  templateUrl: 'dashboard.component.html'
})
export class DashboardComponent implements OnInit
...
```

2. Comment the object literal properties
```ts
@Component({
  // moduleId: module.id,
  // selector: 'my-dashboard',
  // templateUrl: 'dashboard.component.html',
})
export class DashboardComponent implements OnInit
```

3. Now @Component must be marked as error but the error isn't shown until I edit any other part of my source code

![angular-ls-problem](https://cloud.githubusercontent.com/assets/372013/21155854/9a0a442c-c128-11e6-92a2-22c3347855a1.gif)

**Comment by ayazhafiz** [comment]
This is no longer the behavior; closing.
