### ISSUE TITLE
Non functional on Angular 5.1 beta & CLI 1.6 beta

### ISSUE THREAD

**Issue by bogacg** [angular/vscode-ng-language-service#190]
I've installed next release betas, while I have no errors in my app (serve & build) language service extension is totally useless on Angular 5.1.0-beta.0 & CLI 1.6.0-beta.0. (Typescript 2.6 / VS-Code 1.18.0)

I'm not talking about Output window annoyment, talking about no visible functionality of the extension at all.

## UPDATE

I've created a new app with `ng new` (same config above) and that one seems to wok fine. I have no idea why with updated old codebase add-in crash but with new created one works.

**Comment by nikochan2k** [comment]
Same problem on 5.1.0 released version.

"Angular language service", on vscode console, said:
_Angular Language Service: 5.1.0
TypeScript: 2.4.2_

I uninstalled typescript 2.6.2
`npm uninstall typescript`
and installed typescript 2.4.2.
`npm install typescript@2.4.2`
=> Work fine !

Next, I installed typescript 2.5.3
`npm install typescript@2.5.3`
=> Work fine, too !

So I will downgrade typescript to 2.5.3 for a while.

**Comment by chuckjaz** [comment]
Alternately you can just remove `@angular/language-service` from the `package.json` produces by the cli `yarn` or `npm install` to remove it.

The releases of the language service that go out with angular are not as tested as the ones bundled in the service itself. Removing the `@angluar/language-service` dev dependency will revert to using the bundled version of the language service.
