### ISSUE TITLE
VSCode Extension. Ability to set typescript SDK location, as it's done with native Typescript plugin

### ISSUE THREAD

**Issue by Arilas** [angular/vscode-ng-language-service#1900]
VSCode extension comes with typescript `4.8.2` which is old and did not support modern features like `moduleResolution: bundler` and it fails to load when it detects this moduleResolution.

If you import pure ESM package inside your Angular component, you will receive error from Typescript, that that module is not found, but it will not trigger this error with `moduleResolution: bundler` and it will work with Angular.

# 🚀 feature request

### Description
Add setting to use Workspace Typescript version with VSCode Extension

### Feature Type

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like

Please look on other extensions like Typescript itself or Prettier or at least upgrade TypeScript in extension to 5.1.

### Describe alternatives you've considered
Setting `moduleResolution` to `node` will result in missing types information from a pure ESM module, setting it to `node16` needs to convert the entire codebase to valid ESM, and schematics will result in invalid code.

### Anything else relevant?

<img width="1488" alt="image" src="https://github.com/angular/vscode-ng-language-service/assets/3540524/569d7bea-a750-4468-b1a8-cf8dd559db66">

**Comment by Arilas** [comment]
Debugged a little bit. Seems that `typescript.tsdk` is supported, but it had almost impossible conditions to really use it, because it should have an absolute path. If it contains relative path, probeLocations has extension itself before project root.

So in order to use newer version of TypeScript I should put absolute path to typescript in `typescript.tsdk` which is not portable and/or shareable.

**Comment by atscott** [comment]
The bundled TS version is meant to be kept up to date with the version used in the main Angular repository. Generally, that one is up to date with the latest TS release. Unfortunately, this has been forgotten in the last couple of releases. I'll get a release out with an updated version soon.

As for supporting `typescript.tsdk` beyond the current support, I can't say this is likely to happen.
