### ISSUE TITLE
VS Code: Angular Language Service Auto-Completion Conflict with GitHub Copilot AI - Why?

### ISSUE THREAD

**Issue by FrancoisJULIENNE** [angular/vscode-ng-language-service#1907]
Hi,

When I use VS Code with the Angular Language Service and GitHub Copilot AI extensions, the auto-completion feature of Angular Language Service doesn't seem to work. However, when I disable GitHub Copilot AI, the auto-completion is restored. Why is this happening? Thx

VS CODE:

Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

GitHub Copilot:
v1.101.317

Angular Language Service:
v16.1.4

**Comment by atscott** [comment]
Closing as an issue in vscode rather than the language service extension. Please refer to https://github.com/microsoft/vscode/issues/131940 for possible solutions.
