### ISSUE TITLE
Failure with TypeScript 5.2.2.

### ISSUE THREAD

**Issue by drackp2m** [angular/vscode-ng-language-service#1913]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 5.1.6 (of Typescript)

### Description

 A clear and concise description of the problem...

Basic things like autocompletion, type checking, etc. simply stop working.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Run 'yarn add typescript@5.2.2' in your terminal.
2. Run 'Reload window' command on Visual Studio Code.
3. Plugin breaks

### **Logs**

<details>
  <summary>Logs on typescript version 5.1.6</summary>
  
  ```
  [Info  - 7:38:50 PM] Angular language server process ID: 69
  [Info  - 7:38:50 PM] Using typescript/lib/tsserverlibrary v5.1.6 from /usr/src/app/node_modules/typescript/lib/tsserverlibrary.js
  [Info  - 7:38:50 PM] Using @angular/language-service v16.1.8 from /home/node/.vscode-server/extensions/angular.ng-template-16.1.8/node_modules/@angular/language-service/index.js
  [Info  - 7:38:50 PM] Logging is turned off. To enable, run command 'Open Angular server log'.
  [Info  - 7:39:01 PM] Enabling Ivy language service for /usr/src/app/apps/app/tsconfig.app.json.

  ```
</details>

<details>
  <summary>Logs on typescript version 5.2.2</summary>
  
  ```
  [Info  - 7:19:03 PM] Angular language server process ID: 42
  [Info  - 7:19:03 PM] Using typescript/lib/tsserverlibrary v5.2.2 from /usr/src/app/node_modules/typescript/lib/tsserverlibrary.js
  [Info  - 7:19:03 PM] Using @angular/language-service v16.1.8 from /home/node/.vscode-server/extensions/angular.ng-template-16.1.8/node_modules/@angular/language-service/index.js
  [Info  - 7:19:03 PM] Logging is turned off. To enable, run command 'Open Angular server log'.
  [Error - 7:19:08 PM] No config file for /usr/src/app/apps/app/src/pages/example/example.page.html
  [Error - 7:19:08 PM] No config file for /usr/src/app/apps/app/src/pages/example/example.page.html
  [Error - 7:19:08 PM] No config file for /usr/src/app/apps/app/src/pages/example/example.page.html
  · · ·
  ```
</details>

## 🌍  Your Environment
**Angular Version:**
<pre><code>❯ ng version
? Would you like to share pseudonymous usage data about this project with the Angular Team
at Google under Google's Privacy Policy at https://policies.google.com/privacy. For more
details and how to change this setting, see https://angular.io/analytics. No
Global setting: disabled
Local setting: No local workspace configuration file.
Effective status: disabled

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.0
Node: 20.2.0 (Unsupported)
Package Manager: yarn 1.22.19
OS: linux arm64

Angular: 16.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.13.1
    
Warning: The current version of Node (20.2.0) is not supported by Angular.
</code></pre>

Extension Version:
<pre><code>v16.1.8</code></pre>

VSCode Version:
<pre><code>Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0</code></pre>

Operating System:
<pre><code>macOS Ventura Version 13.5.1 (22G90)</code></pre>

Extension options:
<pre><code>N/A</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
15.2 support is coming in version 17.  You can check the version in the upstream Angular package.json to see the latest version support that the language service should have: https://github.com/angular/angular/blob/main/package.json#L152
