### ISSUE TITLE
Intellisense > Not working consistantly

### ISSUE THREAD

**Issue by BerndHme** [angular/vscode-ng-language-service#1914]
# 🐞 bug report
### Description

I regurarly have to restart the Angular Language Service.
It seems to fail everytime I generate a new component.

When typing directives or properties in a component template, the suggestions don't pop up.

**Comment by bazobehram** [comment]
it is similar on my side. it has been a long time that is still the same.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.

**Comment by BerndHme** [comment]
@atscott Ok... I've found that the suggestions accessing properties on a FromControl element "just suddenly stop" popping up.
- In this example the "touched" in UserName.touched just stops popping up
- While the *ngFor directive "does" keep popping up.

Just out of the blue... it stops.
I have a feeling this is something very hard to find out what is happening.
... it seems like it just times out or something.

![image](https://github.com/angular/vscode-ng-language-service/assets/132269491/3b181d43-141b-44aa-bd90-59d84a5a88e1)

**Comment by atscott** [comment]
Does `UserName.touched` work elsewhere? That looks like an enum, which is a known issue: https://github.com/angular/vscode-ng-language-service/issues/1740. Are you able to share your project's `tsconfig.json` to confirm what the `angularCompilerOptions` are? Not having strict template enabled also affects the accuracy of types in the template.

If you can extract this to a small demo project, that would be helpful

**Comment by BerndHme** [comment]
Hi @atscott ,

Tanks for replying.
These are the component files and project files.
the.touched property is a boolean on a FormControl object.
I will try to follow up, but haven't noticed a concreet pattern of when it is occuring.

The files are from a learning project I'm following.

Also... how do you emphasize words like you did in your reply?
... like the "UserName.touched" or "angularCompilerOptions"?
I've been looking for the markdown syntax but can't find it.

[form-custom-validation.component.ts.txt](https://github.com/angular/vscode-ng-language-service/files/12472394/form-custom-validation.component.ts.txt)
[form-custom-validation.component.html.txt](https://github.com/angular/vscode-ng-language-service/files/12472400/form-custom-validation.component.html.txt)
[angular.json.txt](https://github.com/angular/vscode-ng-language-service/files/12472399/angular.json.txt)
[tsconfig.json.txt](https://github.com/angular/vscode-ng-language-service/files/12472397/tsconfig.json.txt)
[tsconfig.app.json.txt](https://github.com/angular/vscode-ng-language-service/files/12472398/tsconfig.app.json.txt)
[tsconfig.spec.json.txt](https://github.com/angular/vscode-ng-language-service/files/12472396/tsconfig.spec.json.txt)

**Comment by atscott** [comment]
@BerndHme If the files are from a learning project and something you can share, would you be able to upload the whole thing to Github so we can debug it that way? 

> Also... how do you emphasize words like you did in your reply?

Code highlighting is done with the back tick (`)

**Comment by BerndHme** [comment]
Ok ... I didn't realize.
https://github.com/BerndHme/Angular_IntellisenseIssue
`thanks`

**Comment by atscott** [comment]
@BerndHme  Thanks for the project. I really can't reproduce any kind of intermittent failure

Can you enable verbose server tracing and verbose logging in the extension settings?

![image](https://github.com/angular/vscode-ng-language-service/assets/479713/8efce0d4-d4a6-4721-bcb2-a6b61033cf5c)

In the output panel, you will see logs like this

![image](https://github.com/angular/vscode-ng-language-service/assets/479713/e9e60f33-f024-4cf1-a6c4-92fa01546ac7)

And by opening the server logs using the "Angular: Open Angular server log" command from the command palette, you should see something like this

![image](https://github.com/angular/vscode-ng-language-service/assets/479713/a1cc5bc0-fab9-4da3-846c-38e3a906ff8d)


If the request for completions or hover aren't working, you should see some indication in those logs

**Comment by BerndHme** [comment]
@atscott ok will do.
I'll post when it is happening again.

Also ... I really wonder if no more people are experiencing this.

-----

**\*\*\*@ other readers\*\*\***
maybe you could feedback like this too.
