### ISSUE TITLE
The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by eamine84** [angular/vscode-ng-language-service#1918]
Angular Language service crash in VSCode 

VS CONSOLE ERROR:

ERR Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (c:\Users\xxxx\ .vscode\extensions\angular.ng-template-16.1.8\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)

ANGULAR version:

"@angular/animations": "16.2.4",
"@angular/cdk": "16.2.2",
"@angular/common": "16.2.4",
"@angular/compiler": "16.2.4",
"@angular/core": "16.2.4",
"@angular/flex-layout": "15.0.0-beta.42",
"@angular/forms": "16.2.4",
"@angular/material-moment-adapter": "16.2.2",
"@angular/platform-browser": "16.2.4",
"@angular/platform-browser-dynamic": "16.2.4",
"@angular-devkit/build-angular": "16.2.1",
"@angular/cli": "16.2.1",
"@angular/compiler-cli": "16.2.4",
"@angular/language-service": "16.2.4"

TYPESCRIPT VERSION
"typescript": "5.2.2"

Can anyone help me?

Thank you

**Comment by atscott** [comment]
Do you have an example project you can upload to GitHub and steps to reproduce the crash?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
