### ISSUE TITLE
Respect vscode recommandations for Go To Symbol feature

### ISSUE THREAD

**Issue by jeandat** [angular/vscode-ng-language-service#1925]
# 🚀 feature request

### Description
When using "Go to symbol" feature, search is case sensitive and do not handle fuzzy search making the whole feature almost useless. If you have to know in advance the exact name including the case, it is way more useless.

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
As mentionned by the team in [this related ticket](https://github.com/microsoft/vscode/issues/33746), it is the plugin responsability to interpret the search in a relaxed way.

> The query-parameter should be interpreted in a relaxed way as the editor will apply its own highlighting and scoring on the results. A good rule of thumb is to match case-insensitive and to simply check that the characters of query appear in their order in a candidate symbol. Don't use prefix, substring, or similar strict matching.

I might be wrong, but it seems to me this is this plugin responsability then for an angular project.

**Comment by jeandat** [comment]
To complete my previous statement:
- let's say a method _syncMyAwesomeProperty() exists
- syncawe: X
- syncAwe: OK
- scAwe: X

**Comment by atscott** [comment]
Can you explain what you’re requesting a bit more? We do not even provide symbol searches at all. Are you talking about typescript searching for symbols in typescript? This would be the typescript extension, not Angular

**Comment by jeandat** [comment]
Damn, I hesitated between both. Then I will close the ticket and go there. Thanks.
