### ISSUE TITLE
feat: code folding support for block syntax

### ISSUE THREAD

**Issue by eneajaho** [angular/vscode-ng-language-service#1930]
# 🚀 feature request

### Feature Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
I want to be able to fold blocks in the new template syntax
![CleanShot 2023-10-04 at 11 26 38@2x](https://github.com/angular/vscode-ng-language-service/assets/25394362/222d600c-72e2-4a1f-b138-186faadbc2c9)

**Comment by atscott** [comment]
Fixed by https://github.com/angular/vscode-ng-language-service/pull/1938
