### ISSUE TITLE
Auto completion for event binding not working in template files

### ISSUE THREAD

**Issue by welkie** [angular/vscode-ng-language-service#194]
I noticed this problem while exploring the features of this language service. If I'm editing a template where the markup is in the ```x.component.ts``` file, like this...

```typescript
// x.component.ts

@Component({
  selector: 'app-x',
  template: `
    <div (click)="OnTextClicked()">Click Me</div>
  `
})
export class XComponent {
  onTextClicked() {
    console.log('Text clicked.');
  }
}
```

...then code completion will work for the event binding, string interpolation, etc as I edit the template. I get help with the names of the class properties and methods. However, if I do with the template in a separate file, like this...

```typescript
// x.component.ts

@Component({
  selector: 'app-x',
  templateUrl: 'x.component.html'
})
export class XComponent {
  onTextClicked() {
    console.log('Text clicked.');
  }
}
```

```html
<!-- x.component.html -->

<div (click)="OnTextClicked()">Click Me</div>
```

...then this code completion doesn't work.

I was wondering if this behavior is a bug or if this is not yet supported. If it isn't supported, I think it would make sense to implement it according to the convention that the component class associated with a template file would be the one where the filename is the same except the file extension ends with ```.ts``` instead of ```.html```.

My setup:

CPU Arch: Intel Core i5

OS: Antergos

VS Code info:
Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T12:44:48.751Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by chuckjaz** [comment]
Can you produce a project that reproduces this and supply a link to the repository?

**Comment by welkie** [comment]
Thanks for responding. I created a new Angular project to recreate it and this time it worked. I'm not sure if restarting, recreating the project, or an update to Angular or VS Code helped with this.

Right now, in my template files, I get code completion in that VS Code is able to help with the list of event types I can bind to (when I typed ```(``` on an ```h1``` element I get the list including ```click```, etc. When I chose click, I did not get code completion to help me with the methods available on my component, but when I typed the ```(``` after the name of a known method of my component, code completion kicked in and helped me with it, confirming it was a method of the component. Typing ```(``` at any spot after the ```(click)="``` enabled that code completion.

However, I got no help with the method's parameters though, and no red underlining warning me about calling it with incorrect arguments. Is this limitation a part of the language service's current state, or do you think this is a bug I'm experiencing.

Here is [a repo](https://github.com/welkie/TestAngularBug) with this test project.
