### ISSUE TITLE
Syntax highlighting for control flow code

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#1944]
New angular control flow syntax is in developer preview soon, it would good to have a syntax coloring scheme in place for it.

See screenshot:

<img width="470" alt="Screenshot 2023-10-20 at 17 05 40" src="https://github.com/angular/vscode-ng-language-service/assets/9585787/ecd51bc0-4e59-4146-b928-9efb87c9d4ee">

**Comment by atscott** [comment]
This is done and you can download the extension here: https://github.com/angular/vscode-ng-language-service/releases/tag/v17.0.0-next.2

the vscode marketplace does not support semantic versioning so we cannot publish pre-release versions.
