### ISSUE TITLE
Tooltips for control flow syntax

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#1946]
Just need to add tooltips on mouseover on new control flow syntax `if`, `defer` etc

**Comment by atscott** [comment]
This is in progress for `defer` because it’s unique but likely won’t have anything for common syntaxes like `switch`, `if`, and `for`

**Comment by jpike88** [comment]
That's too bad, as `for` has the `track` statement, it's nice to be reminded of its full capability.
