### ISSUE TITLE
In version 1.84 of vscode, all html files with ngzorro and other component properties get errors.

### ISSUE THREAD

**Issue by Pursuemc** [angular/vscode-ng-language-service#1949]
In version 1.84 of vscode, all html files with ngzorro and other component properties get errors.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
