### ISSUE TITLE
Unable to find the config file of component/ library after 17.0.0 update

### ISSUE THREAD

**Issue by wout-junius** [angular/vscode-ng-language-service#1959]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 16.1.8

### Description

When updating to 17.0.0 the service stops working and complains that it cannot find the config file in my mono repo

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Update the vscode extention to 17.0.0
2. Open any component file or html
3. Show the output of the ALS
4. See the error pop up

**Expected behavior**

Finding the config and starting for the given file

### **Logs**

<pre><code>
-----------------------------------------------
Project '/dev/null/inferredProject1*' (Inferred)
	Files (612)

-----------------------------------------------
Open files: 
	FileName: /Users/woutjunius/dev/snd-web/libs/shared/ui/loading-spinner/src/lib/loading-spinner.component.html ProjectRootPath: undefined
		Projects: /dev/null/inferredProject1*
Err 257   [14:25:16.32] No config file for /Users/woutjunius/dev/snd-web/libs/shared/ui/loading-spinner/src/lib/loading-spinner.component.html

</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
@angular-devkit/architect          0.1602.5
@angular-devkit/build-angular      16.2.5
@angular-devkit/core               16.2.5
@angular-devkit/schematics         16.2.5
@angular/cdk                       16.2.7
@angular/cli                       16.2.5
@angular/material                  16.2.7
@angular/material-moment-adapter   16.2.7
@schematics/angular                16.2.5
ng-packagr                         16.2.3
rxjs                               7.8.1
typescript                         4.9.3
zone.js                            0.13.0
</code></pre>

Extension Version:
<pre><code>
v 17.0.0
</code></pre>

VSCode Version:
<pre><code>
Version: 1.83.1 (Universal)
</code></pre>

Operating System:
<pre><code>
MacOS: 13.5 (22G74)
</code></pre>

**Anything else relevant?**
Using NX mono repo

**Comment by atscott** [comment]
@wout-junius Please provide a project that can reproduce this problem. Given the steps to reproduce it in the report, I was unable to.

**Comment by atsjo** [comment]
Have the same problem in nx, but works when using language service 17 with angular 16 with correct ts version (5.1)... But if I update typescript to 5.2 with angular 16 it breaks, and downgrading to ts 5.1 fixes it again. I think I observed the same with language service 16.1.8...

But now I have updated to angular 17, and then also ts 5.2, and it breaks again... Just gets lots of

```
[Error - 2:50:07 PM] No config file for c:/Users/atles/source/repos/teve-no/task4s/apps/devtest/src/app/home/home.component.html
[Error - 2:56:58 PM] No config file for c:/Users/atles/source/repos/teve-no/task4s/libs/shared-web/src/lib/services/user-lookup.service.ts
```

in the language service log... Not sure if this is a problem with nx or angular... I haven't tried to isolate the problem, but in my case I suspect it has something to do with upgrading to ts 5.2... I will try to reproduce using only angular cli or a minimal nx repo...

**Comment by atsjo** [comment]
can confirm it works fine with a barebone angular-cli project, so probably an nx problem...

**Comment by atsjo** [comment]
I just tested downgrading typescript in my nx repo to 5.1.6... then it works again... (apart from the unmet peer deps warnigs)

**Comment by NachmanBerkowitz** [comment]
I am having the same issue and I don't have nx in my project.

**Comment by NachmanBerkowitz** [comment]
Updating my tsconfig as per @diegovilar worked for me.

**Comment by atscott** [comment]
I've narrowed this down to the [5.2.0-dev.20230607](https://www.npmjs.com/package/typescript/v/5.2.0-dev.20230607) nightly typescript release.

**Comment by atscott** [comment]
I have a PR that appears to fix the issue for solution-style projects in https://github.com/angular/vscode-ng-language-service/pull/1972. Will hopefully get this merged early next week and do another release. 

Have a great weekend, everyone! Thanks for digging into this a bit - the TS version hint was very helpful.
