### ISSUE TITLE
Generics do not correctly infer in template pipe usage

### ISSUE THREAD

**Issue by foxel** [angular/vscode-ng-language-service#196]
Please take a look at the minimal example below:
```typescript
@Pipe({name: 'map'})
export class MapPipe implements PipeTransform {
  transform<T, R>(value: T[], func: (value: T) => R): R[] {
    return value ? value.map(func) : [];
  }
}

// the component
interface InData {
  foo: string;
}

interface OutData {
  bar: string;
}

@Component({
  selector: 'app-test',
  template: `
    <span *ngFor="let item of items | map: _mapper">
      {{item.bar}}
    </span>
  `,
})
export class TestComponent {
  @Input() items: InData[];

  _mapper(item: InData): OutData {
    return {
      bar: item.foo,
    };
  }
}
```

Angular language service (v5.0.2) gives me an error:
```Error:(7, 9) Angular: Identifier 'bar' is not defined. 'R' does not contain such a member```

**Comment by chuckjaz** [comment]
Tracking as https://github.com/angular/angular/issues/21224

**Comment by kyliau** [comment]
This has been fixed in Angular extension v9. Please open a new issue if problem persists.
The latest version can be downloaded from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
