### ISSUE TITLE
Exception causing language service to crash

### ISSUE THREAD

**Issue by BorntraegerMarc** [angular/vscode-ng-language-service#197]
Error "The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted."
This is what I see in the output:
```
C:\Users\BorntraegerMarc\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\typescript\lib\typescript.js:79436
}.call(this, exports, require, module, __filename, __dirname); });
                                                             ^
SyntaxError: Unexpected token ;
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\BorntraegerMarc\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:3:10)
[Error - 8:48:40 AM] Connection to server got closed. Server will not be restarted.
```
It didn't happen to me before. I re-installed Windows and then this happened.

**Comment by chuckjaz** [comment]
What version of Windows are you using?

Have you tried uninstalling the plugin and reinstalling?

**Comment by BorntraegerMarc** [comment]
I'm using Windows 10. Now I've I've even re-installed windows and vscode. So the problem was fixed with that. But I thought I leave the issue open in case somebody wants to add some error handling :)

**Comment by ChenReuven** [comment]
> I'm using Windows 10. Now I've I've even re-installed windows and vscode. So the problem was fixed with that. But I thought I leave the issue open in case somebody wants to add some error handling :)

i have the same problem with angular 5 and i install previous version 0.1.5 of angular language service vs code

**Comment by kyliau** [comment]
Closing this, since issue is two years old. It has already been fixed.
