### ISSUE TITLE
$first in a @for control flow is known as number instead of boolean

### ISSUE THREAD

**Issue by ssougnez** [angular/vscode-ng-language-service#1971]
# 🐞 bug report

### Is this a regression?

Not applicable

### Description

 A clear and concise description of the problem...

I'm trying to use the ngFor control flow with angular with this code:

```
@for (f of foo; track f; let first = $first) {
  @if (first === true) {

  }
}
```

where `foo` is a number[].
The issue is that Visual Studio shows this:

<img width="675" alt="image" src="https://github.com/angular/vscode-ng-language-service/assets/10199821/fa8d2781-4aff-4050-8307-3c5631ff425f">

Which is not correct as `first` is a boolean.
Note that `ng build` works and does not complaint about this.

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [X] Angular Language Service server

## Reproduction

See description

**Expected behavior**

vscode should not complain about this as `first` is supposed to be a boolean indicating whether the item is the first of the array or not.

### **Screenshots**

<img width="675" alt="image" src="https://github.com/angular/vscode-ng-language-service/assets/10199821/fa8d2781-4aff-4050-8307-3c5631ff425f">

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
</code></pre>

Extension Version:
<pre><code>v17.0.1
</code></pre>

VSCode Version:
<pre><code>v1.84.2
</code></pre>

Operating System:
<pre><code>Windows 10
</code></pre>

**Comment by atscott** [comment]
Indeed, [this](https://github.com/angular/angular/issues/52730) was fixed upstream and will just require another release to update the `@angular/language-service` dependency.

**Comment by ssougnez** [comment]
Ah sorry, I did a search on `first` but not `last`.

Good news then, thanks.

**Comment by atscott** [comment]
17.0.2 was released this morning and included the aforementioned fix.
