### ISSUE TITLE
Report a bug that does not exist

### ISSUE THREAD

**Issue by ivanferrer** [angular/vscode-ng-language-service#1983]
I'm using Angular 8 in my project, but it keeps reporting an error that doesn't exist on the template page:
![Captura de tela de 2023-12-13 12-18-25](https://github.com/angular/vscode-ng-language-service/assets/4295101/1ccd018e-e5cc-4aac-9263-2033418c058c)

**Comment by atscott** [comment]
Hi Ivan, this is expected. The current version of the language service will not work for an old Angular 8 project. You should instead install an older version of the extension. Anything before the version 11 release should support the old compiler version. If you're using version 11 or later, you would need to enable view engine support in the extension options (which in turn is not available in the latest versions).
