### ISSUE TITLE
No error for undefined variables when using *ngIf

### ISSUE THREAD

**Issue by enersis-pst** [angular/vscode-ng-language-service#1985]
### Description

Not existing variables woudnt show an error. This is the case of elements which parent have a `*ngIf`.

In this example the variable `context_` doesnt exist. But for the  neasted element this woudnt show an error.
```
{{ context_ }}
<ng-container *ngIf="context_">
  {{ context_ }}
</ng-container>
{{ context_ }}
```
<img width="303" alt="image" src="https://github.com/angular/vscode-ng-language-service/assets/76100214/ea9bd31c-a268-48a2-9010-8334c7c6cc71">

## 🌍  Your Environment
**Angular Version:** 16.1
Angular Language Service: 17.0.3
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.1.8
@angular/cli                    16.1.8
@schematics/angular             16.1.8
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3

</code></pre>

Extension Version:
17.0.3

</code></pre>

VSCode Version:
1.85.1 

</code></pre>

Operating System:
macos 12.3.1 (21E258)

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. It seems likely that your project is not using strict template type checking. 

Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.

**Comment by enersis-pst** [comment]
@atscott 
thanks for the hint.
after i add `"fullTemplateTypeCheck": true` to my tsconfig it shows the error.

**Comment by atscott** [comment]
`fullTemplateTypeCheck` is deprecated and actually skips a lot of checks: https://angular.io/guide/angular-compiler-options#fulltemplatetypecheck. The option you want is `"strictTemplates": true`

**Comment by enersis-pst** [comment]
i think i have to clean much code firstly ;-)

**Comment by atscott** [comment]
@enersis-pst There is also an extension option to force strict templates without changing your `tsconfig`. This does mean that you are choosing to use compiler options for the language service that differ from what's used in the application so you will see more errors. But at least you can continue compiling and running the application and fix things as you see them.

**Comment by enersis-pst** [comment]
thanks thats what i need ;-)
