### ISSUE TITLE
Angular 7 code spaming false positive errors

### ISSUE THREAD

**Issue by EduardoKSibata** [angular/vscode-ng-language-service#1987]
I have an Angular 7 project and recently, visual code start to spaming some errors like "'CommonModule' does not appear to be an NgModule class" and something linked to Ivy.
I'm using Angular 9.1.7 globally, but in this particular project i'm using the 7.2.0 version.
After report to visual code project as a bug, the response is that it's caused by an extension, in order of all installed extensions, this is the only one that could be causing the problem, after disable Angular Language Service all works fine.

[https://github.com/microsoft/vscode/issues/201877#issue-2067179295](url)

**Comment by atscott** [comment]
I'm not sure what version of the extension you're using but I would recommend installing an old one that was released around the time Angular 7 was. Closing as we do not support those version of Angular anymore.
