### ISSUE TITLE
Go To Definition - incorrectly reports multiple definitions and opens Peek Definition

### ISSUE THREAD

**Issue by briancodes** [angular/vscode-ng-language-service#200]
Ctrl+Click or F12 on a template data-bound property opens the Component file with incorrect number of definitions displayed, and also opens the _peek definition_ of the currently open file within that file itself. 

If I _disable_ the extension and reload, it works as expeceted. Enable and reload, problem reoccurs. 

I have tested this with different versions of the Angular and Typescript (Windows 10)

VSCode 1.18.1
Tested with Angular 4 (non cli) and latest Angular CLI (v1.6.0)
Typescript version of VSCode matching Workspace version 2.4.2 (but also with 2.6.1)

![issue](https://user-images.githubusercontent.com/15702512/33804472-1bf06472-dda6-11e7-9523-41f75d583917.gif)

**Comment by chuckjaz** [comment]
Can you produce a project that demonstrates this issue and supply a link to a repository I can clone?

**Comment by briancodes** [comment]
It's a default Angular CLI `ng new project-name`

**Comment by kyliau** [comment]
Closing this, as I believe the bug has been fixed. Please reopen otherwise.
