### ISSUE TITLE
incorrectly importing default exported component via quickfix

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/vscode-ng-language-service#2014]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

## Bug Type
What does this bug affect

- [+] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Create component and add  default export to it like so `export default class SignInFormComponent {
` 
2. write component selector inside other component html and then click option to quick-fix it

**Expected behavior**

it should import component with its default export name instead of 
`import { default } from "./sign-in-form/sign-in-form.component";`
it should be
`import SignInComponent from "./sign-in-form/sign-in-form.component"`

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

</code></pre>

### **Screenshots**
![image](https://github.com/angular/vscode-ng-language-service/assets/56136563/3f7c4f44-39e1-4281-9593-b2aa0ff021e9)
![image](https://github.com/angular/vscode-ng-language-service/assets/56136563/54922e0c-6b78-4b92-b7b8-6f8f5d846e41)

![Example Screenshot](./output.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

</code></pre>

Extension Version:
<pre><code>

</code></pre>

VSCode Version:
<pre><code>

</code></pre>

Operating System:
<pre><code>

</code></pre>

Extension options:
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by eneajaho** [comment]
This can be closed as it was fixed in the last release 🎉
