### ISSUE TITLE
*ngTemplateOutlet  Detect the parameter and redirect to the corresponding template in the HTML using the "control" + right-click combination.

### ISSUE THREAD

**Issue by fordnike** [angular/vscode-ng-language-service#2026]
# 🚀 feature request

### Description
Detect the parameter and redirect to the corresponding template in the HTML using the "control" + right-click combination.
This option exists in WebStorm and is very useful
#### See video below:
[Capture vidéo du 2024-04-24 10:30:51.webm](https://github.com/angular/vscode-ng-language-service/assets/5923222/b0046381-8428-4424-bd2e-51e1d50b8860)

**Comment by atscott** [comment]
This feature is already present in the language service. You may need to ensure you have strict template enabled. The language service is entirely dependent on how template type checking is configured for the compiler.

https://github.com/angular/vscode-ng-language-service/assets/479713/0f49b513-acd5-4b92-81b9-d7808fedda4f
