### ISSUE TITLE
Compatibility issues between Angular 9 and Angular Language Service 17.x

### ISSUE THREAD

**Issue by manusoftar** [angular/vscode-ng-language-service#2030]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.1.2

### Description

 I was working on a a project based on Angular 9 and another project based on Angular 15, the extension automatically selected version 17.x, it had no issues as far as I could see with the Angular 15 project but it completely broke the older project.

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

## Bug Type
What does this bug affect

- [ x ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

Just create an Angular 9 project with ngx-bootstrap and ngx-toastr and node 14.20.0 with this extension installed (version 17.x) and it will show alledged errors on app.modules.ts which are not actually true and if you try to fix those false issues you may end up breaking the whole project (like it happened to me)

**Expected behavior**

I would expect this extension to be retrocompatible with older Angular versions, actually, I would expect it to get the propper angular version from the project itself and not present these kind of errors.

**Comment by atscott** [comment]
Angular 9 has long been dropped from LTS and is not guaranteed to be compatible with the most recent versions of the language service. The extension uses the Angular compiler and cannot guarantee infinite backwards compatibility. Instead, you should install a version of the extension that is closer to that of the project.
