### ISSUE TITLE
Getting "Unsupported expression in a two-way binding" in ngModel

### ISSUE THREAD

**Issue by SidiBecker** [angular/vscode-ng-language-service#2041]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: `17.3.2`

### Description
Getting `Unsupported expression in a two-way binding` when use a condition in `ngModel`

## Bug Type
The code is compiling successfully, but getting error coding on VS Code.

- [X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction
.ts file:
```ts
 public myCondition = true;
 public modelA: string = '';
 public modelB: string = '';
```

.html:
```html
<input [(ngModel)]="myCondition ? modelA : modelB" />
```

.module.ts
```ts
imports: [
    FormsModule,
    ReactiveFormsModule
    ....
]
```

### **Screenshots**
![image](https://github.com/angular/vscode-ng-language-service/assets/40251890/866fd53c-44cf-434b-a1db-5bd7d3471248)

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 17.0.6
Node: 18.19.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6 (cli-only)
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6 (cli-only)
@angular-devkit/schematics      17.0.6
@angular/cdk                    17.0.3
@angular/forms                  17.3.11
@angular/material               17.0.3
@schematics/angular             17.0.6
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2</code></pre>

Extension Version:
<pre><code>v.18.0.0</code></pre>

VSCode Version:
<pre><code>Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621</code></pre>

Operating System:
<pre><code>Windows 11 Pro</code></pre>

Extension options:
<pre><code>none</code></pre>

**Comment by atscott** [comment]
This is a correct diagnostic. While that change wasn't made a compiler error until v18, it doesn't really work correctly even in previous versions. I'm going to close this as working as expected/intended (you shouldn't have expressions in two way bindings)
