### ISSUE TITLE
Control flow syntax highlight not coloring nested if statement

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#2062]
```
@if (form) {
			<mat-card style="min-width: 260px;">
				<mat-card-content>
					<fields [form]="form"></fields>
					<button>
						@if (form.submitted) {
							<mat-progress-spinner
								[mode]="'indeterminate'"
								[diameter]="16"
								style="display: inline-block; margin-right: 12px;"
							>
							</mat-progress-spinner>
						}
					</button>
				</mat-card-content>
			</mat-card>
		}
```

in the above example, that inner if statement is not colourized, it's just grey like below:
<img width="788" alt="Screenshot 2024-07-10 at 8 28 54 AM" src="https://github.com/angular/vscode-ng-language-service/assets/9585787/284eb17a-7163-4895-981c-7ac7ec99a3a6">

**Comment by eneajaho** [comment]
I was just going to open this issue 😅

**Comment by Taras-R** [comment]
> I was just going to open this issue 😅

Same here. Worked in v. 18.0.0, crashed in v. 18.1.0. I guess they will fix it soon.
