### ISSUE TITLE
quick info / go to definition doesn't work for nested function calls in the templates 

### ISSUE THREAD

**Issue by eneajaho** [angular/vscode-ng-language-service#2068]
![CleanShot 2024-07-17 at 00 33 05@2x](https://github.com/user-attachments/assets/1ec62b88-d029-4bef-8eef-acc0aae6a700)

Linked issue: https://github.com/angular/angular/issues/56476

**Comment by atscott** [comment]
@eneajaho Any reason to have a duplicate issue for this? We should close one of them.

**Comment by eneajaho** [comment]
Because the typechecking part works fine from what I saw, I guess the issue should live in the vscode plugin. So, close whatever you think it's best.

**Comment by atscott** [comment]
OK, I'm going to close this one. I started looking at what you had in the WIP PR and it does look like there are issues in the code that lives in angular/angular (you have tests there that fail)
