### ISSUE TITLE
Help understand how a language service detects an Angular project

### ISSUE THREAD

**Issue by Bilal-io** [angular/vscode-ng-language-service#2069]
# 🚀 feature request

### Description
The Zed Edit project is looking to implement support for Angular, and there is a [discussion here](https://github.com/zed-industries/extensions/issues/169) to under what is the best way to detect an Angular project.

I did my best to understand and describe how the VS Code Language Service extension does it in the issue linked above, but I am not sure how correct/wrong I am.

### Feature Type
- [ ] Angular Language Service VSCode extension
- [x] Angular Language Service server

### Describe the solution you'd like
Assistance with the Zed editor if possible, or helpful guidance

### Describe alternatives you've considered
None

### Anything else relevant?
None

**Comment by atscott** [comment]
Your comment is correct. The extension activates on all TS or HTML files. Beyond that, there is short-circuit logic to check that the program for the given document contains `@angular/core` in the sources.
