### ISSUE TITLE
the angualr server crachs

### ISSUE THREAD

**Issue by Bader975** [angular/vscode-ng-language-service#2074]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

**Expected behavior**

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

</code></pre>

### **Screenshots**

<img width="499" alt="Screenshot 2024-07-26 at 2 28 15 PM" src="https://github.com/user-attachments/assets/e505b646-41ab-4466-8c8d-d73780d8f0be">

![Example Screenshot](./output.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

18

</code></pre>

Extension Version:
<pre><code>

<div class="block block-extensions" style="box-sizing: border-box; font-size: 12px; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="block-info" id="systemInfo" style="box-sizing: border-box; background-color: rgb(60, 60, 60) !important; color: rgb(204, 204, 204) !important; font-size: 12px; margin: 5px 5px 1.5em; overflow: auto; overflow-wrap: break-word; padding: 10px; width: 595px;">
Extension | Author (truncated) | Version
-- | -- | --
chrome-extension-developer-tools | aar | 2.0.4
vscode-color-pick | ada | 0.6.2
codesnap | adp | 1.3.4
vscode-css-formatter | aes | 1.0.2
bootstrap5-vscode | Anb | 0.4.4
jsx-html-tags | ang | 1.0.1
ng-template | Ang | 18.1.2
vscode-color | ans | 0.4.5
bootstrap-5-snippets | bab | 0.2.0
vscode-styled-jsx | bla | 2.1.1
vscode-tailwindcss | bra | 0.12.5
simple-react-snippets | bur | 1.2.8
npm-intellisense | chr | 1.4.5
path-intellisense | chr | 2.9.0
vscode-css-modules | cli | 0.5.1
package-json-upgrade | cod | 3.0.0
codeium | Cod | 1.10.1
vscode-eslint | dba | 3.0.10
add-to-git-ignore | djl | 1.0.1
docs-markdown | doc | 1.0.8
docs-preview | doc | 1.0.7
es7-react-js-snippets | dsz | 4.4.3
gitlens | eam | 15.2.1
vscode-html-css | ecm | 2.0.10
vscode-great-icons | emm | 2.1.105
prettier-vscode | esb | 10.4.0
vscode-expo-tools | exp | 1.5.0
auto-close-tag | for | 0.5.15
auto-rename-tag | for | 0.1.10
code-runner | for | 0.12.2
shell-format | fox | 7.2.5
live-sass | gle | 6.1.2
gluestack-vscode | glu | 0.1.22
vue-snippets | hol | 1.0.4
vscode-npm-dependency | how | 1.2.2
vscode-react-typescript | inf | 1.3.1
fontawesome-autocomplete | Jan | 1.3.2
vscode-npm-scripts | jia | 0.2.4
Angular2 | joh | 18.0.2
vsc-python-indent | Kev | 1.18.0
next-js-ts-snippets | loc | 2.0.3
vscode-language-babel | mgm | 0.0.40
git-graph | mhu | 1.30.0
code-beautifier | mic | 2.3.3
Angular-BeastCode | Mik | 17.0.4
dotenv | mik | 1.0.1
million-lint | mil | 0.1.13
mongodb-vscode | mon | 1.6.1
vscode-docker | ms- | 1.29.1
debugpy | ms- | 2024.8.0
python | ms- | 2024.10.0
vscode-pylance | ms- | 2024.7.1
remote-containers | ms- | 0.375.1
remote-wsl | ms- | 0.88.2
js-debug-nightly | ms- | 2024.7.2417
vscode-typescript-next | ms- | 5.6.20240724
vsliveshare | ms- | 1.0.5936
vscode-react-native | msj | 1.13.0
mysql-autocomplete | nes | 0.5.0
vscode-extension-auto-import | Nuc | 1.4.3
material-icon-theme | PKi | 5.8.0
polacode | pnp | 0.3.4
prisma | Pri | 5.17.0
vscode-thunder-client | ran | 2.24.13
reactree | Rea | 1.0.8
LiveServer | rit | 5.7.9
vs-code-prettier-eslint | rve | 6.0.0
rainbow-fart | sae | 1.4.1
angular-cli | seg | 0.0.19
js-jsx-snippets | sky | 11.1.3
autoimport | ste | 1.5.4
ejs-snippets | The | 0.7.0
pdf | tom | 1.2.2
errorlens | use | 3.20.0
intellicode-api-usage-examples | Vis | 0.2.8
vscodeintellicode | Vis | 1.3.1
vscode-icons | vsc | 12.8.0
volar | Vue | 2.0.28
console-ninja | Wal | 1.0.332
quokka-vscode | Wal | 1.0.649
wallaby-vscode | Wal | 1.0.379
JavaScriptSnippets | xab | 1.8.0
primeflexsnippets | yig | 1.0.3
pretty-ts-errors | Yoa | 0.5.4
html-css-class-completion | Zig | 1.20.0
vue | znc | 0.12.0

</div></div><br class="Apple-interchange-newline">

</code></pre>

VSCode Version:
<pre><code>

Version: 1.91.1 (Universal)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:54.982Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

</code></pre>

Operating System:
<pre><code>

PUs | Apple M3 Pro (12 x 2400)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_graphite: disabled_off video_decode: enabled video_encode: enabled webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) | 2, 2, 2
Memory (System) | 18.00GB (0.06GB free)
Process Argv | --crash-reporter-id de1dc57c-6b38-40f4-af36-f5616678aca0
Screen Reader | no
VM | 0%

</code></pre>

Extension options:
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
