### ISSUE TITLE
Replace Angular.io with Angular.dev on VSCode marketplace 

### ISSUE THREAD

**Issue by BojanKogoj** [angular/vscode-ng-language-service#2082]
# 🐞 bug report

### Description

On extension page domain still points to angular.io instead of angular.dev

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Go to https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

**Expected behavior**

Url should point to angular.dev
![image](https://github.com/user-attachments/assets/d4bd7330-60d2-4c9f-934b-af51d3ca42b5)

**Comment by sheikalthaf** [comment]
This has been fixed now.
