### ISSUE TITLE
Autocompletion of HTML tag attributes sometimes eats the ending quote

### ISSUE THREAD

**Issue by LaXiS96** [angular/vscode-ng-language-service#2093]
# 🐞 bug report

### Is this a regression?

Don't know, it may be but I have not verified previous versions

### Description

I noticed that sometimes but not always, autocompleting values in element attributes causes the editor to eat the closing quote.

Please see the recording:
![Image](https://github.com/user-attachments/assets/b1be8b31-3e3d-409d-8c73-2850be5a602f)

As you can see the `the` suggestion removes the closing `"` after it is applied by Tab.  
It is not related to the length of the suggestion, it happens with longer ones too.  
It is also not related to the specific attribute, it happens with `class` and others too.

I confirmed the issue is caused by the Angular Language Service extension because it doesn't happen when this extension is disabled. Other extensions were disabled during testing, too.

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

Please see the screen recording above, keystrokes are shown on the upper right

**Expected behavior**

Autocompletion should not remove the ending quote

### **Logs**

Not relevant

### **Screenshots**

See above

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 17.3.8
Node: 18.20.3
Package Manager: yarn 4.5.0
OS: win32 x64

Angular: 17.3.10
... animations, common, compiler, compiler-cli, core, forms     
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
</code></pre>

Extension Version:
<pre><code>
v18.2.0
</code></pre>

VSCode Version:
<pre><code>
Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
</code></pre>

Operating System:
<pre><code>
Windows 10 Version 22H2 OS Build 19045.4894
</code></pre>

Extension options:
<pre><code>
No customized options
</code></pre>

**Anything else relevant?**

**Comment by Segdo** [comment]
This looks like a duplicate of #1791?

**Comment by LaXiS96** [comment]
Yeah I missed that issue, it's the same problem.
Thank you
