### ISSUE TITLE
Please add support for latest V19-Next

### ISSUE THREAD

**Issue by spock123** [angular/vscode-ng-language-service#2095]
**Is your feature request related to a problem? Please describe.**

Latest V19 builds have now standalone:true as default.
This makes the angular language service show errors in VSCode when using the imports array in a component.:

`imports is only valid on a components that is standalone `

# 🚀 feature request

### Description
Add support for standalone: true as default (ie. allow imports array)

**Comment by spock123** [comment]
![Image](https://github.com/user-attachments/assets/032b2956-afe5-46de-a16d-33c4f6e72f09)

**Comment by devversion** [comment]
should be done

**Comment by 188599** [comment]
I'm still getting this same error, am I missing something?

![Image](https://github.com/user-attachments/assets/e2852281-efe1-4247-8e78-875772eda4f0)
![Image](https://github.com/user-attachments/assets/6c7c0723-c8e0-41ef-ab46-9bf747b35547)

**Comment by devversion** [comment]
@188599 potentially you have a workspace with multiple Angular versions in your project? consider clicking on VSCode's `Output` tab right by the terminal, and then click on Angular language service. It should print the "found version"

**Comment by 188599** [comment]
> [@188599](https://github.com/188599) potentially you have a workspace with multiple Angular versions in your project? consider clicking on VSCode's `Output` tab right by the terminal, and then click on Angular language service. It should print the "found version"

Yes,  that is the case.

I'm migrating a very old Angular project and I have both the old one and the new one in the same workspace. The language service is pulling the version from the old project in this case.

![Image](https://github.com/user-attachments/assets/5cc25f0f-aa10-4391-a250-4f11b8ac2bb4)

**Comment by devversion** [comment]
Ah yeah, that's a known limitation of the version detection we have. I don't know if there is a tracking issue for this somewhere.

**Comment by 188599** [comment]
Is there a way to force a specific version to be used instead?

**Comment by devversion** [comment]
Can you create a feature request for this? I think this is a good suggestion

**Comment by 188599** [comment]
Created this one https://github.com/angular/vscode-ng-language-service/issues/2118
