### ISSUE TITLE
External HTML component not known element

### ISSUE THREAD

**Issue by devinci** [angular/vscode-ng-language-service#210]
### Env
IDE: VSCode Insider Build
Angular CLI: 1.6.3
Angular Language Service (ALS): 5.2.0-beta.1
Typescript: 2.4.2
OS: Windows 10

### Issue
External HTML files with custom components, errors out, showing **(component) is not known element**.
Go to definition doesn't resolve and hover shows **[Angular] error**. Auto-complete is also non-functional, however native tags i.e. `<div>, <input>`, have valid hover and Go to resolution. TS files have no issue either.

Have tried with and without Angular Language Service extension installed on VSCode and/or package installed via package.json

Exact same repo on **OSX works**, has component definition and peek available with no issues.

Possible a duplicate of the issues below, referencing **tsconfig aliasing issues** with ALS, but as far as I can tell, those seem to be resolved in the version I am using?

 - https://github.com/angular/angular/issues/18484
 - https://github.com/angular/angular/issues/16382

Any help or direction would be greatly appreciated.

### TSConfig
[TSConfig.txt](https://github.com/angular/vscode-ng-language-service/files/1614411/TSConfig.txt)

#### Windows 
![image](https://user-images.githubusercontent.com/7167770/34712072-38cdc454-f52a-11e7-8038-70408d69b50e.png)

**Comment by kyliau** [comment]
Hi, referencing your screenshot, please try to open `events-edit.component.ts`, then open `events-edit.component.html`, and see if the language service works

**Comment by devinci** [comment]
Hi, thanks for getting back to me. As you can see in the screen shot below, having the .ts open first or even simultaneously doesn't affect the result.

![image](https://user-images.githubusercontent.com/7167770/34933928-5dbb6012-f9e1-11e7-9dee-24110f9d0ba0.png)

I also then proceeded to generate a new project using Angular CLI 1.6.4 and then copied over the package.json dependencies over to my project as I noticed that they weren't updating using the usual methods. See the ng --version below.

![image](https://user-images.githubusercontent.com/7167770/34938664-e0bcf93e-f9f1-11e7-830e-09577e6a51eb.png)

**Comment by kyliau** [comment]
Could you please try out the latest version and check if the problem still exists?
We've completely rewrote the entire extension, and it has fixed many fundamental problems like this.
I'd like to close this issue for now, since it is almost two years old.
Please open a new issue if this bug still persists. Thank you.
