### ISSUE TITLE
Can't resolve all parameters error when using path aliases

### ISSUE THREAD

**Issue by Ristaaf** [angular/vscode-ng-language-service#211]
I get an error squigly under the Component  decorator of components that have injected services that are imported from aliased paths.

Error:
[Angular] Can't resolve all parameters for ButtonComponent in c:/myapp/src/app/button/button.component.ts: (?, ?, ?, ?, [object Object], ?).

The ? injections in the constructor comes from services imported from aliases defined in tsconfig.json like this:

"paths": {
      "@myapp/*": ["src/app/*"]
    }

and imported with:

import { MyService } from "@myapp/services/my.service";

Everything works fine in runtime when built!

Depending on where this error originates it might be connected to this issue?:
https://github.com/Microsoft/TypeScript/issues/19113

**Comment by kyliau** [comment]
looks like this has been fixed in https://github.com/angular/angular/issues/16382
what version of angular are you running?

**Comment by Ristaaf** [comment]
Ok, thanks for the info, I use Angular 5.2 however since this vscode extension is hardcoded to use a beta of Angular language service 5.0 which has the bug (seems to be fixed in Angular 5.1) I am pretty much screwed until a new version of this plugin is released, and this project seems to be quite dead (no release since August!)

**Comment by Ristaaf** [comment]
Anyway since this is not directly related to the vscode plugin, I will close this issue.
