### ISSUE TITLE
Extension don't work if you have accents in the path

### ISSUE THREAD

**Issue by vmcbaptista** [angular/vscode-ng-language-service#212]
If the path for a project contain accents for exemple:
`C:\Users\vítor\Desktop\New folder`
Angular Language Services doesn't work and the log appears like this.
```
Search path: c:/Users/vÃ­tor/Desktop/New folder/apptest/src/app
No config files found.
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
getTemplateRefrences: 259ms
getDiagnostics: 13ms

```
Altough, if I place the same project in a path without accents for example:
`C:\New folder`
Angular Language Services works and the log appears like this.
```
Search path: c:/New folder/apptest/src/app
Config file name: c:/New folder/apptest/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
getTemplateRefrences: 1329ms
Add recursive watcher for: c:/New folder/apptest
Opened configuration file c:/New folder/apptest/tsconfig.json
getDiagnostics: 30ms

```

**Comment by kyliau** [comment]
This has been fixed in the new extension. Please open a new issue otherwise. Thank you!
