### ISSUE TITLE
Extension thinks components are default standalone false with 19.1.0-next.0

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#2123]
![Image](https://github.com/user-attachments/assets/013bc380-24f9-47e9-95dd-0cce26519cb5)

This error was not an issue on angular 19.0.1, and typescript 5.6.3

**Comment by BBboy01** [comment]
same here, the reason is angular@19 takes components as `standalone: true` by default now. If you use the latest language server for projects angular version less than 19 and `standalone` option is lacked, all your components are treated as standalone.

**Comment by jpike88** [comment]
See my initial comment, I am already on angular 19. This is possibly because this extension breaks if a newer version of typescript is being used

**Comment by Segdo** [comment]
Have the same problem on angular/core 19.1.0-next.2 with angular/cli 19.1.0-next.0.
Typescript is still on 5.6.3 (also tested typescript 5.7.2) so I don't think it's a typescript problem.

Would guess that the language service thinks angular 19.1 prereleases have standalone default to false?

**Comment by jpike88** [comment]
@crisbeto any comments on above? Seems like this standalone detection logic is only tested for here, but not for versions 'above' 19.0.0?

https://github.com/angular/vscode-ng-language-service/blob/main/integration/lsp/ivy_spec.ts#L556

**Comment by crisbeto** [comment]
I've sent out https://github.com/angular/angular/pull/59061 which will handle pre-releases properly. Note that it'll take a bit of time for it to make it to the extension, because it needs to be released, the extension needs to be updated and released.

**Comment by jpike88** [comment]
wow you're a legend. thanks a lot
