### ISSUE TITLE
Publish language server as an npm package

### ISSUE THREAD

**Issue by rcjsuen** [angular/vscode-ng-language-service#213]
Am I missing something or is the language server not actually published to npm?

I see that the scripts use `installServerIntoExtension` which is all fine and good to be used for the VS Code extension but what about people that want to use the language server in other clients?

**Comment by kyliau** [comment]
The core of the language service is here: https://github.com/angular/angular/tree/master/packages/language-service
The corresponding npm package is https://www.npmjs.com/package/@angular/language-service
We're moving to a new architecture where we don't need to maintain a separate server, but install the language service as a Typescript plugin instead.

**Comment by rcjsuen** [comment]
@kyliau Is there an issue open that's tracking this new effort that I can take a look at and read up on?

**Comment by chuckjaz** [comment]
#222

Closing this issue as the language service is already on npm.

**Comment by rcjsuen** [comment]
@chuckjaz Just to clarify, the language service is not what I am looking for me. I want a binary/JavaScript script that I can invoke that starts a server for a client/editor to connect to. I am not interested in the language service as an API or library.

**Comment by chuckjaz** [comment]
You can get this by adding the language service as a plugin to tsserver. You need to add it to the plugins section of the tsconfig.json file and then request completions and other services. This currently only works well for templates in string literals and we are working with Microsoft to improve the architecture of tsserver to allow it to support html files as well.

**Comment by kyliau** [comment]
We published @npm/language-server, and it's currently in version 9 RC. 
https://www.npmjs.com/package/@angular/language-server
