### ISSUE TITLE
Language Service not working

### ISSUE THREAD

**Issue by jtsom** [angular/vscode-ng-language-service#214]
Trying to edit some text, and it looks like the language service isn't doing anything - not syntax checking, not providing popup completion. I don't see any errors in the console log. This is with the latest VSCode Insiders, and the latest Angular Language service extension. Is it dead?

**Comment by jtsom** [comment]
A small update. I have one project where it seems to work, but more than one where it doesn't. I have noticed in the project where it works (shows popup info while editing), in the Output window, the "getHoverAt" value is > 0. The projects where it does not work, the "getHoverAt" value is always 0ms

**Comment by ankemp** [comment]
I'm also encountering the same issue, working in one project and not in another. I've also gone through and made sure all angular related packages were the same as the working project, but that doesn't seem to help.
I've also gone through tsconfig.json in both projects, but they are identical.

**Comment by ankemp** [comment]
And right after I post that, i seem to have found it.
Doesn't look like this plugin plays well with typescript 2.6. If you revert back to typescript 2.5.3 it seems to be working again.

**Comment by jtsom** [comment]
Which is a shame, since Angular and the CLI are touting TS 2.6 compatibility with their latest release.

**Comment by bbaia** [comment]
Same here. Had to revert Typescript to 2.5.3.

**Comment by chuckjaz** [comment]
#220 Should fix this issue.

You can work around this issue by removing the `@angular/language-service` installed in the project directory.

This reason this is failing is that two versions of typescript are being loaded, one from the extensions direction, one from the projects directory. There should only be one copy of typescript in the service and #220 address this.

By removing `@angular/language-service` you fall back to the version of the language service in the extension that will load the same version of `typescript` used by the rest of the service.

**Comment by jmurphzyo** [comment]
@chuckjaz that didn't seem to work on my projects.

**Comment by serkanparlak81** [comment]
> fddf

> 

> `dfd`

**Comment by bhanukumar04** [comment]
@chuckjaz chuckjaz Thank you. By removing @angular/language-service worked for me.

**Comment by DoanVanThuong** [comment]
Language service extension not working in my project
ng: v8.0
@angular/language-service: 8.1.2
typescript: 3.4.5

**Comment by osnersanchez** [comment]
> #220 Should fix this issue.
> 
> You can work around this issue by removing the `@angular/language-service` installed in the project directory.
> 
> This reason this is failing is that two versions of typescript are being loaded, one from the extensions direction, one from the projects directory. There should only be one copy of typescript in the service and #220 address this.
> 
> By removing `@angular/language-service` you fall back to the version of the language service in the extension that will load the same version of `typescript` used by the rest of the service.

I would like to know that if I uninstall the angular language service from my package.json it will not affect my project in any way? since I am working in a large development team

**Comment by kyliau** [comment]
Closing this, since original issue was fixed in https://github.com/angular/vscode-ng-language-service/issues/214#issuecomment-359961369
