### ISSUE TITLE
Move to a single server, plugin architecture

### ISSUE THREAD

**Issue by chuckjaz** [angular/vscode-ng-language-service#222]
# Proposal

Convert this plugin to register a typescript plugin instead a separate server.

## Justification

The current architecture requires two copies of `typescript` to be loaded as well as a special server.

TypeScript supports a plugin architecture that would allow the language service to be loaded into `tsserver.js` and request for completions can be returned directly from `tsserver.js` with no need to run a separate service. This reduces memory consumption by nearly half as well as killing the most common bugs reported regarding `editorServices` and `lineInfo` which are local copies of code in `tsserver.js`

**Comment by kyliau** [comment]
Closing this, since the work is already done.
