### ISSUE TITLE
Extension doesn't populate Changelog tab

### ISSUE THREAD

**Issue by PaluMacil** [angular/vscode-ng-language-service#223]
If you include the release changes in a CHANGELOG.md in the workspace root, it will greatly enhance the experience of users who always read all their changelogs (that's me! not sure how many of us there are...)

**Comment by chuckjaz** [comment]
If you look at the commit history there change it is not very interesting because all the interesting work is done as part of https://github.com/angular/angular and this repository will mostly just be updating which version of the language service is used by default.

**Comment by PaluMacil** [comment]
I respectfully disagree with not showing your users what changes you've made when your extension gets updates. I always read changelogs and tend to distrust a project that is open source but hides changes or ignores norms of the ecosystem where it is distributed. I also disagree with an assertion that developers won't know the difference between Angular and this extension. The distinction is quite clear, and I often look for changes in how my extensions impact my environment.

Would you reconsider if I make the pull request?

**Comment by mackelito** [comment]
@chuckjaz I do agree with @PaluMacil.. a changelog should be present :)
