### ISSUE TITLE
Windows下更新0.1.8版本之后，导致HTML中无法跳转TS定义，感觉插件完全废了！！！

### ISSUE THREAD

**Issue by 15380831711** [angular/vscode-ng-language-service#225]
#**# Windows下更新0.1.8版本之后，导致HTML中无法跳转TS定义，感觉插件完全废了，建议先还原到0.1.7版本！
Windows下有这个问题，MAC上没有这个问题**！

**Comment by chuckjaz** [comment]
This is a duplicate of #217. Please see it for more details.

这是＃217的重复。 请参阅更多细节。

**Comment by 15380831711** [comment]
@chuckjaz Thank you very much for fixing it.
