### ISSUE TITLE
After an update to 0.1.8 "Go to definition" doesn't work anymore

### ISSUE THREAD

**Issue by vhb56** [angular/vscode-ng-language-service#226]
In the past i could click on the component name and go to the file, now can't, no errors in output, just nothing happens. Intellisense doesn't work too. I don't have language-service installed in my package.json.

**Comment by vhb56** [comment]
after downgrade to 0.1.7 everything works again

**Comment by micdenny** [comment]
I had to downgrade to 0.1.7 because everything stopped to work for me, all the intellisense, not just for the "go to definition"

Is there something we are missing?

**Comment by gabrielverao** [comment]
Yep, 0.1.8 doesn't work , I had to downgrade to 0.1.7. Works fine

**Comment by Tyler-V** [comment]
Confirming this as well, can't for the life of me get the Angular Language Service to work.

Angular Language Service ext 0.1.8
Typescript 2.6.2

**Comment by rfuhrer** [comment]
See #217, seems like it's a windows pathing problem from the 0.1.8 update. They're working on it

**Comment by MainaWycliffe** [comment]
I can confirm the same thing here, I updated and everything stopped working. And i can confirm everything is working after downgrading back 0.1.7. Am also using a windows PC.

**Comment by chuckjaz** [comment]
This is a duplicate of #217. Please see #217 for more informaiton.
