### ISSUE TITLE
VS Code ... Angular Language Service conflicts with Emmet

### ISSUE THREAD

**Issue by user3323** [angular/vscode-ng-language-service#232]
VS Code v. 1.21.0-insiders
OS: win7x64

When your plugin is enabled - somehow it disables the Emmet suggestions in VS Code.
It comes like this in **.html** file.

take a look at it:
![ng lang service conflicts with emmet](https://user-images.githubusercontent.com/24613274/36349551-691340d0-1492-11e8-8f97-f690960b0945.gif)
_(clickable)_

Is that the plugin's fault, or the VS Code's one?

**Comment by blasyaselli** [comment]
I am having this same issue. Once I install the plugin, Emmet no longer works.

**Comment by ekzotech** [comment]
Impacted by this issue too. Actually, the Emmet still works, you can just type, for example, "mycustomtag", then type a space after word, then delete the space and the last character (in this example "g") and then after retype "g" you'll be able to hit <TAB> to get your abbreviation expanded.

**Comment by kyliau** [comment]
Similar to https://github.com/angular/vscode-ng-language-service/issues/177, will track this issue there.
