### ISSUE TITLE
valid template syntax marked as error

### ISSUE THREAD

**Issue by Hotell** [angular/vscode-ng-language-service#233]
**Plugin Version:**  0.1.9

**Angular pacakges versions:**
```
Angular CLI: 1.7.0
Node: 8.9.3
OS: darwin x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack: 3.11.0
```

**tsconfig.json**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "strict": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "skipMetadataEmit": true,
    "strictInjectionParameters": true,
    "preserveWhitespaces": false
  }
}
```

**Problem:**

![ng-lang-service-bug-0 1 9](https://user-images.githubusercontent.com/1223799/36450407-27f7cd02-168e-11e8-9f1e-4069706bccdb.gif)

**Expected Behaviour:**

Properly reflect language service output within VScode

**Comment by waelkdouh** [comment]
Not sure if this is related but I am facing an issue where I have to close the html file for the error to go away which is extremely annoying and counter productive.

**Comment by briancodes** [comment]
@waelkdouh I have the same problem. On occasion I have to close the file, and sometimes VSCode, for errors to clear. Usually happens if I make a lot of changes at once e.g. delete/checkout a branch, revert a file

 extension v0.1.9
TypeScript v2.7.2
VSCode v1.21.0
Windows 10

**Comment by michaeljota** [comment]
I don't think this is an error. The compiler is warning you because you have `strict` mode. `*ngIf` actually check for a falsy/truthy value. I understand that from the development pov this `*ngIf` should use guards somehow, but should guard to what? Because to show the template, it just will be a truthy value.

Meaning this won't be null, sure, but what value will this have?

**Comment by kyliau** [comment]
This has been fixed by https://github.com/angular/angular/pull/33016 and https://github.com/angular/angular/pull/33245
