### ISSUE TITLE
[Angular] Member 'd' is not callable 

### ISSUE THREAD

**Issue by Liero** [angular/vscode-ng-language-service#234]
If I use default [Modal sample from ng-bootstrap](https://ng-bootstrap.github.io/#/components/modal/examples) I get errors like 

> [Angular] Member 'd' is not callable 

    <ng-template #confirmDlg let-c="close" let-d="dismiss">
        <div class="modal-header">
          <h4 class="modal-title">Confirm</h4>
          <button type="button" class="close" aria-label="Close" (click)="d('Cross click')">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Content</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-dark" (click)="d('Cross click')">Close</button>
        </div>
      </ng-template>

using

- VS Code 1.20.1, 
- Angular 5.2.0 (app genereted by ng CLI)
- Angular Language Service 0.1.9 VS Code extension
- `@ng-bootstrap/ng-bootstrap: "^1.0.0"`

**Comment by razzildinho** [comment]
I had the same issue, managed a workaround where I add the function call to the assignment.
```html
<ng-template #content let-ca="close('a')" let-cb="close('b')" let-d="dismiss()">
  <button (click)="ca">Close with 'A'</button>
</ng-template>
```

**Comment by kyliau** [comment]
Sorry it took so long, https://github.com/angular/angular/pull/33782 should fix this.

**Comment by JustinPierce** [comment]
I'm not sure if it's a regression, but I'm seeing this problem again using `ngneat/transloco`, Angular 9, and Angular Language Service 0.900.11. Before upgrading to Angular 9, I was using Angular 8 and v0.802.3 of the language service without issues.
