### ISSUE TITLE
Inline template highlighting uses wrong positions with CRLF

### ISSUE THREAD

**Issue by Goobles** [angular/vscode-ng-language-service#235]
When using CRLF line endings the symbol positions get offset 1 charater per line

This does not occur when using LF.

![code_2018-03-09_13-03-26](https://user-images.githubusercontent.com/8776771/37206764-4a617870-239a-11e8-9047-51194bcff912.png)

Using:
Plugin Version: 0.1.9
Typescript: 2.6.2
VSCode: 1.20.1

**Comment by kyliau** [comment]
Created the following test case to expose this bug:

```
it('should work correctly with CRLF endings', () => {
    const fileName = '/app/test.ng';
    const content = mockHost.override(fileName, '\r\n<div>\r\n{{line0}}\r\n{{line1}}\r\n{{line2}}\r\n</div>');
    const ngDiags = ngLS.getDiagnostics(fileName);
    expect(ngDiags.length).toBe(3);
    for (let i = 0; i < 3; ++i) {
      const {messageText, start, length} = ngDiags[i];
      expect(messageText)
          .toBe(
              `Identifier 'line${i}' is not defined. The component declaration, template variable declarations, and element references do not contain such a member`);
      // Assert that the span is actually highlight the bounded text. The span
      // would be off if CRLF endings are not handled properly.
      expect(content.substring(start !, start ! + length !)).toBe(`line${i}`);
    }
  });
```

However, there is no easy fix for now due to way the HTML parser tokenizes the string.
`\r\n{{line0}}\r\n{{line1}}\r\n{{line2}}` is tokenize as a whole.
When `CR` characters are stripped from the string, source span information is lost.

**Comment by andrius-pra** [comment]
@kyliau, a possible fix is [here](https://github.com/andrius-pra/angular/commit/47696136e3d487098c2ba466e21b09cbb6bdfaeb)

**Comment by kyliau** [comment]
@andrius-pra thanks for the suggestion! I've tested it and submitted a PR. Marking this fixed for now.
Ref https://github.com/angular/angular/pull/33241
