### ISSUE TITLE
Cannot get this to work on a non-angular-cli project

### ISSUE THREAD

**Issue by anhallbe** [angular/vscode-ng-language-service#236]
I've been trying to use this extension on and off for a while, but I've never managed to get it to work properly in our projects. I figured maybe somebody here could help me figure out what's going on:

## The Problem
- I'm not getting any syntax highlighting, type-checking or auto-completion in inline templates
- No syntax highlighting, type-checking or auto-completion in inline styles

## Project setup
Without going into too much detail, the basic setup is:
- Running on a Windows machine
- Project is not created or managed by @angular/cli
- Source files are not named like angular-cli components (no *.component.ts)
- Components and Modules are sometimes declared in the same file
- Templates and styles are always inline
- We are using JIT, so no angularCompilerOptions in tsconfig
- Currently using angular 5.2.8, no language-service dependency (have tried with other versions)
- Currently using Typescript 2.7.2 (have tried with other versions)
- The only other extension in use is TSLint

## Example source file
```javascript
// project/componentdir/something.ts

import { Component, NgModule, Input } from "@angular/core";

@Component({
  template: `
    <p>{{something}}</p>
  `,
  styles: [`
    .selector { ... }
  `],
})
export class MyComponent {
  @Input() something: Something;
}

@NgModule({
  imports: [],
  declarations: [MyComponent],
  entryComponents: [MyComponent]
})
export class MyModule {}
```

Looking at the VSCode output for Angular Language Service, it appears that it is at least doing _something_:
```
Search path: d:/path/to/project/componentdir
Config file name: d:/path/to/project/tsconfig.json
getTemplateReferences: 0ms
updating project structure from ...
updated: ng - 64ms
updating project structure from ...
updated: ng - 0ms
getHoverAt: 0ms
updating project structure from ...
updated: ng - 0ms
getDiagnostics: 74ms
getHoverAt: 0ms
getHoverAt: 0ms
getHoverAt: 1ms
getHoverAt: 0ms
```

**Edit:** Actually, it seems like I sometimes get some (incorrect?) intelisense:
```
// Our UI library is often using Directives with inputs like so:
template: `
  <input ui-lib-input [something]="xyz"> // Error here
`
```
The code above does get marked with `[Angular] Can't bind to 'something' since it isn't a known property of 'input'.`. Could this be related?

**Comment by anhallbe** [comment]
Oh and here's some VSCode info:

- Extension Name: ng-template
- Extension Version: 0.1.9
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.21.0

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 45,
		"activateCallTime": 17,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:typescript"
	}
}
```

**Comment by jdforsythe** [comment]
I think you may have hit the nail on the head:

> Source files are not named like angular-cli components (no *.component.ts)

I was just about to put up an issue for this. I want "page" components to be named `*.page-component.ts` because they are "different" (i.e. no selector, not reusable) but that disables any intellisense or code completion in the HTML template.

If you start a new project with `ng new` and in the default `app.component.html` change:

```html
<h1>
  Welcome to {{ title }}
</h1>
```

to 

```html
<h1>
  Welcome to {{ err }}
</h1>
```

you get the red squiggly error. Rename the `app.component.*` files to `app.page-component.*` and the error squiggly goes away, as does code completion. Hovering also does nothing (although the event is firing in the the output panel).

CTRL+Hover does show the declaration line from the `app.page-component.ts` file and the error still shows in the VSCode problems panel.

**Comment by DerZyklop** [comment]
Same here with different Editors (vscode and atom). 

@anhallbe I heard that template Autocompletion is only supported in AOT projects, not in JIT. But i can not confirm since the language-service guide (https://angular.io/guide/language-service) doesn‘t give any info about AOT/JIT requirements.

**Comment by kyliau** [comment]
@anhallbe @DerZyklop 
My apologies for the lack of response. I recently took over this project and started to comb through the issues. The language service has been completely rewritten, so many problems like these have been fixed. Could you please give it another try and let me know if it works?
If not, please feel reopen this ticket. Thank you!

**Comment by DerZyklop** [comment]
@kyliau 
I still have no language support in *.html template files in atom. 
I can not tell whats the state in vscode.
