### ISSUE TITLE
 typescript variables highlight in html

### ISSUE THREAD

**Issue by linocatucci** [angular/vscode-ng-language-service#237]
Hello,
I have seen that typescript variables highlight in html is not working. 
In the below code block the string interpolation of {{formOutput.projectName}} is not highlighted.

<div class="help-block" *ngIf="submitted">
        <p>Your input was: {{formOutput.projectName}}</p>

Also typescript methods in html are not highlighted either. In the below expression there is no highlighting:
*ngIf="!projectForm.get('prjName').valid

Is this a bug? Do I need to configure something extra in the preferences?

Best regards,
Lino

**Comment by kdcro101** [comment]
Same here.. Click on  angular component in template does nothing

**Comment by kyliau** [comment]
Could you please provide more info? Do you mean "syntax highlighting" in template, or the underline the shows up when you hover over the variable? 
The language service does not have support for syntax highlighting, yet.
However, you should see proper **underline** when hovering over a variable, or click "Go to definition".
It'd be best if you could show a screenshot. Thank you!

**Comment by kyliau** [comment]
Closing this, please open a new issue with more info, and include a screenshot. Thank you!
