### ISSUE TITLE
The definite assignment assertion modifiers in ts 2.7 break data binding

### ISSUE THREAD

**Issue by CodySchrank** [angular/vscode-ng-language-service#241]
My component has this property:

`vehicle!: CustomerVehicleResource;`

But it is not recognized in the html:
`{{vehicle.vehicleDescription.vehicleName}}`

Showing error 
"Identifier 'vehicleDescription' is not defined. '<anonymous>' does not contain such a member"

It compiles just fine and works, it is just being incorrectly marked as an error on Typescript 2.7.2

**Comment by thw0rted** [comment]
Is this a duplicate of #230?

**Comment by CodySchrank** [comment]
@thw0rted appears to be yes
