### ISSUE TITLE
Unknown method '$any' in VSCode

### ISSUE THREAD

**Issue by doggy8088** [angular/vscode-ng-language-service#242]
I've got this error in the Visual Studio Code.  Does the Angular Language Service extension support using `$any` in the template now?

![image](https://user-images.githubusercontent.com/88981/38468963-186b51ee-3b80-11e8-8330-f1e6ee319b7f.png)

Ref: [The $any() type cast function](https://angular.io/guide/template-syntax#the-any-type-cast-function)

**Comment by danielleiszen** [comment]
I have the same issue, however it appears only in one file, in other files I use $any no error appears. Are there any conditions on where and how it should not be used?

**Comment by AndrewWeb-Dev** [comment]
Experiencing the same problem

**Comment by Dassderdie** [comment]
I experience this error on all occurrences of $any() in all templates.
Is there $any chance this issue could be resolved in the next time? It's quite annoying and seems (I have no idea -> please correct me if I'm wrong) not too complex or time-consuming to fix.

**Comment by kyliau** [comment]
This will be available in `@angular/language-service` v9.0.0-next.13 onwards  or v9 rc. v9 rc is scheduled for later this week or next week.
