### ISSUE TITLE
doesn't work in angular cli@1.7.4, VScode 1.22.2, Mac OS

### ISSUE THREAD

**Issue by akazupin** [angular/vscode-ng-language-service#245]
├─┬ @angular/cli@1.7.4
│ ├─┬ @angular-devkit/build-optimizer@0.3.2
│ │ └── typescript@2.6.2 
│ └─┬ @schematics/angular@0.3.2
│   └── typescript@2.6.2 
└── typescript@2.6.2

**Comment by kyliau** [comment]
Could you please provide more info?
1. version of language service (run `ng version`)
2. log files from the extension output
3. actual error message / stack trace.
Please reopen issue with more info, thank you!
