### ISSUE TITLE
Event binding give wrong IntelliSense when property name suffix with 'Changed'

### ISSUE THREAD

**Issue by doggy8088** [angular/vscode-ng-language-service#246]
When event binding on a  property name suffix `Changed` with the `@Output()` decorator, it will produce wrong IntelliSense suggestion.  See the following screenshot:

![image](https://user-images.githubusercontent.com/88981/38775202-5a55d816-40af-11e8-9084-0c0b7306553e.png)

**Comment by kyliau** [comment]
This has been fixed in https://github.com/angular/angular/pull/33311
