### ISSUE TITLE
Entering text near [disabled] in <input/> makes typing stutter and freeze, also 100% CPU usage at the moment

### ISSUE THREAD

**Issue by idchlife** [angular/vscode-ng-language-service#247]
VSCode version: 1.22.2
Extension version: 0.1.9

Steps to reproduce:

1) Create template with reactive form, start typing

```html
<input type="button" [disabled]="some_prop" />
```

I have problem with those tags which has this attribute, [disabled]

I recorded a video showing the problem (be patient it will unfreeze at the end):

https://streamable.com/g1rz6

**Comment by idchlife** [comment]
:(

Now it like this near every input

**Comment by kyliau** [comment]
This is similar to https://github.com/angular/vscode-ng-language-service/issues/336
Will track this issue there.
