### ISSUE TITLE
Server wont start: Connection to server got closed, `Unexpected token .`

### ISSUE THREAD

**Issue by codelemur** [angular/vscode-ng-language-service#248]
**System Details:**
* OS: Windows Version	10.0.16299
* TypeScript: 2.6.2 (local) and 2.8.1 (vscode)
* VS Code: 
  * Version 1.22.2
  * Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
  * Date 2018-04-12T16:38:45.278Z
  * Shell 1.7.12
  * Renderer 58.0.3029.110
  * Node 7.9.0
  * Architecture x64

**Expected Behavior:**
When I load the extension for the first time in a project, it should not crash

**Actual behavior:**
Extension crashes on initial load

**Things I've tried:**

* disabling/re-enabling
* reinstalling extension
* changing typescript version to 2.6.2

I was able to load the file (`C:\Users\<user>\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js`) where the error appeared,and it looks like this:
![image](https://user-images.githubusercontent.com/2126677/39240642-6a8d94a8-4852-11e8-8ab7-0da308c9a2c2.png)

Seemed kinda strange. Would love to help out if I can, but not sure how to check what's going on :(.

Full Error:
<details>

```log
C:\Users\<username>\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\typescript\lib\typescript.js:58175
}.call(this, exports, require, module, __filename, __dirname); });
 ^
SyntaxError: Unexpected token .
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\<username>\.vscode\extensions\Angular.ng-template-0.1.9\server\documents.js:3:10)
[Error - 6:22:30 AM] Connection to server got closed. Server will not be restarted.
```

</details>

**Comment by kyliau** [comment]
Closing this, since issue is likely fixed in the latest version. Please reopen otherwise.
