### ISSUE TITLE
Fixed problems persisting until file re-opened

### ISSUE THREAD

**Issue by diminutivesloop** [angular/vscode-ng-language-service#249]
Issue Type: <b>Bug</b>

Frequently when I correct a problem reported by the Angular Language Service extension VSCode will continue to report the problem until the file is closed and re-opened.

Extension version: 0.1.9
VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930MX CPU @ 3.00GHz (8 x 3192)|
|Memory (System)|31.94GB (14.41GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|yes|
|VM|0%|

</details>

**Comment by Amosss** [comment]
Looks like I'm having the same problem using the same extension version and vscode version. Did you solve this problem eventually?

**Comment by diminutivesloop** [comment]
Nope. Still encountering the problem.

**Comment by kyliau** [comment]
This has been fixed in v0.900.0 onwards
