### ISSUE TITLE
Model's object properties set by const literals not detected

### ISSUE THREAD

**Issue by rlexa** [angular/vscode-ng-language-service#250]
When model is an object with properties set by const literals (possible at the very least in Angular 6) the template signals an error because the extension doesn't seem to detect those properties.

Model Type:
```typescript
const KEY_FLAGS = 'flags';
export interface Model {
  id: number;
  [KEY_FLAGS]: number[];
}
```

In Component:
```typescript
@Input() data: Model;
```

In Template:
```html
<label>{{ data.id }}</label>
<label>{{ data.flags }}</label> <!-- this fails -->
```

**Comment by deftomat** [comment]
The same issue even with the simple index types:

```
export interface Model {
  [key: string]: number[];
}
```

**Comment by kyliau** [comment]
This is similar to https://github.com/angular/vscode-ng-language-service/issues/110
Will track progress in that ticket.
