### ISSUE TITLE
[Feature Request] Rename variables in template

### ISSUE THREAD

**Issue by michaeljota** [angular/vscode-ng-language-service#252]
I don't know if this is even something that VS Code could allow, but it would nice if you could refactor variables names in template, either right in the template, or in the component code. Both ways should update each other. 

> some.component.html
```html
Hello {{ world }}
```

> some.component.ts
```ts
...
@Component(
...
)
class SomeComponent {
  world; // <-- rename to `people` should update also in the html template
}
```

Renaming can be triggered with `F2`, and it currently updates any references to that symbol, but references in Angular template.

**Comment by alagane** [comment]
In the same way, using  `Shift` + `F12` to find references from the component code should also show those of the template.

**Comment by ikilinc** [comment]
IntelliJ has this feature too.

**Comment by kresdjan** [comment]
Yeah IntelliJ works, every time all the time. Great product.

**Comment by tomaszs** [comment]
@ikilinc @kresdjan How do your comments refer to the Visual Code extension feature request?

**Comment by ikilinc** [comment]
@tomaszs 

I dont know exactly which part of angular have to implement it so that it works. I thought its the language service.

Perhaps VS Code do not support such kind of editing, it would be cool to see this, also because IntelliJ can this, and best editor in this world dont.

**Comment by ayazhafiz** [comment]
It is the language service’s issue. We are happy to track it here, since many people see issues with the language service by using the extension.

**Comment by michaeljota** [comment]
@ikilinc @kresdjan 

> Intellij is an IDE. This is a text editor. That's like comparing a Chevy and a Mustang because you can take a ride in both.
