### ISSUE TITLE
no syntax highlighting of angular template

### ISSUE THREAD

**Issue by martinjirku** [angular/vscode-ng-language-service#257]
Issue Type: <b>Bug</b>

When I open angular html template, I am not able to see syntax highlighting on my angular template. 
Suggestions/intellisense and emmet seems to work properly.
I've tried to reinstall Visual Studio.

Extension version: 0.1.9
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.49GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

In the `Angular Language Service` Output I see this:
```
Search path: c:/dev/project/client-app/src/app
Config file name: c:/dev/propject/client-app/tsconfig.json
Angular Language Service: 5.2.2-250c8da
TypeScript: 2.6.2
getTemplateReferences: 956ms
Add recursive watcher for: c:/dev/project/client-app
Opened configuration file c:/dev/project/client-app/tsconfig.json
getTemplateReferences: 0ms
getDiagnostics: 50ms
getHoverAt: 6ms
getHoverAt: 7ms
getCompletions: 12ms
getCompletions: 9ms
getHoverAt: 7ms
```

**Comment by jakewtaylor** [comment]
I'm also getting this. Suggestions/linting work fine, but there's no new highlighting for angular syntax.

Any solutions?

**Comment by PhiLhoSoft** [comment]
Same here with v. 0.1.10, VSC v. 1.27.2, on Windows 10.
I opened a template file, everything was displayed in black and white (was OK before installing the extension). I deactivated the extension, the colors went back.

**Comment by mik01aj** [comment]
Same here, using VSC 1.30.0 on Linux.

**Comment by PhiLhoSoft** [comment]
Note: I use the Light+ standard theme, in case it is related to the fact I use a non-dark theme. My colleague installed this extension and has syntax highlighting OK with his dark theme.
I tried again today with v. 0.1.11 and VSCode 1.21.1, still the same issue.

**Comment by spybug** [comment]
I found a temporary workaround to get syntax highlighting working by adding a files.associations option in the VSCode settings. You can add them by going to settings and clicking on the `{}` at the top right.

```   
"files.associations": {
    "*.ng.html": "html"
},
```

**Comment by kyliau** [comment]
This is because the extension used to register `.ng.html` as a special language. Once that's done though, it's no longer associated with regular HTML and hence the missing syntax highlighting. Such language is never needed, and it has been removed.
