### ISSUE TITLE
autocomplete doesnot work for variable with underscore(_) inside interface

### ISSUE THREAD

**Issue by sachinGAcharya** [angular/vscode-ng-language-service#258]
I am using Visual Studio Code for Angular 5 project I have converted my post JSON data into typeScript file like

//interface class of post data
export interface Client {
  ctm_id: number;
  firstname: string;
  middlename: string;
}

//interface class of post data
export interface ClientContact {
  phone: number;
  alternate_phone: number;
}

//interface class of post data
export interface ClientPostData {
  client: Client;
  clientContacts: ClientContact;
  clientMedical_info:Clientmedicalinfo;
}

// and declared in component class like     
export class FormComponent implements OnInit {
  public model: ClientPostData = {};
  public ffirst_name:string;
}
I have installed Angular language service to get suggestions for variables from the interface.

When I type f it suggests firstname in html.but it doesn't suggest clientMedical_info when I type model.(dot).It suggests model.clients and model.clientContacts

How can I get suggestion of client_contact when I type model.(dot)

**Comment by olivermuc** [comment]
I accidentally posted the same issue here: https://github.com/Microsoft/vscode/issues/56077
I case you need another example.

**Comment by olivermuc** [comment]
Could it be related to this line:
https://github.com/angular/vscode-ng-language-service/blob/f0d3e2a48e05f2bca854b2109f11250feed8aa2d/server/src/server.ts#L91

**Comment by olivermuc** [comment]
No updates on this?

**Comment by NitashEU** [comment]
I have the exact same issue.

On the template, the properties with underscore don't get suggested.

**Comment by olivermuc** [comment]
> ..."improve text insertion for attributes"

Well, I guess the intent was to provide some sanity checking to the auto completion logic.
Unfortunately, it appears they went too restrictive.

As I wrote above https://github.com/angular/vscode-ng-language-service/issues/258#issuecomment-412037859 , I tinkered with that expression a bit but really couldn't make it work at all.

Rolling back the entire commit sounds harsh, but if that fixes it (or puts it back in a state that works for us) why not?!

Let me know if there is anything I can help with re: Pull Request - QA / test etc.
I can't own the PR but happy to support this!

**Comment by ednjv** [comment]
Same issue here

**Comment by Meligy** [comment]
> It's really all about commenting out this line:
> 
> [vscode-ng-language-service/server/src/server.ts](https://github.com/angular/vscode-ng-language-service/blob/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3/server/src/server.ts#L97)
> 
> Line 97 in [f5e2317](/angular/vscode-ng-language-service/commit/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3)
> ```ts
>  return TextEdit.replace(range, insertText);
> ```

Based on that file, it might also be correct that the actual fix is removing `_` from:

https://github.com/angular/vscode-ng-language-service/blob/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3/server/src/server.ts#L92

**Comment by olivermuc** [comment]
> > It's really all about commenting out this line:
> > [vscode-ng-language-service/server/src/server.ts](https://github.com/angular/vscode-ng-language-service/blob/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3/server/src/server.ts#L97)
> > Line 97 in [f5e2317](/angular/vscode-ng-language-service/commit/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3)
> > ```ts
> >  return TextEdit.replace(range, insertText);
> > ```
> 
> Based on that file, it might also be correct that the actual fix is removing `_` from:
> 
> [vscode-ng-language-service/server/src/server.ts](https://github.com/angular/vscode-ng-language-service/blob/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3/server/src/server.ts#L92)
> Line 92 in [f5e2317](/angular/vscode-ng-language-service/commit/f5e23171bcfad1d3af55164f9a1ea57f5aa2e0f3)
>  const special = /\(|\)|\[|\]|\*|\-|\_|\./;

It seems like the logical place to make the change, but for whatever reason this did not fix it for me, I tried.

**Comment by myml** [comment]
Same issue here

**Comment by afonsoma9** [comment]
Same issue here

**Comment by jgraffin** [comment]
Same issue here! Any workaround to resolve this?

**Comment by viiskies** [comment]
Same

**Comment by kyliau** [comment]
@ayazhafiz fixed this in https://github.com/angular/angular/pull/33091

For reference, this is how the word boundary was determined before:
https://github.com/angular/vscode-ng-language-service/blob/a9f4440d671600ea32fb300478744dc5ede4c7ed/server/src/server.ts#L90-L107

Starting from v0.900.0, the replacement span is determined by looking at the proper AST.
