### ISSUE TITLE
Add some dependency as official list

### ISSUE THREAD

**Issue by xanscale** [angular/vscode-ng-language-service#260]
hi, i want  to suggest to add some dependency to improve programming experience

a minimal (and updated) list of usefull extention, like:
- formulahendry.auto-close-tag
- formulahendry.auto-rename-tag
- msjsdiag.debugger-for-chrome
- editorconfig.editorconfig
- christian-kohler.path-intellisense
- eg2.tslint

- an icon theme like pkief.material-icon-theme OR robertohuertasm.vscode-icons

- a Css formatter (i don't know who are the best)

**Comment by kyliau** [comment]
Thank you for the suggestion! The Angular team does not want to be in the position to recommend any specific third party extensions, but we could add a document to this repo to keep track of such list instead. Could you please open a pull request? Thank you!
