### ISSUE TITLE
Problems not being detected

### ISSUE THREAD

**Issue by ShaneCourtrille** [angular/vscode-ng-language-service#261]
Issue Type: Bug

I'm seeing the opposite of #249 whereby problems do not appear after I break something.  An easy way to replicate is to remove anything reference in a separate .html template from the .ts component file.  There will not be an error reported.

Extension version: 0.1.9
VS Code version: Code 1.24.1
OS version: Windows 10

**Comment by kyliau** [comment]
This is similar to https://github.com/angular/vscode-ng-language-service/issues/380, will track issue there.
