### ISSUE TITLE
Make the language server process easier to identify 

### ISSUE THREAD

**Issue by egamma** [angular/vscode-ng-language-service#268]
As you can see in the screenshot below it can be difficult to identify a particular language server in the process info. Therefore, please change the file 'server.ts' to a more specific name, e.g. 'ngServer.ts'.

![image](https://user-images.githubusercontent.com/172399/42366553-c0c2d9ae-8101-11e8-8dbb-6131f12a1d2e.png)

**Comment by kyliau** [comment]
We could print the process ID of the server to the editor console.
