### ISSUE TITLE
Can someone tell me how to fix this?

### ISSUE THREAD

**Issue by Alejandro696** [angular/vscode-ng-language-service#269]
C:\Users\Usuario\project>ng generate component footer
Unexpected token ] in JSON at position 794

extra data:
Angular CLI: 6.0.8
Node: 8.11.2
Angular: 6.0.6

**Comment by kqadem** [comment]
You probably have an error in one of your json files (tsconfig, angular, package.json). You may try deleting your package-lock.json (after creating a backup of course).

**Comment by Alejandro696** [comment]
I could fix it,changing the file "angular.json" of the project with another "angular.json" file of a new project.Thanks for the advice!

**Comment by kqadem** [comment]
The JSON's does not allow trailing comma's 😅
