### ISSUE TITLE
The Angular Language Service server crashed

### ISSUE THREAD

**Issue by aitboudad** [angular/vscode-ng-language-service#27]
Hi, I get the following error while editing the file [formly.field.ts](https://github.com/formly-js/ng2-formly/blob/master/src/core/components/formly.field.ts)

```ts
The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

![2016-12-17 19-18](https://cloud.githubusercontent.com/assets/1753742/21289156/ad702370-c48d-11e6-926e-7b15fe6c66c1.gif)

Project url: https://github.com/formly-js/ng2-formly

**Comment by sgruhier** [comment]
Is there any logs we can check ?

**Comment by aitboudad** [comment]
seems that has been fixed, I couldn't reproduce it anymore.
