### ISSUE TITLE
attribute highlighting issue w/ VS Code 1.26

### ISSUE THREAD

**Issue by FelschR** [angular/vscode-ng-language-service#275]
After updating to VS COde 1.26 I noticed that angular attributes are displayed in a single color including their Angular specific characters.
Before these extra characters ([], (), *) used to be highlighted in a different color (white).

Also I noticed that the type "HTML" was recognized for the file. I'm not sure how this was before 1.26 but I guess the "Angular template" file type would've been selected.
Manually switching to that type renders the whole text in the file in white.
So it seems there is something wrong.

I guess this could also be a bug in VS Code 1.26 but I'm not sure so I created the issue here.

**Comment by kyliau** [comment]
We used to register Angular template as a custom file type, but that has since been removed. This should not be an issue anymore. Please reopen the ticket otherwise, thank you!
