### ISSUE TITLE
VSCode Language Service cannot give suggestion for a member of an array.

### ISSUE THREAD

**Issue by psyblade12** [angular/vscode-ng-language-service#277]
I don't know if I config the extension wrong, but it couldn't show any suggestion for a member of an array.

Here, I have an array of heroes named _heroes_, and a variable that stores the hero that the user chooses, named _selectedHero_. The extension gives suggestion for _selectedHero_ variable correctly, but cannot give any suggestion to a member of an array of heroes. (eg: _heroes[0]_)

![untitled2](https://user-images.githubusercontent.com/28593221/44309241-ec30d500-a3ed-11e8-9caf-894cf098ee0a.png)

![untitled](https://user-images.githubusercontent.com/28593221/44309216-775d9b00-a3ed-11e8-8568-6bb651bbcaf3.png)

This code is Tour of Heroes, the official tutorial of Angular 6 from angular.io.
https://angular.io/tutorial

**Comment by rezaeieng1994** [comment]
Did you get any answer or find out any solution?

**Comment by ayazhafiz** [comment]
fixed with https://github.com/ayazhafiz/angular/commit/ec1fa59629bdbfcebd0223694e0cb5af4e2bb984
