### ISSUE TITLE
plugin with 0.10.beta can run on linux but not on windows

### ISSUE THREAD

**Issue by wszgrcy** [angular/vscode-ng-language-service#280]
I git the source and complie on linux(deepin),then the vscode on linux can hint property and events.
Then on win10. I uninstall all plugins and install this.but can not work.
What message or log can I report if you need,please tell me.
Thanks .
--------------  
- The release version 0.1.10 also can't work on win10
- I only install this plugin but can't work
--------

VS Code version: Code - Insiders 1.27.0-insider (3f8088b5c5f1d44b5e1af4a8e67448abbe66470e, 2018-08-27T07:36:47.732Z)
OS version: Windows_NT x64 10.0.15063

CPUs | Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8 x 2295)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.88GB (10.46GB free)
Process Argv | C:\Users\chen\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
ng-template | Ang | 0.1.10-beta
vscode-language-pack-zh-hans | MS- | 1.27.0

**Comment by kyliau** [comment]
What is the version of Node.js that you were using?

**Comment by wszgrcy** [comment]
@kyliau 
node v8.9.4
npm v6.4.0
ng

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.5
Node: 8.9.4
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.5
@angular-devkit/core         0.7.5
@angular-devkit/schematics   0.7.5
@schematics/angular          0.7.5
@schematics/update           0.7.5
rxjs                         6.2.2
typescript                   2.9.2

**Comment by kyliau** [comment]
I tested it on WIndows and it seemed to work fine. I've also published the new version to VSCode Marketplace. Please download it and try your project again.

**Comment by wszgrcy** [comment]
@kyliau I try on win7(another pc) and it work .but win10(my system or all system?) ,maybe I should add some debug message on source and see Web Console

**Comment by kyliau** [comment]
Closing this since issue looks like it's fixed. Please open a new issue otherwise, thank you!
