### ISSUE TITLE
Excluded files in tsconfig should not get NgModule declaration errors

### ISSUE THREAD

**Issue by PooSham** [angular/vscode-ng-language-service#285]
In my tsconfig.json I have excluded folders called 'testing' by adding this line: 
> ` "exclude": ["**/testing/*"]`

In some of these files, I have helper directives and components that I use in spec-files. The project compiles just fine, but the vscode language service mark some files red because the directives and components aren't declared in app.module.ts. I get the following error:

> Directive 'MyStubDirective' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration

Is there a way I can make the language service ignore these errors? If not, I have some ideas. Ideally, the extension shouldn't give these errors on files that are excluded from the app. I realize this can cause some issues such as not knowing which tsconfig-file to use, but maybe there could be extension options? Or it could try to be smart and select the tsconfig with the most appropriate name (such as tsconfig.app.json rather than tsconfig.spec.json) or even look in webpack.config.js if present.

**Comment by kyliau** [comment]
In your test file, please make sure that test components are not exported. It should remove the error.
We will also look at https://github.com/angular/vscode-ng-language-service/issues/308 to let users disable certain category of errors.

**Comment by kyliau** [comment]
Please see https://github.com/angular/vscode-ng-language-service/issues/308#issuecomment-550213532
