### ISSUE TITLE
tamplate from

### ISSUE THREAD

**Issue by Mallesh25nayak** [angular/vscode-ng-language-service#286]
i `tried` this code but not getting expected output
` <div *ngIf="firstName.errors.required">First Name is required.
          <div *ngIf="firstName.errors.minlength">First Name should be minimum 3 character.</div>
          <div *ngIf="firstName.errors.pattern">First Name doesn't Match pattern.</div>
         </div>
      `

**Comment by kyliau** [comment]
Could you please clarify what do you mean by "expected output"?
Do you expect to see diagnostics errors?
Please reopen issue with more info.
