### ISSUE TITLE
Angular 6 library build fails

### ISSUE THREAD

**Issue by s-albert** [angular/vscode-ng-language-service#287]
I had to remove this extension from my extension pack, because angular 6 library builds fail like that: 
If I rebuild it without changes the build is successful. We have that behavior in all angular library projects.

ng build --prod ngx-common-utilities

>>>>>>>>>
..................
Building Angular Package

BUILD ERROR
EPERM: operation not permitted, unlink 'c:\Data\repos\Angular\ngx-common-utilities\dist\ngx-common-utilities\lib\versioninfo'
Error: EPERM: operation not permitted, unlink 'c:\Data\repos\Angular\ngx-common-utilities\dist\ngx-common-utilities\lib\versioninfo'

EPERM: operation not permitted, unlink 'c:\Data\repos\Angular\ngx-common-utilities\dist\ngx-common-utilities\lib\versioninfo'
Error: EPERM: operation not permitted, unlink 'c:\Data\repos\Angular\ngx-common-utilities\dist\ngx-common-utilities\lib\versioninfo'
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by shairez** [comment]
related to #224

**Comment by kyliau** [comment]
Will track this in https://github.com/angular/vscode-ng-language-service/issues/224
