### ISSUE TITLE
Feature request: Get references in template (getReferencesAtPosition)

### ISSUE THREAD

**Issue by kukjevov** [angular/vscode-ng-language-service#29]
Hi,

as for now you can navigate to source by ctrl+click, or peek definition, but if you use find all usages template occurencies on methods or properties are not in result window.

This would be awesome, but i`m not sure that this is possible to do in VsCode, but it would be nice :). Especially while refactoring code, since right now this occurencies can be forgotten or must be string searched.

Thank you

**Comment by simonnagl** [comment]
This would also enabling symbols in templates (i.e. using F2)

**Comment by przemo098** [comment]
Someone is doing something with this?!

**Comment by EylonSu** [comment]
anything new?

**Comment by ayazhafiz** [comment]
We should be able to implement this by adding [`getReferencesAtPosition`](https://github.com/microsoft/TypeScript/blob/7f004ad8dfd4d3aa047173a890c0beaeb8a307de/lib/tsserverlibrary.d.ts#L4929) to the Language Service's [TypeScript plugin](https://github.com/angular/angular/blob/master/packages/language-service/src/ts_plugin.ts). However, we will probably hold off on doing this until the language service is rewritten to use Angular's new Ivy compiler, which will make it easier to extract the class properties used in a template.

<sub>(note: perhaps we can use the Angular indexing API or similar for this)</sub>

**Comment by abdulkareemnalband** [comment]
@kukjevov @kyliau Can you update title and content of this issue
many people are creating duplicates as this is not visible in search

Suggestion: Find property references in template from typescript

**Comment by kukjevov** [comment]
It had different name *Feature request: Find usages shows also occurencies in templates* as you can see but it was changed by @kyliau 

So you have to make agreement with him :).

**Comment by Niaro** [comment]
4 years?) I wonder how WebStorm got this faster than VScode O_o

**Comment by furmandev** [comment]
This would be a great feature. Is there any timeline or priority on this? I think this issue also relates to #252

**Comment by kyliau** [comment]
We hear you! @ayazhafiz and I are thinking about ways to support this in Angular language service. @ayazhafiz already has a PR ready that partially* supports this feature.
We're currently looking into the best way to introduce get references without adding too much overhead, since much of this code will not be reused once we switch the backend to Ivy.

Re partial support:
References from template can be easily retrieved, whereas references from TS (for example a field in a class) is more difficult because we need to check the template. The former is what Ayaz's PR is for.

**Comment by webia1** [comment]
I would be very thankful for every process.

**Comment by Harpush** [comment]
Any news on this? Seems the PR wasn't merged

**Comment by Exomus** [comment]
Really excited about this feature, is there any news about it ?
Very painful to track down broken reference in the template while renaming the symbol in the typescript file.

**Comment by kyliau** [comment]
We are going to launch Ivy version of the language service in version 11 (November 2020). Once it's achieve feature parity with the existing View Engine language service, we'll prioritize this feature! Switching to the Ivy backend enables us to implement features like this one, which was almost impossible previously.

**Comment by atscott** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
It's an opt-in feature for now, please give it a try and let us know if you have any feedback.
For the best editor experience, please make sure your project has [`strictTemplates`](https://angular.io/guide/angular-compiler-options#stricttemplates) enabled in `angularCompilerOptions`.
In case you run into similar bug, please file a new issue. I'll close this for now.

**Comment by ic3guy** [comment]
Should we be seeing the correct # of references via CodeLens too? Because Ctrl-Click / Find all References does work, but codelens references and a click on it does not show template refs. I'm assuming that CodeLens pulls these refs from somewhere else, or am I missing a config flag somewhere?

**Comment by atscott** [comment]
> Should we be seeing the correct # of references via CodeLens too?

Great question! It looks like there's [additional configuration](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#codelens-show-actionable-context-information-within-source-code) needed on our end for integrating with CodeLens. Could you open a new issue for this?

**Comment by kukjevov** [comment]
@atscott @ic3guy Guys am I missing something, or is there something weird with configuration of project :)? Because i tried it in my own project and it does not work, I even tried latest version of Angular cli, generated new project, there is `title` property, but if i use find all references, reference from template is not displayed? Am I missing something :D ?

Thx

**Comment by kukjevov** [comment]
@atscott hmmm i looked at it and i found out, that it needs to be turned on, but if i turn it on, it keeps crashing and restarting, should i open new *issue* or paste it here :) ?

**Comment by atscott** [comment]
> @atscott hmmm i have looked at it and i found out, that it needs to be turned on, but if i turn it on, it keeps crashing and restarting, should i open new _issue_ or paste it here :) ?

@kukjevov yes, please submit a new issue for this.

**Comment by erosostolato** [comment]
Hey guys, I couldn't get it to work. What do I need to do? Do I need to enable any option?

**Comment by kukjevov** [comment]
@erosostolato if you have installed language server and vscode extensions for angular then in user preferences you can find Angular: Experimental-ivy, if you enable it it should start working, in my case it is crashing, i need to create new issue for it

**Comment by erosostolato** [comment]
@kukjevov 

The only thing that I can do is renaming a template variable like this:
![image](https://user-images.githubusercontent.com/75269233/109512641-0fd73a80-7a83-11eb-9a65-4d1da0aa8946.png)

But if I try to rename it directly in the interface, it doesn't work... it doesn't even show the reference count
![image](https://user-images.githubusercontent.com/75269233/109512896-50cf4f00-7a83-11eb-846f-47b3dad2e6f8.png)

This is my settings:
![image](https://user-images.githubusercontent.com/75269233/109513037-76f4ef00-7a83-11eb-9a5c-e3792b722601.png)

**Comment by kukjevov** [comment]
If i saw it correctly, what should be working so far is only getting correct number of references in templates :), renaming is feature that i saw in Angular 12 beta.0 so it is not working, because it is still not there :), but it should be soon :).

**Comment by kukjevov** [comment]
Codelens also needs some work, so only find all references should be working, but still there is some problem in my project because if i turn it on, it crashes :).

**Comment by atscott** [comment]
FYI - renaming for Angular is only available in external templates. There is now way to ensure that the Angular extension is used in TypeScript files so we opted to disable it there. See https://github.com/microsoft/vscode/issues/115354. If you would like this feature, it could be worth upvoting the vscode issue so it gets prioritized sooner.

**Comment by erosostolato** [comment]
@kukjevov you're right, I saw it working for find all references.

@atscott got it! I already upvoted

**Comment by atscott** [comment]
> Codelens also needs some work, so only find all references should be working. 

In reference to Codelens, there is no way to augment those results with ours. We can consider providing our own, separate lens in addition to the typescript one that could say something like “# references in templates” but we can’t include our results in the same one that’s already there.

**Comment by erosostolato** [comment]
> > Codelens also needs some work, so only find all references should be working.
> 
> In reference to Codelens, there is no way to augment those results with ours. We can consider providing our own, separate lens in addition to the typescript one that could say something like “# references in templates” but we can’t include our results in the same one that’s already there.

I liked the idea of having “# references in templates”
