### ISSUE TITLE
Extension hangs on installing.

### ISSUE THREAD

**Issue by Domvel** [angular/vscode-ng-language-service#290]
This extention hangs on installing. This is the only extension that does not work anymore.
I click on `Install` and then the status hangs on `installing` for ever.
I also removed the folder from `C:\Users\<username>\.vscode\extensions\` (`.angular.ng-template-<version>`) but nothing helped. - I see no output / error log. It just hangs on installing.

Extension Version: 0.1.10

Version: 1.27.1 (system setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by ironicnet** [comment]
I still have the same error. here is what appears in the logs: 
```
[2019-01-09 13:22:58.805] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-01-09 13:22:58.805] [exthost] [error] TypeError: Cannot read property 'displayParts' of undefined
	at w.resolveCompletionItem (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:99172)
	at <anonymous>

```
I don't know if there is a debug mode to have more info

**Comment by Domvel** [comment]
For me it works again. Idk what the problem was. Sometimes an installation of VS Code extensions need a lot of time. In this case here, the installation really failed. I waited for hours. But currently it works well.

**Comment by kyliau** [comment]
The extension that was shown in your logs, `typescript-language-features`, is the native vscode extension for Typescript, it is not Angular language service.
