### ISSUE TITLE
wrong error when checking derived class members

### ISSUE THREAD

**Issue by LeonardoX77** [angular/vscode-ng-language-service#291]
Hi
I get an error (problem) working with an Angular2 project:

[Angular] Identifier 'myService' refers to a private member of the component

Scenario:
I have a derived service class which inherits from a base class with a public method. So the error is detected when I declare this in a html file:

<myComponent [show]="myService.loading()"></myComponent>

It seems Angular Language Service can't reach base class method, despite this method is declared as public.

Cheers!!

**Comment by kyliau** [comment]
@LeonardoX77 I was unable to reproduce the error. Could you please show the TypeScript code in the example you gave?

**Comment by kyliau** [comment]
I created the test case below, but it did not produce any error, could someone please point out what I missed?

```typescript
  it('should not produce errors on members and methods of base class', () => {
    mockHost.override(APP_COMPONENT, `
      import {Component} from '@angular/core';

      class BaseComponent {
        protected readonly baseProperty = 'foo';
        baseMethod() { return 'base'; }
      }

      @Component({
        template: \`
          <div [id]="baseProperty" (click)="baseMethod()">
           {{ baseProperty }}
           {{ baseMethod() }}
           {{ derivedProperty }}
           {{ derivedMethod() }}
          </div>
        \`
      })
      export class AppComponent extends BaseComponent {
        derivedProperty = 'bar';
        derivedMethod() { return 'derived'; }
      }
    `);
    const tsDiags = tsLS.getSemanticDiagnostics(APP_COMPONENT);
    expect(tsDiags.length).toBe(0);
    const ngDiags = ngLS.getDiagnostics(APP_COMPONENT);
    expect(ngDiags.length).toBe(0);
  });
```

**Comment by SteffenKoehler** [comment]
I think it might be related to the service being declared private in the constructor. 

Public
![basePublic](https://user-images.githubusercontent.com/9463791/69629228-64079980-104c-11ea-9907-846fbfd408f2.png)

Private
![basePrivate](https://user-images.githubusercontent.com/9463791/69629264-68cc4d80-104c-11ea-85c4-b8823a56bd19.png)

**Comment by kyliau** [comment]
@SteffenKoehler Thank you for the clarification.
In this case, the language service is working as intended. 
Private fields (whether in the current class or parent classes) are not visible in template.

**Comment by kyliau** [comment]
I'll mark this issue as closed for now.
