### ISSUE TITLE
Template reference without assignation should throw

### ISSUE THREAD

**Issue by michaeljota** [angular/vscode-ng-language-service#293]
Currently, if you have a template reference without an assignation is a runtime error: `Error: Failed to execute 'setAttribute' on 'Element': '#' is not a valid attribute name.`. This should be considered as a non intentional typo from the developer, and such, it should be throw as a static error by the language service. 

[Repo](https://stackblitz.com/edit/angular-template-reference-unassigned)

**Comment by ayazhafiz** [comment]
this should be a compile-time error, no? @kyliau @alxhub
