### ISSUE TITLE
Support optional chaining in template

### ISSUE THREAD

**Issue by IMM9O** [angular/vscode-ng-language-service#296]
I use reactive form i create a method called displyFiledError it take filed name and return ValidationErrors so i can access it in template but i got an error

> [Angular] Identifier 'email' is not defined. '__type' does not contain such a member

![fun](https://user-images.githubusercontent.com/11165508/47615670-6189e780-daba-11e8-9ed8-b51cf50dc68e.JPG)
![html](https://user-images.githubusercontent.com/11165508/47615671-6189e780-daba-11e8-8f0b-3ca4cbd828cc.JPG)

even in typescript there is no suggestions but no error in run type

**Comment by Shoizz** [comment]
As an addition to this. 
![image](https://user-images.githubusercontent.com/944858/47987196-a2e84b80-e0e7-11e8-8ea7-eaa97929daef.png)
![image](https://user-images.githubusercontent.com/944858/47987231-b09dd100-e0e7-11e8-8a4f-b516798b0f55.png)

**Comment by andreiucm** [comment]
I have the same issue using reactive forms

**Comment by gaikwadvaibhav** [comment]
I have the same issue using angular 6 reactive forms validation.

![untitled](https://user-images.githubusercontent.com/20417649/50966074-d4bbcb00-14f9-11e9-9118-899b701285ed.png)

**Comment by khashashin** [comment]
same here. 
![image](https://user-images.githubusercontent.com/17837758/51347623-ee808380-1aa0-11e9-9872-fbdfed6021da.png)

VSCode version:
```
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```

It can be solved by adding `!!` like in example below, before expression, but in my case I don't need `true` or `false` as return statement

![image](https://user-images.githubusercontent.com/17837758/51347934-b3328480-1aa1-11e9-8d56-38184f9a9d92.png)

**Comment by kyliau** [comment]
This is similar to https://github.com/angular/vscode-ng-language-service/issues/149, will track issue there.
