### ISSUE TITLE
Status of this extension

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/vscode-ng-language-service#298]
@kyliau @StephenFluin I would like to know the status of this extension, as it doesn't seem actively maintained anymore, while it's a major VS Code extension to have a good Angular development experience.

As an Angular trainer, I teach courses in many different companies with different hardwares (from very good to very bad), so here is some feedback.

Previously:
- the extension was (quite) reliable on computers with good hardware,
- but it was really messy on computers with bad hardware.

It is mainly because of the process checking if components are declared: as the CLI creates files on the fly, the extension has to refresh the whole project to know a new component is indeed declared in a `NgModule`. But it can take a really long time when the hardware is bad, and often it even doesn't work at all until a full restart of VS Code.

Restart of VS Code = you also need to launch `ng serve` again, which is also very slow on bad hardware, resulting in a very bad overall dev experience. For beginners, it's really bad: each time they create a new component, the extension reports errors which are not really errors, and students are completely confused.

But from a few weeks, the extension is now also unreliable on computers with good hardware. I suppose it's because the extension has not been updated for Angular 7 and TypeScript 3.1.

The course I'm teaching this week has been really disturbed by these issues.

Also, compared to React JSX, this extension was the answer for Angular to have (quite) the same level of assistance and validation. So it's very important, and if it's not maintained anymore, it would be a huge step back.

**Comment by cyrilletuzi** [comment]
Additional question: is something similar to the new [TypeScript TSLint plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) planned?

It allows to not have duplications of the TypeScript process (as mentioned in the README of this repo but still not resolved), and would help a lot on bad hardware.

**Comment by kyliau** [comment]
@cyrilletuzi thank you for the feedback.
The extension was originally authored by @chuckjaz. Since Chuck moved on to another team, the development of this work has been deprioritized. 
We do have plans to release a new version, but it's currently pending the release of Ivy. That's because with Ivy, there'll be a significant change (namely metadata.json will no longer be generated) that would fundamentally change how the language service works. For the next version, we'll also convert the tool to be a Typescript plugin, as you mentioned.
Meanwhile, I'll take a look at upgrading the current implementation to support Angular 7 and Typescript 3.1

**Comment by dylanvdmerwe** [comment]
Ivy is only coming around Angular 8 time frame. There are many maintenance issues that still should be addressed in the mean time - this is a major plugin for many angular developers in a very popular cross platform editor and it being deprioritized is really not great news.

**Comment by cyrilletuzi** [comment]
@kyliau Thanks for the answser.

@dylanvdmerwe I've got an idea, I'll release it in a few days and post an update here.

**Comment by cyrilletuzi** [comment]
For everyone who wants an efficient and up to date Angular Language Service in VS Code:
[https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.typescript-angular-plugin](https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.typescript-angular-plugin) 👍

**Comment by Shoizz** [comment]
@cyrilletuzi Installed. Will give it a battle test immediately.

**Comment by cyrilletuzi** [comment]
Closing this as the extension has been updated.
