### ISSUE TITLE
Non-null check in ngIf not respected for variables

### ISSUE THREAD

**Issue by inmogr** [angular/vscode-ng-language-service#301]
I'm using VSCode version 1.29.1 and Angular CLI version 7.0.4
I have the following issue

In my typescript component file I have declared an object as the following
```
object: Type | undefined
```

In my HTML I wanted to use that object as the following
```
<div *ngIf="object">
	{{ object.someField }}
</div>
```

but I'm having error highlights with the following message
```
[Angular] The expression might be null
```

**Comment by kyliau** [comment]
Closing this, @andrius-pra fixed this in https://github.com/angular/angular/pull/33016

**Comment by Maistho** [comment]
This issue still appears for me, using Angular 9. Using the latest version of the angular.ng-template extension. Can this issue be reopened?

**Comment by kyliau** [comment]
This is fixed by https://github.com/angular/angular/pull/35200
