### ISSUE TITLE
newest release breaks intellisense. 

### ISSUE THREAD

**Issue by matrosovas** [angular/vscode-ng-language-service#304]
0.1.11 broke intellisense and added ~1-2+second lag to it in typescript and html files. After reverting to 0.1.10 it works as expected.

**Comment by ic3guy** [comment]
I too was having issues with the newest version, but what is nice is that the newest version of VSCode now allows you to install older versions of packages.

**Comment by Alucard1766** [comment]
for me the downgrade did not improve performance.

**Comment by abannsunny** [comment]
intellisense takes a long of time to come up with the list of recommendations. 

Reverting back to the previous version seems to help.

**Comment by nhustak** [comment]
This is still am a major issue and even 1.1.10 is now incredibly slow.    It's like it never pre-loads it anymore.

**Comment by nhustak** [comment]
Today it spent almost 45s with the little thing at the top making its circuit before I gave up.

**Comment by nhustak** [comment]
In case this helps, here's an Angular Language Service Dump.  FYI, this is running off an SSD with 16 gig of ram.  

Search path: c:/ProjDotNet/suretax-site/src/app/payment/batch-payment
Config file name: c:/ProjDotNet/suretax-site/tsconfig.json
Angular Language Service: 7.2.6
TypeScript: 3.1.6
getTemplateReferences: 34830ms
Add recursive watcher for: c:/ProjDotNet/suretax-site
Opened configuration file c:/ProjDotNet/suretax-site/tsconfig.json
Search path: c:/ProjDotNet/suretax-site/src/app/models/view
Config file name: c:/ProjDotNet/suretax-site/tsconfig.json
getTemplateReferences: 0ms
Search path: c:/ProjDotNet/suretax-site/src/app/payment/batch-payment
Config file name: c:/ProjDotNet/suretax-site/tsconfig.json
getTemplateReferences: 0ms
getTemplateReferences: 0ms
getHoverAt: 1ms
getCompletions: 161ms
getCompletions: 0ms
getCompletions: 9162ms
getDiagnostics: 193ms
updating project structure from ...

and on the same line, trying to get intellisense for a property on an object

getCompletions: 8701ms
getDiagnostics: 151ms
updating project structure from ...
getTemplateReferences: 122ms
updated: ng - 0ms
getCompletions: 121ms
getCompletions: 0ms
getDiagnostics: 118ms
updating project structure from ...
getTemplateReferences: 90ms
updated: ng - 0ms
getDiagnostics: 7912ms
updating project structure from ...
getTemplateReferences: 96ms
updated: ng - 0ms
getCompletions: 113ms
getCompletions: 8846ms
getDiagnostics: 184ms
updating project structure from ...
getTemplateReferences: 136ms
updated: ng - 0ms
getCompletions: 110ms
getDiagnostics: 132ms
updating project structure from ...
getTemplateReferences: 91ms
updated: ng - 0ms
getCompletions: 8412ms
getDiagnostics: 115ms
updating project structure from ...
getTemplateReferences: 87ms
updated: ng - 0ms
getCompletions: 144ms
getDiagnostics: 154ms
updating project structure from ...
getTemplateReferences: 162ms
updated: ng - 0ms
getHoverAt: 0ms
getCompletions: 7847ms
getDiagnostics: 122ms
updating project structure from ...
getTemplateReferences: 127ms
updated: ng - 0ms
getCompletions: 123ms
getDiagnostics: 110ms
updating project structure from ...
getTemplateReferences: 93ms
updated: ng - 0ms

**Comment by acidduckling** [comment]
This is a bit frustrating - it's been busted for months now. For me, installing a previous version doesn't fix the issue. It can take over 20 seconds for intellisense suggestions to appear, and I have to manually trigger with ctrl+space.

If I disable the extension, suggestions appear instantly.

So for now, I am going to completely disable the extension. I really hope someone can address this - I found it invaluable when it was working!

**Comment by nhustak** [comment]
@acidduckling Yep, I disabled it a couple of months ago so that at least regular typescript intellisense works.  It pretty frustrating after having it to begin with - as you said, it's very very nice when it works.  I'm really taken aback at the way the Angular team is ignoring this issue.   It's seems a bit insane to ignore one of the top editors out there not to mention..well just flat out ignore the multiple threads.  I mean, I get it...busy...but this seems pretty important.

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/issues/329
- https://github.com/angular/angular/issues/27904
