### ISSUE TITLE
Not working when specifying paths in conofig.ts 

### ISSUE THREAD

**Issue by yantrab** [angular/vscode-ng-language-service#305]
Hi, when i add path to tsconfig.json file, the service stop working.
  ```
  "paths": {
      "jszip": [
        "node_modules/jszip/dist/jszip.min.js"
      ],
      "shared/*": [
        "../shared/*"
      ],
      "api/*": [
        "src/app/api/*"
      ],
    }
```

**Comment by oktav777** [comment]
@yantrab that's an invalid `JSON`, you have a trailing comma.

Replace 
```json
...
    "api/*": [
      "src/app/api/*"
    ],
...
```
with
```json
...
    "api/*": [
      "src/app/api/*"
    ]
...
```
Notice the coma after closing array's square bracket.

Hope this helps!

**Comment by manuelreina** [comment]
Aargh, I didn't spot it  :-(
Thanks @oktav777
Removing the comma worked for me

**Comment by kyliau** [comment]
Closing this, since it is already fixed in https://github.com/angular/vscode-ng-language-service/pull/346
