### ISSUE TITLE
Resolve component's properties and methods inside PUG Angular templates

### ISSUE THREAD

**Issue by Rush** [angular/vscode-ng-language-service#306]
I got the idea from a bug report I found on the Webstorm bug tracker - -https://youtrack.jetbrains.com/issue/WEB-35848 - it seems this feature works fine in the latest version of Webstorm

The feature request is simple - when editing PUG templates VS Code should provide validation for component names, component attributes the same as it works for HTML templates. 

I originally posted it at https://github.com/Microsoft/vscode/issues/65521
Related ticket I found https://github.com/angular/vscode-ng-language-service/issues/34 (unfortunately closed)

**Comment by kyliau** [comment]
The Angular language service uses a HTML parser, so unfortunately it does not support Pug.

**Comment by initplatform** [comment]
So that would be a feature request, no? I would like to see this support pug as well.
