### ISSUE TITLE
Visual Studio Code 1.30.1

### ISSUE THREAD

**Issue by MarcOne68** [angular/vscode-ng-language-service#307]
I have installed Visual Studio Code 1.30.1 and Angular Language Service extension 0.1.11. I'm working with Angular 7.1.4 and the extension doesn't work.

**Comment by HybridFox** [comment]
Same issue here on 1.30.2, i have tried to check th econsole but have found no errors etc.

**Comment by oktav777** [comment]
Check your output carefully!

- Open your `Terminal` in `vscode`
- Go to `OUTPUT`
- In the dropdown select `Angular Language Service` - that's the logging for extension

If you see an error like:
```
SERVER ERROR: Unexpected token } in JSON at position xxx
``` 
That's probably a problem with your `tsconfig.json`.
Try to `JSON.parse` your `tsconfig.json` and find what's wrong.
My problem was a trailing comma. After fixing this extension is working properly now!

**Comment by zhengbli** [comment]
1.30.2 on linux.
the plugin doesn't work for me on a new ng cli generated project.

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/issues/329
- https://github.com/angular/angular/issues/27904
