### ISSUE TITLE
Version shows up incorrectly

### ISSUE THREAD

**Issue by johnpapa** [angular/vscode-ng-language-service#31]
I installed 0.0.11 and it shows up as 0.0.10. See below

![image](https://cloud.githubusercontent.com/assets/1202528/21391053/e3188c52-c757-11e6-9f54-dc7243780820.png)

I used this link [0.0.11 Experimental Release](https://github.com/angular/vscode-ng-language-service/releases/tag/0.0.11)

**Comment by chuckjaz** [comment]
This is fixed for 0.0.12
