### ISSUE TITLE
Permissions issue blocks switching branches

### ISSUE THREAD

**Issue by Ksan8** [angular/vscode-ng-language-service#310]
_NOTE:  Disabling this extension provides normal expected behavior_

I have a bizarre thing happening with VS Code and SourceTree, that was only fixed by disabling the Angular Language Service extension:

1. I commit something on a branch, then have a clean working directory
2. I try to switch to a different branch, but get a permissions error (below)
3. After I close the error, I'm able to then switch branches without the error

![als error](https://user-images.githubusercontent.com/20333203/52021765-20cfaf00-24ab-11e9-8aa4-73185fa0ffa9.PNG)

Also, this happens _only_ if I have a file open in the VS Code editor panel. If all files are closed (but a project folder loaded), I don't get the error when switching branches.

Other notes:
- the error message includes files that exist on the branch I'm trying to switch to (but not on the one I'm switching from)
- the same error is duplicated if I use a terminal
- Windows 10 Pro
- VS Code version: 1.30.2

A possibly related issue is that the file paths don't seem to be recognized by VS Code when I switch branches:

![path errors](https://user-images.githubusercontent.com/20333203/52022424-ace2d600-24ad-11e9-82f2-6c62febf867b.PNG)

Thanks in advance for your help! For the time being, I've simply disabled Angular Language Service, but I thought you'd like to know that this bug may be preventing some users from making use of this extension.

**Comment by kyliau** [comment]
The root cause of this is due to https://github.com/angular/vscode-ng-language-service/issues/224. Will use that ticket to track this issue.
