### ISSUE TITLE
Extension crashes on VSCode 1.31.0

### ISSUE THREAD

**Issue by JacobMillward** [angular/vscode-ng-language-service#312]
As of VSCode 1.31.0 (January 2019) the extension crashes on use.

The error:
```
internal/process/next_tick.js:63
          Reflect.apply(callback, undefined, tock.args);
                  ^

TypeError: Reflect.apply is not a function
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Nemesis19** [comment]
I encounter this problem too

**Comment by andrews-phoenix** [comment]
I have the same problem :(

**Comment by Bbaale15** [comment]
Same issue here. I have decided to use an older stable version for now. You might want to turn off automatic updates as well.

**Comment by randallmeeker** [comment]
@Bbaale15 when you say "older stable version" are you referring to this extension or VSCode? thanks

**Comment by Bbaale15** [comment]
@randallmeeker I am referring to VSCode.

**Comment by briansg** [comment]
Same issue after 1.31 upgrade.

**Comment by Nemesis19** [comment]
Vscode version 1.31.1 has the same issue as 1.31.0

**Comment by Nemesis19** [comment]
Tested 1.31.1 on 2 projects: 1 in Angular 6 and 1 in angular 5, in Angular 6 no issues, the crash happens on Angular 5 projects.
Can anyone report if it's the same situation?
Thanks

**Comment by blopez2010** [comment]
@Nemesis19 That is not true, I'm having same issue in Angular 6 version:

```
Angular CLI: 6.0.7
Node: 9.10.1
OS: darwin x64
Angular: 6.0.3
```

**Comment by Nemesis19** [comment]
I have a colleague working on angular 6 and 7 projects. No issue at all. 
I tried to disable one by one the extensions, the crashes happen even if Angular language service is the lone installed.

I'm on MacOS 10.13.6, node 11.9

**Comment by OmniAndy** [comment]
Same here

**Comment by scorbin** [comment]
same here
mac 10.13.6 node 11.9

**Comment by otecMuxah** [comment]
if i delete node_modules folder - bug is gone

**Comment by Nemesis19** [comment]
@otecMuxah tried that, doesn't work unfortunately on Angular 5 projects, maybe on other versions?

**Comment by alecgorge** [comment]
Downgrading to 1.30.2 was the only thing that worked for me on Angular 6

**Comment by v1per** [comment]
I believe we should move to this extension https://github.com/angular/vscode-ng-language-service/issues/298#issuecomment-439100085

**Comment by melgish** [comment]
From what I can tell the vscode extension is built to use 7.1.x but actually uses the whatever version is found in your project.  

I see the crash for our angular 5 projects created with nx (using LS 5.2.7).   Running `npm install @angular/language-service@7.1.x` in that project stops it from crashing, and seems to work correctly.

I haven't run enough to know if there will be other problems, but it looks promising.

**Comment by briansg** [comment]
> I believe we should move to this extension [#298 (comment)](https://github.com/angular/vscode-ng-language-service/issues/298#issuecomment-439100085)

@v1per Looks good but it's not suitable for everyone, keep in mind that it only supports inline templates at this time.

**Comment by jagdishjadeja** [comment]
i am having same issue with 
macos mojave - 10.14.1
vscode  1.31.1 (1.31.1) - 1b8e8302e405050205e69b59abb3559592bb9e60

**Comment by hariharan618** [comment]
Same issue here as well 

Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by melgish** [comment]
see: https://github.com/angular/angular/issues/21420  From what I can tell the fix wouldn't be in any version before 6.0.8.  I tested by installing latest 6.1.x and it worked for me.

**Comment by Nemesis19** [comment]
Updated language service package as said by @melgish and it works for me too!

**Comment by OmniAndy** [comment]
running this worked for me as well:
`npm install @angular/language-service@7.1.x`

**Comment by tonysamperi** [comment]
thanks @melgish

**Comment by nhustak** [comment]
I'm on @angular/language-service 7.2.8 and it and it still is silly slow.

**Comment by csongebalazs** [comment]
We used @angular/language-service": "6.0.6", 6.0.8 CLI and typescript 2.7.2. After vscode 1.31 released, this problem appears. Same issue with 1.32.3.

Based on this topic, downgrading to vscode 1.30 version was a temp solution. But freezing the version of the developer tool seems not fine in a long term future.

Via **melgish**'s comment, we changed to the language-service 6.1.10 and CLI 6.2.9 (typescript did not changed), we deleted node_modules and made a new npm install, then we updated vscode version to 1.32.3. This resulted a working dev environment, and the product still worked fine. If major angular version change is not possible in the given project, this minor version change can help. 

Just for "fun", we upgraded to anguage-service 7.2.8, to 7.3.5 CLI and to 3.1.6 typecsript. After this, dev environment remains fine, but we had to made some code correction beacuse of the mayor angular version change. After these fixes, product still seems ok.

**Comment by dcanning** [comment]
> Just for "fun", we upgraded to anguage-service 7.2.8, to 7.3.5 CLI and to 3.1.6 typecsript. After this, dev environment remains fine, but we had to made some code correction beacuse of the mayor angular version change. After these fixes, product still seems ok.

I'm not sold on your definition of "fun" :-)

**Comment by datasinfo** [comment]
> running this worked for me as well:
> `npm install @angular/language-service@7.1.x`

This worked for me! thanks

**Comment by kyliau** [comment]
Closing this, since the issue has been fixed. Please reopen otherwise.
