### ISSUE TITLE
Publish language server as separate npm package

### ISSUE THREAD

**Issue by mickaelistria** [angular/vscode-ng-language-service#317]
The language server is independent of VSCode and could be reused by other IDEs. To make it easier and more likely for the LS to get mainstream to many IDEs, it'd be great to publish the LS module as a dedicated module on npmjs.

**Comment by kyliau** [comment]
@mickaelistria  Is @angular/language-service sufficient for your purpose? If not, could you please let me know what's missing from the package?
https://www.npmjs.com/package/@angular/language-service

**Comment by mickaelistria** [comment]
Yes, we managed to get the @angular/languag-service plugin working with the typescript-language-server we're using. However, we're facing a glitch that makes it pollute non-angular HTML files as it tries to parse them as TypeScript files (see https://github.com/theia-ide/typescript-language-server/issues/104 ). As neither the IDE nor the language server are supposed to know how to make the difference between HTML files with or without Angular, it's not something that can/should easily be fixed downstream.
Hence why I am wondering about this LS. Is it working better for HTML files?

**Comment by kyliau** [comment]
That's the exact issue I'm tackling right now. Moving forward the Angular language service will no longer be a standalone extension, but rather a plugin to tsserver. When the work is done, the @angular/language-service package will be able to handle HTML files.

**Comment by mickaelistria** [comment]
Ok. I had open the issue in https://github.com/microsoft/TypeScript/issues/31423 as I didn't know which end was erroneous. Do you confirm I should then close the TypeScript one and that the fix is only to be in the @angular/language-service side? Do you have a reference to another ticket about this issue for @angular/language-service?

**Comment by mickaelistria** [comment]
I'm closing this one, as https://github.com/angular/vscode-ng-language-service/issues/317#issuecomment-493149361 is a better approach.
Is there an existing ticket for the issue of HTML files parsed as TypeScript or should I create one?
