### ISSUE TITLE
Language service doesn't work at all in VSCode

### ISSUE THREAD

**Issue by NanaseRuri** [angular/vscode-ng-language-service#319]
Angular Language Service edition 0.1.11
`Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cli                      7.3.6
@angular/compiler-cli             7.2.9
@angular/language-service         7.2.9
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0`

Is there any solution except downgrade my angular or typescript version?

**Comment by nhustak** [comment]
It's pretty disappointing.  There's no response from anyone at Angular.  It's pretty much useless at this point and it's too far out of date (IMHO) to even think about reverting.   It was incredibly useful so it sucks.

**Comment by JohnnyDevNull** [comment]
https://github.com/angular/vscode-ng-language-service/issues/318

**Comment by andresbm05** [comment]
In my case the problem was because of the path to my project. I had a folder containing an "é" character that languaje service was looking for as "Ã©". Just renaming the folder solved the issue

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/issues/329
- https://github.com/angular/angular/issues/27904
