### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Apsistec** [angular/vscode-ng-language-service#325]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `0.1.11`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\doug\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kyliau** [comment]
@Apsistec Could you please let me know the version of Angular your project uses?

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/issues/329
- https://github.com/angular/angular/issues/27904
