### ISSUE TITLE
Language Service does not traverse index.ts recursively

### ISSUE THREAD

**Issue by cluxig** [angular/vscode-ng-language-service#326]
### Environment
VS Code: 1.33.0
Angular Language Service 0.1.11

### Current behavior
I've created a custom NPM module to import Components from a shared module. The public_api.ts contains a simple entry
`export * from './lib'`
whereas another `index.ts` file is placed in sub-folder 'lib' and many more in deeper folders, like `lib/widgets/custom-widget/index.ts`.
Angular build and serve is fine, but I'm facing this message in VS Code:
```
[Angular]
'custom-widget' is not a known element:
1. If 'custom-widget' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

### Workaround
If all files are directly mentioned within the public_api.ts, the ngls is working as expected:
`export * from './lib/widgets/custom-widgets/custom-widget.component'`

### Expected behavior
The ngls should interprete all index-files properly as angular build does.

**Comment by JohnnyDevNull** [comment]
you have to export them with `export * from './lib/index'` and then build a npm module. This way solved all my problems in my core components library

**Comment by kyliau** [comment]
Closing this in favor of the suggestion above. Please reopen if more discussion is needed.
