### ISSUE TITLE
angular language service template auto-complete doesn't work

### ISSUE THREAD

**Issue by rezaeieng1994** [angular/vscode-ng-language-service#327]
angular language service template auto-complete doesn't work
I have used these also but didn't help.
https://github.com/angular/vscode-ng-language-service/releases/tag/0.1.7
https://github.com/angular/vscode-ng-language-service/releases/tag/0.1.9
This is so many peoples' problems.
![bug](https://user-images.githubusercontent.com/31925338/57180899-9d0ad180-6ea2-11e9-84a8-5e8181296366.jpg)

@chuckjaz

**Comment by JohnnyDevNull** [comment]
https://github.com/angular/vscode-ng-language-service/issues/318 sounds like the same problem

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/issues/329
- https://github.com/angular/angular/issues/27904
