### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by albertoeps** [angular/vscode-ng-language-service#329]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `0.1.11`
- OS Version: `Linux x64 4.19.36-1-MANJARO`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/albertoi/Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kyliau** [comment]
@albertoeps Could you please let me know the version of Angular that your project uses?

**Comment by kyliau** [comment]
I've released a beta version of the language service.
So far, users have reported that it fixes this issue.
Please try it out, and let me know if it still causes high CPU load for you. Thank you!

https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0-rc.0

**Comment by kyliau** [comment]
Thank you for the confirmation! I'll release the new version to the Marketplace once Angular version 8 stable is released this week.

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0
- https://github.com/angular/angular/issues/27904
