### ISSUE TITLE
how is this extension Working?

### ISSUE THREAD

**Issue by squadwuschel** [angular/vscode-ng-language-service#33]
Hi,

I've managed to install the extension into my current vscode and I've opend a ng2 app, but I don't know if I have to do something else, that the intelliSense is working in my templates, because currently its not working. A Installation Instruction would be really nice an a litte how to use it.

thx
 squadwuschel

**Comment by kukjevov** [comment]
Well you dont have to do anything special except installation itself. But there is a problem with standalone html templates see https://github.com/angular/vscode-ng-language-service/issues/24 

Easiest way to test it if it is working is write inline template and you should see intellisense and errors in html if there are any.
