### ISSUE TITLE
Angular language service blocking/slow-down vscode quick-suggestion

### ISSUE THREAD

**Issue by AmirFawzy** [angular/vscode-ng-language-service#331]
**Problem**
Angular language service blocking native `quick-suggestion` in VSCode

**What happening?** 
when i try to working in `ts` file of the component while coding quick-suggestion doesn't show up until i press `ctrl+space` even so it take 5 seconds to show up the suggestion menu, when i tried to disable the extension and restart VSCode `quick-suggestion` worked perfectly without any delay or blocking for suggestions.

**Expected behavior**
`quick-suggestion` should working without any delay or blocking with enabling angular language service extension

`angular version`: 7.2.15 (latest)
`os`: windows 10 Pro

**Comment by kyliau** [comment]
Released v0.800.0 that fixed performance regression.
Multiple beta users confirmed that language service works well with Angular v7 and v8.
Please open another issue if this is not the case.
https://github.com/angular/vscode-ng-language-service/releases/tag/v0.800.0

Related issues:
- https://github.com/angular/vscode-ng-language-service/issues/329
- https://github.com/angular/angular/issues/27904
