### ISSUE TITLE
Consolidate with cyrilletuzi/vscode-typescript-angular-plugin

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#332]
Can there be some guidance on which plugin is best, now the performance regression bug has been fixed?

**Comment by kyliau** [comment]
Hi @jpike88, the angular language service will eventually be a tsserver plugin, like the extension you mentioned in the title. The last thing that I need to flush out is to make sure support for external template is solid. That's the only issue left preventing us from switching to the plugin. I'm actively working on it, but it requires from infrastructural changes in both vscode and typescript.

**Comment by Springrbua** [comment]
@kyliau the mentioned plugin did only support the vscode version of typescript as well as the integrated Angular Language Service.
Are there any plans on supporting the workspace version of Typescript and the Angular Language Service?

**Comment by kyliau** [comment]
@Springrbua, yes, when the language service becomes a tsserver plugin, you could use the workspace version of Typescript and language service. In fact, that would be the recommended way to load plugin because it solves the version mismatch issue.

**Comment by kyliau** [comment]
Closing this, because https://github.com/cyrilletuzi/vscode-typescript-angular-plugin was deprecated and archived.
https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.typescript-angular-plugin
