### ISSUE TITLE
using bind.this in template arguments is not recognized

### ISSUE THREAD

**Issue by MicMicMon** [angular/vscode-ng-language-service#337]
To bind a component method to a component attribute, I use
```
[attribute_method]="componentMethod.bind(this)"
```
But this gives a lint error:
```
method componentMethod of TestComponent
Unknown method 'bind' | Angular
```

**Expected:**
Should not output error.

**Comment by kyliau** [comment]
Similar to https://github.com/angular/vscode-ng-language-service/issues/93, will track issue there
