### ISSUE TITLE
IntelliSense performance problems tsserver blocking

### ISSUE THREAD

**Issue by JohnnyDevNull** [angular/vscode-ng-language-service#339]
Original from: https://github.com/angular/vscode-ng-language-service/issues/336#issuecomment-498597082

## Description:

I recognize performance problems from jump to source or displaying library informations on hovering types and displaying inline docs with pressed CTRL and hovering. While here the debug output from the plugin looks smooth there is invisible blocking time between the **Search Path** step and the **Config file name**

**My setup:**

* Big project with a lot of modules per lazy loading
* Some libraries like  DevExtreme, ng-bootstrap, lodash, moment, etc
* Our own internal angular library
* Angular Version 7.2.15
* Angular Language Service Plugin 0.800.0

## Reproduction:

1. define something like this:

```ts
  public gridEditingOptions: DevExpress.ui.dxDataGridOptions['editing'] = {
    mode: 'batch',
    allowUpdating: true,
    allowAdding: true,
    allowDeleting: true,
    startEditAction: 'dblClick',
    selectTextOnEditStart: true,
    useIcons: true
  };
```

2. hovering the type goes mostly fast: 
![image](https://user-images.githubusercontent.com/5759334/58867740-4bc94a00-86bb-11e9-88e4-b014899829c4.png)

3. now move away hover it again and press and hold CTRL:
![image](https://user-images.githubusercontent.com/5759334/58868221-2d178300-86bc-11e9-94a9-7422d15e2e47.png)

Some times it works fast when only hovering, but mostly especially with pressed CTRL it takes some time, but the debug console looks clean.

4. hover, press CTRL and click to jump to source or press F12: same as 3. sometimes with long blocking time.

5. With disabled language service it opens up instantly every time, no slow down, memory and cpu load not mentionable

## Possible reasone:

After trying to find out where this comes i can only say that i can push the ram and cpu consumption up with a hovering and moveaway loop

1. No file open and waited some time so that vscode calmed down:

![image](https://user-images.githubusercontent.com/5759334/58870345-589c6c80-86c0-11e9-8bd8-6cd176a2b971.png)

2. after hovering i think 20 times... with each step the loading takes a bit longer...

![image](https://user-images.githubusercontent.com/5759334/58870386-681bb580-86c0-11e9-88bd-056247e025c1.png)

I think the problem is that the duplicate tsserver here blocks each other or the main blocks the angular one or vice versa, but here i can make only assumptions.

**Comment by JohnnyDevNull** [comment]
Maybe this is fixed with https://github.com/angular/vscode-ng-language-service/issues/338 ?

**Comment by andrius-pra** [comment]
I had a similar issue and I solved it with changes from this daf0cea commit:
* Share the same DocumentRegistry instance [DocumentRegistry](https://github.com/microsoft/TypeScript/blob/e46c846ee6e20687ea4a39055f1081ba73ca89ec/src/services/documentRegistry.ts#L3-L9) between all language services. 
* Disabled Angular language service for InferredProjects (projects without tsconfig config file)
* Retain the configured project even I close last opened file from the project. This prevents do not create or remove project on every time I open or close a file.

@JohnnyDevNull, can you try to compile and test extension from this [branch](https://github.com/andrius-pra/vscode-ng-language-service/tree/improve-performance).

**Comment by gayanper** [comment]
@andrius-pra when i try to build your branch i get the following error
```
$ yarn run compile                                                                                               
yarn run v1.17.3                                                                                                 
$ node $(yarn bin)/installServerIntoExtension ../client ./package.json ./tsconfig-build.json && cp yarn.lock ../c
lient/server && tsc -p tsconfig-build.json                                                                       
internal/modules/cjs/loader.js:583                                                                               
    throw err;                                                                                                   
    ^                                                                                                            
```

**Comment by andrius-pra** [comment]
@gayanper Compiled and uploaded [here](https://drive.google.com/drive/folders/1RHWuHyNTVNlvQnMNAdWwl8Z4rFgqYpSX). 
Disable official extension while testing this build.

**Comment by gayanper** [comment]
@andrius-pra You improvement solved my issue. When can we expect these changes to end up in the master ?

**Comment by andrius-pra** [comment]
Great! I will split my changes into smaller PR in coming days and @kyliau will decide if it worth to merge to master.
