### ISSUE TITLE
template engine support (Pug)

### ISSUE THREAD

**Issue by tycho01** [angular/vscode-ng-language-service#34]
Hi, thanks for making this project!

I've been happily using Angular with Pug (having tried to make things more Angular-friendly from [their side](https://github.com/tycho01/pug-plugin-ng)), and I was wondering if I might be able to enable the awesomeness of the language services for that as well.
I found a [few](https://github.com/angular/vscode-ng-language-service/blob/master/client/language-configuration.json) [files](https://github.com/angular/vscode-ng-language-service/blob/master/client/syntaxes/NG.plist) that looked like they were about HTML, though I've only quickly glanced through the codebase.

Could you perhaps give pointers as to what it might take to achieve this? Moreover, what would be the best place to put this (PR / branch / fork / [plugin to your plugin](http://i1.kym-cdn.com/photos/images/newsfeed/000/001/122/xzibit-happy.jpg))?

**Comment by chuckjaz** [comment]
We have no plans to extend this beyond Angular.  

I have no problem someone taking parts of my plugin to make a separate plugin that support pug or similar.

**Comment by tycho01** [comment]
That's fine, I wasn't expecting others to do this for me.
I'm not so familiar with the architecture of this plugin though, so if you'd have some notion of which parts in the code-base would be HTML-specific, that might help me a lot.

**Comment by chuckjaz** [comment]
This project doesn't contain any of the really good bits as it is just a connection between `@angular/language-service` which is in [here]( https://github.com/angular/angular/tree/master/modules/%40angular/language-service).  This, however, relies on the HTML parser in the angular compiler [here]( https://github.com/angular/angular/tree/master/modules/%40angular/compiler/src/ml_parser).

**Comment by tycho01** [comment]
I'll try to look into those; thank you! :)

**Comment by Aides359** [comment]
@tycho01 what is the current state of this? Is there any repository we could watch, etc?

**Comment by tycho01** [comment]
@Aides359: I haven't managed to so far, sorry!
