### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Hardkore9t8** [angular/vscode-ng-language-service#342]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `0.800.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/DaddyNupe/Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kyliau** [comment]
Could you please provide more information?
What's the version of Angular that's used in your project?
If you use the CLI, please paste info from `ng version`, thank you!

**Comment by kyliau** [comment]
This is similar to https://github.com/angular/vscode-ng-language-service/issues/336
Will use that issue to track this problem.
