### ISSUE TITLE
Duplicated completion items in external templates

### ISSUE THREAD

**Issue by andrius-pra** [angular/vscode-ng-language-service#370]
Language server returns completions for html tags in external templates. So we have duplicated completion items in vscode editor:
![image](https://user-images.githubusercontent.com/17968027/63887997-a76b5100-c9e6-11e9-93a5-c8c3a4a5aa4b.png)

Environment:
```
@angular/language-service@~9.0.0-next.2
angular.ng-template: v0.900.0-next.0
```

**Comment by kyliau** [comment]
The previous implementation filter them out here: https://github.com/angular/vscode-ng-language-service/blob/a9f4440d671600ea32fb300478744dc5ede4c7ed/server/src/server.ts#L130 but I think the fix should be in `@angular/language-service`. These completions are never needed in the first place.

**Comment by kyliau** [comment]
Standard HTML autocomplete should not be provided by Angular, but they are needed for inline templates. The proper fix here is to 
1. Remove standard HTML completions in `@angular/language-service`
2. Register HTML block in Typescript files using TextMate grammar.
3. Let native HTML extension handle standard completions.

I've been thinking of doing (2) for quite some time now, doing it in this version is a nice enhancement.

Besides completions, users would also get syntax highlighting in inline templates.
