### ISSUE TITLE
Add TypeScript formatter to repository

### ISSUE THREAD

**Issue by ayazhafiz** [angular/vscode-ng-language-service#373]
It would be nice to add a formatter to enable consistent styling of TypeScript code in this repo. A good option is `clang-format` with the same options as in the [Angular repo](https://github.com/angular/angular).

The [NPM `clang-format` package](https://www.npmjs.com/package/clang-format) is preferable to reduce barrier of entry for developers on this repo.

There's not a lot that must be done to enable this, and what must be done can be broken up into discrete steps:

- [x] add formatter
- [x] add formatter documentation
- [ ] add Travis test for formatter
- [ ] perform mass formatting migration of repository

**Comment by kyliau** [comment]
Should consider adding an script entry to `package.json` for users who do not have the `clang-format` extension in their editor.

**Comment by ayazhafiz** [comment]
> Should consider adding a script entry to `package.json` for users who do not have the `clang-format` extension in their editor.

This already exists with `yarn format`.
