### ISSUE TITLE
Language service "component not in module" error when using `require.context` 

### ISSUE THREAD

**Issue by mrahhal** [angular/vscode-ng-language-service#374]
# 🐞 bug report

### Affected Package
@angular/language-service

### Is this a regression?
No

### Description

I use dynamic importing of components (require.context) to import them into angular modules. Angular language service can't detect that so it issues me the `Component 'x' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration` error on all of my components.

I know that angular can't do much here to detect those usages, so can I at least disable this error in the language service?

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.2
Node: 12.4.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.2
@angular-devkit/core         7.3.2
@angular-devkit/schematics   7.3.2
@schematics/angular          7.3.2
@schematics/update           0.13.2
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

Note: I first created this in the angular repo, but it's not getting any visibility and I'm not getting any replies. This is a really big issue in my team, we had to disable this whole extension completely. We make heavy use of dynamic importing. There should be a way to disable some errors,

**Comment by ayazhafiz** [comment]
Moving a discussion over to the original issue 🙂
