### ISSUE TITLE
publish language server on npmjs

### ISSUE THREAD

**Issue by mickaelistria** [angular/vscode-ng-language-service#377]
To ease consumption in other IDEs, the language server should be published separately on npmjs.

**Comment by kyliau** [comment]
Yes, we'll have to release the server as standalone package.
See https://github.com/angular/vscode-ng-language-service/issues/375#issuecomment-526754768

**Comment by kyliau** [comment]
@mickaelistria I published [@angular/language-server](https://www.npmjs.com/package/@angular/language-server)

The command line flags are different from before, so if you're using this package, be sure to check out the `--help` documentation.

**Comment by mickaelistria** [comment]
Thank you very much!
