### ISSUE TITLE
Undefined identifier not getting detected in template

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#381]
This is good:

<img width="1313" alt="Screen Shot 2019-09-04 at 6 01 41 PM" src="https://user-images.githubusercontent.com/9585787/64249533-10e6e480-cf3e-11e9-8761-17e6f2fdd03a.png">

This is bad:

<img width="657" alt="Screen Shot 2019-09-04 at 6 02 04 PM" src="https://user-images.githubusercontent.com/9585787/64249547-1f350080-cf3e-11e9-83e1-15a69cab5d08.png">

**Comment by jpike88** [comment]
maybe it's due to the fact it's got && operators in there

**Comment by andrius-pra** [comment]
This issue is already fixed in angular [v9.0.0-next.11](https://github.com/angular/angular/blob/master/CHANGELOG.md#900-next11-2019-10-15)
