### ISSUE TITLE
Go to definition not working on html template

### ISSUE THREAD

**Issue by mehermestiri** [angular/vscode-ng-language-service#387]
Vs Code Version: 1.38.0
Mac OS
extension: 0.802.3

This was working before and was not stable but starting this week no more able to navigate to the typescript definition from html template and properties are not shown when I use the {{}} in the template.

In another new project I created when I try using the extension it works fine.
I don't know if it's because of the amount of the code existing in the project so it does no more load definitions or it's a configuration in my side that is not good.

Please help.
Thanks

**Comment by andrius-pra** [comment]
Do you any errors in output window of Angular language service? What version of "Angular Language Service" do you use? You can find version in output window.

**Comment by mehermestiri** [comment]
For the version of the extension it's: 0.802.3
You said the output window of Angular language service.. From where I can find this?
I ony got the output tab openend when I focus the terminal and there I got no errors

**Comment by andrius-pra** [comment]
Select "Angular language service" from drop-down in output tab.
![image](https://user-images.githubusercontent.com/17968027/64700208-22386f80-d4af-11e9-8954-bf010a761a8c.png)

**Comment by mehermestiri** [comment]
Thanks for letting me know about that ^^
Actually, nope no erros:
getDefinitionAt: 0ms
getDefinitionAt: 0ms
getDefinitionAt: 0ms
getHoverAt: 0ms
getDefinitionAt: 0ms
getHoverAt: 0ms

**Comment by ayazhafiz** [comment]
Are you able to share the repository that is not working with the language service?

**Comment by mehermestiri** [comment]
Hello @ayazhafiz unfortunately not possible for me.

**Comment by kyliau** [comment]
Closing this, since this targets 0.802.3
