### ISSUE TITLE
E2E tests broken on master

### ISSUE THREAD

**Issue by ayazhafiz** [angular/vscode-ng-language-service#388]
`yarn test:e2e` is broken on master (since at least a842599cbdc0c023d90704af8fdd35d31539d9c8). I don't have the bandwidth to look at this right now, but may tomorrow. If someone else is interested, feel free to pick it up!

**Comment by kyliau** [comment]
@ayazhafiz Did you manage to get the test to run ?

**Comment by ayazhafiz** [comment]
Yep!
