### ISSUE TITLE
Component methods not recognized in template editor

### ISSUE THREAD

**Issue by AsherBarak** [angular/vscode-ng-language-service#39]
![image](https://cloud.githubusercontent.com/assets/6647171/21796129/3988da6c-d70f-11e6-9219-ce8ceb967a2a.png)
Methods do exist and 'Navigate to symbol' (F12) does work.
![image](https://cloud.githubusercontent.com/assets/6647171/21796138/48f1b78a-d70f-11e6-979d-7eee2ed05578.png)

It appears this is not uniform. It seems to happened in a case where two components reside in the same dir. It might be that the tool uses the model of the wrong component (names do match i.e. c1.ts with c1.html & c2.ts with c2,thml).

**Comment by chuckjaz** [comment]
Can you produce a github repository that can reproduce this problem?

**Comment by chuckjaz** [comment]
Please re-open if you reproduce in `0.1.0`
