### ISSUE TITLE
Extremely inefficient memory usage

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#391]
I have a workspace with several ts projects. Only one of them is angular.

the ```electron_node server.js``` process in this extension is incredibly resource intensive, even when I'm opening ts files in other non-angular projects, the memory of the process just like 300 mb *per file opened*, .

When opening an angular component file, even one with a complex inline template, it seems that memory only jumps up like 70-80mb.

The memory goes over 2 gigs after opening just 5 files in my server and seed projects, which again, has zero angular code in them.

<img width="430" alt="Screen Shot 2019-09-12 at 1 06 30 PM" src="https://user-images.githubusercontent.com/9585787/64758202-28d1f000-d55e-11e9-9c0d-809bc2757457.png">

Two things:

- [ ] This plugin should be smart enough to know when it's touching a project that has no angular code, or it should be possible to configure limitations on what files this plugin should be allowed to run against.

- [ ] It looks like it has a memory leak because even after closing all files in the project, the memory continues to sit at around 2 gigs indefinitely. In contrast, the tslint plugin backs off memory usage substantially.

**Comment by kyliau** [comment]
The second bullet point here is fixed in the new extension. We no longer maintain our own `ProjectService`, and instead delegate the responsibility to stock `tsserver`, so the behavior of project management is the same in both TypeScript and Angular.

**Comment by jpike88** [comment]
you are a legend, glad to see this getting the love it deserves! finally can be proud to use this plugin lol
