### ISSUE TITLE
Add rollup to build pipeline

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#393]
In order to speed up extension load time, it's preferable to ship a single bundle to vscode marketplace. This should be done for both client and server.
Today, we install the production dependencies then ship the entire directory, including `node_modules`.

Previously, before the restructuring of the project layout, we ship **everything** in the repo, which produces a "binary" that's ~24mb. With prod deps only, it's now ~8mb. The size could be reduced further.

See https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by ayazhafiz** [comment]
Are you suggesting we publish a rollup'd package?

**Comment by kyliau** [comment]
Yes! Not only for our code, but for third party deps as well.
