### ISSUE TITLE
Syntax highlighting for inline templates

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#395]
The extension should provide a textmate grammar for inline templates so that syntax highlighting shows up for HTML.
Once that is done, we should look into whether native html extension would handle autocomplete for inline template. Ideally, such autocompletion should be delegated to the native html extension, but that's not the case today. Angular should add only Angular-specific completions.
There's already existing [extension](https://github.com/natewallace/angular2-inline) that provides such grammar, perhaps we should reach out to the author for potential collaboration.

**Comment by jpike88** [comment]
relevant:

https://github.com/natewallace/angular2-inline

**Comment by jpike88** [comment]
bonus requests to make this plugin start kicking serious ass:

- auto-formatting applies to html and css as well as TS in one go
- css syntax highlighting is modernised (see attached image for incorrect highlighting)
- html and css can be collapsed/uncollapsed

![Screen Shot 2019-11-04 at 11 39 41 am](https://user-images.githubusercontent.com/9585787/68099924-d4ad1180-fef7-11e9-8b4c-0a36e983da0b.png)

**Comment by jpike88** [comment]
Other irregularities with syntax highlighting (functions aren't being detected properly)


![Screen Shot 2019-11-04 at 12 34 39 pm](https://user-images.githubusercontent.com/9585787/68101848-52761a80-ff02-11e9-8c07-681380946ce0.png)

**Comment by ayazhafiz** [comment]
If no one else is interested in picking this up, I'll start on this next week :)

**Comment by kyliau** [comment]
@ayazhafiz is there any remaining work to be done here?

**Comment by ayazhafiz** [comment]
I think we can close this one and open a new one for syntax highlighting Angular template syntax.
