### ISSUE TITLE
[feature] Support for "bind-", "on-" and "bind-on-" syntax in template

### ISSUE THREAD

**Issue by RKaczmarek** [angular/vscode-ng-language-service#398]
Hi,

angular supports an alternative way of binding properties and events with the prefixes "bind-", "on-" and "bind-on-" on attributes. A support by this plugin would be nice.

example:
```ts
class AnyComponent {
  foo: String = "bar";
}
```

template with angular syntax:
```html
<other-component [foo]="foo"></other-component>
```
alternative html conform way:
```html
<other-component bind-foo="foo"></other-component>
```

**Comment by kyliau** [comment]
#34445 will fix the LHS of the binding. Another PR is needed to add suggestions for the RHS of the binding.
