### ISSUE TITLE
autocomplete not working on windows

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#401]
@kyliau I followed the instructions to install v0.900.0-next.0, however there are no auto-complete suggestions for anything (e.g component selectors, properties, events, etc).

_Originally posted by @Proantagonist in https://github.com/angular/vscode-ng-language-service/issues/335#issuecomment-532872106_

**Comment by kyliau** [comment]
@Proantagonist this is most likely because the extension failed to find `@angular/language-service`, similar to https://github.com/angular/vscode-ng-language-service/issues/369
Could you please open the `Output` tab and inspect the logs?

It should be similar to this:
![Screenshot from 2019-09-18 14-52-29](https://user-images.githubusercontent.com/2941178/65188741-f6c00280-da23-11e9-9ded-f54201a044f3.png)

**Comment by Proantagonist** [comment]
Certainly. Here is the output:

![image](https://user-images.githubusercontent.com/3969818/65192572-1ca5d100-da3d-11e9-81d9-16f99ea6977c.png)


```
[Info  - 5:52:16 PM] Angular LS probe location: c:\Github\Work\tamu-gisc-monorepo
[Info  - 5:52:16 PM] Success: @angular/language-service loaded
[Info  - 5:52:16 PM] Log file: c:\Users\imacl\AppData\Roaming\Code\logs\20190918T174927\exthost1\Angular.ng-template\nglangsvc.log
[Error - 5:52:18 PM] Failed to find project for c:\Github\Work\tamu-gisc-monorepo\apps\angular-aggiemap-trees\src\app\components\map\map.component.html
```

**Comment by Proantagonist** [comment]
I should add that this VSC workspace is an Nx workspace with multiple `libs` and `apps`

The target app is consuming components from `libs`.

**Comment by kyliau** [comment]
Ahh ... please open a TS file first, then the HTML. This shall be fixed before the next release.

**Comment by Proantagonist** [comment]
Opening a TS first gets rid of the error, but unfortunately it still does not provide suggestions.

`tamu-gisc-layer-filter` is a known valid component selector.

![xJhFfoDOAt](https://user-images.githubusercontent.com/3969818/65193483-e66a5080-da40-11e9-8c5a-cd3f020504b4.gif)

**Comment by kyliau** [comment]
Could you please try "Go to definition" for `tamu-gisc-layer-filter` in the template?
It is likely that `@angular/language-service` is not found, even though the log message claims that it is loaded. If that's the case, https://github.com/angular/vscode-ng-language-service/pull/402 would fix it.

**Comment by Proantagonist** [comment]
"Go to definition" navigates to it correctly. 

I looked at #402 but I'm not sure I know what to do from here. 

Thank you for all your help!

**Comment by andrius-pra** [comment]
@kyliau, this issue is already fixed here: #367. The pre-release verson(v0.900.0-next.0) doesn't in windows os.

**Comment by kyliau** [comment]
Thanks @andrius-pra, I'll cut another beta release this week with all the fixes.

**Comment by kyliau** [comment]
Closing this, v0.900-.0-next.1 is released.
