### ISSUE TITLE
Project not found when HTML file is opened without any TS files

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#411]
Currently, in order for the language service to work, users have to first open some TS files, then only HTML files.
Opening only HTML files produces the error
```
Failed to find project for /some/path/to/template.html
```

This is because the project is immediately removed after it's created when a HTML file is opened.
This is already fixed in TS 3.6 in commit https://github.com/microsoft/TypeScript/commit/10ee85c98c9027321bc88fc8e42f4d759c7c0c63

`@angular/language-service` will upgrade to TS 3.6 pending https://github.com/angular/angular/pull/32946

**Comment by andrius-pra** [comment]
@kyliau, This bug is still valid in v0.900.0-next.2. The language server should only load typescript from workspace directory when version >= 3.6.0

**Comment by ayazhafiz** [comment]
Reference @andrius-pra's PR #431
