### ISSUE TITLE
Intellisense for Angular Templates not working in v0.900.0-next.1

### ISSUE THREAD

**Issue by prasworld** [angular/vscode-ng-language-service#416]
After the latest upgrade the angular intellisense has ceased to work. 
Cli version @angular/cli                       7.3.0
Platform Windows 
VS Code Version 1.39.1

**Comment by iamcco** [comment]
Seems need `@angular/language-service >= v9.0.0` to work

**Comment by Urastor** [comment]
Having the same problem. 

CLI version ~8.2.5
Platform Windows
VS Code Version 1.39.1
@angular/language-service 9.0.0-next.10

App is working fine using child router-outlet, but template gives error. 

![Anmerkung 2019-10-11 111055](https://user-images.githubusercontent.com/7266207/66639779-d0067d80-ec17-11e9-9139-c22f80690cf3.png)

**Comment by kyliau** [comment]
Thanks for trying out the beta version! 
Could you please open the "Output" console in vscode and paste the logs here?
It should look something like this:

<img width="1792" alt="Screen Shot 2019-10-11 at 10 43 23 AM" src="https://user-images.githubusercontent.com/2941178/66672829-11952980-ec14-11e9-9c7f-5f1a45f5c933.png">

**Comment by iamcco** [comment]
I have this log:

```
[Info  - 2:33:10 PM] Using typescript v3.5.3 from /Users/aioi/.vscode/extensions/angular.ng-template-0.900.0-next.1/node_modules/typescript
[Info  - 2:33:10 PM] Using @angular/language-service v9.0.0-next.10 from /Users/aioi/.vscode/extensions/angular.ng-template-0.900.0-next.1/server/node_modules/@angular/language-service
[Info  - 2:33:10 PM] Log file: /Users/aioi/Library/Application Support/Code/logs/20191015T142646/exthost1/Angular.ng-template/nglangsvc.log
[Info  - 2:33:18 PM] Disabling language service for /Users/aioi/workspace/pxn/anduin/tsconfig.json because it is not an Angular project.
```

It's weird the log `it is not an Angular project.`

**Comment by iamcco** [comment]
![image](https://user-images.githubusercontent.com/5492542/66883357-3ddbec00-f000-11e9-9610-2abea96e9153.png)

I have `@angular/core` installed and it works with previous version。

**Comment by kyliau** [comment]
@iamcco Do you mind sharing your `tsconfig.json` please? Is `node_modules` excluded?

**Comment by iamcco** [comment]
The tsconfig.json

```jsonc
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "target": "es2015",
    "lib": [
      "es2017",
      "dom"
    ],

    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,

    // "strict": true,
    "alwaysStrict": true,
    "noImplicitAny": false,
    "noImplicitThis": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true
  }
}

```

**Comment by andrius-pra** [comment]
Which version of @angular/core do you use? You can find version in package.json file.

**Comment by kyliau** [comment]
@iamcco The tsconfig looks fine. Based on the screenshot you shared, it looks like there's another issue that could be the probable cause. It says "No config file for ..."
Please make sure you open a TypeScript file that has Angular directives in it and try again. It would be helpful if you could actually share the entire output messages and also the log file. Thank you!

**Comment by iamcco** [comment]
@andrius-pra  I have  `@angular/core": "8.2.6"`

@kyliau 
this is the full log when open ts file first.

```
[Info  - 10:40:37 AM] Using typescript v3.5.3 from /Users/aioi/.vscode/extensions/angular.ng-template-0.900.0-next.1/node_modules/typescript
[Info  - 10:40:37 AM] Using @angular/language-service v9.0.0-next.10 from /Users/aioi/.vscode/extensions/angular.ng-template-0.900.0-next.1/server/node_modules/@angular/language-service
[Info  - 10:40:37 AM] Log file: /Users/aioi/Library/Application Support/Code/logs/20191018T103958/exthost3/Angular.ng-template/nglangsvc.log
[Info  - 10:40:45 AM] Disabling language service for /Users/aioi/workspace/pxn/anduin/tsconfig.json because it is not an Angular project.
```

if i first open html file it will have the `No config file for...` log

```
[Info  - 10:43:52 AM] Using typescript v3.5.3 from /Users/aioi/.vscode/extensions/angular.ng-template-0.900.0-next.1/node_modules/typescript
[Info  - 10:43:52 AM] Using @angular/language-service v9.0.0-next.10 from /Users/aioi/.vscode/extensions/angular.ng-template-0.900.0-next.1/server/node_modules/@angular/language-service
[Info  - 10:43:52 AM] Log file: /Users/aioi/Library/Application Support/Code/logs/20191018T103958/exthost4/Angular.ng-template/nglangsvc.log
[Info  - 10:43:56 AM] Disabling language service for /Users/aioi/workspace/pxn/anduin/tsconfig.json because it is not an Angular project.
[Error - 10:43:56 AM] No config file for /Users/aioi/workspace/pxn/anduin/src/app/modules/new-pos/new-pos-earnings.component.html
[Info  - 10:44:36 AM] Disabling language service for /Users/aioi/workspace/pxn/anduin/tsconfig.json because it is not an Angular project.

```

**Comment by kyliau** [comment]
@iamcco Thank you so much for sharing the log file, it's very helpful. In your case, there are files in your project which exceeded the hard-coded limit in tsserver. Specifically, it's this line:

```
Info 38   [10:44:30.409] Non TS file size exceeded limit (22477522). Largest files: /Users/aioi/workspace/pxn/anduin/dist/trading-view/charting_library.min.d.ts:49496, /Users/aioi/workspace/pxn/anduin/vendor/trading-view/charting_library.min.d.ts:49496, /Users/aioi/workspace/pxn/anduin/src/app/models/eos-proxy-abi.ts:34245, /Users/aioi/workspace/pxn/anduin/src/app/modules/kyc/countries.ts:24028, /Users/aioi/workspace/pxn/anduin/src/app/modules/kyc-result/countries.ts:24028
```

The total size of your project exceeded 22477522 bytes, which causes tsserver to automatically disable the language service. The message about the project not being Angular is just a red herring.
Do you actually get native TypeScript language features? The same should be happening to the native tsserver.

**Comment by iamcco** [comment]
It's weird, I can also have native tsserver completion items.

update plugin to latst version and still get this error.

If delete dist directory I get this log now.

[log.log](https://github.com/angular/vscode-ng-language-service/files/3746092/log.log)

**Comment by kyliau** [comment]
@iamcco It looks like you have an old version of `@angular/language-service` in `/Users/aioiyuuko/workspaces/pxn/anduin/node_modules/`. Could you please try to update to the latest v9 version and try again?
Even though there's a v9 version bundled with the extension as a fallback, it looks like `tsserver` prioritizes the `node_modules` directory where TS is found over the provided `pluginProbeLocations`.

**Comment by kyliau** [comment]
I filed an issue with TypeScript: https://github.com/microsoft/TypeScript/issues/34616

**Comment by iamcco** [comment]
It works if install the latest version of @angular/language-service

**Comment by kyliau** [comment]
I'll mark this issue closed for now. Please open another issue if similar problem occurs.
