### ISSUE TITLE
[LS] HTML template completion insert text without overriding matching range

### ISSUE THREAD

**Issue by mickaelistria** [angular/vscode-ng-language-service#417]
This is causing https://github.com/eclipse/wildwebdeveloper/issues/279

a .ts component
```ts
@Component({
	templateUrl: './app.componentWithHtml.html'
})
export class AppComponentWithHtml {
	title = 'angular-app';
}
```
with a .html template
```html
<h1>{{t}}</h1>
```

Asking completion after `t` in the template sends
```json
{"jsonrpc":"2.0","id":"2","result":[{"label":"title","kind":10,"detail":"property","sortText":"title","textEdit":{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":7}},"newText":"title"}}]}
```
which, consistently with the spec, results in
```html
<h1>{{ttitle}}</h1>
```
(with 2 `t`s).

The message is incorrect: either the `newText` should only be `itle` or the range should be `{"start":{"line":0,"character":6},"end":{"line":0,"character":7}}` to override the existing `t`

**Comment by kyliau** [comment]
This is a known issue, and @ayazhafiz is working on it.
WIP PR: https://github.com/angular/angular/pull/33091

**Comment by kyliau** [comment]
Closing this, since https://github.com/angular/angular/pull/33091 is done.
