### ISSUE TITLE
Enable way to easily profile performance of the plugin

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#429]
As this plugin does a couple of things which may involve a processing delay, it's probably a good idea to allow people using it to easily turn on some sort of easy way to see how long it takes for a given file to process. Is the processing pipeline it as simple as a run through TS with the angular plugin?

**Comment by kyliau** [comment]
> Is the processing pipeline it as simple as a run through TS with the angular plugin?

Yes. Internally, `@angular/language-service` is installed as a tsserver plugin. It's all default TypeScript behavior. The only difference is that HTML files (external templates) are opened and passed to the server.

I'll look into a way to turn on timers to trace each request.

**Comment by kyliau** [comment]
This has been fixed by https://github.com/angular/vscode-ng-language-service/pull/1057. 
When tracing is enabled, the log will show how long each request takes.
