### ISSUE TITLE
Plugin process maxing out for ages on each file load

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#432]
![Screen Shot 2019-10-28 at 12 12 08 pm](https://user-images.githubusercontent.com/9585787/67653528-57742080-f97c-11e9-8852-201facfc5b50.png)

^ This is happening practically non-stop, it's choking on files that don't even have angular templates enabled.

I'm uninstalling this plugin and just doing without, as it's rendering things unusable for me. I'm on a recent model Mac mini with 16gb of ram, plenty of resources and it's bringing it to its knees.

**Comment by ayazhafiz** [comment]
What version of the plugin are you on?

**Comment by kyliau** [comment]
@jpike88 Could you please provide the log files to help us debug this issues?
The location of the log file is shown when you open the output tab in vscode.
It'd look similar to this:
![Screenshot from 2019-09-18 14-52-29](https://user-images.githubusercontent.com/2941178/67700808-e88ecb80-f96b-11e9-8c62-5ba30caa2541.png)

**Comment by jpike88** [comment]
I think I know the problem.

```107	918	44223	             /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/joshpike/.vscode/extensions/angular.ng-template-0.900.0-next.6/server --logFile /Users/joshpike/Library/Application Support/Code/logs/20191029T115049/exthost1/Angular.ng-template/nglangsvc.log --logVerbosity terse --ngProbeLocations /Users/joshpike/Projects/aquipa,/Users/joshpike/.vscode/extensions/angular.ng-template-0.900.0-next.6/server --tsProbeLocations node_modules/typescript/lib,/Users/joshpike/Projects/aquipa,/Users/joshpike/.vscode/extensions/angular.ng-template-0.900.0-next.6 --node-ipc --clientProcessId=44214```

This process spikes on a single keypress. If I do 20 or 30 characters, the process just maxes out for ages, like 20 seconds.

Do you debounce any aspect of this plugin?

**Comment by kyliau** [comment]
@jpike88 thanks for the logs! The logs did not give much info about the situation you encountered, but I think I should look into implementing [request cancellation](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#cancellation).
This new extension started out as a prototype, so that part was skipped. It currently uses a null cancellation token.

https://github.com/angular/vscode-ng-language-service/blob/fe9cdfa356d25da26df5aad22a332614c490140c/server/src/session.ts#L46-L58

It'll involve both client side and server side changes, so I'll have to spend some time to do some research.

Meanwhile, I should also look into disabling local plugins (like tsslint) from loading in the Angular language server. Could you please confirm that `tslint` was installed as a local plugin in your `tsconfig.json`?

**Comment by andrius-pra** [comment]
@kyliau, I think it's not necessary to request diagnostic messages on each key press. You can restore old [functionality ](https://github.com/angular/vscode-ng-language-service/blob/archive/server/src/errors.ts#L12-L28)from v0.802.3

**Comment by jpike88** [comment]
my tsconfig:

```
{
  "compileOnSave": true,
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true
  },
  "compilerOptions": {
    "plugins": [
      {
        "name": "@angular/language-service",
      },
      {
        "name": "typescript-tslint-plugin"
      }
    ],
    "moduleResolution": "node",
    "target": "ESNext",
    "lib": [
      "esnext",
      "dom"
    ],
    "emitDecoratorMetadata": true,
    "outDir": "../dist",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "noEmitHelpers": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitThis": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "baseUrl": "./",
    "paths": {
      "@client/*": [
        "./components/*"
      ],
      "@shared/*": [
        "./../../shared/*"
      ]
    }
  },
  "exclude": [
    "./../node_modules"
  ]
}
```

**Comment by kyliau** [comment]
> @kyliau, I think it's not necessary to request diagnostic messages on each key press. You can restore old [functionality ](https://github.com/angular/vscode-ng-language-service/blob/archive/server/src/errors.ts#L12-L28)from v0.802.3

Thanks for pointing that out. Typescript's default behavior is to wait 200ms after a change, and if there's no further change or reload messages then it'll send the diagnostics request.

https://github.com/microsoft/vscode/blob/7b944a16f52843b44cede123dd43ae36c0405dfd/extensions/typescript-language-features/src/features/bufferSyncSupport.ts#L493-L497

**Comment by andrius-pra** [comment]
Typescript also cancels pending request and schedules a new event with initial delay. So it never check for errors while you writing the code.

https://github.com/microsoft/TypeScript/blob/304fcee09bca0f87180652160a0fff5e8cc80e4d/src/server/utilities.ts#L126-L161

https://github.com/microsoft/vscode/blob/7b944a16f52843b44cede123dd43ae36c0405dfd/extensions/typescript-language-features/src/utils/async.ts#L10-L62
