### ISSUE TITLE
False error using the ReactiveFormsModule

### ISSUE THREAD

**Issue by IngAjVillalon** [angular/vscode-ng-language-service#441]
Hello, congratulations on your excellent work in developing this plugin. It is awesome!

I want to report that when I use FormGroup and FormControl with ReactiveFormsModule:

```
signInForm = new FormGroup({
    email: new FormControl(""),
    password: new FormControl(""),
    rememberMe: new FormControl(false),
  });
```

In the HTML the template I get a false error in the validators:
`* ngIf = "signInForm.controls.password.invalid"`
I get the following error:

> Identifier 'password' is not defined. '__type' does not contain such a member

No intention is to ask you to fix that, but a way to make an exception for those types of errors

**How can I add a global exception to the plug-in to ignore those types of "errors"?**

**Comment by ayazhafiz** [comment]
I opened an issue a while ago to support configuration of reported errors (https://github.com/angular/angular/issues/32663). Such a configuration probably won't be done until after the Ivy rewrite, as it will likely require a sizable change in architecture.

**Comment by IngAjVillalon** [comment]
@ayazhafiz , thank you very much for the information. I'll follow it.
Have a good day my friend.
