### ISSUE TITLE
extension fails to load in vscoder insider (debug mode)

### ISSUE THREAD

**Issue by ferozsho** [angular/vscode-ng-language-service#449]
Issue Type: <b>Bug</b>

The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.

Extension version: 0.802.3
VS Code version: Code - Insiders 1.41.0-insider (a747d264d668a947eeacd3492b60df6ce8dee6b4, 2019-11-23T11:09:42.834Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (17.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andrius-pra** [comment]
output logs:
```
Debugger listening on ws://127.0.0.1:6009/203b1305-2797-46a8-8c82-a98b7f2e1e41
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:630
    throw err;
    ^

Error: Cannot find module 'c:\Users\Andrius\.vscode-insiders\extensions\angular.ng-template-0.802.3\server\out\server.js'
    at Function._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function._load (internal/modules/cjs/loader.js:531:27)
    at Function.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 16:18:29] Connection to server got closed. Server will not be restarted.
```
VSCode insider tries to load the extension in [debug mode](https://github.com/angular/vscode-ng-language-service/blob/archive/client/src/extension.ts#L29-L50). The debug mode [uses non-existing path ](https://github.com/angular/vscode-ng-language-service/blob/archive/client/src/extension.ts#L30)for server module.

**Comment by juristr** [comment]
Can confirm. Just installed rc.3 on inside version and I'm getting the same issue

**Comment by andrius-pra** [comment]
I think it's caused by  microsoft/vscode#85417. This pull request added `inspect-port=0` to process arguments and this change will force  to run all extensions in debug mode because of arguments will match [DEBUG_FLAGS_PATTERN](https://github.com/microsoft/vscode/blob/0d9307ff597666896bc02d0d8cad84de193f2f7e/src/vs/code/electron-browser/processExplorer/processExplorerMain.ts#L24) pattern.

**Comment by PowerMogli** [comment]
> I think it's caused by [microsoft/vscode#85417](https://github.com/microsoft/vscode/pull/85417). This pull request added `inspect-port=0` to process arguments and this change will force to run all extensions in debug mode because of arguments will match [DEBUG_FLAGS_PATTERN](https://github.com/microsoft/vscode/blob/0d9307ff597666896bc02d0d8cad84de193f2f7e/src/vs/code/electron-browser/processExplorer/processExplorerMain.ts#L24) pattern.

Any idea what we can do?

**Comment by andrius-pra** [comment]
> Any idea what we can do?

Update to latest version. This issue (microsoft/vscode#85490) is already fixed.
