### ISSUE TITLE
Component not found in NgModule

### ISSUE THREAD

**Issue by fbcarpinato** [angular/vscode-ng-language-service#458]
**Describe the bug**
In every component of my project, I get the error that tells me that I didn't import the component inside the NgModule, but in reality, it compiles and works.

The language service don't recognize the component as registered in a NgModule.

**To Reproduce**
Update to 0.900

Steps to reproduce the behaviour:
1. Go to a component class and hover the @Component decorator

**Expected behaviour**

It should just recognize that my component is registered in a NgModule.

**Logs**

1. Console output
{
	"resource": "/Users/fabiocarpinato/Workspace/user-client-v2/src/app/features/commons/invoices-container/invoices-container-page/invoices-container-page.component.ts",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "0",
	"severity": 8,
	"message": "Component 'InvoicesContainerPageComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration.",
	"source": "ng",
	"startLineNumber": 11,
	"startColumn": 2,
	"endLineNumber": 11,
	"endColumn": 11
}

**Comment by kyliau** [comment]
@fbcarpinato is your `NgModule` exported?
We only look for `@Component` and `@NgModule` that are exported (that could totally be a bug on our side).

**Comment by kyliau** [comment]
@fbcarpinato Could you please attach a screenshot of the console output and the log file contents?
It should look like this:

![output](https://user-images.githubusercontent.com/2941178/69664544-71695780-103d-11ea-8ca0-f23c4a8b9e07.png)

**Comment by fbcarpinato** [comment]
<img width="1149" alt="Schermata 2019-11-27 alle 09 10 26" src="https://user-images.githubusercontent.com/18047094/69705416-cec0df80-10f5-11ea-8adc-5486e517be9d.png">

**Comment by kyliau** [comment]
I think this shares the same root cause as https://github.com/angular/vscode-ng-language-service/issues/457, I'll use that ticket for investigation for now.
