### ISSUE TITLE
index value is not number error in template

### ISSUE THREAD

**Issue by sheikalthaf** [angular/vscode-ng-language-service#460]
**Describe the bug**

Showing error for index value from ngFor is not numeric value.
```
(variable) i
Expected a numeric typeng(0)
```
**To Reproduce**

**Expected behavior**

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
2. Log file (Path is printed to the console output at startup)

**Screenshots**

![image](https://user-images.githubusercontent.com/22526247/69695115-29ac0400-1101-11ea-9026-33199da6c072.png)

**Additional context**

**Comment by ChamaraWP** [comment]
I getting same kind of error for the *ngIf check. I didn't get this before
![Capturess](https://user-images.githubusercontent.com/21265782/69695793-93c5a880-1103-11ea-90e3-c3c2c2fb9946.PNG)

**Comment by migel-wimtore** [comment]
I am getting the same error when interpolating the index variable from an `ngFor` and trying to add a number to it. For example:

```
<ng-container *ngFor="let item of items; index as i">

{{i + 1}}

</ng-container>
```

I have noticed that if the keyvalue pipe is used in the ngFor declaration, the error does not appear. For example:

```
<ng-container *ngFor="let item of items | keyvalue; index as i">

{{i + 1}}

</ng-container>
```

**Comment by kombasltd** [comment]
Same error here and somehow this ist new after a VS Code update and maybe an update of "Angular Files". I was wondering because this was old code which now throws this error, but serves and builds fine.

```
<div *ngFor="let product of productItems; let i = index">
      <div *ngIf="i % 3 === 0 " class="card-deck mt-2">
        <div class="card" *ngFor="let item of productItems.slice(i,i+3)">
...
```

The variable "i" in lines 2 and 3 are marked as an error "Expected a numeric type ng(0)".

**Comment by p4309027** [comment]
in my case it is saying: 

`Expected a number type ng(0)`

for following code
```
<div *ngFor="let file of files; let i = index;">
   <p>File #{{i+1}}: {{file.name}}</p>
</div>
....
```

**Comment by masterlavidobrasil** [comment]
No meu caso usei conversão via pipe {{ (index | number) + 1 }} e parou o problema

**Comment by wesleyxavier** [comment]
No meu caso usei conversão via pipe {{ (index | number) + 1 }} e parou o problema
