### ISSUE TITLE
Syntax highlighting for inline template should be disabled for comment

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#470]
**Describe the bug**

When an inline template is commented out in TypeScript, syntax highlighting still lingers.

**To Reproduce**

Comment out `template` attribute in any `@Component`.

**Expected behavior**

Syntax highlighting should be disabled and revert to normal TypeScript highlighting.

**Screenshots**

![wrong-syntax](https://user-images.githubusercontent.com/2941178/70001354-eba04d00-1511-11ea-8f70-b6c7c2fbf528.png)

**Comment by kyliau** [comment]
@ayazhafiz is it ok to close this?

**Comment by ayazhafiz** [comment]
Yes :-)
