### ISSUE TITLE
Proposal to remove getExternalFiles()

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#473]
Currently, when a `program` is created or updated, TypeScript not only traverses the entire source tree to look for TypeScript sources, but also asks each plugin whether there are any external files, and add those files to a `Project`.

This is done through the `getExternalFiles()` API.

When this function is called, Angular language service does its own traversal to discover all external templates.

I think it is not necessary to do this global traversal in Angular because:

1. The operation is somewhat expensive, and I'd argue it is unnecessary.
2. Angular does not check whether the external templates actually exist. It merely "resolves" the file by concatenating the path. When TypeScript tries to create a `ScriptInfo` for an invalid external file, it'd fail.

We should take a step back, and decide if it is actually necessary for TypeScript and Angular to perform such traversal.

For TypeScript, the reason is obvious because it needs to know what is in a "compilation unit" and watch for changes in those files.

For Angular, however, telling tsserver which external templates are in a "compilation unit" does not serve any meaningful purpose. A template is inherently "private" to a Component, so we should not perform any operations on it until it is actually opened by the user. One could say that knowing all external templates up front would allow us to perform a global diagnostic check, and report errors even for templates that are not open. I think this is a niche enough use case that is okay to be omitted in favor of better performance and cleaner code.

A quick hack I did confirmed that the extension would continue to work correctly without knowing any external files up front. An external template is added to a Project only when it is opened by the user.

A little bit of historical context: the `getExternalFiles()` API was created by the TypeScript team for the Angular extension to experiment with a plugin system that would work with files other than TS/JS. After quite a bit of discussion, we decided that this is not the right approach, and continued down the path of using our own tsserver. This effectively makes `getExternalFiles()` redundant, but we never got to clean up the experimental API in both codebases.

@andrius-pra @ayazhafiz What do you think? I'd like to discuss this here before making a PR in case I missed any critical piece of information.

**Comment by ayazhafiz** [comment]
This sounds reasonable and preferable to me. My understanding is that TypeScript also does not provide global diagnostics for non-opened files. Is that correct?

**Comment by andrius-pra** [comment]
`getExternalFiles()` might be required for additional features like [Find All References ](https://www.youtube.com/watch?v=DvQz9JMiGDM&feature=youtu.be&start=105&end=120), Rename, or code actions.

**Comment by kyliau** [comment]
I think we could still do that without telling vscode what the external files are, because it is up to the language service plugin to define the implementation for those methods, and internally we do keep track of all templates.
This proposal is mainly to stop telling tsserver what the external files are every time it updates the program. I don't think it serves any meaningful purpose. If we get rid of this we could gain some performance improvements.
