### ISSUE TITLE
Component binding inputs disappeared

### ISSUE THREAD

**Issue by AvshT** [angular/vscode-ng-language-service#484]
**Describe the bug**

Component binding inputs disappeared.

**To Reproduce**
Take **nebular nb-alert** for example
Go back to V0.802.3
Check against V0.900.1

**Expected behavior**

All relevant binding inputs should be shown.

In V: 0.802.3
![image](https://user-images.githubusercontent.com/29532821/70387850-d6646c00-19b2-11ea-9236-d24e3b5b5ccd.png)

In V: 0.900.1- a lot of irrelevant results
![image](https://user-images.githubusercontent.com/29532821/70387873-1cb9cb00-19b3-11ea-8153-03e38cfdc70c.png)

I'm using 
Ang: 8.0.3
TS: 3.4.5

What I missing?

Thanks in advance.

**Comment by shifenis** [comment]
@AvshT this issue is already opened (#474)

**Comment by ayazhafiz** [comment]
Closed to track in #474
