### ISSUE TITLE
Language service cannot resolve paths in tsconfig.app.json

### ISSUE THREAD

**Issue by Chazing** [angular/vscode-ng-language-service#485]
**Describe the bug**

In case of using Angular namespace with some Applications.
I use components from one Angular project (test-app), the other project (demo).
I don't want to use relative path components, so I added paths at tsconfig.app.json

``` 
"paths": {
       "@aa/shared": [
         "src/app/shared"
       ],
       "@aa/shared/*": [
         "src/app/shared/*"
       ]
     }
```

And I wrote the import in this way -

```
import {SharedModule} from '@ aa / shared / shared.module';
```
Angular language service does not recognize the components in ts, nor the components tags in html.

**To Reproduce**

1. Go to https://github.com/Chazing/test-language-service
2. Download tha project, open in vscode
3. run ng s --project=demo=> the project in working in the compilation and browser
4. Open the 'projects\demo\src\app\app.module.ts' file and see that the SharedModule is not known
5. Open the 'projects\demo\src\app\app.component.html' file and see that <app-hello-world> is not known

**Expected behavior**
angular language service know the components from othe application

**Screenshots**

![Capture](https://user-images.githubusercontent.com/33194200/70425714-5b668880-1a7a-11ea-9a32-b922fd06473c.PNG)

![Capture](https://user-images.githubusercontent.com/33194200/70425787-7a651a80-1a7a-11ea-8b42-5f861acb64b7.PNG)

**Additional context**

Version 0.900.1

**Comment by kyliau** [comment]
@Chazing Thank you for the feedback. Could you please try adding the paths to `tsconfig.json` instead of `tsconfig.app.json`? TypeScript compiler does not recognize non-standard tsconfig file names.

**Comment by Chazing** [comment]
It works!
I renamed the file from tsconfig.app.json to tsconfig.json, this solved the problem.
Thanks!
