### ISSUE TITLE
Incorrect diagnostic span in inline template

### ISSUE THREAD

**Issue by a-gerescher** [angular/vscode-ng-language-service#520]
**Describe the bug**

A component is opened. The component has the following sourcecode:

```
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-state',
  template: `



  <div> {{res<Cursor>}} </div>
  `,
  styles: []
})
export class StateComponent {
  @Input() resourceId: string;
}
```

**To Reproduce**

**Expected behavior**

Whatever code magic you are doing, to provide autocomplete, the line breaks in the multiline template literal are subtracted from the correct offset, so i get the correct autocompletion if i move my cursor to the following position -> (cursor colunm - (linebreaks after beginning of javascript string literal) ). 
The problem is clearly visible if you add a nonexisting (in the component class) property to the template, and the missing property is underlined red incorrectly, the underline is shifted to the left according to the number of linebreaks before the missing property.

**Screenshots**

![image](https://user-images.githubusercontent.com/22237310/71189145-9dfe4100-2282-11ea-9fb0-a544946ac6e9.png)

**Comment by ayazhafiz** [comment]
@a-gerescher are you on Windows?

**Comment by a-gerescher** [comment]
Yes

**Comment by kyliau** [comment]
This issue was fixed for external template, but somehow still broken in TS files with CRLF line endings. I'll take a look.
