### ISSUE TITLE
event binding and property binding user experience

### ISSUE THREAD

**Issue by doggy8088** [angular/vscode-ng-language-service#521]
**Describe the bug**

Related to https://github.com/angular/vscode-ng-language-service/issues/474

The developing experience for event binding and property binding user experience is changed in this new version `0.900.3`.

**To Reproduce**

1. find a tag
2. add a `(click)=""` event binding or `[accessKey]=""` property binding

**Expected behavior**

When you type `(cli` then hit `Tab` should appear `(click)="<CURSOR_HERE>"`.

**Logs**
N/A
**Screenshots**

`0.900.3` Video
https://youtu.be/JB23F7vflL8

`0.802.3` Video
https://youtu.be/i1XoRvyibjo

The original (`0.802.3`) DX is a bit nicer. Please change it back to the original behavior.

**Additional context**

Hope to get the same or better developer experience (DX) of the code snippet feature.

**Comment by ayazhafiz** [comment]
@kyliau we can probably extend the replacement span to include the closing parantheses in these cases, since we know know the kind of binding we're in before providing a completion. What do you think?

**Comment by ayazhafiz** [comment]
@doggy8088 does this remain a strong pain point for you?

**Comment by doggy8088** [comment]
@ayazhafiz I'm using the latest version (`0.900.15`). The UX issue still there. Let me give you an example.

1. Pick any tag, add an event binding syntax such as `(click)=""`
2. Enter `(`, enter `cli`, then hit `Tab` to complete. The current version will produce:

    ```ts
    (click|)
    ------↑
    ```

    I expected to get the following result:

    ```ts
    (click)="|"
    ---------↑
    ```

**Comment by ayazhafiz** [comment]
Okay, we will take a look at what can be done here :)

**Comment by doggy8088** [comment]
@kyliau The event binding is broken again in `v12.0.0`. There is no IntelliSense at Angular v12.0.0 version in the Visual Studio Code.

**Comment by dragonhelios** [comment]
can add to this that by changing settings to use legacy view instead of ivy the intellisense seems to be working again

**Comment by doggy8088** [comment]
@ayazhafiz The event binding's IntelliSense is still broken in `12.2.0`.

**Comment by ivanwonder** [comment]
I think we can pick the PR #820 up, move the code into `@angular/language-service`, and this feature can be opt-out via the config [`includeCompletionsWithSnippetText`](https://sourcegraph.com/github.com/microsoft/TypeScript/-/blob/lib/tsserverlibrary.d.ts?L9415:18).
@atscott
