### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kaumikaze** [angular/vscode-ng-language-service#522]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `0.900.3`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\kaumi\Angular.ng-template-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kyliau** [comment]
@kaumikaze Please use the standard issue template, and attach the relevant logs from both VSCode and the extension. Please also attach any relevant screenshots. Without these info, it is almost impossible for us to debug the problem.
Closing this for now, please open a new issue with more info, thank you.
