### ISSUE TITLE
Weird HTML syntax highlighting issue

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#526]
Latest version of everything, see screenshot.

<img width="908" alt="Screen Shot 2019-12-23 at 8 32 03 PM" src="https://user-images.githubusercontent.com/9585787/71360755-66b1cc00-25c3-11ea-8eab-48639028ebb3.png">

**Comment by ayazhafiz** [comment]
Can you provide a code listing of a minimal reproduction of this problem?

**Comment by jpike88** [comment]
1. Just declare a component, with some inline HTML.
2. Have another component with a name that DOES NOT include hyphens
3. It will be red.

<img width="655" alt="Screen Shot 2019-12-24 at 2 26 00 PM" src="https://user-images.githubusercontent.com/9585787/71400430-50eee600-2659-11ea-986f-c1b4ac5ab704.png">

In above screenshot I am referencing a component with selector 'popover'. It works fine and builds properly, but the syntax appears to be red.

Below it is a selector that doesn't exist, it is correctly underlined and listed with 'this is now a known element'. This issue sits completely with syntax highlighting logic. Component selectors should not be red just because they don't have a hyphen.

**Comment by ayazhafiz** [comment]
Okay, the PR above will fix this.
