### ISSUE TITLE
Metohd definition two times on mouse over event

### ISSUE THREAD

**Issue by rash03** [angular/vscode-ng-language-service#530]
Issue Type: <b>Bug</b>

1. Cleaned editor history
2. uninstalled all extension
3. installed Angular language service
On mouse over a method I get definition twice

Extension version: 0.900.3
VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:57:35.999Z)
OS version: Windows_NT x64 10.0.17134

**Comment by ayazhafiz** [comment]
Please use the standard bug issue template to submit a new issue with screenshots and logs attached. Without this information, it’s very difficult to tell what the problem is and how to reproduce it.
