### ISSUE TITLE
Enhance template syntax highlighting

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#538]
Loving the work so far, it's in a much better place than last year.

A couple of enhancement ideas:

![Screen Shot 2020-01-10 at 12 08 03 pm](https://user-images.githubusercontent.com/9585787/72127316-ddabda80-33a1-11ea-81c3-623e01dd1fd7.png)

if possible, ```itemChosen()```, ```env.isCordova```, the number 5 (cornerRadius expects a number), ```false``` for the ```round``` property (which expects boolean), all items in double brackets should be highlighted in a special way.

**Comment by ayazhafiz** [comment]
Thanks for the issue. These are known features we are planning to add, kept track in #483. Closing as a dupe of that.
