### ISSUE TITLE
config file not found if no TS file is open

### ISSUE THREAD

**Issue by victos** [angular/vscode-ng-language-service#546]
This is my first time to use angular language server on VSCode. After installing the extension, when I try to edit something, nothing happens.

**Logs**

`
[Info  - 2:21:16 PM] Angular language server process ID: 14573
[Info  - 2:21:16 PM] Using typescript v3.6.4 from /home/jack/.vscode-oss/extensions/angular.ng-template-0.900.4/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 2:21:16 PM] Using @angular/language-service v9.0.0-rc.8 from /home/jack/.vscode-oss/extensions/angular.ng-template-0.900.4/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 2:21:16 PM] Log file: /home/jack/.config/Code - OSS/logs/20200114T141708/exthost1/Angular.ng-template/nglangsvc.log
[Error - 2:21:19 PM] No config file for /home/jack/WorkStation/vscodeProject/my-app/src/app/app.component.html
`
![angular_language_server_issue](https://user-images.githubusercontent.com/3107600/72320174-174f4f00-36dc-11ea-9749-09a15897a29a.png)

**Comment by andrius-pra** [comment]
Do you have `tsconfig.json` file in `/home/jack/WorkStation/vscodeProject/my-app/` folder? Did you try first open `app.component.ts` and then open `app.component.html`?

**Comment by victos** [comment]
Yes, the tsconfig.json is exists and I just tried to open the files in order, and it didn't help.

**Comment by ayazhafiz** [comment]
@victos could you provide the contents of the log file mentioned in the output log as well?

**Comment by victos** [comment]
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4057876/nglangsvc.log)
Here is the log.

**Comment by Clemens-E** [comment]
Same Issue here. I'm using it on a repo where no config file was changed or moved for months, but it suddenly tells me that it can't find a config file. 
I used it on the same repo since months, and it worked just fine, but now nothing works....

**Comment by kyliau** [comment]
> Do you have `tsconfig.json` file in `/home/jack/WorkStation/vscodeProject/my-app/` folder? Did you try first open `app.component.ts` and then open `app.component.html`?

The TypeScript file needs to *stay open*. This can be done by double clicking the filename in vscode.
As seen in the screenshot, there is no TS files open.
We are very close to landing TS 3.7 in the main monorepo, and it'll fix this problem once and for all.
