### ISSUE TITLE
Server shutdown: TypeError: Cannot read property 'getSemanticDiagnostics' of undefined

### ISSUE THREAD

**Issue by simondel** [angular/vscode-ng-language-service#557]
**Describe the bug**

The Angular Language Service crashes

**To Reproduce**

Exact repro steps are a bit tricky. It seems to happen about 5-10 minutes after I open Visual Studio Code. Before it crashes, I'm also unable to navigate from a html file to a component defined in the html file. 

**Expected behavior**
No crash

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
```
[Info  - 16:03:16] Angular language server process ID: 7832
[Info  - 16:03:16] Using typescript v3.6.4 from c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 16:03:16] Using @angular/language-service v9.0.0-rc.8 from c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 16:03:16] Log file: c:\Users\USERNAME\AppData\Roaming\Code\logs\20200116T160301\exthost1\Angular.ng-template\nglangsvc.log
[Error - 16:04:43] No config file for c:\git\MYAPP.FrontEnd\MYAPP\.storybook\preview-head.html
c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\index.js:1010
	            const diagnostics = ngLS.getSemanticDiagnostics(fileName);
	                                     ^

TypeError: Cannot read property 'getSemanticDiagnostics' of undefined
    at Session.sendPendingDiagnostics (c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\index.js:1010:39)
    at Timeout._onTimeout (c:\Users\USERNAME\.vscode\extensions\angular.ng-template-0.900.4\server\index.js:990:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
[Error - 16:08:14] Connection to server is erroring. Shutting down server.
^^^ This error repeats about 450 times
```

2. Log file (Path is printed to the console output at startup)
If this is required, please contact me at simondelang@gmail.com

**Screenshots**

None

**Additional context**

Extension version: v0.900.4
@angular/core: 8.2.14

**Comment by simondel** [comment]
Removing the `coverage` folder from my project seems to solve the issue (for now)

**Comment by kyliau** [comment]
@simondel Thank you for the update. May I know what's in the `coverage` folder? Are there any Angular code or `node_modules` in there?
If possible, could you please send us the log file for the project? It's located at `c:\Users\USERNAME\AppData\Roaming\Code\logs\20200116T160301\exthost1\Angular.ng-template\nglangsvc.log`
Without detailed log entries, it is almost impossible for us to investigate this issue, especially since this is the first time we see this crash happening.
If you do not feel comfortable sharing it in public, please email it to kyliau@angular.io
Thank you!

**Comment by simondel** [comment]
In my case, the `coverage` folder contains a tree of my folders, but with no files inside. I believe there are files inside sometimes. It's simply the coverage folder generated by running the unit tests (I believe this is part of the default Angular CLI config).

I have sent you the logging :)

**Comment by sandervanteinde** [comment]
Hi @kyliau , I am a team member of Simon and am also experiencing this issue. Would it be helpful for you if I also send you the logs of my machine?
