### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ramanareddyc** [angular/vscode-ng-language-service#565]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `0.900.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Ramana Reddy\Angular.ng-template-unresponsive.cpuprofile.txt
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/4089637/Angular.ng-template-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/4089649/Angular.ng-template-unresponsive.cpuprofile.txt)

**Comment by yglin** [comment]
I'd like to report this issue, too.
It happened a few times in these 2 days, sometimes halt my entire OS for seconds.
The memory usage is very high in screenshot
<img width="708" alt="DeepinScreenshot_select-area_20200121212349" src="https://user-images.githubusercontent.com/5110555/72808788-4003b580-3c95-11ea-9c21-45ccde105a83.png">

System OS: Linux Mint 19.3 Tricia
Kernel: 5.3.0-26-generic x86_64
VSCode version: 1.41.1
Angular Language Service Extension Version: 0.900.4

**Comment by ayazhafiz** [comment]
Hi! Please use the standard issue template, and attach the relevant logs from both VSCode and the extension. Please also attach any relevant screenshots. We would love to help solve this issue, and without these info, it is almost impossible for us to debug the problem.
Closing this for now, please open a new issue with more info, thank you.
