### ISSUE TITLE
Debug enabled when  NG_DEBUG env variable is set to false

### ISSUE THREAD

**Issue by jabby** [angular/vscode-ng-language-service#579]
**Describe the bug**

I worked on Wild Web Developer and we integrated the angular-language-server to provide support of Angular in Eclipse. One of our user ask us why we run angular language server into debug mode. I ding into this issue and found a problem in our code. In fact, we always add NG_DEBUG='true' to our process env. 

I set the env variable to false but when I checked the result for the end user, the information message `Angular Language Service is running under DEBUG mode` was always printed. 

After a quick look into the server.ts code, I think the problem is about truthy / falsy values in JS. 
As you can see in the following code, condition about NG_DEBUG does not validate the type of the env variable. 

```js
if (process.env.NG_DEBUG) {
  session.info('Angular Language Service is running under DEBUG mode');
}
if (process.env.TSC_NONPOLLING_WATCHER !== 'true') {
  session.warn(`Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.`);
}
```

Accordingly to the nodejs documentation and especiallt the linux manual documentation, `The variable environ points to an array of pointers to strings called the "environment"`. So I guess we have a string instead of a boolean.

* https://nodejs.org/api/process.html#process_process_env
* http://man7.org/linux/man-pages/man7/environ.7.html

**To Reproduce**

* Set NG_DEBUG=false in a shell 
* Launch angular language server
* Check the log, there is the following message `Angular Language Service is running under DEBUG mode`

**Expected behavior**

Debug mode should be enabled only when NG_DEBUG is set to true.

**Workaround**

Does not set the NG_DEBUG env variable.

**Comment by ayazhafiz** [comment]
Thank you for this report. The PR linked above should fix this
