### ISSUE TITLE
The TypeScript extension crashed

### ISSUE THREAD

**Issue by CsabaMarko** [angular/vscode-ng-language-service#582]
Issue Type: <b>Bug</b>

Not sure. It happened randomly.

Extension version: 0.900.7
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (2.36GB free)|
|Process Argv|--extensions-dir /Users/csaba/.vscode/extensions_angular|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ayazhafiz** [comment]
Hi, thanks for the report. Unfortunately, with the amount of information provided, it is very difficult to investigate the cause of this issue. Please open another issue following the standard issue template provided by this repository, including logs from the Angular extension.
