### ISSUE TITLE
Error on Sub Component "Not a Known Element"

### ISSUE THREAD

**Issue by thesaadmirza** [angular/vscode-ng-language-service#588]
On Sub Components, if you try to add a child component in the parent component, it will give you an error that this is not a know Element even if you defined those in-app module declarations.

**To Reproduce**

1. Create a Component
2. Create its 1st Child Component
3. Now Create Another child under 1st Child Component, naming it as 1.1st Child.
4. Now try to add 1st child component in the parent Component

**Expected behavior**
It Should not give Error

**Logs**

'app-recipe-list' is not a known element:
1. If 'app-recipe-list' is an Angular component, then verify that it is part of this module.
2. If 'app-recipe-list' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this

**Screenshots**

![Screenshot 2020-01-28 12 55 51](https://user-images.githubusercontent.com/14211943/73245315-c7898100-41cd-11ea-9438-666bdd52fd96.png)
![Screenshot 2020-01-28 12 55 57](https://user-images.githubusercontent.com/14211943/73245316-c8221780-41cd-11ea-96f3-31da852b8dad.png)
![Screenshot 2020-01-28 12 56 03](https://user-images.githubusercontent.com/14211943/73245317-c8221780-41cd-11ea-856c-c35516df4861.png)
![Screenshot 2020-01-28 12 56 11](https://user-images.githubusercontent.com/14211943/73245318-c8221780-41cd-11ea-885d-1ca2e6ba740d.png)

**Comment by BO41** [comment]
Does it transpile?

What is the definition of `RecipeListComponent`?
Do you have an attribute selector on it?
`selector: 'app-recipe-list[someAttribute]',`

**Comment by thesaadmirza** [comment]
![Screenshot 2020-01-28 16 48 34](https://user-images.githubusercontent.com/14211943/73261573-2f4fc400-41ee-11ea-82fc-4395af2bcb97.png)
![Screenshot 2020-01-28 16 49 27](https://user-images.githubusercontent.com/14211943/73261574-2fe85a80-41ee-11ea-83c5-c647a9939d26.png)

**Comment by ayazhafiz** [comment]
Can you copy/paste code snippets for the NgModules all of these components/directives are defined in?

**Comment by thesaadmirza** [comment]
`import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";

import { AppComponent } from "./app.component";
import { HeaderComponent } from "./header/header.component";

import { RecipeListComponent } from "./recipes/recipe-list/recipe-list.component";
import { RecipesComponent } from "./recipes/recipes.component";
import { RecipeDetailComponent } from "./recipes/recipe-detail/recipe-detail.component";
import { RecipeItemComponent } from "./recipes/recipe-list/recipe-item/recipe-item.component";
import { ShoppingListComponent } from "./shopping-list/shopping-list.component";
import { ShoppingEditComponent } from "./shopping-list/shopping-edit/shopping-edit.component";
import { DropdownDirective } from "./shared/dropdown.directives";
import { shoppingListService } from "./shopping-list/shopping-list.service";

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    RecipeListComponent,
    RecipesComponent,
    RecipeDetailComponent,
    RecipeItemComponent,
    ShoppingListComponent,
    ShoppingEditComponent,
    DropdownDirective
  ],
  imports: [BrowserModule],
  providers: [shoppingListService],
  bootstrap: [AppComponent]
})
export class AppModule {}`

**Comment by ayazhafiz** [comment]
I cannot reproduce this issue. @thesaadmirza can you make a version of this issue that uses a small number, e.g. 2 or 3 components? If we have all the code and it is a small example it will be easier to debug the problem.

Also, what versions of the language service and typescript are you using? (see https://github.com/angular/vscode-ng-language-service/blob/master/.github/ISSUE_TEMPLATE/bug_report.md for how to get this)

**Comment by ayazhafiz** [comment]
Friendly ping @thesaadmirza -- can you provide the details above?

**Comment by ayazhafiz** [comment]
Closing due to a lack of activity. If you are still experiencing this issue, feel free to comment and we can re-open, or open a new issue.
