### ISSUE TITLE
Red Highlighted greater sign on the right syntax

### ISSUE THREAD

**Issue by julioelifas** [angular/vscode-ng-language-service#595]
![Desktop Screenshot 2020 01 30 - 21 12 32 46](https://user-images.githubusercontent.com/60472725/73452813-a9767900-43a5-11ea-968a-ad0b79bafd41.png)
**Describe the bug**

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

**To Reproduce**

**Expected behavior**

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
2. Log file (Path is printed to the console output at startup)

**Screenshots**

![Example Screenshot](./output.png)

**Additional context**

**Comment by ayazhafiz** [comment]
This appears to be the same as #575. Marking as a duplicate.
