### ISSUE TITLE
There's nothing happens after I install the extensions.

### ISSUE THREAD

**Issue by victos** [angular/vscode-ng-language-service#599]
**Describe the bug**

After installing the extension, when I try to edit something, nothing happens.

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
[Info  - 10:17:18 AM] Angular language server process ID: 6437
[Info  - 10:17:18 AM] Using typescript v3.7.4 from /home/jack/.vscode-oss/extensions/angular.ng-template-0.900.8/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 10:17:18 AM] Using @angular/language-service v9.0.0-rc.12 from /home/jack/.vscode-oss/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 10:17:18 AM] Log file: /home/jack/.config/Code - OSS/logs/20200131T101715/exthost1/Angular.ng-template/nglangsvc.
2. Log file 
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4137252/nglangsvc.log)

**Screenshots**
![angular_language_server_not_work](https://user-images.githubusercontent.com/3107600/73507402-cc3f7680-4413-11ea-8b71-f54c31d391e1.png)

**Comment by ayazhafiz** [comment]
What do you expect to happen? It looks like the language service is recommending `ng-container`.

**Comment by victos** [comment]
the ngIf should be there right ?

**Comment by ayazhafiz** [comment]
No. Only if you do `*ng..`.


________________________________
От: victos <notifications@github.com>
Отправлено: воскресенье, февраля 2, 2020 1:48 AM
Кому: angular/vscode-ng-language-service
Копия: hafiz; Comment
Тема: Re: [angular/vscode-ng-language-service] There's nothing happens after I install the extensions. (#599)


the ngIf should be there right ?

**Comment by victos** [comment]
![no-ngif](https://user-images.githubusercontent.com/3107600/73619137-de652300-4666-11ea-92ba-3b5f58af4743.png)

**Comment by ayazhafiz** [comment]
Can you provide more information? It is difficult to diagnose what the problem here is by only showing the template. What component does the template belong to, and what module is the template declared in? For example, the `ngIf` directive may not be loaded if your module does not import `CommonModule` from `@angular/core`.

If you are able to provide a minimal code snippet and an explanation of the issue you are seeing, it would be very much appreciated. Thank you!

**Comment by victos** [comment]
Hi, it works now after I reinstall all the dependencies. I don't know why, but it works. Thank you.
