### ISSUE TITLE
Memory usage too high

### ISSUE THREAD

**Issue by kepicorp** [angular/vscode-ng-language-service#602]
Issue Type: <b>Bug</b>

The extension keep crashing because of memory ussage
```bash
dmesg | tail
```
[ 1170.629476] [   5507]  1000  5507   173857        0   626688     3153             0 io.elementary.t
[ 1170.629478] [   5515]  1000  5515    12893        1   106496     1222             0 bash
[ 1170.629480] [   5914]  1000  5914   674593     1507  1196032    10626             0 Web Content
[ 1170.629482] [   5972]  1000  5972   652890        0   884736     4439             0 Web Content
[ 1170.629484] [   6300]  1000  6300   147822     9113  1564672       64             0 code
[ 1170.629486] [   6301]  1000  6301  1974137  1664185 20668416    24044             0 code
[ 1170.629488] [   6316]  1000  6316   145300     6633  1441792       73             0 code
[ 1170.629490] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice,task=code,pid=6301,uid=1000
[ 1170.629526] Out of memory: Killed process 6301 (code) total-vm:7896548kB, anon-rss:6656740kB, file-rss:0kB, shmem-rss:0kB
[ 1170.926319] oom_reaper: reaped process 6301 (code), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

Extension version: 0.900.8
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.3.0-28-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m7-6Y75 CPU @ 1.20GHz (4 x 2673)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|7.46GB (5.25GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ayazhafiz** [comment]
Hi! Please use the standard issue template, and attach the relevant logs from both VSCode and the extension. We would love to help solve this issue, and without these info, it is almost impossible for us to debug the problem.
Closing this for now, please open a new issue with more info, thank you.
