### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by asphub** [angular/vscode-ng-language-service#615]
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `0.900.9`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/4158606/Angular.ng-template-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ayazhafiz** [comment]
Hi! Please use the standard issue template, and attach the relevant logs from both VSCode and the extension. We would love to help solve this issue, and without these info, it is almost impossible for us to debug the problem.  Closing this for now, please open a new issue with more info, thank you.
