### ISSUE TITLE
Position of "let i = index" inside *ngFor breaks syntax check

### ISSUE THREAD

**Issue by Etiake** [angular/vscode-ng-language-service#617]
The position of "let i = index" inside a *ngFor declaration seems effect the detection of html and errors.

**To Reproduce**

- Create a *ngFor like this:
![image](https://user-images.githubusercontent.com/46519278/73960297-e6dd8800-490a-11ea-9334-6cacedad234f.png)

- Add a loop on index:
![image](https://user-images.githubusercontent.com/46519278/73959555-c6f99480-4909-11ea-9f94-8f64d83256db.png)
As you can see, the colors changed and detect that the syntax is wrong in some elements.

- Put the loop at the start of *ngFor:
 ![image](https://user-images.githubusercontent.com/46519278/73959748-1a6be280-490a-11ea-9f42-c33304450ed8.png)
No errors or wrong colors.

**Expected behavior**

I think that the position of "let i = index" should not effect the syntax detection

**Comment by ayazhafiz** [comment]
This is a known issue; see #575. There is an open PR to fix known syntax highlighting bugs: #609
