### ISSUE TITLE
Not recognizing second expression for directives

### ISSUE THREAD

**Issue by sevspo** [angular/vscode-ng-language-service#620]
**Describe the bug**

Not recognizing second expression for *ngFor directive

**To Reproduce**

Add a second expression to a directive

**Screenshot**

![Annotation 2020-02-07 145434](https://user-images.githubusercontent.com/17132540/74035037-cae4ef80-49b9-11ea-9004-42acc1239609.jpg)

**Comment by sitterrus** [comment]
That's probably https://github.com/angular/vscode-ng-language-service/issues/575 issue related

**Comment by ayazhafiz** [comment]
yes
