### ISSUE TITLE
Invalid Template variables don't show up as an error

### ISSUE THREAD

**Issue by johnpapa** [angular/vscode-ng-language-service#621]
**Describe the bug**

When typing an invalid model into a template file, no errors are displayed. Notice in the image below that `fred` is not a valid model. When building we see this error. But we should see it in the template as an error with a red squiggly underline

![image](https://user-images.githubusercontent.com/1202528/74079476-03aab600-4a06-11ea-9553-a3ead3a8b067.png)

**Comment by ayazhafiz** [comment]
Can you please provide the source code you are experiencing this issue with and the relevant logs from the extension, as requested in the bug report issue template you used when filing this issue (https://github.com/angular/vscode-ng-language-service/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by johnpapa** [comment]
I tried to repro today and it is not happening now.

I guess you can close this (although as you can see in the above image it DID happen).

If it happens again, I will open an issue
