### ISSUE TITLE
New models do not appear in intellisense in templates

### ISSUE THREAD

**Issue by johnpapa** [angular/vscode-ng-language-service#622]
**Describe the bug**

1. add a new model to a component
2. go to the html template file for that component
3. try to use it ... notice intellisense has no awareness of it

![2020-02-08_00-02-38 (1)](https://user-images.githubusercontent.com/1202528/74079551-fa6e1900-4a06-11ea-968b-ee2174f07e88.gif)

using angular 9

**Comment by ayazhafiz** [comment]
Can you please provide the source code you are experiencing this issue with and the relevant logs from the extension, as requested in the bug report issue template you used when filing this issue (https://github.com/angular/vscode-ng-language-service/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by johnpapa** [comment]
I tried to repro today and it is not happening now. 

I guess you can close this (although as you can see in the above image it DID happen).

If it happens again, I will open an issue
