### ISSUE TITLE
*matCellDeff or let broke html intellisense

### ISSUE THREAD

**Issue by wupaz** [angular/vscode-ng-language-service#633]
**Describe the bug**

*matCellDeff seem broke intellisence.

**To Reproduce**

1. Create an html file 
2. Paste this code

```
    <mat-header-cell *matHeaderCellDef> Date </mat-header-cell>
    <mat-cell *matCellDef="let row"> {{row.date}} </mat-cell>

    <mat-header-cell *matHeaderCellDef> Date </mat-header-cell>
    <mat-cell *matCellDef="let row"> {{row.problemName}} </mat-cell>

    <mat-header-cell *matHeaderCellDef> Date </mat-header-cell>
    <mat-cell *matCellDef="let row"> {{row.serviceName}} </mat-cell>
```

![image](https://user-images.githubusercontent.com/14102653/74457360-26016100-4e56-11ea-94c3-acb3ad15e2ca.png)

If I add a space after *matCellDef like  "*matCellDef =" bug disapear. 
I only enable language service extension. (disapear if I disable extension)

![image](https://user-images.githubusercontent.com/14102653/74458368-978ddf00-4e57-11ea-9823-5c79bec3e35e.png)

And some function like comment lines (ctrl +/) are broken

![image](https://user-images.githubusercontent.com/14102653/74458471-c0ae6f80-4e57-11ea-827b-95aba6bac101.png)

**Logs**

No log...

I see https://github.com/angular/vscode-ng-language-service/issues/607 but it's not same issue
and I didn't have babel extension, I have only enable for sure language service

![image](https://user-images.githubusercontent.com/14102653/74459340-22230e00-4e59-11ea-8c07-103d6d981094.png)

**Comment by ayazhafiz** [comment]
This is a known problem with a mention in #575. #609 should fix it.
