### ISSUE TITLE
Extension causes high cpu load in Ivy

### ISSUE THREAD

**Issue by Achutharaman** [angular/vscode-ng-language-service#636]
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/4204263/Angular.ng-template-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `ng-template`
- Extension Version: `0.900.12`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.0`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ayazhafiz** [comment]
Thanks for the report. Looks like this the high load is caused by the language service client in the extension, especially at startup. I don't have time to look deeper right now; any help is appreciated.

**Comment by muhammedMoussa** [comment]
it's a very annoying issue, especially at large projects I have to wait from 5:10 minutes till vs code comes up. so every morning after wakeup I open vs code then got to the washroom. 
not only on the startup. every time I generate new service, components, or adding simple util.

**Comment by jeandat** [comment]
I do have also very poor performances with this extension. In my case, it works fine when starting but after a few minutes/compilations, intellisense doesn't work anymore and generally CPU is very high (code helper process).

**Comment by MakePixelsWork** [comment]
Visual Studio Code redirected me to this page. I also have an high CPU load. Attached the 'Angular.ng-template-unresponsive.cpuprofile.txt' as asked by VS Code.
[Angular.ng-template-unresponsive.cpuprofile.txt](https://github.com/angular/vscode-ng-language-service/files/5609652/Angular.ng-template-unresponsive.cpuprofile.txt)

**Comment by lucsarruda** [comment]
Hi,

someone solved this problem?

I have this problem and it is because of the extension

high CPU consumption and crashes everything because of extension

**Comment by doncid** [comment]
Same issue here.

**Comment by earshinov** [comment]
Same issue for me.

```
"C:\Users\earshinov\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\earshinov\.vscode\extensions\angular.ng-template-11.2.7\server --logToConsole --logFile c:\Users\earshinov\AppData\Roaming\Code\logs\20210314T225026\exthost6\Angular.ng-template\nglangsvc.log --logVerbosity verbose --ngProbeLocations c:\Users\earshinov\.vscode\extensions\angular.ng-template-11.2.7,c:\NVIDIA\dev\GRT\frontend --experimental-ivy --tsProbeLocations c:\Users\earshinov\.vscode\extensions\angular.ng-template-11.2.7,c:\NVIDIA\dev\GRT\frontend --node-ipc --clientProcessId=20448
```

This command always eats up one CPU core for me, no matter how long I keep VS Code running (even a day). I've been observing this issue for a week now.

Also, "Go to Definition" is incredibly slow for me, taking from 10-20 seconds to forever, similarly to #1176 which is assumed to be fixed.

I am using the latest version of the extension (v11.2.7).

**Comment by earshinov** [comment]
Same issue with v11.2.8.

Issue tags say `need-repro`. Can I perhaps be of any help with this? I observe this issue as reliably as it could be - CPU usage gets high as soon as I open the workspace and never stops.

**Comment by tonyholt** [comment]
This is happening for me as well.  Once I disabled it, the CPU usage returned to normal.

**Comment by loic49** [comment]
For me, the problem appear with version 11.2.4. Before this version no problem.

**Comment by kyliau** [comment]
@earshinov Could you please set `tracing` to `messages` (see screenshot below), and help us identify which request is taking the most time? Answering the following questions would really help us understand the root cause:

1. Which OS are you using?
2. What's your vscode version?
3. When did you encounter slowness? (when typing in external template / when working on TS source file, etc)
4. Did you run `ng serve` in the background?
5. Is your project using View Engine or Ivy?

Please give us as much information as possible. If it is not possible for you to share the project you are working on, please consider sharing the log file privately (kyliau@angular.io).

In version 12 (May 2021), we will make Ivy the default, so fixing performance issue in Ivy is our main focus. It is unlikely that we'll fix the View Engine mode (`experimental-ivy` set to false).

We are also working on adding performance logging, which will help us identify bottlenecks.

<img width="1144" alt="Screen Shot 2021-03-31 at 1 41 27 PM" src="https://user-images.githubusercontent.com/2941178/113208588-d54df280-9226-11eb-900c-20ee3568b698.png">

**Comment by earshinov** [comment]
@kyliau

My VS Code user settings:

```
{
  "angular.experimental-ivy": true,
  "angular.enable-experimental-ivy-prompt": false,
  "angular.trace.server": "messages",
  <snip>
}
```

Version information:

```
OS: Windows_NT x64 10.0.19042
Visual Studio Code: 1.54.3 (user setup)
```

> Did you run ng serve in the background?

No

> Is your project using View Engine or Ivy?

Ivy

> When did you encounter slowness?

[ ] Angular template
[x] TypeScript source

> Could you please set tracing to messages (see screenshot below), and help us identify which request is taking the most time?

Where should I look for this information? The `nglangsvc.log` file doesn't contain any logs for the past 2 hours, but the process

```
"C:\Users\earshinov\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\earshinov\.vscode\extensions\angular.ng-template-11.2.9\server --logToConsole --logFile c:\Users\earshinov\AppData\Roaming\Code\logs\20210331T110318\exthost8\Angular.ng-template\nglangsvc.log --logVerbosity verbose --ngProbeLocations c:\Users\earshinov\.vscode\extensions\angular.ng-template-11.2.9,c:\myproject --experimental-ivy --tsProbeLocations c:\Users\earshinov\.vscode\extensions\angular.ng-template-11.2.9,c:\myproject --node-ipc --clientProcessId=27748
```

is still consuming 1 CPU core. Also, what I see in the log file doesn't seem very useful for identifying bottlenecks:

```
Info 14159[15:18:6.432] ConfigFilePresence:: Current Watches: :: File: c:/myproject/projects/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: c:/myproject/projects/grt/src/app/dq/dq.routes.ts,c:/myproject/projects/grt/src/app/freeform-dlss/routes.ts,c:/myproject/projects/shared/src/core/service/telemetry.service.ts Status: File removed from open files impacted by this config file
Info 14160[15:18:6.432] ConfigFilePresence:: Current Watches: :: File: c:/myproject/projects/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: c:/myproject/projects/grt/src/app/dq/dq.routes.ts,c:/myproject/projects/grt/src/app/freeform-dlss/routes.ts,c:/myproject/projects/shared/src/core/service/telemetry.service.ts Status: File removed from open files impacted by this config file
Info 14161[15:18:6.432] ConfigFilePresence:: Current Watches: Config file:: File: c:/myproject/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: c:/myproject/projects/grt/src/app/dq/dq.routes.ts,c:/myproject/projects/grt/src/app/freeform-dlss/routes.ts,c:/myproject/projects/shared/src/core/service/telemetry.service.ts Status: File removed from open files impacted by this config file
Info 14162[15:18:6.432] FileWatcher:: Added:: WatchInfo: c:/myproject/projects/grt/src/app/freeform-gfn/freeform-gfn.routes.ts 500 undefined Project:  WatchType: Closed Script info
Info 14163[15:18:6.432] Project 'c:/myproject/tsconfig.json' (Configured)
	Files (3272)

-----------------------------------------------
Open files: 
	FileName: c:/myproject/projects/grt/src/app/dq/dq.routes.ts ProjectRootPath: undefined
		Projects: c:/myproject/tsconfig.json
	FileName: c:/myproject/projects/grt/src/app/freeform-dlss/routes.ts ProjectRootPath: undefined
		Projects: c:/myproject/tsconfig.json
	FileName: c:/myproject/projects/shared/src/core/service/telemetry.service.ts ProjectRootPath: undefined
		Projects: c:/myproject/tsconfig.json
```

**Comment by Rafael-Rezende** [comment]
Same issue here.

**Comment by kfeinUI** [comment]
Very much an issue for me. Typically eats up to 50-70% of my hefty CPU. This is with it just idling. Hopped back in to an Angular project recently after some time way, so I'm afraid I can't pinpoint when the problem was introduced.

VS Code Process Explorer Entry:
> "C:\Program Files\Microsoft VS Code\Code.exe" c:\Users\XXXX\.vscode\extensions\angular.ng-template-11.2.10\server --logToConsole --ngProbeLocations c:\Users\XXXX\.vscode\extensions\angular.ng-template-11.2.10,d:\Projects\web,d:\Projects\webroot --experimental-ivy --tsProbeLocations c:\Users\XXXX\.vscode\extensions\angular.ng-template-11.2.10,d:\Projects\web,d:\Projects\webroot --node-ipc --clientProcessId=22988
**59** <=== CPU
25
33288

Win 7, Node 12, Angular 11.2.6, latest of the production VS Code + extension.
