### ISSUE TITLE
Better module imports in VSCode possible?

### ISSUE THREAD

**Issue by kresdjan** [angular/vscode-ng-language-service#642]
I apologize if this isn't the right place. But I am trying to make VSCode better at importing Angular modules. Take a brand new Angular app created with the CLI as an example. It has the following dependencies installed.
```.json
"dependencies": {
    "@angular/animations": "~9.0.1",
    "@angular/common": "~9.0.1",
    "@angular/compiler": "~9.0.1",
    "@angular/core": "~9.0.1",
    "@angular/forms": "~9.0.1",
    "@angular/platform-browser": "~9.0.1",
    "@angular/platform-browser-dynamic": "~9.0.1",
    "@angular/router": "~9.0.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  }
``` 
But VSCode can't help importing those modules, like `ReactiveFormsModule` or `HttpClientModule` into `app.module.ts`. It has no clue.  You have to manually type the import statement `import { ReactiveFormsModule } from '@angular/forms';` or adding type definitions to `tsconfig.ts` 

```.json
{
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@angular",
      "node_modules/@angular/common",
    ],
  },
}
```
  

Is there something to be included in the Language Service that will expose Angular dependencies?

**Comment by ayazhafiz** [comment]
The language service could provide a suggestion to import a module, but this would be duplicating the job of tsserver in VSCode. Unfortunately, I think adding type definitions to `tsconfig.ts` is the best way to go. Otherwise, a language service (either Angular's or TypeScript's) does not have a reliable way of knowing what type definitions exist and can be imported in your project without scanning all of `node_modules`, which will not work in all cases and is very expensive.

**Comment by ayazhafiz** [comment]
@kresdjan do you have any feedback?

**Comment by kresdjan** [comment]
@ayazhafiz No unfortunately I don't. Maybe this discussion doesn't even belong here, but in Microsoft's vscode or typescript repo...

**Comment by ayazhafiz** [comment]
Okay. Yeah, I think this relates more directly to a feature of the TypeScript language service. Closing for now, feel free to reopen or file another issue if you have any other ideas.

**Comment by kyliau** [comment]
There is an existing ticket for this issue: https://github.com/angular/angular-cli/issues/16879
There are some relevant discussions there, we'll track the work in the other issue.
