### ISSUE TITLE
Extension messing with html colorization

### ISSUE THREAD

**Issue by jbw91** [angular/vscode-ng-language-service#65]
After installing this extension, my html element colorization has been messed up. See screenshot below.

<img width="310" alt="screen shot 2017-04-05 at 10 24 46 am" src="https://cloud.githubusercontent.com/assets/5883616/24715844/2fd6781c-19ea-11e7-9d8d-d1f681629605.png">

I uninstalled the extension to make sure it was this extension, and the colorization went back to how it should be, shown below:

<img width="314" alt="screen shot 2017-04-05 at 10 27 55 am" src="https://cloud.githubusercontent.com/assets/5883616/24715988/9393087a-19ea-11e7-83dd-292ac137abdb.png">

Upon re-installing, the colorization was messed up again.

**Comment by chuckjaz** [comment]
It appears the grammar I have is messing with the `html`. I thought it would only add it if you used one of the extensions I registered. I will remove this in the next release as it is not necessary.
