### ISSUE TITLE
Typeching of context doesn't work with custom directives

### ISSUE THREAD

**Issue by tonivj5** [angular/vscode-ng-language-service#650]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/language-service

### Is this a regression?

No

### Description

Typechecking of context doesn't work. I have copied the ngIf directive and rename it to myIf to test it:
- Code ![image](https://user-images.githubusercontent.com/7110786/74464351-a98d7300-4e93-11ea-8710-dcc14d404277.png)
- with ngIf test is null ![image](https://user-images.githubusercontent.com/7110786/74464387-bad67f80-4e93-11ea-84ad-70676eb45a35.png)
- with myIf test is any ![image](https://user-images.githubusercontent.com/7110786/74464401-c033ca00-4e93-11ea-9152-3b9c411bfc2a.png)

## 🔬 Minimal Reproduction
https://github.com/tonivj5/angular-issues-35424-and-35426

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.2
Node: 13.7.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by ayazhafiz** [comment]
This is a bug. The language service should read from the directive template context rather than provide the one-off typings for ngFor. We already have the infrastructure for getting the template context of a structural directive, so this shouldn't be too difficult to fix..

**Comment by tonivj5** [comment]
Thanks @ayazhafiz for the clarification :+1:. I think https://github.com/angular/angular/pull/35561 should fix it, shouldn't?

Related https://github.com/angular/vscode-ng-language-service/issues/649 (relation lost in the transfer :rocket:)

**Comment by tonivj5** [comment]
Ey @ayazhafiz, I have tryed this feature again with the last release (`9.1.0`), but it doesn't work :laughing: I don't know if it's a regression of the latest release or never worked (I didn't test it again, I've been very busy until now :sweat_smile:)

I have updated the demo to the latest Angular, and `test` follow being `any`. Can this issue be reopen or I should open a new one?

**Comment by ayazhafiz** [comment]
Weird, this should not be the case... what version of the language service/language server extension are you using?

**Comment by tonivj5** [comment]
I'm using the latest of both (`9.1.0`)
![image](https://user-images.githubusercontent.com/7110786/77770593-c944b900-7045-11ea-8519-98cf2035aad4.png)

**Comment by ayazhafiz** [comment]
Hmm okay I will take a look soon

________________________________
От: Toni Villena <notifications@github.com>
Отправлено: Friday, March 27, 2020 8:13:23 AM
Кому: angular/vscode-ng-language-service <vscode-ng-language-service@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Mention <mention@noreply.github.com>
Тема: Re: [angular/vscode-ng-language-service] Typeching of context doesn't work with custom directives (#650)


I'm using the latest of both (9.1.0)
[image]<https://user-images.githubusercontent.com/7110786/77770593-c944b900-7045-11ea-8519-98cf2035aad4.png>

**Comment by tonivj5** [comment]
Thanks :+1:

**Comment by ayazhafiz** [comment]
@tonivj5 I see, it doesn't work with the `MyIf` directive. This is a known problem that won't be fix until we flip the language service to Ivy. Basically the issue is that today the language service cannot resolve generic type parameters.

For `NgIf` we have a special case to look up the type of the variable bound to the directive, but we can't do this for every custom directive.

**Comment by tonivj5** [comment]
So, I will have to wait to use this feature :cry:. I suppose it will happen with Angular 10, won't?

Can this issue hold open meanwhile?

Thanks anyway for the time invested :smile:. I will look forward to this feature :zap:

**Comment by ayazhafiz** [comment]
@kyliau can give us some more insight. Ivy is scheduled to land with 10, right? Do we have an existing issue keeping track of the generic bindings problem?
