### ISSUE TITLE
Why doesn't appear event names in html template?

### ISSUE THREAD

**Issue by roqueorts** [angular/vscode-ng-language-service#656]
Is there any reason when you press Ctrl + Space in a html element, **not showing** all possible event names for Angular?, for example:

<button (click)=""></button> Pressing Ctrl + Space inside the button tag, VS Code should show:

(click) or on-click
(mouseover) or on-mouseover
...and all possible events

Version extension installed:  0.900.14
TypeScript: 3.7.5
@angular/language-service: 9.0.2
VS code version:  1.42.1

Regards

**Comment by ayazhafiz** [comment]
Today we intentionally show events only when parantheses are opened or the on- prefix is present. The PR/reasoning is at https://github.com/angular/angular/pull/34445. @roqueorts is this impacting you strongly? Can you elaborate on why events/properties missing before the ()/[]/on-/bind- prefix missing is an issue?

**Comment by roqueorts** [comment]
It works.
Thanks
