### ISSUE TITLE
Cannot resolve definitions from pnpm modules

### ISSUE THREAD

**Issue by lucas-labs** [angular/vscode-ng-language-service#657]
**Describe the bug**

We are getting an error when using some pipes since we updated Angular Language Service to 0.900.14. 

For example, in one of our components we have the following variable:

```
export class LuBadgeComponent implements OnInit {
    @Input() label: string;
    ...
}
```

Then, in the template we use the uppercase pipe on it:

```
<p>
    {{ label | uppercase }}
</p>
```

And we're getting the following error in VS Code:

![image](https://user-images.githubusercontent.com/12949236/75096108-05828680-557b-11ea-93e3-bc557d071cf6.png)

**To Reproduce**

1. Create a component with a string variable
2. Use the uppercase pipe on the variable inside the template

(see the example above)

**Expected behavior**

We expect no error from this piece of code since the code compiles correctly:

![image](https://user-images.githubusercontent.com/12949236/75096147-7033c200-557b-11ea-8f21-a0eb37439fda.png)

**Logs**

Please attach two logs:

1. Console output 

```
[Info  - 18:18:10] Angular language server process ID: 8428
[Info  - 18:18:10] Using typescript v3.7.4 from c:\Users\lucas\.vscode\extensions\angular.ng-template-0.900.14\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 18:18:10] Using @angular/language-service v9.0.2 from c:\Users\lucas\.vscode\extensions\angular.ng-template-0.900.14\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 18:18:10] Log file: c:\Users\lucas\AppData\Roaming\Code\logs\20200221T181704\exthost1\Angular.ng-template\nglangsvc.log
```

2. Log file
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4239649/nglangsvc.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/12949236/75096108-05828680-557b-11ea-93e3-bc557d071cf6.png)

**Additional context**

**Comment by ayazhafiz** [comment]
Do you have `@angular/common` in your node_modules? I think it is unable to resolve the pipe because the module could be missing.

**Comment by lucas-labs** [comment]
Hi @ayazhafiz, thanks for the answer. I do have @angular/common in my node_modules.

![image](https://user-images.githubusercontent.com/12949236/75131255-dc641200-56b0-11ea-9336-00643ac75487.png)

But, I'm using pnpm and not npm. May that be the problem? The app compiles ok and I'm sure it was working fine and without showing this error in vscode like 2 months ago.

**Comment by lucas-labs** [comment]
@ayazhafiz Regarding your question about my Angular version, I'm working with v8.2.8:

![image](https://user-images.githubusercontent.com/12949236/75131373-90fe3380-56b1-11ea-8dce-e60e367f4d2c.png)

**Comment by lucas-labs** [comment]
@ayazhafiz Regarding your question about my Angular version, I'm working with v8.2.8 in this project:
![image](https://user-images.githubusercontent.com/12949236/75131481-079b3100-56b2-11ea-8d0d-5d7d187f2f67.png)

**Comment by ayazhafiz** [comment]
I think pnpm is the issue. I just made a project with pnpm and repro'd your issue

**Comment by ayazhafiz** [comment]
Not sure what we need to do to support pnpm. Looks like there is some existing issues with this on the TS side (https://github.com/microsoft/TypeScript/pull/35206, https://github.com/microsoft/TypeScript/issues/29221). Community contributions and suggestions are welcome.

**Comment by clov3r** [comment]
Doesn't appear to be just pnpm. I just started getting these same errors tonight, using regular npm. 

<img width="628" alt="Screen Shot 2020-02-25 at 22 13 05pm" src="https://user-images.githubusercontent.com/3375161/75314191-46e59100-581c-11ea-92c9-1f2b17410894.png">

<img width="377" alt="Screen Shot 2020-02-25 at 22 13 49pm" src="https://user-images.githubusercontent.com/3375161/75314206-549b1680-581c-11ea-8a71-356d89edfbd5.png">
<img width="341" alt="Screen Shot 2020-02-25 at 22 14 00pm" src="https://user-images.githubusercontent.com/3375161/75314211-5664da00-581c-11ea-9e20-b824c61a61f8.png">

**Comment by ayazhafiz** [comment]
@clov3r can you provide us with more details (per https://github.com/angular/vscode-ng-language-service/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? There are a number of reasons this error might appear.

**Comment by ivanwonder** [comment]
```
{
  "compilerOptions": {
    "preserveSymlinks": true
  }
}
```
I have submitted a PR.
@lucas-labs @clov3r I think this config can resolve the problem too.

**Comment by ayazhafiz** [comment]
Fixed by @ivanwonder's PR :)
