### ISSUE TITLE
Intellisense no longer working in html

### ISSUE THREAD

**Issue by nirajkheria** [angular/vscode-ng-language-service#659]
Until yesterday my intellisense and suggestions were all working in my visual studio code html template file for angular. But suddenly it stopped working. I even reinstalled vs code and all extensions but to no avail.
Please help.

**Comment by ayazhafiz** [comment]
Please open a new issue with the information requested in the standard bug issue template. Without that information it is impossible for us to diagnose the problem and help you out. Thanks.
