### ISSUE TITLE
Syntax Highlighting issue for non-angular html

### ISSUE THREAD

**Issue by jecraig** [angular/vscode-ng-language-service#667]
**Describe the bug**
When using Angular in conjunction with PHP in vscode the highlighting doesn't appear to work correctly. PHP uses the same bracketing system that Angular does so I'm sure it's getting confused over that.

**To Reproduce**

Use a *.html.twig file with the Twig plugin to enable html syntax highlighting. Use curly brackets with something code like in them, such as a tuple.

**Expected behavior**

It would be nice if there was a way to just allow the service to ignore certain files. 

**Screenshots**
Showing the issue (notice the red angle bracket at the furthest right)
![image](https://user-images.githubusercontent.com/20190406/75730173-5eec6300-5ca9-11ea-8576-777306f6c241.png)

Show the same page with this extension disabled
![image](https://user-images.githubusercontent.com/20190406/75730212-73c8f680-5ca9-11ea-9cef-6d5dde2c9929.png)

**Comment by ayazhafiz** [comment]
Can you provide a minimal code snippet we can copy/paste to see this issue? Also, what is the name of the Twig extension you are using?

**Comment by jecraig** [comment]
```<a target="{{ link.external ? '_blank'}}">```

whatwedo.twig

**Comment by ayazhafiz** [comment]
Okay, the PR linked above should fix this
