### ISSUE TITLE
angalar 4.0.0+: intellisense doesn't work for ngFor variables

### ISSUE THREAD

**Issue by andrius-pra** [angular/vscode-ng-language-service#67]
I'm using vscode 1.10.2, windows 10 and this [project](https://github.com/andrius-pra/Angular2-GettingStarted/tree/master/APM-Final-Updated)
![angular 4 0 1](https://cloud.githubusercontent.com/assets/17968027/24719453/7c2b2822-1a42-11e7-991b-620844d5c8fd.PNG)

it works fine with angular 2.4.10. [project](https://github.com/andrius-pra/Angular2-GettingStarted/tree/master/APM%20-%20Final)
![angular 2 4 10](https://cloud.githubusercontent.com/assets/17968027/24720097/a4c590c2-1a44-11e7-9378-555dfc659679.PNG)

**Comment by chuckjaz** [comment]
I have reproduced this and will work on a fix next week.

**Comment by chuckjaz** [comment]
Fixed in 0.1.4
