### ISSUE TITLE
Ctrl + hover / Ctrl + click is not working for pipes with parameters

### ISSUE THREAD

**Issue by SteffenKoehler** [angular/vscode-ng-language-service#677]
**Describe the bug**
`Ctrl + hover` / `Ctrl + click` is not working for pipes with parameters

**To Reproduce**

1. Check the pipe example on https://angular.io/guide/pipes or check it here (I updated it to angular 9) https://github.com/SteffenKoehler/angular-pipes-example
2. `Ctrl + hover` / `Ctrl + click` above the date pipe 

**Expected behavior**

`Ctrl + hover` / `Ctrl + click` should also work for pipes with parameters

**Screenshots**

![working](https://user-images.githubusercontent.com/9463791/76233013-d3824d00-6227-11ea-82be-15088b314c8e.png)

![not_working](https://user-images.githubusercontent.com/9463791/76233029-d7ae6a80-6227-11ea-9423-c4d0a399aea7.png)

**Additional context**

I'm using the current version available in the store (0.900.15)

**Comment by ayazhafiz** [comment]
Thanks for the report. The PR above will fix this.
