### ISSUE TITLE
Code completion when binding

### ISSUE THREAD

**Issue by MrAmericanMike** [angular/vscode-ng-language-service#691]
I have noticed that this extension works when using {{}}

However when we do property binding it doesn't show auto complete, for example on

[class]="..." ( Inside the ... )

Is this intended to happen for some particular reason?

Thanks in advance.

**Comment by ayazhafiz** [comment]
No, completions should be shown inside property bindings. What version of the language service extension are you using? Can you provide a minimal example, as requested in the [issue template]? Thanks.

[issue template]: https://github.com/angular/vscode-ng-language-service/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by MrAmericanMike** [comment]
Ok I went back to VSC to reproduce the problem, but it's not happening now, it's suggesting the variables with no problem. I guess it was some temporary problem, or maybe VSC just needed a restart.
Thanks for the feedback, nice to know this is actually a feature already ;)
