### ISSUE TITLE
Using template with require causes error to be reported.

### ISSUE THREAD

**Issue by mikerhyssmith** [angular/vscode-ng-language-service#70]
In a component where we use require to load in the template angular language service reports this error:
[Angular] Component TestComponent must have a template or templateUrl.

@Component({
    selector: "test-component",
    template: require("./test-component.html")
})

**Comment by mikerhyssmith** [comment]
Seen this is a known issue.

**Comment by ValeriiVasin** [comment]
@mikerhyssmith What does that mean? Known issue is tracked where? I do have same issue and do not see any opened ones in the repo related to it.

**Comment by bhagatparwinder** [comment]
This is an issue with 0.1.7 paired with TypeScript 2.4.2

![Screenshot](https://user-images.githubusercontent.com/6809087/30167167-26807d18-93ab-11e7-9024-9de70454fa55.png)
