### ISSUE TITLE
Conflicts with auto-rename-tag

### ISSUE THREAD

**Issue by temacode** [angular/vscode-ng-language-service#704]
Auto-rename-tag stops renaming tags, which is components (clickable in html)

**Comment by ayazhafiz** [comment]
Can you provide an example?

**Comment by ayazhafiz** [comment]
Can you provide an example? I do not see an issue:

![angular-issues-35424-and-35426-1585352755518](https://user-images.githubusercontent.com/20735482/77808878-73264480-704a-11ea-961f-30329378fb7d.gif)

**Comment by temacode** [comment]
I realized that the problem was not in this extension, while I was trying to find what exactly caused bugs to reproduce it. The problem is in auto-rename-tag, when all attributes are on new lines, and there is no space after the name of the first tag
