### ISSUE TITLE
Infer more accurate values in `as`

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/vscode-ng-language-service#725]
![image](https://user-images.githubusercontent.com/8111351/78852848-051d4c80-7a50-11ea-9b94-50f3f1881fa0.png)
This should be `5`
![image](https://user-images.githubusercontent.com/8111351/78852910-3007a080-7a50-11ea-8956-9c432ac47f25.png)
This should be `readonly [1, 'string']`
![image](https://user-images.githubusercontent.com/8111351/78852988-5af1f480-7a50-11ea-8c5a-055f070de9b4.png)
This should be `{ readonly a: 1 }`

**Comment by ayazhafiz** [comment]
This will be fixed with the language service's update to Ivy. Stay tuned!

**Comment by xiaoxiangmoe** [comment]
@ayazhafiz Will `as` in Ivy language service typesafe for [ngrxLet](https://ngrx.io/guide/component/let)？

**Comment by ayazhafiz** [comment]
With Ivy we compile templates into TypeScript code that is checked by `tsc`. So with no type erasure or bugs in the Ivy compiler, it will be as typesafe as it would be if you wrote any expression with pure TypeScript.

**Comment by xiaoxiangmoe** [comment]
Great!
Another question: Can we check if the `@Input` parameters are required in Ivy compiler?

**Comment by ayazhafiz** [comment]
What do you mean?

________________________________
От: ZHAO Jinxiang <notifications@github.com>
Отправлено: Wednesday, April 15, 2020 7:32:31 PM
Кому: angular/vscode-ng-language-service <vscode-ng-language-service@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Mention <mention@noreply.github.com>
Тема: Re: [angular/vscode-ng-language-service] Infer more accurate values in `as` (#725)


Great!
Another question: Can we check if the @Input parameters are required in Ivy compiler?

**Comment by xiaoxiangmoe** [comment]
see image *Top notch DX/Intellisense within JSX/templates — courtesy of TypeScript* in [React, TypeScript and defaultProps dilemma](https://medium.com/@martin_hotell/react-typescript-and-defaultprops-dilemma-ca7f81c661c7)

![image](https://user-images.githubusercontent.com/8111351/79409563-db74a000-7fd0-11ea-911f-469e2f480e2e.png)
![image](https://user-images.githubusercontent.com/8111351/79409573-dfa0bd80-7fd0-11ea-9a25-3ce045d1ac99.png)

The *onClick* prop is required. JSX template will show a error if no *onClick* prop provided.

**Comment by ayazhafiz** [comment]
I see. I'm not sure, but we should be able to warn about missing input properties today (even if we don't)

**Comment by kyliau** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
It's an opt-in feature for now, please give it a try and let us know if you have any feedback.
For the best editor experience, please make sure your project has [`strictTemplates`](https://angular.io/guide/angular-compiler-options#stricttemplates) enabled in `angularCompilerOptions`.
In case you run into similar bug, please file a new issue. I'll close this for now.
