### ISSUE TITLE
Not a known element when referencing an Angular Component from a library project using npm link

### ISSUE THREAD

**Issue by epaitz** [angular/vscode-ng-language-service#735]
I have created an Angular Workspace with the out-of-the-box Library project. Then I used [npm link](https://docs.npmjs.com/cli/link.html) to create a symbolic link to the output of the library in the global node_modules folder. Then I created a normal Angular application and added another symbolic link, using [npm link](https://docs.npmjs.com/cli/link.html), to the symbolic link in the global node_modules. I am using the npm link command because I am not ready to publish the library to npm. 

There are no modifications to the Library project after its was created by the Angular CLI. As for the application project, I had to add ["preserveSymlinks": true](https://angular.io/cli/build) to the angular.json file. This was discussed in [Getting Started Building Component Libraries with Angular CLI](https://itnext.io/angular-cli-libraries-79b0a32a1443).

The library and application projects both build successfully, and display correctly in the browser, but I am seeing the following error in Visual Studio Code. 

![image](https://user-images.githubusercontent.com/30181382/79589202-0af3dd00-80a3-11ea-9e26-febd05e2bbfc.png)

```
'lib-sparta' is not a known element:
1. If 'lib-sparta' is an Angular component, then verify that it is part of this module.
2. If 'lib-sparta' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

I have created two GitHub repos to demonstrate the issue.

- [Sparta Workspace](https://github.com/epaitz/sparta-workspace)
- [Sparta Application](https://github.com/epaitz/sparta-application/)

The application project builds correctly and displays correctly in a browser but I am seeing this syntax language error in VSCode. Since its not a build error I thought it might be related to the [Angular Language Service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) extension. I am using version 0.901.2.

Maybe the Angular Language Service extension does not correctly recognize the <lib-sparta> component is coming from a library via the npm link?

**Comment by ayazhafiz** [comment]
Currently, the language service cannot recognize projects built with Ivy (as your library appears to be built with). See this issue: https://github.com/angular/vscode-ng-language-service/issues/645#issuecomment-587282612

There is a migration of the language service to the Ivy compiler that will not require such a workaround, but for now it's all we have.

**Comment by epaitz** [comment]
Thanks for the fast reply. Can I build my library project without Ivy? I believe there was reference to adding `--prod` to the `ng build` command that would control that?

**Comment by ayazhafiz** [comment]
Yeah, I think `ng build lib-sparta --prod` with `"enableIvy": false` in lib-sparta's tsconfig under [`angularCompilerOptions`](https://angular.io/guide/angular-compiler-options#angular-compiler-options) would do the job.

**Comment by epaitz** [comment]
The sparta-lib project has [tsconfig.lib.prod.json](https://github.com/epaitz/sparta-workspace/blob/master/projects/sparta/tsconfig.lib.prod.json#L4) with `"enableIvy": false` so I deleted the dist folder and ran `ng build sparta-lib --prod` which created a slightly different output in the dist folder. I assume `--prod` will use the tsconfig.lib.prod.json file?

Then I restarted VSCode for the sparta-application project. At first the error did not appear but if I run `ng-build` the error shows up agian. Am I missing a step?

**Comment by ayazhafiz** [comment]
Re the comment I linked above:

> But you also need to make sure to Restart Angular Language service after each build in vs-code.

**Comment by epaitz** [comment]
So I read that comment and I just blanked on it, my fault. I am experimenting with the Reload Extension for VSCode to reload without having to restart VSCode. I am looking forward to a future version of the Angular Language Service extension where this issue has been fixed. Thanks for your help!

**Comment by ayazhafiz** [comment]
Oh, you can reload just the Angular language service extension — there is a “restart angular language service” command in the command drop down you get with ctrl+shift+p :)

Yeah, I hope we can get this fixed soon too.
