### ISSUE TITLE
Go to definition or CTRL+Click a symbol, works only once when this extension is active

### ISSUE THREAD

**Issue by isometriq** [angular/vscode-ng-language-service#74]
When the plugin is installed, whenever I go to certain definitions (for example "Promise") it works only once. Afterwards, the functionality does not work anymore and I have to Reload Window.

Not all definitions cause this, but it seem to happen more on core classes.
By turning off this extension, I've narrowed it to this one.

So for now, I unfortunately have no choice to deactivate the extension to continue working. Let me know if you need more information. Thanks

Using latest VSCode 1.11.1

**Comment by chuckjaz** [comment]
I believe this is related to other issues already reported but I cannot be sure with a repro project.

There will be a new release today or tomorrow. Let me know if this bug is still an issue after that release.

**Comment by chuckjaz** [comment]
This should be fixed in `0.1.3`. Reopen if it continues to reproduce.

**Comment by isometriq** [comment]
Yes it seems fine now, thanks
