### ISSUE TITLE
Be able to beautify the HTML template of Angular components

### ISSUE THREAD

**Issue by AlbertoMontalesi** [angular/vscode-ng-language-service#742]
It would be nice to be able to beautify the HTML.

**Comment by ayazhafiz** [comment]
I think this is outside the scope of the extension. This can be achieved by other extensions that beautify HTML.

**Comment by BO41** [comment]
https://prettier.io supports Angular perfectly.
Also available as VSCode extension

**Comment by ayazhafiz** [comment]
For inline templates there is already an open issue for this: #333. Closing for this reason and the comment above.

**Comment by AlbertoMontalesi** [comment]
My bad, i didn't see the issue for inline templates. All good
