### ISSUE TITLE
Highlight quirk on ngClass

### ISSUE THREAD

**Issue by AlbertoMontalesi** [angular/vscode-ng-language-service#748]
Subsequent lines after an ngClass are not properly highlighted unless i terminate with a semicolon

Before:
![image](https://user-images.githubusercontent.com/23130353/80167451-9c66d000-860a-11ea-9d66-c1d36066ccf0.png)

After:
![image](https://user-images.githubusercontent.com/23130353/80167489-bd2f2580-860a-11ea-8963-4d63225775c1.png)

**Comment by ayazhafiz** [comment]
Thanks for the report! I'll take a look at this.

**Comment by ayazhafiz** [comment]
Hm.. could you provide a code snippet I could copy/paste to reproduce this? I am trying with

```html
<div
    [ngClass]="type === 'area' ? 'cellAreaContainer' :
    'cellContainer'"
    (mouseenter)="showEditButton = true"
    (mouseleave)="showEditButton = false;"
    (click)="$event.stopPropagation();">
</div>
```
But am unable to see an issue.

**Comment by AlbertoMontalesi** [comment]
My bad, it was a quirk caused by another extension, not from this one. I'll close the issue
