### ISSUE TITLE
Cannot rename/move directories.

### ISSUE THREAD

**Issue by Goobles** [angular/vscode-ng-language-service#750]
**Describe the bug**

In windows, the ng language service plugin locks all folder/subfolders of the workspace.

I tracked this lock down with LockHunter.exe:
![image](https://user-images.githubusercontent.com/8776771/80316511-9b968f80-87fe-11ea-8409-1359f349c30b.png)
It points to the VSCode subprocess for `angular.ng-template.0.901.3\server`.

This lock causes renaming directories to fail with:
`Error: EPERM: operation not permitted, rename '<source>' -> '<target>'`

**To Reproduce**

1. Open any angular workspace that has subdirectories
2. Rename/move a directory within that workspace

**Expected behavior**

Folder renaming should work.

**Logs**

Not applicable.

**Screenshots**

**Additional context**

Version info:
```
Angular CLI: 9.1.1
Node: 12.11.1     
OS: win32 x64     

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@angular/cli                      9.1.1
@angular/material                 9.2.1
@ngtools/webpack                  9.1.1
@schematics/angular               8.3.25
@schematics/update                0.901.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
```

**Comment by kyliau** [comment]
This used to be a problem when we rolled our own tsserver, but we've stopped doing that, and now Angular LS relies completely on stock tsserver for file / project management. I wonder if we could reproduce the same problem using just tsserver.

**Comment by kyliau** [comment]
One area we need to investigate is whether NON_POLLING_WATCHER is used. It is the default watcher, and is known to be more efficient and avoid problems like this.

**Comment by blogcraft** [comment]
This happens to me also. Is it related to when finally changing folder, the imports wont update?

**Comment by mvanderlee** [comment]
Still seeing this in `0.1001.0` 
Angular language server process holds a lot of locks forever, and I can not rename any files.

```
[Info  - 4:52:05 PM] Using typescript/lib/tsserverlibrary v4.0.2 from c:\Users\maste\.vscode\extensions\angular.ng-template-0.1001.0\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 4:52:05 PM] Using @angular/language-service v10.1.1 from c:\Users\maste\.vscode\extensions\angular.ng-template-0.1001.0\server\node_modules\@angular\language-service\bundles\language-service.js
```

**Comment by nischi** [comment]
Is there any workaround, its super annoying if the refactor is need to be done by hand.

**Comment by blogcraft** [comment]
still no solution... 😔

**Comment by andrius-pra** [comment]
Angular language service use [non-pooling directory watchers](https://github.com/angular/vscode-ng-language-service/blob/dfedf3cbb05a8bfbf98df820addbd77c2d6e5eb9/client/src/client.ts#L285-L289) and it does not allow to rename directories. Currently, it's not possible to change this behavior by `.vscode\settings.json` or [tsconfig.json](https://www.typescriptlang.org/docs/handbook/configuring-watch.html#configuring-file-watching-using-a-tsconfigjson)

**Comment by kyliau** [comment]
The non-polling watchers are used to improve performance, but now that there's [built-in option](https://www.typescriptlang.org/docs/handbook/configuring-watch.html) to configure watch mode, we should remove the environment variable.

**Comment by atscott** [comment]
Re-opening since we have to revert commit 17708d4 to address #1310
