### ISSUE TITLE
Syntax coloring of inline templates

### ISSUE THREAD

**Issue by jpike88** [angular/vscode-ng-language-service#768]
This syntax coloring in my inline template is starting to make my eyes bleed:

<img width="1003" alt="Screen Shot 2020-05-07 at 9 37 02 PM" src="https://user-images.githubusercontent.com/9585787/81300889-e4760000-90aa-11ea-8b6f-b1b973c655b9.png">

Inline templates are all we have because it greatly reduces file clutter. But this is a nasty price to pay. What's involved in improving this?

**Comment by ayazhafiz** [comment]
Improving the grammar in the syntaxes/ directory of this repo. The README in there should have enough info to help a contributor get started. We’d be thrilled to accept PRs for this, but I don’t have the bandwidth to work on this on my own currently.

**Comment by jpike88** [comment]
I'm guessing it's something along the lines of merging the contents of template.json into inlineTemplate.json?

**Comment by ayazhafiz** [comment]
Yeah, but it should be simpler than that. Notice that the inline template grammar already includes the Angular template grammar:

https://github.com/angular/vscode-ng-language-service/blob/f0d5cbf81c2dc6dd5d8258b23ac9602cdf28ef12/syntaxes/inline-template.json#L65-L73

Ideally we should figure out why the inline template grammar isn't being picked up (maybe the HTML grammar on the include clause above it overrides it).

**Comment by Goobles** [comment]
It seems that since version 0.1000.0 the inline template html syntax has been completely broken:
![image](https://user-images.githubusercontent.com/8776771/86280839-db9e3800-bbdc-11ea-8302-35cd4aec2152.png)
This behavior seems the exact opposite of the OP, attribute/event bindings and structural directives are highlighted correctly, but the html syntax is not and just left white.

**Comment by ayazhafiz** [comment]
I finally figured out the OP issue, it was actually pretty simple and I can't believe I didn't spot it sooner!

@Goobles sorry for the delay; are you still experiencing this issue with the latest version of the extension?

**Comment by ayazhafiz** [comment]
@Goobles if you are still having a problem, please open a new issue.
