### ISSUE TITLE
Question: Typescript 2.3.3

### ISSUE THREAD

**Issue by jvbianchi** [angular/vscode-ng-language-service#77]
[Typescript 2.3 RC](https://blogs.msdn.microsoft.com/typescript/2017/04/10/announcing-typescript-2-3-rc/) is out. 

Can we use this extension with typescript 2.3 RC? Will it make any difference?

**Comment by kukjevov** [comment]
@chuckjaz can you make transition from typescript 2.1 directly to 2.3 ? :)

**Comment by chuckjaz** [comment]
Probably. I need to look at how much the implementation of the editor services API changed. I am just beginning that work now so I will look at it this week.

**Comment by jvbianchi** [comment]
[Typescript 2.3 is out](https://blogs.msdn.microsoft.com/typescript/2017/04/27/announcing-typescript-2-3/)

**Comment by cebor** [comment]
Will it possible to use angular-language-service as plugin for ts 2.3?

**Comment by kukjevov** [comment]
It already is. I am using it that way in combination with this plugin. Works well, not very well, but well enough :). When it will be fully updated for TS 2.3 it will by perfect i hope :). But it already works nicely.
