### ISSUE TITLE
Plugin doesn't work with FESM packages

### ISSUE THREAD

**Issue by fshchudlo** [angular/vscode-ng-language-service#82]
Hello.
Yesterday I rebuild my angular package according to best practices described by [Jason Aden at ngconf conference](https://www.youtube.com/watch?v=unICbsPGFIA&list=PLOETEcp3DkCoS_2cW205cfRGl-Xp5jw4K&index=61).

I've updated my demo application to latest version and it compiles and works just the same way. However, now there is an errors in HTML templates produced by language service.

You can reproduce this bug with the following steps
- Clone [right-angled-demo repository](https://github.com/eastbanctechru/right-angled-demo).
- Checkout branch `language-service-works`
- Run `yarn` from project directory to install dependencies
- Open any template, for example  'src\app\quick-tour\use-list\use-list.component.html' - everything works.
- Checkout branch `language-service-broken`
- Run `yarn` from project directory to install dependencies
- Open any template, for example 'src\app\quick-tour\use-list\use-list.component.html' - language service reports an error.

![image](https://cloud.githubusercontent.com/assets/5251012/25061851/5f51f16e-21e9-11e7-953f-9d84b7776739.png)

The only difference between branches is version of [right-angled](https://www.npmjs.com/package/right-angled) library. First branch uses version 1.0.0 which is just a regular package. Second branch uses version 1.1.0 which is builted according to angular best practices.

**Comment by chuckjaz** [comment]
This is a duplicate of #67. I have a fix pending in Angular.
