### ISSUE TITLE
Support safe navigation operator with object access via string literal

### ISSUE THREAD

**Issue by bampakoa** [angular/vscode-ng-language-service#836]
**Is your feature request related to a problem? Please describe.**

Occasionally, I am using a string literal to access object properties in my templates such as `user.info[name]` where the `name` is filled automatically from a `ngFor` directive. Sometimes, the `user` object does not have an `info` property filled in.

**Describe the solution you'd like**

It would be great if I could use the safe navigation operator as `user.info?[name]`

**Describe alternatives you've considered**

Currently I am using `ngIf` directive to avoid problems with `undefined` values.

**Additional context**

**Comment by ayazhafiz** [comment]
This would be a feature for the Angular template language, and should be proposed in the main angular repo https://github.com/angular/angular.
