### ISSUE TITLE
bug(language-service) using ngForTemplate (sugarized) with inline-template will mess-up html lint/format

### ISSUE THREAD

**Issue by andreElrico** [angular/vscode-ng-language-service#839]
# 🐞 bug report

### Affected Package
?language service?

(I hope its the right repo to put this)

### Is this a regression?

I think: no, not 100% sure

### Description

Steps to reproduce: 

1. copy this into *.ts in vscode

```
@Component({
  selector: 'my-app',
  template: `
    <ng-container *ngFor="let el of [1,2,3,4]; template: myTpl">
    </ng-container>

    <ng-template let-el #myTpl>
      <p> {{el}} </p>
    </ng-template>
    
    <hr>

    <ng-template ngFor let-item="$implicit" [ngForOf]="[11,22,33,44]" [ngForTemplate]="myTpl"></ng-template>
  `,
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {}
```
(Stackblitz does not use language feature in inline tpl)
+ [STACKBLITZ](https://stackblitz.com/edit/angular-ivy-1dpoq2?file=src/app/app.component.ts)

+ When I use this in vscode its messes up the HTML linting/ styling.

## 🔥 Exception or Error

Messed up html

![image](https://user-images.githubusercontent.com/44729345/83764554-5b86c000-a67a-11ea-9659-d1963e7adb7c.png)
what it should look like (ignore red error line. There is no templateLOL input)
![image](https://user-images.githubusercontent.com/44729345/83764835-b4eeef00-a67a-11ea-9d97-cdbee4ea897b.png)

## 🌍  Your Environment

+ vscode Version: `1.45.1`
+ Angular Language Service angular.ng-template `0.901.9`

**Angular Version:**
<pre><code>
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.6
@angular-devkit/build-angular      0.901.6
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.6
@angular-devkit/build-webpack      0.901.6
@angular-devkit/core               9.1.6
@angular-devkit/schematics         9.1.6
@angular/cdk                       9.2.4
@angular/cli                       9.1.6
@angular/flex-layout               9.0.0-beta.31
@angular/material                  9.2.4
@ngtools/webpack                   9.1.6
@schematics/angular                9.1.6
@schematics/update                 0.901.6
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0</code></pre>

**Current workaround**

use of "de-sugarized" version will not mess with linting/ formating.

`<ng-template ngFor let-item="$implicit" [ngForOf]="[11,22,33,44]" [ngForTemplate]="myTpl"></ng-template>`

**Comment by kyliau** [comment]
@ayazhafiz could you please take a look at this?

**Comment by ayazhafiz** [comment]
Yes, will do within the next 3 days
