### ISSUE TITLE
Support static evaluation of array methods in annotations

### ISSUE THREAD

**Issue by chuckjaz** [angular/vscode-ng-language-service#856]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

Using pure method of an array, such as `concat`, are not supported.

## Expected behavior

Should support methods like `concat`, `copyWithin`, `join`, `slice`.
Consider supporting `map`, `reduce`, `reduceRight` using lambda that qualify as macros.

## Minimal reproduction of the problem with instructions

```ts
  describe('build array functions', () => {
    it('should support concat', () => {
      const fileName = '/tmp/src/use_array.ts';
      const data = {
        '/tmp/src/arrays.ts': `
          export const A1_4 = [1, 2, 3, 4];
          export const A5_9 = [5, 6, 7, 8, 9];
        `,
        '/tmp/src/use_array.ts': `
          import {Component} from '@angular/core';
          import {A1_4, A5_9} from './arrays';

          @Component({
            providers: [{ provide: 'v', value: A1_4.concat(A5_9)}]
          })
          export class C {}
        `
      };

      init({...DEFAULT_TEST_DATA, ...data});

      const symbol = symbolResolver.getStaticSymbol(fileName, 'C');
      expect(reflector.annotations(symbol)[0].providers[0].value).toEqual([1,2,3,4,5,6,7,8,9]);
    })
  });
```

## What is the motivation / use case for changing the behavior?

Better support for well used JavaScript features as well as better fidelity with JIT applications.

**Comment by kyliau** [comment]
This has been fixed by the new Ivy-native language service, released in [v11.1.0](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0).
