### ISSUE TITLE
Angular Language Service fails to find RouterModule if it's encapsulated in a separate module

### ISSUE THREAD

**Issue by Verbon** [angular/vscode-ng-language-service#87]
I'm new to Angular 2 and now learn Angular 2 by Tour of Heroes Angular guide. Following their example I encapsulated my routes config in another module:

**app-routing.module.ts**
![image](https://cloud.githubusercontent.com/assets/9406367/25303885/b4ae5550-2764-11e7-8e25-3cd3997637ce.png)

And then imported it in my main module and registered in within `imports` section of `@NgModule` decorator:

**app.module.ts**
![image](https://cloud.githubusercontent.com/assets/9406367/25303910/f219b2fe-2764-11e7-8b72-1ea87037c410.png)

However, Angular Language Service fails to see that I actually imported routing in my app, so when I write code that uses routing I get the following errors:
**app.component.html**
![image](https://cloud.githubusercontent.com/assets/9406367/25303930/61c745e4-2765-11e7-8a78-417089883023.png)

**dashboard.component.html**
![image](https://cloud.githubusercontent.com/assets/9406367/25303941/840c39fc-2765-11e7-8e0f-8bf306c99e73.png)

P.S. Please, also note that static `routerLink`ing doesn't cause an error.
P.P.S. Compiled app works fine, it's not an Angular 2 error.
P.P.S. Disabling/uninstalling Angular Language Service extension makes these error disappear.

Please, fix this :)

**Comment by hccampos** [comment]
Similar issue here actually. Components declared in imported modules don't seem to be picked up by the language service. @Verbon could you set up a small repo with all your code for @chuckjaz to take a look at?

**Comment by Verbon** [comment]
@hccampos @chuckjaz 
Yes, please, here's my test Tour of Heroes project - https://github.com/Verbon/TourOfHeroes.

**Comment by tzachov** [comment]
I'm pretty sure it's more than just RouterModule issue - I have pipes and directives that are also not recognized by the language service when they are imported through another module.

**Comment by bnymncs** [comment]
Yes, I'm having the same issue as well.
I have a SharedModule which imports CommonModule, FormsModule, TranslateModule and export those as well. In another feature module, it gives me an error on html files but the application works just fine. If I move those import lines to that feature module, it doesn't complain.

**Comment by hccampos** [comment]
As I said in my previous comment, it is indeed a problem with modules exported from another module. All the modules exported by our `SharedModule` don't get picked up by the language service.

**Comment by renehamburger** [comment]
@hccampos is absolutely right: no pipes/directives/components from other (imported) modules are picked up. @chuckjaz, I'm sure you're aware of this. Is this on your roadmap or are you aware of a workaround?

**Comment by chuckjaz** [comment]
The linked example does not reproduce with 0.1.4. Is this still an issue? Does it reproduce after a "Reload Window"?

**Comment by bnymncoskuner** [comment]
@chuckjaz It should be working now. I had a similar problem, and it got away when I updated to 0.1.4.

**Comment by chuckjaz** [comment]
Closing for now then.

**Comment by schippie** [comment]
I saw this issue was closed quite a while ago (and am unsure if that means I should be creating a new one) But with version: 5.2.8 I'm experiencing the same issues as described above. Re-exported modules from a shared Module cause the language service to not recognize the bindings HTML component tags etc.
