### ISSUE TITLE
Private methods are not underlined in templates

### ISSUE THREAD

**Issue by Cammisuli** [angular/vscode-ng-language-service#88]
Using a private method in a template does not show an error in the html file. Seen here:
![image](https://cloud.githubusercontent.com/assets/4332460/25499483/a0c4a41a-2b59-11e7-954a-8a21a208de34.png)

It's pretty easy to reproduce, `ng new app` and use a private method in a template.

Here's some information about my environment:
```
Angular Plugin: 0.1.3
Angular Language Service: 4.1.0-beta.0-96aa236
TypeScript: 2.1.6
OS: Windows 10
node: v7.4.0
```

**Comment by Cammisuli** [comment]
I created an issue over at the angular repo (angular/angular#16451) as this seems to be more with the language service than the extension. This problem also appears in WebStorm.

**Comment by littleStudent** [comment]
could be related to this? https://github.com/angular/angular/issues/11978
Since AOT is targeted as the standard, the language service is working as expected? your property should be public.

**Comment by Cammisuli** [comment]
Yea, it should be public, but I'm not getting any errors in the template
saying that you can't use private methods.
When I use a private property I get the red squiggles in the template, that
red squiggle doesn't show for the method.

**Comment by littleStudent** [comment]
sorry for the confusion, obviously i did not read your description properly 😞 .

**Comment by Cammisuli** [comment]
Hey, no worries. It happens 🙂

**Comment by bhaskerchari** [comment]
Is there any update on this issue its been open since quite a long time?? It seems to be a critical issue from production build standpoint and may need to be addresses soon.

Thanks.

**Comment by kyliau** [comment]
This has been fixed. https://github.com/angular/angular/blob/43ffe7257a3b88c590760ed81d0258481a7405d1/packages/language-service/test/diagnostics_spec.ts#L127-L130
