### ISSUE TITLE
Language server formatting capabilities

### ISSUE THREAD

**Issue by ihodev** [angular/vscode-ng-language-service#884]
Hello!

I've created [LSP-angular](https://github.com/sublimelsp/LSP-angular) plugin for Sublime Text that uses `@angular/language-server` package.

The only missing feature is formatting. Can you tell me does the ng ls support it or should I do some extra steps to enable it?

Thanks in advance!

**Comment by ayazhafiz** [comment]
Neither the angular/language-service package nor the VSCode extension support code formatting. There was some discussion of this in #333 but my impression is that formatting would be better handled by existing tools that do it well.

**Comment by ihodev** [comment]
I see, thanks.
