### ISSUE TITLE
Custom pipes not found within Angular CLI Library

### ISSUE THREAD

**Issue by 18clans** [angular/vscode-ng-language-service#888]
**Describe the bug**
I'm getting an error `The pipe 'reverseString' could not be found` in the `.HTML` file that uses the custom pipe but the application builds and runs fine during runtime.

The bug can be found in this project:
[Angular Library Demo](https://github.com/18clans/demo-pipe)

**To Reproduce**

1. Make sure you have `Angular Language Service` extension installed and enabled
2. Clone `https://github.com/18clans/demo-pipe`
3. `npm i`
4. `ng build demo-lib`
5. Error will be in `src > app > app.component.html`

**Expected behavior**

When you navigate to `src > app > app.component.html`, you should see an error when your mouse hovers over the custom pipe.

**Logs**

No error logs

**Screenshots**

<img width="893" alt="Screen Shot 2020-08-13 at 2 00 37 PM" src="https://user-images.githubusercontent.com/41965764/90177035-8c1c6180-dd6f-11ea-953b-7dec85453dc3.png">

**Additional context**
[Old issue](https://github.com/angular/vscode-ng-language-service/issues/98)

I tested this out with a stand-alone Angular project and everything works as it should.  There was no error in the `.HTML` file and it ran just fine.  An example project can be found here: [Working demo project](https://github.com/18clans/custom-pipes).

**Comment by andrius-pra** [comment]
I see 3 issues in you demo project.

1. It is missing required packages: ng-packagr, tsickle
2. You can't use [typescript Barrel](https://basarat.gitbook.io/typescript/main-1/barrel) in `projects\demo-lib\src\public_api.ts` and all its dependencies. You need to use full path to file or add \index to your export statements. ex: use `export * from "./reverse-string/index";` instead of `export * from "./reverse-string";`.  (ng-packagr/ng-packagr#195)
3. angular language service doesn't support ivy library packages. You can disable ivy in you library by adding `"enableIvy": false` to angularCompilerOptions in `projects\demo-lib\tsconfig.lib.json`

I have created [branch](https://github.com/andrius-pra/demo-pipe/commits/fix) with all [changes](https://github.com/18clans/demo-pipe/compare/master...andrius-pra:fix).

**Comment by 18clans** [comment]
> I see 3 issues in you demo project.
> 
> 1. It is missing required packages: ng-packagr, tsickle
> 2. You can't use [typescript Barrel](https://basarat.gitbook.io/typescript/main-1/barrel) in `projects\demo-lib\src\public_api.ts` and all its dependencies. You need to use full path to file or add \index to your export statements. ex: use `export * from "./reverse-string/index";` instead of `export * from "./reverse-string";`.  ([ng-packagr/ng-packagr#195](https://github.com/ng-packagr/ng-packagr/issues/195))
> 3. angular language service doesn't support ivy library packages. You can disable ivy in you library by adding `"enableIvy": false` to angularCompilerOptions in `projects\demo-lib\tsconfig.lib.json`
> 
> I have created [branch](https://github.com/andrius-pra/demo-pipe/commits/fix) with all [changes](https://github.com/18clans/demo-pipe/compare/master...andrius-pra:fix).

Thanks, I updated master with your changes.  This doesn't resolve the issue `The pipe 'reverseString' could not be found`.

**Comment by andrius-pra** [comment]
Did you try restart vscode? I have checked out your demo project and it works. I used these steps:
```
git clone https://github.com/18clans/demo-pipe.git
cd demo-pipe
npm i
ng build demo-lib
code .
```
![image](https://user-images.githubusercontent.com/17968027/90273151-2f9c6d80-de67-11ea-882d-cd186cb83fa6.png)

**Comment by 18clans** [comment]
> Did you try restart vscode? I have checked out your demo project and it works. I used these steps:
> 
> ```
> git clone https://github.com/18clans/demo-pipe.git
> cd demo-pipe
> npm i
> ng build demo-lib
> code .
> ```
> 
> ![image](https://user-images.githubusercontent.com/17968027/90273151-2f9c6d80-de67-11ea-882d-cd186cb83fa6.png)

Weird, after a restart the error was gone but when I ran `ng build demo-lib` the error showed up again.  I restarted VSCode once more and the error is no longer there.  I'll have to do this fix on my real project.  Thank you @andrius-pra

**Comment by JohnnyDevNull** [comment]
@18clans try to change your setup like i mentioned in this issue & comment: https://github.com/angular/vscode-ng-language-service/issues/340#issuecomment-651742333

The default library development setup is not that optimal for developing a library. With a good path mapping you have to build your library only when you want to release or publish it. For development you can then just use `ng serve` with that approach.
