### ISSUE TITLE
Possibility to get error information in ng serve console ? 

### ISSUE THREAD

**Issue by virgil-av** [angular/vscode-ng-language-service#89]
Hi,

   Thank you for this great plugin it helps a lot in development.
   Is there any way you can include the errors to the ng serve console, this would help a lot in development.

Thank you.

**Comment by chuckjaz** [comment]
I am currently working on this here: https://github.com/angular/angular/issues/15988

**Comment by ayazhafiz** [comment]
Template type checking is now provided with Ivy, in at least AOT mode. Closing; please open a new issue if you face this again.
