### ISSUE TITLE
Issues running in nx-style monorepo: 

### ISSUE THREAD

**Issue by s4m0r4m4** [angular/vscode-ng-language-service#908]
**Describe the bug**
I routinely get errors thrown by the Angular Language Service extension in VS code, when working in an nx-style monorepo (multiple angular libs and apps).

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

**To Reproduce**

1. Open the workspace, and make sure that the first typescript file opened is in an angular _library_ (if I have a typescript file open from an angular _application_ this seems to work ok).
2. Watch the extensions window
3. See the error in the log below
4. I have verified that I do indeed have angular installed in the root package.json and node_modules.

**Expected behavior**
No errors.

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)

[Info  - 3:02:45 PM] Disabling language service for c:/AIMDev/CI-Web/libs/lib-images/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
```
[Info  - 3:02:42 PM] Angular language server process ID: 6620
[Info  - 3:02:43 PM] Using typescript/lib/tsserverlibrary v3.9.5 from c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 3:02:43 PM] Using @angular/language-service v10.0.14 from c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\server\node_modules\@angular\language-service\bundles\language-service.js
[Info  - 3:02:43 PM] Log file: c:\Users\A9FZGZZ\AppData\Roaming\Code\logs\20200903T150237\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 3:02:45 PM] Disabling language service for c:/AIMDev/CI-Web/libs/lib-images/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
[Error - 3:02:46 PM] TypeError: Cannot read property 'endsWith' of undefined
    at isAngularProject (c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\server\index.js:1294:23)
    at Session.checkIsAngularProject (c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\server\index.js:1264:15)
    at Session.handleProjectServiceEvent (c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\server\index.js:893:27)
    at ProjectService.eventHandler (c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\server\index.js:844:40)
    at ProjectService.sendProjectLoadingFinishEvent (c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\node_modules\typescript\lib\tsserverlibrary.js:144944:22)
    at ConfiguredProject.updateGraph (c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\node_modules\typescript\lib\tsserverlibrary.js:144200:37)
    at updateProjectIfDirty (c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\node_modules\typescript\lib\tsserverlibrary.js:144667:45)
    at c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\node_modules\typescript\lib\tsserverlibrary.js:146752:33
    at c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\node_modules\typescript\lib\tsserverlibrary.js:144624:33
    at c:\Users\A9FZGZZ\.vscode\extensions\angular.ng-template-0.1000.8\node_modules\typescript\lib\tsserverlibrary.js:101632:24
[Error - 3:02:46 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'endsWith' of undefined
```
2. Log file (Path is printed to the console output at startup)
--> attached 
[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/5170935/nglangsvc.log)

**Comment by s4m0r4m4** [comment]
Also getting this: `[Error - 3:16:13 PM] Cannot read file 'c:/AIMDev/CI-Web/tsconfig.base.json'.`

I know Angular was trying to move to the "solution-style" config, but then stuff didn't work out and they reverted (in 10.1 I think). That is definitely confusing a lot of tools.

**Comment by s4m0r4m4** [comment]
It looks like this might be due to an invalid "Extends" property in the tsconfig of the offending library.

**Comment by s4m0r4m4** [comment]
Perhaps the solution is just to report out bad tsconfig extends properties so the user can fix them?

**Comment by ayazhafiz** [comment]
Apologies for the delay. This error comes from line 575 in

https://github.com/angular/vscode-ng-language-service/blob/7cfd369b2a0f264d19ee4af8b0da6dfc107b8bf1/server/src/session.ts#L569-L580

Since we get the project files from TypeScript APIs, we would expect them to be correct. This may be a bug with TypeScript. Could you provide a reproduction of the invalid tsconfig that caused this?

**Comment by s4m0r4m4** [comment]
Thanks for looking into this! Hmmmm, now I get a much nicer error message for a bad tsconfig extends property, saying:
`[Error - 4:16:13 PM] Cannot read file 'c:/<path-here>/tsconfig123.json'.`

I don't know if something changed in the Typescript repo, this repo, VS code, or perhaps it was an issue in my local setup. In any event, I'd say we can consider this closed. I can reopen it if I somehow get the error again.
