### ISSUE TITLE
Angular Language Server doesn't declare support for workspaceFolders

### ISSUE THREAD

**Issue by mickaelistria** [angular/vscode-ng-language-service#909]
**Describe the bug**

Angular Language Server doesn't declare support for workspaceFolders capability. As a result, IDEs that have used it to determine the multiplicity of the LS (eg Wild Web Developer) now start multiple LS instance as there is nothing to hint that a single instance is enough.

**To Reproduce**

With Wild Web Developer, open multiple .ts files from multiple projects.
See that as many `node .../angular-language-server...` processes are started.
Enabling the langauge server log, the server capabilities only say
```
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":2,"completionProvider":{"resolveProvider":false,"triggerCharacters":["<",".","*","[","(","$","|"]},"definitionProvider":true,"hoverProvider":true}}}
```

**Comment by kyliau** [comment]
Closed by #910
