### ISSUE TITLE
Unknown method .bind

### ISSUE THREAD

**Issue by YogliB** [angular/vscode-ng-language-service#93]
I'm using VS Code v1.12.1, and Angular Language Service v0.1.3, with an Ionic 3 project, and I get these warnings, despite everything being fine...

**Comment by bkbonner** [comment]
I just saw this with Angular Language Service and VS Code 1.13.   happens in Heroes Tutorial when adding (save()) method to hero-detail-component.html

Code functions fine, but shows red squiggly lines even though method is clearly there.

**Comment by chuckjaz** [comment]
@bkbonner I cannot reproduce this with https://angular.io/generated/zips/toh-pt6/toh-pt6.zip Do you have a modification to this that shows this issue.

**Comment by bkbonner** [comment]
I can try to send my codebase.   Let me see if there is something else different in i you're that lets it work.

**Comment by bkbonner** [comment]
Hi @chuckjaz .   So if I go and modify the .ts file and remove the save() method and then go to the corresponding html file and modify the method name call in the html file, it underlines it.   If I add the method back on the .ts side, and go back to the .html file, the squiggly line stays until I click ctrl+space and select one of the method options in the drop-down.

I'm not sure if this is how it was behaving before, but maybe it's how the validation of the method's existence is being triggered that is causing the confusing result.

**Comment by bkbonner** [comment]
I included a video to show how it looks:   https://youtu.be/UjfFprgvTQg   no audio, but I included closed captions to describe it.

**Comment by karocksjoelee** [comment]
I am facing same problem as well ...

**Comment by Kyderman** [comment]
I have the same problem using .bind in a template.

It works but we get errors.

**Comment by spacedawwwg** [comment]
+1 same issue here

**Comment by CaffGeek** [comment]
Any solution yet?

**Comment by JorgeSanchezGr** [comment]
+1 here too!

**Comment by Luchnik** [comment]
+1 exact same issue. Any updates?

**Comment by RafaelKr** [comment]
Same error with `.bind(this)` here.

**Comment by shamilovtim** [comment]
Confirmed still happening in VS Code with angular language service. Ionic 3, Angular 5.

**Comment by AndrWeisR** [comment]
Also happening with 'hasError' in extension 0.1.9 in VS Code 1.24.1:

`<div *ngIf="form.get('phone').hasError(validation.type)">`

complains that hasError is not a function, although it is (in the AbstractControl class of Angular forms).

**Comment by aj-r** [comment]
Also happening with `$any()`, which should always exist (https://angular.io/guide/aot-compiler#disabling-type-checking-using-any)

**Comment by aj-r** [comment]
Never mind my previous comment - I added this to my `tsconfig.json`:

```
"plugins": [
        { "name": "@angular/language-service" }
    ]
```

and the errors with `$any()` went away.

**Comment by JosepAlacid** [comment]
Same issue here Ionic3 Angular5

**Comment by joseluisq** [comment]
I got the same error in VS Code `v1.25.1` + Angular `v6.0.1`

**Comment by 1011178l** [comment]
Got the same error in VS code 1.25.1

Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Comment by pgwest** [comment]
Same error in Angular 5 and VS Code 1.26.0

**Comment by MarkvanTurnhout** [comment]
I have the same problem in Angular 6.

`[displayWith]="displayFn.bind(this)"`

Everything works fine and I see no errors while running, just in the editor:

> [Angular] Unknown method 'bind'

**Comment by Spaier** [comment]
The same happens to me.
```
[myFun]="myService.myFunc.bind(myService)"
```

**Comment by eugensunic** [comment]
Is there any way to surpress this warning instead of everyone saying I have the same problem?

**Comment by multilexus** [comment]
try adding a semicolon after function name like this

<ion-button (click)="test();">
  Test Button
</ion-button>

This seems to remove the warning.

**Comment by YogliB** [comment]
Honestly, I have no idea if this is still an issue.
VS Code & the ALS have been updated a lot since then, and I haven't seen this warning in a long time...

**Comment by RafaelKr** [comment]
Yes, this is still an issue.
![image](https://user-images.githubusercontent.com/14234815/52943485-8c4fc280-336d-11e9-81ad-5bc73b503261.png)

VS Code About:
```
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic
```

**Comment by multilexus** [comment]
Try to put ; after it.On Feb 18, 2019 5:09 AM, Rafael <notifications@github.com> wrote:Yes, this is still an issue.

VS Code About:
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Comment by RafaelKr** [comment]
@multilexus this is not working.

**Comment by anonymuos1** [comment]
> Yes, this is still an issue.
> ![image](https://user-images.githubusercontent.com/14234815/52943485-8c4fc280-336d-11e9-81ad-5bc73b503261.png)
> 
> VS Code About:
> 
> ```
> Version: 1.31.1
> Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
> Date: 2019-02-12T02:19:29.629Z
> Electron: 3.1.2
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Linux x64 4.15.0-45-generic
> ```

Same problem here :-/ Any solution?

**Comment by ace90210** [comment]
+1 with angular 7 displayWith on a mat-autocomplete
![image](https://user-images.githubusercontent.com/2934101/53249707-b0ced600-36b0-11e9-8cf1-4f2bbb44ba4b.png)

**Comment by LMariano** [comment]
@multilexus is right i'm working with Angular 7 in VS code 1.31.1

**Comment by mspoerry** [comment]
It is still a problem. Any news?

**Comment by aakash18012** [comment]
> The same happens to me.
> 
> ```
> [myFun]="myService.myFunc.bind(myService)"
> ```

write like this:--
 **`[myFun]='handleFun'  ---in html`
`this.handleFun=this.myService.myFunc.bind(myService);**`

**Comment by aakash18012** [comment]
> > Yes, this is still an issue.
> > ![image](https://user-images.githubusercontent.com/14234815/52943485-8c4fc280-336d-11e9-81ad-5bc73b503261.png)
> > VS Code About:
> > ```
> > Version: 1.31.1
> > Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
> > Date: 2019-02-12T02:19:29.629Z
> > Electron: 3.1.2
> > Chrome: 66.0.3359.181
> > Node.js: 10.2.0
> > V8: 6.6.346.32
> > OS: Linux x64 4.15.0-45-generic
> > ```
> 
> Same problem here :-/ Any solution?

>write like this:--
[myFun]='handleFun'
>---in html

>this.handleFun=this.setLanguage.bind(this,language);
>--in ts file

**Comment by aakash18012** [comment]
> +1 with angular 7 displayWith on a mat-autocomplete
> ![image](https://user-images.githubusercontent.com/2934101/53249707-b0ced600-36b0-11e9-8cf1-4f2bbb44ba4b.png)
> 
> Works fine but warnings

>write like this:--
>[displayWith]='displayFun'
>---in html

>this.displayFun=this.displayFun.bind(this);
>--in ts file

**Comment by MagicCurlyHair** [comment]
Encountered this bug when using ```$any()``` method in ```<ng-template>``` in Angular 7.

**Comment by lonix1** [comment]
Still complaining for `hasError` in
````
<div *ngIf="form.get('phone').hasError(validation.type)">
````
VSCode 1.34.0
extension 0.800.0

**Comment by klenium** [comment]
Until they fix it, there's a workaround (at least for `myMethod.bind(this)`:

```
bindMyMethodWithThis() {
    return this.myMethod.bind(this);
}

<MyComponent [myInput]="bindMyMethodWithThis()">
```

**Comment by andrius-pra** [comment]
> Until they fix it, there's a workaround (at least for `myMethod.bind(this)`:
> 
> ```
> bindMyMethodWithThis() {
>     return this.myMethod.bind(this);
> }
> 
> <MyComponent [myInput]="bindMyMethodWithThis()">
> ```

It's a bad idea to use `bind` function inside template. `bind` function creates a new function on every call. So you will create a new function on every change detection. it's better to assign arrow function to class property:

 ```typescript
myMethod = (param1: any, param2: any) => {
    // method logic
}
```
```html
<MyComponent [myInput]="myMethod">
```

**Comment by klenium** [comment]
@andrius-pra Nice idea, I'll now use this, thanks.

**Comment by kyliau** [comment]
Sorry everyone that it took so long for us to address this issue. The PR above should fix it.
