### ISSUE TITLE
solo terminp

### ISSUE THREAD

**Issue by Garcia123** [angular/vscode-ng-language-service#937]
Issue Type: <b>Bug</b>

solo termino no se pucho  lo unico abri y salio el error

Extension version: 0.1001.0
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.3.7-301.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 x 2390)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|13.65GB (2.13GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id d08a5d57-eea7-470a-bc35-39a88abc96dc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by ayazhafiz** [comment]
Thank you for the report. Unfortunately, to better diagnose crashes we need more information. Could you please provide us any logs of the language service invocation, or if those are not available, more information on what you were doing before this error occurred? Please submit these as a new issue so it is easier to track. Thank you.
