### ISSUE TITLE
Cannot install from vscode ext window

### ISSUE THREAD

**Issue by acostaf** [angular/vscode-ng-language-service#94]
Hi All 

Nothing happens when clicking install

![screen shot 2017-05-09 at 17 27 48](https://cloud.githubusercontent.com/assets/1760318/25861505/dc97fe06-34dc-11e7-8fe7-6b17c44adbaa.png)

**Comment by Bulan** [comment]
That's most likely something on your end with VS Code. (Or a bug  in VSCode)
That said, I might have seen that sometime as well sometime, try clicking on the row to see details, and try to install it from there instead.

**Comment by acostaf** [comment]
Hi Bulan,

Thanks for your answer, already try that, do you how to see any error log ? I don't even know why it is failing to install.

**Comment by acostaf** [comment]
Also disabled all my existing extensions but not luck

**Comment by chuckjaz** [comment]
I have no control of this code or the download process. @Bulan suggests, it might be something related on your machine or or connection with the store.
