### ISSUE TITLE
Allow suppression of errors

### ISSUE THREAD

**Issue by omirobarcelo** [angular/vscode-ng-language-service#943]
**Is your feature request related to a problem? Please describe.**

I am working on testing Angular components and modules. I have some dummy components, like an empty template one or a root component with just `<router-outlet></router-outlet>` that I reuse in many tests.  
When declaring these components outside of a module, the language service, rightfully so, indicates that the components are not declared in a module (just warning) or that `router-outlet` is not a known element (an error).  
It still works, because then these components are declared in a testing module with the right dependencies, but it is annoying to have the error constantly there.

**Describe the solution you'd like**

For linters, usually you can add a line in front of the error line indicating to skip linting in the next line. Something similar would be helpful. Maybe a line indicating don't check for errors in this component, or just in the template...

**Describe alternatives you've considered**

My current alternatives are: or ignore the error, or declare the component in each test that needs it.

**Comment by ayazhafiz** [comment]
This is a known limitation of the language service, there is an RFC for a feature like this at https://github.com/angular/angular/issues/32663. Unfortunately, it probably won't be gotten to for a while ): However, https://github.com/angular/angular/issues/32663 is already tracking limitations like this, I am marking this report as closed.
