### ISSUE TITLE
Generic types are incorrectly inferred when function is called in template 

### ISSUE THREAD

**Issue by lemnis** [angular/vscode-ng-language-service#952]
When a function is called that contains a generic the extension fails to infer its type, while Typescript can infer the type correctly. I believe similar bugs are reported, but I was unable to find this specific one. See code & screenshot for an example.

```ts
import { Component } from '@angular/core';

interface Parent {
  bar: string;
}

interface Child extends Parent {
  foo: string;
}

@Component({
  selector: 'app-foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.css']
})
export class FooComponent {
  someValue: Child = {
    foo: 'foo',
    bar: 'bar'
  };

  parsedValue = this.someFunction(this.someValue);

  someFunction<T extends Parent>(value: T): T {
    return value;
  }
}
```

```html
<p>
  {{ someValue.foo }}
  {{ someValue.bar }}
</p>
<p>
  {{ parsedValue.foo }}
  {{ parsedValue.bar }}
</p>
<p>
  {{ this.someFunction(someValue).foo }}
  {{ this.someFunction(someValue).bar }}
</p>
```

**Screenshots**

<img width="813" alt="image" src="https://user-images.githubusercontent.com/3999815/98007533-cb4cd280-1df3-11eb-9241-801a7a16ab50.png">

Tested with:
- Angular Language Service v0.1001.0
- typescript/lib/tsserverlibrary v4.0.2
- @angular/language-service v10.1.1

**Comment by ayazhafiz** [comment]
This is a known issue (https://github.com/angular/angular/issues/21224) and is fixed by the Ivy language service, beta released in Angular 11 (https://github.com/angular/vscode-ng-language-service/issues/335#issuecomment-693545000)
