### ISSUE TITLE
Add parenthesis after auto-completing methods if parenthesis NOT exists already

### ISSUE THREAD

**Issue by adurmus** [angular/vscode-ng-language-service#973]
It is annoying and time consuming when coding in angular template that a method name  needs to be changed It automatically adds parenthesis '()' without checking whether parenthesis already there.

Example:
`(click)="oldMethod()"`  while changing method name to `newMethod()` intellisense  helps you pick the method instead of typing all characters. However, you end up with duplicated parenthesis  like `(click)="newMethod()()"`  and you would click there to remove duplicated parenthesis.

**Comment by atscott** [comment]
Hi @adurmus - the new Angular Language Service that's available as experimental in the 11.1 release no longer adds parenthesis for autocompleting methods. This is aligned with what the native TypeScript Language Service so we don't intend to add the auto-parens feature back.
