### ISSUE TITLE
Custom paths can't be resolved

### ISSUE THREAD

**Issue by Modellium** [angular/vscode-ng-language-service#99]
Example:
`import { FooService } from 'app/services/foo.service.ts
`
I get the component decorator highlighted saying it cannot resolve fooService relative to this component

**Comment by ciel** [comment]
I'm also experiencing this. I know the paths are correct, and the application runs, but the service reports an error.

**Comment by abierbaum** [comment]
Looks like it doesn't take into account the "baseUrl" setting from tsconfig.json.

**Comment by Meligy** [comment]
Like @abierbaum said, this is not even about custom `paths`, it's just about taking `baseUrl` (from `tsconfig.json`) into account, although technically both might be the same thing under the hood.

**Comment by DBosley** [comment]
Having this problem as well. Any workarounds?

**Comment by chuckjaz** [comment]
Tracking in https://github.com/angular/angular/issues/17651

**Comment by kyliau** [comment]
Closing this, since https://github.com/angular/angular/issues/17651 has been closed.
