### ISSUE TITLE
New command: Run ngcc

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#991]
Ivy-native LS requires ngcc to run not only at startup, but also whenever the dependencies change.
In Angular CLI, this is done in conjunction with incremental compilation, but in LS, we do not have such feature (yet).
For example, if users install new packages after the initial ngcc run, they'll need to run ngcc manually, otherwise the new packages won't be picked up by the compiler.
It'll be helpful if we implement a `Run ngcc` command so that users can invoke it on-demand, right from their editor.

**Comment by ayazhafiz** [comment]
Would be nice if we can also detect such changes and run ngcc automatically.
